{
  "name": "SemanticModel",
  "compatibilityLevel": 1400,
  "model": {
    "culture": "zh-CN",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/10 8 1 66;test_yueying",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "10.8.1.66",
            "database": "test_yueying"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "kind": "SQL",
          "path": "10.8.1.66;test_yueying",
          "Username": "sa",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "dim_budget",
        "columns": [
          {
            "name": "c1",
            "dataType": "string",
            "sourceColumn": "c1"
          },
          {
            "name": "c2",
            "dataType": "string",
            "sourceColumn": "c2"
          },
          {
            "name": "c3",
            "dataType": "string",
            "sourceColumn": "c3"
          },
          {
            "name": "c1_name",
            "dataType": "string",
            "sourceColumn": "c1_name"
          },
          {
            "name": "c2_name",
            "dataType": "string",
            "sourceColumn": "c2_name"
          },
          {
            "name": "c3_name",
            "dataType": "string",
            "sourceColumn": "c3_name"
          },
          {
            "name": "lxxl_type",
            "dataType": "int64",
            "sourceColumn": "lxxl_type"
          },
          {
            "name": "type",
            "dataType": "int64",
            "sourceColumn": "type"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_dim_budget = Source{[Schema=\"dbo\",Item=\"dim_budget\"]}[Data]",
                "in",
                "    dbo_dim_budget"
              ]
            }
          }
        ]
      },
      {
        "name": "dim_channel",
        "columns": [
          {
            "name": "c1",
            "dataType": "string",
            "sourceColumn": "c1"
          },
          {
            "name": "c2",
            "dataType": "string",
            "sourceColumn": "c2"
          },
          {
            "name": "c3",
            "dataType": "string",
            "sourceColumn": "c3"
          },
          {
            "name": "c4",
            "dataType": "string",
            "sourceColumn": "c4"
          },
          {
            "name": "c5",
            "dataType": "string",
            "sourceColumn": "c5"
          },
          {
            "name": "c6",
            "dataType": "string",
            "sourceColumn": "c6"
          },
          {
            "name": "c1_name",
            "dataType": "string",
            "sourceColumn": "c1_name"
          },
          {
            "name": "c2_name",
            "dataType": "string",
            "sourceColumn": "c2_name"
          },
          {
            "name": "c3_name",
            "dataType": "string",
            "sourceColumn": "c3_name"
          },
          {
            "name": "c4_name",
            "dataType": "string",
            "sourceColumn": "c4_name"
          },
          {
            "name": "c5_name",
            "dataType": "string",
            "sourceColumn": "c5_name"
          },
          {
            "name": "c6_name",
            "dataType": "string",
            "sourceColumn": "c6_name"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_dim_channel = Source{[Schema=\"dbo\",Item=\"dim_channel\"]}[Data]",
                "in",
                "    dbo_dim_channel"
              ]
            }
          }
        ]
      },
      {
        "name": "dim_cus",
        "columns": [
          {
            "name": "c1",
            "dataType": "string",
            "sourceColumn": "c1"
          },
          {
            "name": "c2",
            "dataType": "string",
            "sourceColumn": "c2"
          },
          {
            "name": "c3",
            "dataType": "string",
            "sourceColumn": "c3"
          },
          {
            "name": "c4",
            "dataType": "string",
            "sourceColumn": "c4"
          },
          {
            "name": "c5",
            "dataType": "string",
            "sourceColumn": "c5"
          },
          {
            "name": "c6",
            "dataType": "string",
            "sourceColumn": "c6"
          },
          {
            "name": "c1_name",
            "dataType": "string",
            "sourceColumn": "c1_name"
          },
          {
            "name": "c2_name",
            "dataType": "string",
            "sourceColumn": "c2_name"
          },
          {
            "name": "c3_name",
            "dataType": "string",
            "sourceColumn": "c3_name"
          },
          {
            "name": "c4_name",
            "dataType": "string",
            "sourceColumn": "c4_name"
          },
          {
            "name": "c5_name",
            "dataType": "string",
            "sourceColumn": "c5_name"
          },
          {
            "name": "c6_name",
            "dataType": "string",
            "sourceColumn": "c6_name"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_dim_cus = Source{[Schema=\"dbo\",Item=\"dim_cus\"]}[Data]",
                "in",
                "    dbo_dim_cus"
              ]
            }
          }
        ]
      },
      {
        "name": "dim_org",
        "columns": [
          {
            "name": "c1",
            "dataType": "string",
            "sourceColumn": "c1"
          },
          {
            "name": "c2",
            "dataType": "string",
            "sourceColumn": "c2"
          },
          {
            "name": "c3",
            "dataType": "string",
            "sourceColumn": "c3"
          },
          {
            "name": "c4",
            "dataType": "string",
            "sourceColumn": "c4"
          },
          {
            "name": "c5",
            "dataType": "string",
            "sourceColumn": "c5"
          },
          {
            "name": "c6",
            "dataType": "string",
            "sourceColumn": "c6"
          },
          {
            "name": "c1_name",
            "dataType": "string",
            "sourceColumn": "c1_name"
          },
          {
            "name": "c2_name",
            "dataType": "string",
            "sourceColumn": "c2_name"
          },
          {
            "name": "c3_name",
            "dataType": "string",
            "sourceColumn": "c3_name"
          },
          {
            "name": "c4_name",
            "dataType": "string",
            "sourceColumn": "c4_name"
          },
          {
            "name": "c5_name",
            "dataType": "string",
            "sourceColumn": "c5_name"
          },
          {
            "name": "c6_name",
            "dataType": "string",
            "sourceColumn": "c6_name"
          },
          {
            "name": "type",
            "dataType": "int64",
            "sourceColumn": "type"
          },
          {
            "name": "function_type",
            "dataType": "int64",
            "sourceColumn": "function_type"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_dim_org = Source{[Schema=\"dbo\",Item=\"dim_org\"]}[Data]",
                "in",
                "    dbo_dim_org"
              ]
            }
          }
        ]
      },
      {
        "name": "dim_product",
        "columns": [
          {
            "name": "c1",
            "dataType": "string",
            "sourceColumn": "c1"
          },
          {
            "name": "c2",
            "dataType": "string",
            "sourceColumn": "c2"
          },
          {
            "name": "c3",
            "dataType": "string",
            "sourceColumn": "c3"
          },
          {
            "name": "c4",
            "dataType": "string",
            "sourceColumn": "c4"
          },
          {
            "name": "c5",
            "dataType": "string",
            "sourceColumn": "c5"
          },
          {
            "name": "c6",
            "dataType": "string",
            "sourceColumn": "c6"
          },
          {
            "name": "c1_name",
            "dataType": "string",
            "sourceColumn": "c1_name"
          },
          {
            "name": "c2_name",
            "dataType": "string",
            "sourceColumn": "c2_name"
          },
          {
            "name": "c3_name",
            "dataType": "string",
            "sourceColumn": "c3_name"
          },
          {
            "name": "c4_name",
            "dataType": "string",
            "sourceColumn": "c4_name"
          },
          {
            "name": "c5_name",
            "dataType": "string",
            "sourceColumn": "c5_name"
          },
          {
            "name": "c6_name",
            "dataType": "string",
            "sourceColumn": "c6_name"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_dim_product = Source{[Schema=\"dbo\",Item=\"dim_product\"]}[Data]",
                "in",
                "    dbo_dim_product"
              ]
            }
          }
        ]
      },
      {
        "name": "dim_strategy_library",
        "columns": [
          {
            "name": "StrategyKey",
            "dataType": "int64",
            "sourceColumn": "StrategyKey"
          },
          {
            "name": "lxxl_type",
            "dataType": "int64",
            "sourceColumn": "lxxl_type"
          },
          {
            "name": "lxxl_level",
            "dataType": "int64",
            "sourceColumn": "lxxl_level"
          },
          {
            "name": "subject",
            "dataType": "string",
            "sourceColumn": "subject"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "rank",
            "dataType": "int64",
            "sourceColumn": "rank"
          },
          {
            "name": "strategy",
            "dataType": "string",
            "sourceColumn": "strategy"
          },
          {
            "name": "influencing_factor",
            "dataType": "string",
            "sourceColumn": "influencing_factor"
          },
          {
            "name": "status",
            "dataType": "int64",
            "sourceColumn": "status"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_dim_strategy_library = Source{[Schema=\"dbo\",Item=\"dim_strategy_library\"]}[Data]",
                "in",
                "    dbo_dim_strategy_library"
              ]
            }
          }
        ]
      },
      {
        "name": "dim_supply",
        "columns": [
          {
            "name": "c1",
            "dataType": "string",
            "sourceColumn": "c1"
          },
          {
            "name": "c2",
            "dataType": "string",
            "sourceColumn": "c2"
          },
          {
            "name": "c3",
            "dataType": "string",
            "sourceColumn": "c3"
          },
          {
            "name": "c4",
            "dataType": "string",
            "sourceColumn": "c4"
          },
          {
            "name": "c5",
            "dataType": "string",
            "sourceColumn": "c5"
          },
          {
            "name": "c6",
            "dataType": "string",
            "sourceColumn": "c6"
          },
          {
            "name": "c1_name",
            "dataType": "string",
            "sourceColumn": "c1_name"
          },
          {
            "name": "c2_name",
            "dataType": "string",
            "sourceColumn": "c2_name"
          },
          {
            "name": "c3_name",
            "dataType": "string",
            "sourceColumn": "c3_name"
          },
          {
            "name": "c4_name",
            "dataType": "string",
            "sourceColumn": "c4_name"
          },
          {
            "name": "c5_name",
            "dataType": "string",
            "sourceColumn": "c5_name"
          },
          {
            "name": "c6_name",
            "dataType": "string",
            "sourceColumn": "c6_name"
          },
          {
            "name": "type",
            "dataType": "int64",
            "sourceColumn": "type"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_dim_supply = Source{[Schema=\"dbo\",Item=\"dim_supply\"]}[Data]",
                "in",
                "    dbo_dim_supply"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_amount_repaid",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "ChannelKey",
            "dataType": "int64",
            "sourceColumn": "ChannelKey"
          },
          {
            "name": "repaid_amt",
            "dataType": "double",
            "sourceColumn": "repaid_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_amount_repaid = Source{[Schema=\"dbo\",Item=\"fact_amount_repaid\"]}[Data]",
                "in",
                "    dbo_fact_amount_repaid"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_application_fee",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "ChannelKey",
            "dataType": "int64",
            "sourceColumn": "ChannelKey"
          },
          {
            "name": "BudgetKey",
            "dataType": "int64",
            "sourceColumn": "BudgetKey"
          },
          {
            "name": "cost_amt",
            "dataType": "double",
            "sourceColumn": "cost_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_application_fee = Source{[Schema=\"dbo\",Item=\"fact_application_fee\"]}[Data]",
                "in",
                "    dbo_fact_application_fee"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_channel_costs",
        "columns": [
          {
            "name": "ChannelKey",
            "dataType": "int64",
            "sourceColumn": "ChannelKey"
          },
          {
            "name": "BudgetKey",
            "dataType": "int64",
            "sourceColumn": "BudgetKey"
          },
          {
            "name": "cost_amt",
            "dataType": "double",
            "sourceColumn": "cost_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_channel_costs = Source{[Schema=\"dbo\",Item=\"fact_channel_costs\"]}[Data]",
                "in",
                "    dbo_fact_channel_costs"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_company",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "dot_count",
            "dataType": "int64",
            "sourceColumn": "dot_count"
          },
          {
            "name": "dot_amt",
            "dataType": "double",
            "sourceColumn": "dot_amt"
          },
          {
            "name": "fixed_assets_amt",
            "dataType": "double",
            "sourceColumn": "fixed_assets_amt"
          },
          {
            "name": "cash_inflow_amt",
            "dataType": "double",
            "sourceColumn": "cash_inflow_amt"
          },
          {
            "name": "cash_out_amt",
            "dataType": "double",
            "sourceColumn": "cash_out_amt"
          },
          {
            "name": "receivable_amt",
            "dataType": "double",
            "sourceColumn": "receivable_amt"
          },
          {
            "name": "payable_amt",
            "dataType": "double",
            "sourceColumn": "payable_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_company = Source{[Schema=\"dbo\",Item=\"fact_company\"]}[Data]",
                "in",
                "    dbo_fact_company"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_customer",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "sale_amt",
            "dataType": "double",
            "sourceColumn": "sale_amt"
          },
          {
            "name": "cost_amt",
            "dataType": "double",
            "sourceColumn": "cost_amt"
          },
          {
            "name": "cus_cost_amt",
            "dataType": "double",
            "sourceColumn": "cus_cost_amt"
          },
          {
            "name": "redundancy",
            "dataType": "double",
            "sourceColumn": "redundancy"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_customer = Source{[Schema=\"dbo\",Item=\"fact_customer\"]}[Data]",
                "in",
                "    dbo_fact_customer"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_external_performance",
        "columns": [
          {
            "name": "SupplyKey",
            "dataType": "int64",
            "sourceColumn": "SupplyKey"
          },
          {
            "name": "capacity_score",
            "dataType": "double",
            "sourceColumn": "capacity_score"
          },
          {
            "name": "quality_score",
            "dataType": "double",
            "sourceColumn": "quality_score"
          },
          {
            "name": "value_for_money_score",
            "dataType": "double",
            "sourceColumn": "value_for_money_score"
          },
          {
            "name": "delivery_score",
            "dataType": "double",
            "sourceColumn": "delivery_score"
          },
          {
            "name": "efficiency_score",
            "dataType": "double",
            "sourceColumn": "efficiency_score"
          },
          {
            "name": "service_score",
            "dataType": "double",
            "sourceColumn": "service_score"
          },
          {
            "name": "finance_score",
            "dataType": "double",
            "sourceColumn": "finance_score"
          },
          {
            "name": "development_score",
            "dataType": "double",
            "sourceColumn": "development_score"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_external_performance = Source{[Schema=\"dbo\",Item=\"fact_external_performance\"]}[Data]",
                "in",
                "    dbo_fact_external_performance"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_fin_costs",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "cash_flow_amt",
            "dataType": "double",
            "sourceColumn": "cash_flow_amt"
          },
          {
            "name": "invest_amt",
            "dataType": "double",
            "sourceColumn": "invest_amt"
          },
          {
            "name": "total_assets_amt",
            "dataType": "double",
            "sourceColumn": "total_assets_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_fin_costs = Source{[Schema=\"dbo\",Item=\"fact_fin_costs\"]}[Data]",
                "in",
                "    dbo_fact_fin_costs"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_internal_plan",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "program_subjects",
            "dataType": "string",
            "sourceColumn": "program_subjects"
          },
          {
            "name": "StageStartDateKey",
            "dataType": "int64",
            "sourceColumn": "StageStartDateKey"
          },
          {
            "name": "StageEndDateKey",
            "dataType": "int64",
            "sourceColumn": "StageEndDateKey"
          },
          {
            "name": "result",
            "dataType": "string",
            "sourceColumn": "result"
          },
          {
            "name": "person",
            "dataType": "string",
            "sourceColumn": "person"
          },
          {
            "name": "FinishDateKey",
            "dataType": "int64",
            "sourceColumn": "FinishDateKey"
          },
          {
            "name": "is_finish",
            "dataType": "int64",
            "sourceColumn": "is_finish"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_internal_plan = Source{[Schema=\"dbo\",Item=\"fact_internal_plan\"]}[Data]",
                "in",
                "    dbo_fact_internal_plan"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_order",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "ChannelKey",
            "dataType": "int64",
            "sourceColumn": "ChannelKey"
          },
          {
            "name": "OrgProductKey",
            "dataType": "int64",
            "sourceColumn": "OrgProductKey"
          },
          {
            "name": "OrgChannelKey",
            "dataType": "int64",
            "sourceColumn": "OrgChannelKey"
          },
          {
            "name": "qty",
            "dataType": "double",
            "sourceColumn": "qty"
          },
          {
            "name": "order_amt",
            "dataType": "double",
            "sourceColumn": "order_amt"
          },
          {
            "name": "pay_amt",
            "dataType": "double",
            "sourceColumn": "pay_amt"
          },
          {
            "name": "cost_amt",
            "dataType": "double",
            "sourceColumn": "cost_amt"
          },
          {
            "name": "OrderDateKey",
            "dataType": "int64",
            "sourceColumn": "OrderDateKey"
          },
          {
            "name": "PayDateKey",
            "dataType": "int64",
            "sourceColumn": "PayDateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_order = Source{[Schema=\"dbo\",Item=\"fact_order\"]}[Data]",
                "in",
                "    dbo_fact_order"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_org_costs",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "BudgetKey",
            "dataType": "int64",
            "sourceColumn": "BudgetKey"
          },
          {
            "name": "cost_amt",
            "dataType": "double",
            "sourceColumn": "cost_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_org_costs = Source{[Schema=\"dbo\",Item=\"fact_org_costs\"]}[Data]",
                "in",
                "    dbo_fact_org_costs"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_performance",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "type",
            "dataType": "int64",
            "sourceColumn": "type"
          },
          {
            "name": "weights",
            "dataType": "double",
            "sourceColumn": "weights"
          },
          {
            "name": "score",
            "dataType": "double",
            "sourceColumn": "score"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_performance = Source{[Schema=\"dbo\",Item=\"fact_performance\"]}[Data]",
                "in",
                "    dbo_fact_performance"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_person_costs",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "BudgetKey",
            "dataType": "int64",
            "sourceColumn": "BudgetKey"
          },
          {
            "name": "cost_amt",
            "dataType": "double",
            "sourceColumn": "cost_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_person_costs = Source{[Schema=\"dbo\",Item=\"fact_person_costs\"]}[Data]",
                "in",
                "    dbo_fact_person_costs"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_stock",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "stock_qty",
            "dataType": "double",
            "sourceColumn": "stock_qty"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_stock = Source{[Schema=\"dbo\",Item=\"fact_stock\"]}[Data]",
                "in",
                "    dbo_fact_stock"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_strategy_log",
        "columns": [
          {
            "name": "StrategyKey",
            "dataType": "int64",
            "sourceColumn": "StrategyKey"
          },
          {
            "name": "rank_old",
            "dataType": "int64",
            "sourceColumn": "rank_old"
          },
          {
            "name": "rank_new",
            "dataType": "int64",
            "sourceColumn": "rank_new"
          },
          {
            "name": "value_old",
            "dataType": "double",
            "sourceColumn": "value_old"
          },
          {
            "name": "value_new",
            "dataType": "double",
            "sourceColumn": "value_new"
          },
          {
            "name": "useful",
            "dataType": "int64",
            "sourceColumn": "useful"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_strategy_log = Source{[Schema=\"dbo\",Item=\"fact_strategy_log\"]}[Data]",
                "in",
                "    dbo_fact_strategy_log"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_supply",
        "columns": [
          {
            "name": "SupplyKey",
            "dataType": "int64",
            "sourceColumn": "SupplyKey"
          },
          {
            "name": "sale_amt",
            "dataType": "double",
            "sourceColumn": "sale_amt"
          },
          {
            "name": "order_amt",
            "dataType": "double",
            "sourceColumn": "order_amt"
          },
          {
            "name": "planned_production_qty",
            "dataType": "double",
            "sourceColumn": "planned_production_qty"
          },
          {
            "name": "actual_production_qty",
            "dataType": "double",
            "sourceColumn": "actual_production_qty"
          },
          {
            "name": "defective_qty",
            "dataType": "double",
            "sourceColumn": "defective_qty"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_supply = Source{[Schema=\"dbo\",Item=\"fact_supply\"]}[Data]",
                "in",
                "    dbo_fact_supply"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_supply_order",
        "columns": [
          {
            "name": "SupplyKey",
            "dataType": "int64",
            "sourceColumn": "SupplyKey"
          },
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "order_prd_qty",
            "dataType": "double",
            "sourceColumn": "order_prd_qty"
          },
          {
            "name": "unit_cost",
            "dataType": "double",
            "sourceColumn": "unit_cost"
          },
          {
            "name": "type",
            "dataType": "int64",
            "sourceColumn": "type"
          },
          {
            "name": "OrderDateKey",
            "dataType": "int64",
            "sourceColumn": "OrderDateKey"
          },
          {
            "name": "PlanDateKey",
            "dataType": "int64",
            "sourceColumn": "PlanDateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_supply_order = Source{[Schema=\"dbo\",Item=\"fact_supply_order\"]}[Data]",
                "in",
                "    dbo_fact_supply_order"
              ]
            }
          }
        ]
      },
      {
        "name": "rank_channel_day",
        "columns": [
          {
            "name": "ChannelKey",
            "dataType": "int64",
            "sourceColumn": "ChannelKey"
          },
          {
            "name": "subject",
            "dataType": "string",
            "sourceColumn": "subject"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "real_value",
            "dataType": "double",
            "sourceColumn": "real_value"
          },
          {
            "name": "ring_value",
            "dataType": "double",
            "sourceColumn": "ring_value"
          },
          {
            "name": "yoy_value",
            "dataType": "double",
            "sourceColumn": "yoy_value"
          },
          {
            "name": "score",
            "dataType": "double",
            "sourceColumn": "score"
          },
          {
            "name": "rank",
            "dataType": "int64",
            "sourceColumn": "rank"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_rank_channel_day = Source{[Schema=\"dbo\",Item=\"rank_channel_day\"]}[Data]",
                "in",
                "    dbo_rank_channel_day"
              ]
            }
          }
        ]
      },
      {
        "name": "rank_channel_month",
        "columns": [
          {
            "name": "ChannelKey",
            "dataType": "int64",
            "sourceColumn": "ChannelKey"
          },
          {
            "name": "subject",
            "dataType": "string",
            "sourceColumn": "subject"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "real_value",
            "dataType": "double",
            "sourceColumn": "real_value"
          },
          {
            "name": "ring_value",
            "dataType": "double",
            "sourceColumn": "ring_value"
          },
          {
            "name": "yoy_value",
            "dataType": "double",
            "sourceColumn": "yoy_value"
          },
          {
            "name": "score",
            "dataType": "double",
            "sourceColumn": "score"
          },
          {
            "name": "rank",
            "dataType": "int64",
            "sourceColumn": "rank"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_rank_channel_month = Source{[Schema=\"dbo\",Item=\"rank_channel_month\"]}[Data]",
                "in",
                "    dbo_rank_channel_month"
              ]
            }
          }
        ]
      },
      {
        "name": "rank_customer_day",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "subject",
            "dataType": "string",
            "sourceColumn": "subject"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "real_value",
            "dataType": "double",
            "sourceColumn": "real_value"
          },
          {
            "name": "ring_value",
            "dataType": "double",
            "sourceColumn": "ring_value"
          },
          {
            "name": "yoy_value",
            "dataType": "double",
            "sourceColumn": "yoy_value"
          },
          {
            "name": "score",
            "dataType": "double",
            "sourceColumn": "score"
          },
          {
            "name": "rank",
            "dataType": "int64",
            "sourceColumn": "rank"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_rank_customer_day = Source{[Schema=\"dbo\",Item=\"rank_customer_day\"]}[Data]",
                "in",
                "    dbo_rank_customer_day"
              ]
            }
          }
        ]
      },
      {
        "name": "rank_customer_month",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "subject",
            "dataType": "string",
            "sourceColumn": "subject"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "real_value",
            "dataType": "double",
            "sourceColumn": "real_value"
          },
          {
            "name": "ring_value",
            "dataType": "double",
            "sourceColumn": "ring_value"
          },
          {
            "name": "yoy_value",
            "dataType": "double",
            "sourceColumn": "yoy_value"
          },
          {
            "name": "score",
            "dataType": "double",
            "sourceColumn": "score"
          },
          {
            "name": "rank",
            "dataType": "int64",
            "sourceColumn": "rank"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_rank_customer_month = Source{[Schema=\"dbo\",Item=\"rank_customer_month\"]}[Data]",
                "in",
                "    dbo_rank_customer_month"
              ]
            }
          }
        ]
      },
      {
        "name": "rank_finance_month",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "subject",
            "dataType": "string",
            "sourceColumn": "subject"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "real_value",
            "dataType": "double",
            "sourceColumn": "real_value"
          },
          {
            "name": "ring_value",
            "dataType": "double",
            "sourceColumn": "ring_value"
          },
          {
            "name": "yoy_value",
            "dataType": "double",
            "sourceColumn": "yoy_value"
          },
          {
            "name": "score",
            "dataType": "double",
            "sourceColumn": "score"
          },
          {
            "name": "rank",
            "dataType": "int64",
            "sourceColumn": "rank"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_rank_finance_month = Source{[Schema=\"dbo\",Item=\"rank_finance_month\"]}[Data]",
                "in",
                "    dbo_rank_finance_month"
              ]
            }
          }
        ]
      },
      {
        "name": "rank_org_month",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "subject",
            "dataType": "string",
            "sourceColumn": "subject"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "real_value",
            "dataType": "double",
            "sourceColumn": "real_value"
          },
          {
            "name": "ring_value",
            "dataType": "double",
            "sourceColumn": "ring_value"
          },
          {
            "name": "yoy_value",
            "dataType": "double",
            "sourceColumn": "yoy_value"
          },
          {
            "name": "score",
            "dataType": "double",
            "sourceColumn": "score"
          },
          {
            "name": "rank",
            "dataType": "int64",
            "sourceColumn": "rank"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_rank_org_month = Source{[Schema=\"dbo\",Item=\"rank_org_month\"]}[Data]",
                "in",
                "    dbo_rank_org_month"
              ]
            }
          }
        ]
      },
      {
        "name": "rank_product_day",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "subject",
            "dataType": "string",
            "sourceColumn": "subject"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "real_value",
            "dataType": "double",
            "sourceColumn": "real_value"
          },
          {
            "name": "ring_value",
            "dataType": "double",
            "sourceColumn": "ring_value"
          },
          {
            "name": "yoy_value",
            "dataType": "double",
            "sourceColumn": "yoy_value"
          },
          {
            "name": "score",
            "dataType": "double",
            "sourceColumn": "score"
          },
          {
            "name": "rank",
            "dataType": "int64",
            "sourceColumn": "rank"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_rank_product_day = Source{[Schema=\"dbo\",Item=\"rank_product_day\"]}[Data]",
                "in",
                "    dbo_rank_product_day"
              ]
            }
          }
        ]
      },
      {
        "name": "rank_product_month",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "subject",
            "dataType": "string",
            "sourceColumn": "subject"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "real_value",
            "dataType": "double",
            "sourceColumn": "real_value"
          },
          {
            "name": "ring_value",
            "dataType": "double",
            "sourceColumn": "ring_value"
          },
          {
            "name": "yoy_value",
            "dataType": "double",
            "sourceColumn": "yoy_value"
          },
          {
            "name": "score",
            "dataType": "double",
            "sourceColumn": "score"
          },
          {
            "name": "rank",
            "dataType": "int64",
            "sourceColumn": "rank"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_rank_product_month = Source{[Schema=\"dbo\",Item=\"rank_product_month\"]}[Data]",
                "in",
                "    dbo_rank_product_month"
              ]
            }
          }
        ]
      },
      {
        "name": "rank_supply_month",
        "columns": [
          {
            "name": "SupplyKey",
            "dataType": "int64",
            "sourceColumn": "SupplyKey"
          },
          {
            "name": "subject",
            "dataType": "string",
            "sourceColumn": "subject"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "real_value",
            "dataType": "double",
            "sourceColumn": "real_value"
          },
          {
            "name": "ring_value",
            "dataType": "double",
            "sourceColumn": "ring_value"
          },
          {
            "name": "yoy_value",
            "dataType": "double",
            "sourceColumn": "yoy_value"
          },
          {
            "name": "score",
            "dataType": "double",
            "sourceColumn": "score"
          },
          {
            "name": "rank",
            "dataType": "int64",
            "sourceColumn": "rank"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_rank_supply_month = Source{[Schema=\"dbo\",Item=\"rank_supply_month\"]}[Data]",
                "in",
                "    dbo_rank_supply_month"
              ]
            }
          }
        ]
      },
      {
        "name": "target_budget",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "BudgetKey",
            "dataType": "int64",
            "sourceColumn": "BudgetKey"
          },
          {
            "name": "target_cost_amt",
            "dataType": "double",
            "sourceColumn": "target_cost_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_target_budget = Source{[Schema=\"dbo\",Item=\"target_budget\"]}[Data]",
                "in",
                "    dbo_target_budget"
              ]
            }
          }
        ]
      },
      {
        "name": "target_channel",
        "columns": [
          {
            "name": "ChannelKey",
            "dataType": "int64",
            "sourceColumn": "ChannelKey"
          },
          {
            "name": "target_sale_amt",
            "dataType": "double",
            "sourceColumn": "target_sale_amt"
          },
          {
            "name": "target_cost_amt",
            "dataType": "double",
            "sourceColumn": "target_cost_amt"
          },
          {
            "name": "target_profit_amt",
            "dataType": "double",
            "sourceColumn": "target_profit_amt"
          },
          {
            "name": "target_redundancy_amt",
            "dataType": "double",
            "sourceColumn": "target_redundancy_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_target_channel = Source{[Schema=\"dbo\",Item=\"target_channel\"]}[Data]",
                "in",
                "    dbo_target_channel"
              ]
            }
          }
        ]
      },
      {
        "name": "target_company",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "target_dot_count",
            "dataType": "int64",
            "sourceColumn": "target_dot_count"
          },
          {
            "name": "target_dot_amt",
            "dataType": "double",
            "sourceColumn": "target_dot_amt"
          },
          {
            "name": "target_fixed_assets_amt",
            "dataType": "double",
            "sourceColumn": "target_fixed_assets_amt"
          },
          {
            "name": "target_cash_inflow_amt",
            "dataType": "double",
            "sourceColumn": "target_cash_inflow_amt"
          },
          {
            "name": "target_cash_out_amt",
            "dataType": "double",
            "sourceColumn": "target_cash_out_amt"
          },
          {
            "name": "target_receivable_amt",
            "dataType": "double",
            "sourceColumn": "target_receivable_amt"
          },
          {
            "name": "target_payable_amt",
            "dataType": "double",
            "sourceColumn": "target_payable_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_target_company = Source{[Schema=\"dbo\",Item=\"target_company\"]}[Data]",
                "in",
                "    dbo_target_company"
              ]
            }
          }
        ]
      },
      {
        "name": "target_customer",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "target_sale_amt",
            "dataType": "double",
            "sourceColumn": "target_sale_amt"
          },
          {
            "name": "target_cost_amt",
            "dataType": "double",
            "sourceColumn": "target_cost_amt"
          },
          {
            "name": "target_profit_amt",
            "dataType": "double",
            "sourceColumn": "target_profit_amt"
          },
          {
            "name": "target_redundancy",
            "dataType": "double",
            "sourceColumn": "target_redundancy"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_target_customer = Source{[Schema=\"dbo\",Item=\"target_customer\"]}[Data]",
                "in",
                "    dbo_target_customer"
              ]
            }
          }
        ]
      },
      {
        "name": "target_finance",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "target_sale_amt",
            "dataType": "double",
            "sourceColumn": "target_sale_amt"
          },
          {
            "name": "target_total_cost_amt",
            "dataType": "double",
            "sourceColumn": "target_total_cost_amt"
          },
          {
            "name": "target_return_amt",
            "dataType": "double",
            "sourceColumn": "target_return_amt"
          },
          {
            "name": "target_invest_amt",
            "dataType": "double",
            "sourceColumn": "target_invest_amt"
          },
          {
            "name": "target_total_assets_amt",
            "dataType": "double",
            "sourceColumn": "target_total_assets_amt"
          },
          {
            "name": "target_cash_flow_amt",
            "dataType": "double",
            "sourceColumn": "target_cash_flow_amt"
          },
          {
            "name": "target_redundancy",
            "dataType": "double",
            "sourceColumn": "target_redundancy"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_target_finance = Source{[Schema=\"dbo\",Item=\"target_finance\"]}[Data]",
                "in",
                "    dbo_target_finance"
              ]
            }
          }
        ]
      },
      {
        "name": "target_org",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "target_sale_amt",
            "dataType": "double",
            "sourceColumn": "target_sale_amt"
          },
          {
            "name": "target_cost_amt",
            "dataType": "double",
            "sourceColumn": "target_cost_amt"
          },
          {
            "name": "target_profit_amt",
            "dataType": "double",
            "sourceColumn": "target_profit_amt"
          },
          {
            "name": "target_redundancy",
            "dataType": "double",
            "sourceColumn": "target_redundancy"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_target_org = Source{[Schema=\"dbo\",Item=\"target_org\"]}[Data]",
                "in",
                "    dbo_target_org"
              ]
            }
          }
        ]
      },
      {
        "name": "target_product",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "target_sale_amt",
            "dataType": "double",
            "sourceColumn": "target_sale_amt"
          },
          {
            "name": "target_cost_amt",
            "dataType": "double",
            "sourceColumn": "target_cost_amt"
          },
          {
            "name": "target_stock_amt",
            "dataType": "double",
            "sourceColumn": "target_stock_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_target_product = Source{[Schema=\"dbo\",Item=\"target_product\"]}[Data]",
                "in",
                "    dbo_target_product"
              ]
            }
          }
        ]
      },
      {
        "name": "target_supply",
        "columns": [
          {
            "name": "SupplyKey",
            "dataType": "int64",
            "sourceColumn": "SupplyKey"
          },
          {
            "name": "target_sale_amt",
            "dataType": "double",
            "sourceColumn": "target_sale_amt"
          },
          {
            "name": "target_profit_amt",
            "dataType": "double",
            "sourceColumn": "target_profit_amt"
          },
          {
            "name": "target_production_capacity",
            "dataType": "double",
            "sourceColumn": "target_production_capacity"
          },
          {
            "name": "target_production_ratio",
            "dataType": "double",
            "sourceColumn": "target_production_ratio"
          },
          {
            "name": "target_delivery_rate",
            "dataType": "double",
            "sourceColumn": "target_delivery_rate"
          },
          {
            "name": "target_residual_rate",
            "dataType": "double",
            "sourceColumn": "target_residual_rate"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_target_supply = Source{[Schema=\"dbo\",Item=\"target_supply\"]}[Data]",
                "in",
                "    dbo_target_supply"
              ]
            }
          }
        ]
      },
      {
        "name": "target_supply_order",
        "columns": [
          {
            "name": "SupplyKey",
            "dataType": "int64",
            "sourceColumn": "SupplyKey"
          },
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "target_order_prd_qty",
            "dataType": "double",
            "sourceColumn": "target_order_prd_qty"
          },
          {
            "name": "target_amt",
            "dataType": "double",
            "sourceColumn": "target_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_target_supply_order = Source{[Schema=\"dbo\",Item=\"target_supply_order\"]}[Data]",
                "in",
                "    dbo_target_supply_order"
              ]
            }
          }
        ]
      },
      {
        "name": "_",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "7",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "_",
            "expression": [
              "[_]-[_]",
              ""
            ]
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "  [_]-[_]"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_",
            "expression": " SUMX('target_product','target_product'[target_sale_amt])"
          },
          {
            "name": "_",
            "expression": " SUMX('fact_order','fact_order'[pay_amt])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_",
            "expression": " SUMX('target_product','target_product'[target_cost_amt])"
          },
          {
            "name": "_",
            "expression": " SUMX('fact_order',('fact_order'[qty] * 'fact_order'[cost_amt]))"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_",
            "expression": " DIVIDE([_], DIVIDE(([]+[]),2))"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_], DIVIDE(([]+[]),2))"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "  [_]-[_]"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],'_'[])"
          },
          {
            "name": "_",
            "expression": "  DIVIDE([_],'_'[])"
          },
          {
            "name": "_",
            "expression": "  DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_",
            "expression": " SUMX('target_product','target_product'[target_stock_amt])"
          },
          {
            "name": "_",
            "expression": " 1"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "",
            "expression": [
              "",
              "VAR FIRST = FIRSTDATE('DimDate'[FullDate])",
              "RETURN",
              "CALCULATE ([], 'DimDate'[FullDate] = FIRST)"
            ]
          },
          {
            "name": "",
            "expression": [
              "",
              "VAR FIRST = FIRSTDATE('DimDate'[FullDate])",
              "RETURN",
              "CALCULATE ([], 'DimDate'[FullDate] = FIRST)"
            ]
          },
          {
            "name": "",
            "expression": [
              "",
              "VAR LAST = LASTDATE('DimDate'[FullDate])",
              "RETURN",
              "CALCULATE ([], 'DimDate'[FullDate] = LAST)"
            ]
          },
          {
            "name": "",
            "expression": [
              "",
              "VAR LAST = LASTDATE('DimDate'[FullDate])",
              "RETURN",
              "CALCULATE ([], 'DimDate'[FullDate] = LAST)"
            ]
          },
          {
            "name": "",
            "expression": "[]* [_]"
          },
          {
            "name": "",
            "expression": "[]* [_]"
          },
          {
            "name": "",
            "expression": "3"
          },
          {
            "name": "",
            "expression": "SUMX('fact_stock','fact_stock'[stock_qty])"
          }
        ]
      },
      {
        "name": "DimDate",
        "columns": [
          {
            "name": "FullDate",
            "dataType": "dateTime",
            "sourceColumn": "FullDate"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          },
          {
            "name": "DateNameEn",
            "dataType": "string",
            "sourceColumn": "DateNameEn"
          },
          {
            "name": "DateNameCn",
            "dataType": "string",
            "sourceColumn": "DateNameCn"
          },
          {
            "name": "WeekKey",
            "dataType": "int64",
            "sourceColumn": "WeekKey"
          },
          {
            "name": "WeekNameEn",
            "dataType": "string",
            "sourceColumn": "WeekNameEn"
          },
          {
            "name": "WeekNameEnShort",
            "dataType": "string",
            "sourceColumn": "WeekNameEnShort"
          },
          {
            "name": "WeekNameCn",
            "dataType": "string",
            "sourceColumn": "WeekNameCn"
          },
          {
            "name": "WeekNameCnShort",
            "dataType": "string",
            "sourceColumn": "WeekNameCnShort"
          },
          {
            "name": "WeekOfYear",
            "dataType": "int64",
            "sourceColumn": "WeekOfYear"
          },
          {
            "name": "WeekDayNameEn",
            "dataType": "string",
            "sourceColumn": "WeekDayNameEn"
          },
          {
            "name": "WeekDayNameEnShort",
            "dataType": "string",
            "sourceColumn": "WeekDayNameEnShort"
          },
          {
            "name": "WeekDayNameCn",
            "dataType": "string",
            "sourceColumn": "WeekDayNameCn"
          },
          {
            "name": "WeekDayNameCnShort",
            "dataType": "string",
            "sourceColumn": "WeekDayNameCnShort"
          },
          {
            "name": "MonthKey",
            "dataType": "int64",
            "sourceColumn": "MonthKey"
          },
          {
            "name": "MonthOfYear",
            "dataType": "int64",
            "sourceColumn": "MonthOfYear"
          },
          {
            "name": "MonthNameEn",
            "dataType": "string",
            "sourceColumn": "MonthNameEn"
          },
          {
            "name": "MonthNameEnShort",
            "dataType": "string",
            "sourceColumn": "MonthNameEnShort"
          },
          {
            "name": "MonthNameCn",
            "dataType": "string",
            "sourceColumn": "MonthNameCn"
          },
          {
            "name": "MonthNameCnShort",
            "dataType": "string",
            "sourceColumn": "MonthNameCnShort"
          },
          {
            "name": "QuarterKey",
            "dataType": "int64",
            "sourceColumn": "QuarterKey"
          },
          {
            "name": "QuarterOfYear",
            "dataType": "int64",
            "sourceColumn": "QuarterOfYear"
          },
          {
            "name": "QuarterNameEn",
            "dataType": "string",
            "sourceColumn": "QuarterNameEn"
          },
          {
            "name": "QuarterNameEnShort",
            "dataType": "string",
            "sourceColumn": "QuarterNameEnShort"
          },
          {
            "name": "QuarterNameCn",
            "dataType": "string",
            "sourceColumn": "QuarterNameCn"
          },
          {
            "name": "QuarterNameCnShort",
            "dataType": "string",
            "sourceColumn": "QuarterNameCnShort"
          },
          {
            "name": "YearKey",
            "dataType": "int64",
            "sourceColumn": "YearKey"
          },
          {
            "name": "YearNameEn",
            "dataType": "string",
            "sourceColumn": "YearNameEn"
          },
          {
            "name": "YearNameCn",
            "dataType": "string",
            "sourceColumn": "YearNameCn"
          },
          {
            "name": "DayOfWeek",
            "dataType": "int64",
            "sourceColumn": "DayOfWeek"
          },
          {
            "name": "DayOfMonth",
            "dataType": "int64",
            "sourceColumn": "DayOfMonth"
          },
          {
            "name": "DayOfQuarter",
            "dataType": "int64",
            "sourceColumn": "DayOfQuarter"
          },
          {
            "name": "DayOfYear",
            "dataType": "int64",
            "sourceColumn": "DayOfYear"
          },
          {
            "name": "InsertDatetime",
            "dataType": "dateTime",
            "sourceColumn": "InsertDatetime"
          },
          {
            "name": "UpdateDatetime",
            "dataType": "dateTime",
            "sourceColumn": "UpdateDatetime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_DimDate = Source{[Schema=\"dbo\",Item=\"DimDate\"]}[Data]",
                "in",
                "    dbo_DimDate"
              ]
            }
          }
        ]
      },
      {
        "name": "_",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"\" ,   [_],) , ",
                "    ( \"\" , [_], ),",
                "    ( \"(2-)\" , 2-[_], ),",
                "    ( \"\" , [_], ),",
                "    ( \"\" , [_], ),",
                "    ( \"\" , [_], ),",
                "    ( \"(2-)\" , 2-[_], )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"\" , [Value1] , \"\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "_",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "6",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "_",
            "expression": " SUMX('target_channel','target_channel'[target_profit_amt])"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_",
            "expression": " SUMX('target_channel','target_channel'[target_sale_amt])"
          },
          {
            "name": "_",
            "expression": " SUMX('fact_order','fact_order'[pay_amt])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "  [_]-[_]"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_",
            "expression": " SUMX('target_channel','target_channel'[target_cost_amt])"
          },
          {
            "name": "_",
            "expression": " SUMX('fact_channel_costs','fact_channel_costs'[cost_amt])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_",
            "expression": "  SUMX('target_channel','target_channel'[target_redundancy_amt])"
          },
          {
            "name": "_",
            "expression": "  IF([_]>0,0,[_])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "  [_]-[_]"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],'_'[])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],'_'[])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "  [_]-[_]"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          }
        ]
      },
      {
        "name": "_",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"\" ,   [_],) , ",
                "    ( \"\" , [_], ),",
                "    ( \"(2-)\" , 2-[_], ),",
                "    ( \"\" , [_], ),",
                "    ( \"\" ,[_], ),",
                "    ( \"\" , [_], )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"\" , [Value1] , \"\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "_",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "6",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_",
            "expression": " SUMX('target_customer','target_customer'[target_sale_amt])"
          },
          {
            "name": "_",
            "expression": " SUMX('fact_customer','fact_customer'[sale_amt])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "  [_]-[_]"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_",
            "expression": "  SUMX('target_customer','target_customer'[target_cost_amt])"
          },
          {
            "name": "_",
            "expression": " SUMX('fact_customer','fact_customer'[cus_cost_amt])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "__",
            "expression": [
              "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
              "",
              ""
            ]
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))",
              "",
              ""
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_",
            "expression": "  DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "  DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_",
            "expression": "  SUMX('target_customer','target_customer'[target_redundancy])"
          },
          {
            "name": "_",
            "expression": "  SUMX('fact_customer','fact_customer'[redundancy])"
          },
          {
            "name": "_",
            "expression": "  DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],'_'[])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],'_'[])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "  [_]-[_]"
          },
          {
            "name": "__",
            "expression": [
              "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
              ""
            ]
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))",
              ""
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          }
        ]
      },
      {
        "name": "_",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"\" , [_], ),",
                "    ( \"\" ,   [_],) , ",
                "    ( \"(2-)\" , 2-[_], ),",
                "    ( \"\" ,[_], ),",
                "    ( \"\" , [_], ),",
                "    ( \"\" , [_], )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"\" , [Value1] , \"\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "_",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "7",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "_",
            "expression": " SUMX('target_supply','target_supply'[target_sale_amt])"
          },
          {
            "name": "_",
            "expression": " SUMX('fact_supply','fact_supply'[sale_amt])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "__",
            "expression": [
              "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
              ""
            ]
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],  DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_",
            "expression": " SUMX('target_supply','target_supply'[target_profit_amt])"
          },
          {
            "name": "_",
            "expression": " [_]-[]"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "__",
            "expression": [
              "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
              ""
            ]
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_",
            "expression": " SUMX('target_supply','target_supply'[target_production_capacity])"
          },
          {
            "name": "_",
            "expression": " []"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "  [_]-[_]"
          },
          {
            "name": "__",
            "expression": [
              "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
              "",
              ""
            ]
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))",
              "",
              ""
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_",
            "expression": " SUMX('target_supply','target_supply'[target_production_ratio])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([],[_])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "  [_]-[_]"
          },
          {
            "name": "__",
            "expression": [
              "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
              "",
              ""
            ]
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))",
              ""
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))",
              "",
              ""
            ]
          },
          {
            "name": "_",
            "expression": " [_]-[]"
          },
          {
            "name": "_",
            "expression": "  [_]-[]"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "  [_]-[_]"
          },
          {
            "name": "__",
            "expression": [
              "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
              "",
              ""
            ]
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))",
              "",
              ""
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))",
              ""
            ]
          },
          {
            "name": "_",
            "expression": " SUMX('target_supply','target_supply'[target_residual_rate])"
          },
          {
            "name": "_",
            "expression": " DIVIDE(SUMX('fact_supply','fact_supply'[defective_qty]),[])"
          },
          {
            "name": "",
            "expression": "SUMX('fact_supply','fact_supply'[order_amt])"
          },
          {
            "name": "",
            "expression": "SUMX('fact_supply','fact_supply'[actual_production_qty])"
          },
          {
            "name": "",
            "expression": "SUMX('fact_supply','fact_supply'[planned_production_qty])"
          },
          {
            "name": "_",
            "expression": " SUMX('target_supply','target_supply'[target_delivery_rate])"
          },
          {
            "name": "_",
            "expression": " 1"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "_",
            "expression": " CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "_",
            "expression": " CALCULATE([_],DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_",
            "expression": [
              "IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[_]),[_])))"
            ]
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": [
              "IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[_]),[_])))"
            ]
          },
          {
            "name": "_",
            "expression": "  DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))",
              ""
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          }
        ]
      },
      {
        "name": "_",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": " ",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "",
            "expression": " DATEDIFF(MIN('DimDate'[FullDate]),MAX('DimDate'[FullDate]),DAY) +1"
          }
        ]
      },
      {
        "name": "_",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"\" ,   [_],) , ",
                "    ( \"\" , [_], ),",
                "    ( \"\" , [_], ),",
                "    ( \"\" , [_], ),",
                "    ( \"\" , [_], ),",
                "    ( \"(2-)\" , 2-[_], ),",
                "    ( \"\" , [_], )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"\" , [Value1] , \"\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "_",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "9",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "8",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "7",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "4",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "VAR LAST = LASTDATE('DimDate'[FullDate])",
              "RETURN",
              "CALCULATE ([], 'DimDate'[FullDate] = LAST)"
            ]
          },
          {
            "type": "calculated",
            "name": "3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "Calculated Column 1",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "_",
            "expression": "SUMX('target_finance','target_finance'[target_redundancy])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_], DIVIDE(([_]+[_]),2))"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "  [_]-[_]"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_",
            "expression": " [_]+[_]+[_]"
          },
          {
            "name": "_",
            "expression": "IF([_]<=0,[_],0)"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "  [_]-[_]"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_",
            "expression": "[_]"
          },
          {
            "name": "_",
            "expression": " SUMX('fact_amount_repaid','fact_amount_repaid'[repaid_amt])"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "  DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "  DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "  [_]-[_]"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "_",
            "expression": "  [_]-[_]"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "_",
            "expression": "  [_]-[_]"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "_",
            "expression": "  [_]-[_]"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_",
            "expression": "SUMX('target_finance','target_finance'[target_total_assets_amt])"
          },
          {
            "name": "_",
            "expression": "SUMX('target_finance','target_finance'[target_invest_amt])"
          },
          {
            "name": "_",
            "expression": " SUMX('target_finance','target_finance'[target_total_cost_amt])"
          },
          {
            "name": "_",
            "expression": "SUMX('target_finance','target_finance'[target_sale_amt])"
          },
          {
            "name": "_",
            "expression": " SUMX('target_finance','target_finance'[target_return_amt])"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "_",
            "expression": " DIVIDE( [_],[_])"
          },
          {
            "name": "_",
            "expression": "SUMX('target_finance','target_finance'[target_cash_flow_amt])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_], DIVIDE(([_]+[_]),2))"
          },
          {
            "name": "_",
            "expression": [
              "",
              "VAR FIRST = FIRSTDATE('DimDate'[FullDate])",
              "RETURN",
              "CALCULATE ([_], 'DimDate'[FullDate] = FIRST)"
            ]
          },
          {
            "name": "_",
            "expression": [
              "",
              "VAR LAST = LASTDATE('DimDate'[FullDate])",
              "RETURN",
              "CALCULATE ([_], 'DimDate'[FullDate] = LAST)"
            ]
          },
          {
            "name": "_",
            "expression": "SUMX('fact_fin_costs','fact_fin_costs'[total_assets_amt])"
          },
          {
            "name": "_",
            "expression": [
              "",
              "VAR FIRST = FIRSTDATE('DimDate'[FullDate])",
              "RETURN",
              "CALCULATE ([_], 'DimDate'[FullDate] = FIRST)"
            ]
          },
          {
            "name": "_",
            "expression": [
              "",
              "VAR LAST = LASTDATE('DimDate'[FullDate])",
              "RETURN",
              "CALCULATE ([_], 'DimDate'[FullDate] = LAST)"
            ]
          },
          {
            "name": "_",
            "expression": "SUMX('fact_company','fact_company'[cash_inflow_amt])"
          },
          {
            "name": "_",
            "expression": "SUMX('fact_company','fact_company'[cash_out_amt])"
          },
          {
            "name": "_",
            "expression": "SUMX('fact_fin_costs','fact_fin_costs'[invest_amt])"
          },
          {
            "name": "_",
            "expression": "SUMX('target_company','target_company'[target_cash_inflow_amt])"
          },
          {
            "name": "_",
            "expression": "SUMX('target_company','target_company'[target_cash_out_amt])"
          }
        ]
      },
      {
        "name": "_",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "6",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "1",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "_",
            "expression": " SUMX('target_org','target_org'[target_sale_amt])"
          },
          {
            "name": "_",
            "expression": " [_]"
          },
          {
            "name": "_",
            "expression": "  DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_",
            "expression": "SUMX('target_org','target_org'[target_cost_amt])"
          },
          {
            "name": "_",
            "expression": "SUMX('fact_org_costs','fact_org_costs'[cost_amt])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_",
            "expression": "  DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "  DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "  [_]-[_]"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],'_'[])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],'_'[])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          },
          {
            "name": "_",
            "expression": " SUMX('target_org','target_org'[target_redundancy])"
          },
          {
            "name": "_",
            "expression": " 1"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " [_]-[_]"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "\tISBLANK([_]),\t",
              "\t0,",
              "   \t(DIVIDE(([_]-[__]), [__])))"
            ]
          },
          {
            "name": "_ %",
            "expression": [
              " IF(",
              "    \tISBLANK([_]),",
              "   \t 0,",
              "\tDIVIDE(([_]-[__]),[__]))"
            ]
          }
        ]
      },
      {
        "name": "_",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"(2-)\" , 2-[_], ),",
                "    ( \"\" ,   [_],) , ",
                "    ( \"\" , [_], ),",
                "    ( \"\" , [_], ),",
                "    ( \"\" , [_], ),",
                "    ( \"\" , [_], ),",
                "    ( \"\" , [_],),",
                "    ( \"\" , [_],),",
                "    ( \"\" , [_], )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"\" , [Value1] , \"\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "_",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"\" , [_], ),",
                "    ( \"\" ,   [_],) , ",
                "    ( \"(2-)\" , 2-[_], ),",
                "    ( \"\" , [_], ),",
                "    ( \"\" , [_], ),",
                "    ( \"\" , [_], )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"\" , [Value1] , \"\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "_",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "3",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "1",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "_",
            "expression": "[_]"
          },
          {
            "name": "_",
            "expression": "[_]"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE('_'[_],'_'[_])"
          },
          {
            "name": "__",
            "expression": [
              "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))",
              ""
            ]
          },
          {
            "name": "__",
            "expression": [
              "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))",
              ""
            ]
          },
          {
            "name": "_",
            "expression": "[_]-[__]"
          },
          {
            "name": "_",
            "expression": "[_]-[__]"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[__])"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[__])"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          }
        ]
      },
      {
        "name": "_",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": " ",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ]
      },
      {
        "name": "__",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "8",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "7",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "1",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "1"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "__SKU",
            "expression": "1"
          },
          {
            "name": "__SKU",
            "expression": "1"
          },
          {
            "name": "__SKU",
            "expression": "[__SKU]-[__SKU]"
          },
          {
            "name": "__SKU",
            "expression": [
              "DIVIDE([__SKU],[__SKU])",
              ""
            ]
          },
          {
            "name": "__",
            "expression": "DIVIDE([_],[__SKU])"
          },
          {
            "name": "__",
            "expression": "DIVIDE([_],[__SKU])"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__SKU])"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__SKU])"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__SKU])"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__SKU])"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          }
        ]
      },
      {
        "name": "__",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "7",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "1",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "__",
            "expression": "1"
          },
          {
            "name": "__",
            "expression": [
              "1",
              ""
            ]
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": [
              "DIVIDE([__],[__])",
              ""
            ]
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": [
              " ",
              "\t",
              "\tSWITCH (",
              "    \t\tTRUE (),",
              "    \t\t[__]<0, [__],",
              "\t\tAND([__]>0, [__]<1), [__]-[__],",
              "    \t\t[__]>1, 0\t)"
            ]
          },
          {
            "name": "__",
            "expression": [
              " ",
              "\t",
              "\tSWITCH (",
              "    \t\tTRUE (),",
              "    \t\t[__]<0, [__],",
              "\t\tAND([__]>0, [__]<1), [__]-[__],",
              "    \t\t[__]>1, 0\t)"
            ]
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          }
        ]
      },
      {
        "name": "__",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "7",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "1",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "__",
            "expression": "1"
          },
          {
            "name": "__",
            "expression": "1"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          }
        ]
      },
      {
        "name": "__",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "7",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "Column1",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "1"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "__",
            "expression": "1"
          },
          {
            "name": "__",
            "expression": "1"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          }
        ]
      },
      {
        "name": "__",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "7",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "5",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "1"
          },
          {
            "type": "calculated",
            "name": "4",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": "[_]"
          },
          {
            "type": "calculated",
            "name": "3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "1",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "__",
            "expression": "1"
          },
          {
            "name": "__",
            "expression": "1"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": " DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": " DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": " DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": " DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[]"
          },
          {
            "name": "__",
            "expression": "SUMX('fact_supply','fact_supply'[planned_production_qty])"
          },
          {
            "name": "__",
            "expression": " DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": " DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          }
        ]
      },
      {
        "name": "__",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": " ",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "Calculated Column 2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "Calculated Column 3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "Calculated Column 4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "Calculated Column 5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "Calculated Column 6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "Calculated Column 7",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "Calculated Column 8",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "Calculated Column 9",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[_]"
          },
          {
            "name": "__",
            "expression": "[__]-[__]"
          },
          {
            "name": "__",
            "expression": "DIVIDE([__],[__])"
          }
        ]
      },
      {
        "name": "_",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": " ",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "Calculated Column 10",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "Calculated Column 11",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "Calculated Column 12",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "_",
            "expression": "1-[_]"
          },
          {
            "name": "_",
            "expression": "1-[_]"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "SUMX('target_company','target_company'[target_dot_count])"
          },
          {
            "name": "_",
            "expression": "SUMX('fact_company','fact_company'[dot_count])"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "SUMX('target_company','target_company'[target_dot_amt])"
          },
          {
            "name": "_",
            "expression": "SUMX('fact_company','fact_company'[dot_amt])"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "DIVIDE('_'[_],'_'[_])"
          },
          {
            "name": "_",
            "expression": "DIVIDE('_'[_],'_'[_])"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          }
        ]
      },
      {
        "name": "_",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "9",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "8",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "7",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "1",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "_",
            "expression": "[_]"
          },
          {
            "name": "_",
            "expression": "SUMX('fact_order','fact_order'[order_amt])"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_",
            "expression": "[_]-[__]"
          },
          {
            "name": "_",
            "expression": "[_]-[__]"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[__])"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[__])"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "[_]"
          },
          {
            "name": "_",
            "expression": "[_]"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_",
            "expression": "[_]-[__]"
          },
          {
            "name": "_",
            "expression": "[_]-[__]"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[__])"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[__])"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "[_]"
          },
          {
            "name": "_",
            "expression": "[_]"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "1"
          },
          {
            "name": "_",
            "expression": "1"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          }
        ]
      },
      {
        "name": "_",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "8",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "7",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "1",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "_",
            "expression": "DIVIDE('_'[_],'_'[_])"
          },
          {
            "name": "_",
            "expression": "DIVIDE('_'[_],'_'[_])"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "[_]"
          },
          {
            "name": "_",
            "expression": "[_]"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "__",
            "expression": [
              "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))",
              ""
            ]
          },
          {
            "name": "__",
            "expression": [
              "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))",
              ""
            ]
          },
          {
            "name": "_",
            "expression": "[_]-[__]"
          },
          {
            "name": "_",
            "expression": "[_]-[__]"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[__])"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[__])"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "[_]"
          },
          {
            "name": "_",
            "expression": "[_]"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_",
            "expression": "[_]-[__]"
          },
          {
            "name": "_",
            "expression": "[_]-[__]"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[__])"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[__])"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": " DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          }
        ]
      },
      {
        "name": "_",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "13",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "122",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "11",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "10",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "9",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "8",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "7",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "12",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "_",
            "expression": "[_]"
          },
          {
            "name": "_",
            "expression": "[_]"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "SUMX('target_company','target_company'[target_fixed_assets_amt])"
          },
          {
            "name": "_",
            "expression": "SUMX('target_company','target_company'[target_fixed_assets_amt])"
          },
          {
            "name": "_",
            "expression": "[_]"
          },
          {
            "name": "_",
            "expression": "[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "[_]"
          },
          {
            "name": "_",
            "expression": "[_]"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "[_]"
          },
          {
            "name": "_",
            "expression": "[_]"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "[_]"
          },
          {
            "name": "_",
            "expression": "[_]"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "SUMX('target_company','target_company'[target_receivable_amt])"
          },
          {
            "name": "_",
            "expression": "SUMX('fact_company','fact_company'[receivable_amt])"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_",
            "expression": "[_]-[__]"
          },
          {
            "name": "_",
            "expression": "[_]-[__]"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[__])"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[__])"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "SUMX('target_company','target_company'[target_payable_amt])"
          },
          {
            "name": "_",
            "expression": "SUMX('fact_company','fact_company'[payable_amt])"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "__",
            "expression": "CALCULATE([_], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "_",
            "expression": "[_]-[__]"
          },
          {
            "name": "_",
            "expression": "[_]-[__]"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[__])"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[__])"
          },
          {
            "name": "_",
            "expression": "[_]-[_]"
          },
          {
            "name": "_",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_1",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_1",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_1",
            "expression": "[_1]-[_1]"
          },
          {
            "name": "_1",
            "expression": "DIVIDE([_1],[_1])"
          },
          {
            "name": "_2",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_2",
            "expression": "DIVIDE([_],[_])"
          },
          {
            "name": "_2",
            "expression": "[_2]-[_2]"
          },
          {
            "name": "_2",
            "expression": "DIVIDE([_2],[_2])"
          }
        ]
      },
      {
        "name": "_",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"\" ,   [_],) , ",
                "    ( \"\" , [_],) , ",
                "    ( \"\" ,[_],) , ",
                "    ( \"\" ,[_],)",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"\" , [Value1] , \"\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "_",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"\" ,   [_],) , ",
                "    ( \"\" , [_],) , ",
                "    ( \"\" ,[_],) , ",
                "    ( \"\" ,[_],) , ",
                "    ( \"(2-)\" , 2-[_],) , ",
                "    ( \"\" , [_],) , ",
                "    ( \"\" ,[_],) , ",
                "    ( \"\" ,[_],) ",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"\" , [Value1] , \"\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "_",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"\" ,   [_],) , ",
                "    ( \"\" , [_],) , ",
                "    ( \"\" ,[_],) , ",
                "    ( \"(2-)\" ,2-[_],) , ",
                "    ( \"\" , [_],) , ",
                "    ( \"\" , [_],) , ",
                "    ( \"\" ,[_],) , ",
                "    ( \"\",[_],) , ",
                "    ( \"\" ,[_],)",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"\" , [Value1] , \"\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "_",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"\" ,   [_],) , ",
                "    ( \"\" , [_],) , ",
                "    ( \"\" ,[_],) , ",
                "    ( \"\" ,[_],) , ",
                "    ( \"\" , [_],) , ",
                "    ( \"\" , [_],) , ",
                "    ( \"\" ,[_],) , ",
                "    ( \"\",[_],) , ",
                "    ( \"\" ,[_],) , ",
                "    ( \"\" ,[_],) , ",
                "    ( \"\" ,[_],) , ",
                "    ( \"1\" ,[_1],) , ",
                "    ( \"2\" ,[_2],) ",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"\" , [Value1] , \"\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "__",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"SKU\" ,   [__SKU],) , ",
                "    ( \"\" , [__], ),",
                "    ( \"\" ,[__], ),",
                "    ( \"(2-)\" ,2-[__],),",
                "    ( \"\" ,[__], ),",
                "    ( \"\" ,[__], ),",
                "    ( \"\" ,[__], ),",
                "    ( \"(2-)\" ,2-[__], )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"\" , [Value1] , \"\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "__",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"\" ,   [__],) , ",
                "    ( \"\" ,  [__],) , ",
                "    ( \"\" , [__],),",
                "    ( \"(2-)\" ,2- [__],) , ",
                "    ( \"\" , [__],) , ",
                "    ( \"(2-)\" , 2-[__],) , ",
                "    ( \"\" , [__],) ",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"\" , [Value1] , \"\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "__",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"\" ,   [__],) , ",
                "    ( \"\" ,  [__],) , ",
                "    ( \"\" , [__],) , ",
                "    ( \"(2-)\" ,2- [__],) , ",
                "    ( \"\" , [__],) , ",
                "    ( \"\" , [__],) , ",
                "    ( \"\" , [__],) ",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"\" , [Value1] , \"\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "__",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"\" ,   [__],) , ",
                "    ( \"\" ,  [__],) , ",
                "    ( \"\" , [__],) , ",
                "    ( \"(2-)\" ,2- [__],) , ",
                "    ( \"\" , [__],) , ",
                "    ( \"\" , [__],) , ",
                "    ( \"\" , [__],)",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"\" , [Value1] , \"\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "__",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"(2-)\" , 2-[__],) , ",
                "    ( \"\" ,   [__],) , ",
                "    ( \"\" ,[__],) , ",
                "    ( \"\" ,   [__],) , ",
                "    ( \"\" , [__],) , ",
                "    ( \"\" , [__],) , ",
                "    ( \"\" , [__],) , ",
                "    ( \"\" ,[__],) , ",
                "    ( \"\" , [__],)",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"\" , [Value1] , \"\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "__",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"\" ,   [__],) , ",
                "    ( \"\" , [__],) , ",
                "    ( \"\" ,   [__],) , ",
                "    ( \"(2-)\" ,2- [__],) , ",
                "    ( \"\" , [__],) , ",
                "    ( \"\" ,  [__],) , ",
                "    ( \"\" , [__],) ",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"\" , [Value1] , \"\" , [Value2] )"
              ]
            }
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "500"
      }
    ]
  },
  "id": "SemanticModel"
}