{
  "name": "SemanticModel",
  "compatibilityLevel": 1400,
  "model": {
    "culture": "zh-CN",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/10 8 1 68;wxxl_yueying",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "10.8.1.66",
            "database": "test_hc"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "kind": "SQL",
          "path": "10.8.1.66;test_hc",
          "Username": "sa",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "DimChannel",
        "columns": [
          {
            "name": "ChannelKey",
            "dataType": "int64",
            "sourceColumn": "ChannelKey"
          },
          {
            "name": "channel1",
            "dataType": "string",
            "sourceColumn": "channel1"
          },
          {
            "name": "channel2",
            "dataType": "string",
            "sourceColumn": "channel2"
          },
          {
            "name": "channel3",
            "dataType": "string",
            "sourceColumn": "channel3"
          },
          {
            "name": "channel4",
            "dataType": "string",
            "sourceColumn": "channel4"
          },
          {
            "name": "channel5",
            "dataType": "string",
            "sourceColumn": "channel5"
          },
          {
            "name": "PersonKey",
            "dataType": "int64",
            "sourceColumn": "PersonKey"
          },
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "cha_id",
            "dataType": "string",
            "sourceColumn": "cha_id"
          },
          {
            "name": "cha_name",
            "dataType": "string",
            "sourceColumn": "cha_name"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_DimChannel = Source{[Schema=\"dbo\",Item=\"DimChannel\"]}[Data]",
                "in",
                "    dbo_DimChannel"
              ]
            }
          }
        ]
      },
      {
        "name": "DimCustomer",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "customer1",
            "dataType": "string",
            "sourceColumn": "customer1"
          },
          {
            "name": "customer2",
            "dataType": "string",
            "sourceColumn": "customer2"
          },
          {
            "name": "customer3",
            "dataType": "string",
            "sourceColumn": "customer3"
          },
          {
            "name": "customer4",
            "dataType": "string",
            "sourceColumn": "customer4"
          },
          {
            "name": "customer5",
            "dataType": "string",
            "sourceColumn": "customer5"
          },
          {
            "name": "cus_id",
            "dataType": "string",
            "sourceColumn": "cus_id"
          },
          {
            "name": "cus_name",
            "dataType": "string",
            "sourceColumn": "cus_name"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_DimCustomer = Source{[Schema=\"dbo\",Item=\"DimCustomer\"]}[Data]",
                "in",
                "    dbo_DimCustomer"
              ]
            }
          }
        ]
      },
      {
        "name": "DimDate",
        "columns": [
          {
            "name": "FullDate",
            "dataType": "dateTime",
            "sourceColumn": "FullDate"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          },
          {
            "name": "DateNameEn",
            "dataType": "string",
            "sourceColumn": "DateNameEn"
          },
          {
            "name": "DateNameCn",
            "dataType": "string",
            "sourceColumn": "DateNameCn"
          },
          {
            "name": "WeekKey",
            "dataType": "int64",
            "sourceColumn": "WeekKey"
          },
          {
            "name": "WeekNameEn",
            "dataType": "string",
            "sourceColumn": "WeekNameEn"
          },
          {
            "name": "WeekNameEnShort",
            "dataType": "string",
            "sourceColumn": "WeekNameEnShort"
          },
          {
            "name": "WeekNameCn",
            "dataType": "string",
            "sourceColumn": "WeekNameCn"
          },
          {
            "name": "WeekNameCnShort",
            "dataType": "string",
            "sourceColumn": "WeekNameCnShort"
          },
          {
            "name": "WeekOfYear",
            "dataType": "int64",
            "sourceColumn": "WeekOfYear"
          },
          {
            "name": "WeekDayNameEn",
            "dataType": "string",
            "sourceColumn": "WeekDayNameEn"
          },
          {
            "name": "WeekDayNameEnShort",
            "dataType": "string",
            "sourceColumn": "WeekDayNameEnShort"
          },
          {
            "name": "WeekDayNameCn",
            "dataType": "string",
            "sourceColumn": "WeekDayNameCn"
          },
          {
            "name": "WeekDayNameCnShort",
            "dataType": "string",
            "sourceColumn": "WeekDayNameCnShort"
          },
          {
            "name": "MonthKey",
            "dataType": "int64",
            "sourceColumn": "MonthKey"
          },
          {
            "name": "MonthOfYear",
            "dataType": "int64",
            "sourceColumn": "MonthOfYear"
          },
          {
            "name": "MonthNameEn",
            "dataType": "string",
            "sourceColumn": "MonthNameEn"
          },
          {
            "name": "MonthNameEnShort",
            "dataType": "string",
            "sourceColumn": "MonthNameEnShort"
          },
          {
            "name": "MonthNameCn",
            "dataType": "string",
            "sourceColumn": "MonthNameCn"
          },
          {
            "name": "MonthNameCnShort",
            "dataType": "string",
            "sourceColumn": "MonthNameCnShort"
          },
          {
            "name": "QuarterKey",
            "dataType": "int64",
            "sourceColumn": "QuarterKey"
          },
          {
            "name": "QuarterOfYear",
            "dataType": "int64",
            "sourceColumn": "QuarterOfYear"
          },
          {
            "name": "QuarterNameEn",
            "dataType": "string",
            "sourceColumn": "QuarterNameEn"
          },
          {
            "name": "QuarterNameEnShort",
            "dataType": "string",
            "sourceColumn": "QuarterNameEnShort"
          },
          {
            "name": "QuarterNameCn",
            "dataType": "string",
            "sourceColumn": "QuarterNameCn"
          },
          {
            "name": "QuarterNameCnShort",
            "dataType": "string",
            "sourceColumn": "QuarterNameCnShort"
          },
          {
            "name": "YearKey",
            "dataType": "int64",
            "sourceColumn": "YearKey"
          },
          {
            "name": "YearNameEn",
            "dataType": "string",
            "sourceColumn": "YearNameEn"
          },
          {
            "name": "YearNameCn",
            "dataType": "string",
            "sourceColumn": "YearNameCn"
          },
          {
            "name": "DayOfWeek",
            "dataType": "int64",
            "sourceColumn": "DayOfWeek"
          },
          {
            "name": "DayOfMonth",
            "dataType": "int64",
            "sourceColumn": "DayOfMonth"
          },
          {
            "name": "DayOfQuarter",
            "dataType": "int64",
            "sourceColumn": "DayOfQuarter"
          },
          {
            "name": "DayOfYear",
            "dataType": "int64",
            "sourceColumn": "DayOfYear"
          },
          {
            "name": "InsertDatetime",
            "dataType": "dateTime",
            "sourceColumn": "InsertDatetime"
          },
          {
            "name": "UpdateDatetime",
            "dataType": "dateTime",
            "sourceColumn": "UpdateDatetime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_DimDate = Source{[Schema=\"dbo\",Item=\"DimDate\"]}[Data]",
                "in",
                "    dbo_DimDate"
              ]
            }
          }
        ]
      },
      {
        "name": "DimOrg",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "org_id",
            "dataType": "string",
            "sourceColumn": "org_id"
          },
          {
            "name": "org_name",
            "dataType": "string",
            "sourceColumn": "org_name"
          },
          {
            "name": "org1",
            "dataType": "string",
            "sourceColumn": "org1"
          },
          {
            "name": "org2",
            "dataType": "string",
            "sourceColumn": "org2"
          },
          {
            "name": "org3",
            "dataType": "string",
            "sourceColumn": "org3"
          },
          {
            "name": "org4",
            "dataType": "string",
            "sourceColumn": "org4"
          },
          {
            "name": "org5",
            "dataType": "string",
            "sourceColumn": "org5"
          },
          {
            "name": "org_type",
            "dataType": "int64",
            "sourceColumn": "org_type"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_DimOrg = Source{[Schema=\"dbo\",Item=\"DimOrg\"]}[Data]",
                "in",
                "    dbo_DimOrg"
              ]
            }
          }
        ]
      },
      {
        "name": "DimOrgMap",
        "columns": [
          {
            "name": "BackKey",
            "dataType": "int64",
            "sourceColumn": "BackKey"
          },
          {
            "name": "FrontKey",
            "dataType": "int64",
            "sourceColumn": "FrontKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_DimOrgMap = Source{[Schema=\"dbo\",Item=\"DimOrgMap\"]}[Data]",
                "in",
                "    dbo_DimOrgMap"
              ]
            }
          }
        ]
      },
      {
        "name": "DimPerson",
        "columns": [
          {
            "name": "PersonKey",
            "dataType": "int64",
            "sourceColumn": "PersonKey"
          },
          {
            "name": "person_name",
            "dataType": "string",
            "sourceColumn": "person_name"
          },
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "person_id",
            "dataType": "string",
            "sourceColumn": "person_id"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_DimPerson = Source{[Schema=\"dbo\",Item=\"DimPerson\"]}[Data]",
                "in",
                "    dbo_DimPerson"
              ]
            }
          }
        ]
      },
      {
        "name": "DimProduct",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "product1",
            "dataType": "string",
            "sourceColumn": "product1"
          },
          {
            "name": "product2",
            "dataType": "string",
            "sourceColumn": "product2"
          },
          {
            "name": "product3",
            "dataType": "string",
            "sourceColumn": "product3"
          },
          {
            "name": "product4",
            "dataType": "string",
            "sourceColumn": "product4"
          },
          {
            "name": "product5",
            "dataType": "string",
            "sourceColumn": "product5"
          },
          {
            "name": "cost",
            "dataType": "double",
            "sourceColumn": "cost"
          },
          {
            "name": "PersonKey",
            "dataType": "int64",
            "sourceColumn": "PersonKey"
          },
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "pro_id",
            "dataType": "string",
            "sourceColumn": "pro_id"
          },
          {
            "name": "pro_name",
            "dataType": "string",
            "sourceColumn": "pro_name"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_DimProduct = Source{[Schema=\"dbo\",Item=\"DimProduct\"]}[Data]",
                "in",
                "    dbo_DimProduct"
              ]
            }
          }
        ]
      },
      {
        "name": "DimSupply",
        "columns": [
          {
            "name": "SupplyKey",
            "dataType": "int64",
            "sourceColumn": "SupplyKey"
          },
          {
            "name": "supply_id",
            "dataType": "string",
            "sourceColumn": "supply_id"
          },
          {
            "name": "supply_name",
            "dataType": "string",
            "sourceColumn": "supply_name"
          },
          {
            "name": "supply1",
            "dataType": "string",
            "sourceColumn": "supply1"
          },
          {
            "name": "supply2",
            "dataType": "string",
            "sourceColumn": "supply2"
          },
          {
            "name": "supply3",
            "dataType": "string",
            "sourceColumn": "supply3"
          },
          {
            "name": "supply4",
            "dataType": "string",
            "sourceColumn": "supply4"
          },
          {
            "name": "supply5",
            "dataType": "string",
            "sourceColumn": "supply5"
          },
          {
            "name": "supply_type",
            "dataType": "int64",
            "sourceColumn": "supply_type"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_DimSupply = Source{[Schema=\"dbo\",Item=\"DimSupply\"]}[Data]",
                "in",
                "    dbo_DimSupply"
              ]
            }
          }
        ]
      },
      {
        "name": "V_DimMonth",
        "columns": [
          {
            "name": "StartDate",
            "dataType": "dateTime",
            "sourceColumn": "StartDate"
          },
          {
            "name": "EndDate",
            "dataType": "dateTime",
            "sourceColumn": "EndDate"
          },
          {
            "name": "MonthKey",
            "dataType": "int64",
            "sourceColumn": "MonthKey"
          },
          {
            "name": "MonthOfYear",
            "dataType": "int64",
            "sourceColumn": "MonthOfYear"
          },
          {
            "name": "MonthNameEn",
            "dataType": "string",
            "sourceColumn": "MonthNameEn"
          },
          {
            "name": "MonthNameEnShort",
            "dataType": "string",
            "sourceColumn": "MonthNameEnShort"
          },
          {
            "name": "MonthNameCn",
            "dataType": "string",
            "sourceColumn": "MonthNameCn"
          },
          {
            "name": "MonthNameCnShort",
            "dataType": "string",
            "sourceColumn": "MonthNameCnShort"
          },
          {
            "name": "QuarterKey",
            "dataType": "int64",
            "sourceColumn": "QuarterKey"
          },
          {
            "name": "QuarterOfYear",
            "dataType": "int64",
            "sourceColumn": "QuarterOfYear"
          },
          {
            "name": "QuarterNameEn",
            "dataType": "string",
            "sourceColumn": "QuarterNameEn"
          },
          {
            "name": "QuarterNameEnShort",
            "dataType": "string",
            "sourceColumn": "QuarterNameEnShort"
          },
          {
            "name": "QuarterNameCn",
            "dataType": "string",
            "sourceColumn": "QuarterNameCn"
          },
          {
            "name": "QuarterNameCnShort",
            "dataType": "string",
            "sourceColumn": "QuarterNameCnShort"
          },
          {
            "name": "YearKey",
            "dataType": "int64",
            "sourceColumn": "YearKey"
          },
          {
            "name": "YearNameEn",
            "dataType": "string",
            "sourceColumn": "YearNameEn"
          },
          {
            "name": "YearNameCn",
            "dataType": "string",
            "sourceColumn": "YearNameCn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_V_DimMonth = Source{[Schema=\"dbo\",Item=\"V_DimMonth\"]}[Data]",
                "in",
                "    dbo_V_DimMonth"
              ]
            }
          }
        ]
      },
      {
        "name": "result_supply_month",
        "columns": [
          {
            "name": "SupplyKey",
            "dataType": "int64",
            "sourceColumn": "SupplyKey"
          },
          {
            "name": "sale_amt",
            "dataType": "double",
            "sourceColumn": "sale_amt"
          },
          {
            "name": "order_amt",
            "dataType": "double",
            "sourceColumn": "order_amt"
          },
          {
            "name": "planned_production_qty",
            "dataType": "double",
            "sourceColumn": "planned_production_qty"
          },
          {
            "name": "actual_production_qty",
            "dataType": "double",
            "sourceColumn": "actual_production_qty"
          },
          {
            "name": "defective_qty",
            "dataType": "double",
            "sourceColumn": "defective_qty"
          },
          {
            "name": "profit_amt",
            "dataType": "double",
            "sourceColumn": "profit_amt"
          },
          {
            "name": "production_ratio",
            "dataType": "double",
            "sourceColumn": "production_ratio"
          },
          {
            "name": "residual_rate",
            "dataType": "double",
            "sourceColumn": "residual_rate"
          },
          {
            "name": "delivery_rate",
            "dataType": "double",
            "sourceColumn": "delivery_rate"
          },
          {
            "name": "MonthKey",
            "dataType": "int64",
            "sourceColumn": "MonthKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_result_supply_month = Source{[Schema=\"dbo\",Item=\"result_supply_month\"]}[Data]",
                "in",
                "    dbo_result_supply_month"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "result_supply_month_供应销售额目标",
            "expression": " SUMX('target_supply_month','target_supply_month'[target_sale_amt])"
          },
          {
            "name": "result_supply_month_供应销售额实际",
            "expression": " SUMX('result_supply_month','result_supply_month'[sale_amt])"
          },
          {
            "name": "result_supply_month_供应销售额目标达成率",
            "expression": " DIVIDE([result_supply_month_供应销售额实际],[result_supply_month_供应销售额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_supply_month_供应销售额目标实际差异",
            "expression": " [result_supply_month_供应销售额实际]-[result_supply_month_供应销售额目标]"
          },
          {
            "name": "result_supply_month_供应销售额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_supply_month_供应销售额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_supply_month_供应销售额实际]-[result_supply_month_供应销售额实际_去年同期]), [result_supply_month_供应销售额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_supply_month_供应销售额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_supply_month_供应销售额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_supply_month_供应销售额实际]-[result_supply_month_供应销售额实际_上月同期]),[result_supply_month_供应销售额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_supply_month_供应利润额目标",
            "expression": " SUMX('target_supply_month','target_supply_month'[target_profit_amt])"
          },
          {
            "name": "result_supply_month_供应利润额实际",
            "expression": " SUMX('result_supply_month','result_supply_month'[profit_amt])"
          },
          {
            "name": "result_supply_month_供应利润额目标达成率",
            "expression": " DIVIDE([result_supply_month_供应利润额实际],[result_supply_month_供应利润额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_supply_month_供应利润额目标实际差异",
            "expression": " [result_supply_month_供应利润额实际]-[result_supply_month_供应利润额目标]"
          },
          {
            "name": "result_supply_month_供应利润额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_supply_month_供应利润额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_supply_month_供应利润额实际]-[result_supply_month_供应利润额实际_去年同期]), [result_supply_month_供应利润额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_supply_month_供应利润额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_supply_month_供应利润额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_supply_month_供应利润额实际]-[result_supply_month_供应利润额实际_上月同期]),[result_supply_month_供应利润额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_supply_month_供应产能目标",
            "expression": " SUMX('target_supply_month','target_supply_month'[target_production_capacity])"
          },
          {
            "name": "result_supply_month_供应产能实际",
            "expression": " SUMX('result_supply_month','result_supply_month'[planned_production_qty])"
          },
          {
            "name": "result_supply_month_供应产能目标达成率",
            "expression": " DIVIDE([result_supply_month_供应产能实际],[result_supply_month_供应产能目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_supply_month_供应产能目标实际差异",
            "expression": "  [result_supply_month_供应产能实际]-[result_supply_month_供应产能目标]"
          },
          {
            "name": "result_supply_month_供应产能同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_supply_month_供应产能实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_supply_month_供应产能实际]-[result_supply_month_供应产能实际_去年同期]), [result_supply_month_供应产能实际_去年同期])))",
              "",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_supply_month_供应产能环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_supply_month_供应产能实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_supply_month_供应产能实际]-[result_supply_month_供应产能实际_上月同期]),[result_supply_month_供应产能实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_supply_month_供应产供比目标",
            "expression": " SUMX('target_supply_month','target_supply_month'[target_production_ratio])"
          },
          {
            "name": "result_supply_month_供应产供比实际",
            "expression": " SUMX('result_supply_month','result_supply_month'[production_ratio])"
          },
          {
            "name": "result_supply_month_供应产供比目标达成率",
            "expression": " DIVIDE([result_supply_month_供应产供比实际],[result_supply_month_供应产供比目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_supply_month_供应产供比目标实际差异",
            "expression": "  [result_supply_month_供应产供比实际]-[result_supply_month_供应产供比目标]"
          },
          {
            "name": "result_supply_month_供应产供比同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_supply_month_供应产供比实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_supply_month_供应产供比实际]-[result_supply_month_供应产供比实际_去年同期]), [result_supply_month_供应产供比实际_去年同期])))",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_supply_month_供应产供比环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_supply_month_供应产供比实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_supply_month_供应产供比实际]-[result_supply_month_供应产供比实际_上月同期]),[result_supply_month_供应产供比实际_上月同期]))",
              "",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_supply_month_供应安全值目标",
            "expression": " 1"
          },
          {
            "name": "result_supply_month_供应安全值实际",
            "expression": " [result_supply_month_供应产能实际]-SUMX('result_supply_month','result_supply_month'[actual_production_qty])"
          },
          {
            "name": "result_supply_month_供应安全值目标达成率",
            "expression": " DIVIDE([result_supply_month_供应安全值实际],[result_supply_month_供应安全值目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_supply_month_供应安全值目标实际差异",
            "expression": "  [result_supply_month_供应安全值实际]-[result_supply_month_供应安全值目标]"
          },
          {
            "name": "result_supply_month_供应安全值同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_supply_month_供应安全值实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_supply_month_供应安全值实际]-[result_supply_month_供应安全值实际_去年同期]), [result_supply_month_供应安全值实际_去年同期])))",
              "",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_supply_month_供应安全值环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_supply_month_供应安全值实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_supply_month_供应安全值实际]-[result_supply_month_供应安全值实际_上月同期]),[result_supply_month_供应安全值实际_上月同期]))",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_supply_month_残品率目标",
            "expression": " SUMX('target_supply_month','target_supply_month'[target_residual_rate])"
          },
          {
            "name": "result_supply_month_残品率实际",
            "expression": " SUMX('result_supply_month','result_supply_month'[residual_rate])"
          },
          {
            "name": "result_supply_month_残品率目标达成率",
            "expression": "  DIVIDE([result_supply_month_残品率实际],[result_supply_month_残品率目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_supply_month_残品率目标实际差异",
            "expression": " [result_supply_month_残品率实际]-[result_supply_month_残品率目标]"
          },
          {
            "name": "result_supply_month_残品率同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_supply_month_残品率实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_supply_month_残品率实际]-[result_supply_month_残品率实际_去年同期]), [result_supply_month_残品率实际_去年同期])))",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_supply_month_残品率环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_supply_month_残品率实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_supply_month_残品率实际]-[result_supply_month_残品率实际_上月同期]),[result_supply_month_残品率实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_supply_month_交期达成率目标",
            "expression": " SUMX('target_supply_month','target_supply_month'[target_delivery_rate])"
          },
          {
            "name": "result_supply_month_交期达成率实际",
            "expression": " SUMX('result_supply_month','result_supply_month'[delivery_rate])"
          },
          {
            "name": "result_supply_month_交期达成率目标达成率",
            "expression": " DIVIDE([result_supply_month_交期达成率实际],[result_supply_month_交期达成率目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_supply_month_交期达成率目标实际差异",
            "expression": "  [result_supply_month_交期达成率实际]-[result_supply_month_交期达成率目标]"
          },
          {
            "name": "result_supply_month_交期达成率同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_supply_month_交期达成率实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_supply_month_交期达成率实际]-[result_supply_month_交期达成率实际_去年同期]), [result_supply_month_交期达成率实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_supply_month_交期达成率环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_supply_month_交期达成率实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_supply_month_交期达成率实际]-[result_supply_month_交期达成率实际_上月同期]),[result_supply_month_交期达成率实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_supply_month_供应销售额实际_去年同期",
            "expression": "CALCULATE([result_supply_month_供应销售额实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_supply_month_供应销售额实际_上月同期",
            "expression": "CALCULATE([result_supply_month_供应销售额实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_supply_month_供应利润额实际_去年同期",
            "expression": "CALCULATE([result_supply_month_供应利润额实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_supply_month_供应利润额实际_上月同期",
            "expression": "CALCULATE([result_supply_month_供应利润额实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_supply_month_供应产能实际_去年同期",
            "expression": [
              "CALCULATE([result_supply_month_供应产能实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))",
              "",
              ""
            ]
          },
          {
            "name": "result_supply_month_供应产能实际_上月同期",
            "expression": "CALCULATE([result_supply_month_供应产能实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_supply_month_供应产供比实际_去年同期",
            "expression": [
              "CALCULATE([result_supply_month_供应产供比实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))",
              ""
            ]
          },
          {
            "name": "result_supply_month_供应产供比实际_上月同期",
            "expression": "CALCULATE([result_supply_month_供应产供比实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_supply_month_供应安全值实际_去年同期",
            "expression": "CALCULATE([result_supply_month_供应安全值实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_supply_month_供应安全值实际_上月同期",
            "expression": "CALCULATE([result_supply_month_供应安全值实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_supply_month_残品率实际_去年同期",
            "expression": "CALCULATE([result_supply_month_残品率实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_supply_month_残品率实际_上月同期",
            "expression": "CALCULATE([result_supply_month_残品率实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_supply_month_交期达成率实际_去年同期",
            "expression": "CALCULATE([result_supply_month_交期达成率实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_supply_month_交期达成率实际_上月同期",
            "expression": "CALCULATE([result_supply_month_交期达成率实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          }
        ]
      },
      {
        "name": "result_product_month",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "profit_amt",
            "dataType": "double",
            "sourceColumn": "profit_amt"
          },
          {
            "name": "sale_amt",
            "dataType": "double",
            "sourceColumn": "sale_amt"
          },
          {
            "name": "cost_amt",
            "dataType": "double",
            "sourceColumn": "cost_amt"
          },
          {
            "name": "stock_amt",
            "dataType": "double",
            "sourceColumn": "stock_amt"
          },
          {
            "name": "stock_rate",
            "dataType": "double",
            "sourceColumn": "stock_rate"
          },
          {
            "name": "day_sale_amt",
            "dataType": "double",
            "sourceColumn": "day_sale_amt"
          },
          {
            "name": "input_output_ratio",
            "dataType": "double",
            "sourceColumn": "input_output_ratio"
          },
          {
            "name": "MonthKey",
            "dataType": "int64",
            "sourceColumn": "MonthKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_result_product_month = Source{[Schema=\"dbo\",Item=\"result_product_month\"]}[Data]",
                "in",
                "    dbo_result_product_month"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "result_product_month_毛利润额目标",
            "expression": " [result_product_month_销售额目标]-[result_product_month_产品成本额目标]"
          },
          {
            "name": "result_product_month_毛利润额实际",
            "expression": "SUMX('result_product_month','result_product_month'[profit_amt])"
          },
          {
            "name": "result_product_month_毛利润额目标达成率",
            "expression": " DIVIDE([result_product_month_毛利润额实际],[result_product_month_毛利润额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_month_毛利润额目标实际差异",
            "expression": " [result_product_month_毛利润额实际]-[result_product_month_毛利润额目标]"
          },
          {
            "name": "result_product_month_毛利润额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_product_month_毛利润额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_product_month_毛利润额实际]-[result_product_month_毛利润额实际_去年同期]), [result_product_month_毛利润额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_month_毛利润额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_product_month_毛利润额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_product_month_毛利润额实际]-[result_product_month_毛利润额实际_上月同期]),[result_product_month_毛利润额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_month_销售额目标",
            "expression": "SUMX('target_product_month','target_product_month'[target_sale_amt])"
          },
          {
            "name": "result_product_month_销售额实际",
            "expression": "SUMX('result_product_month','result_product_month'[sale_amt])"
          },
          {
            "name": "result_product_month_销售额目标达成率",
            "expression": " DIVIDE([result_product_month_销售额实际],[result_product_month_销售额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_month_销售额目标实际差异",
            "expression": " [result_product_month_销售额实际]-[result_product_month_销售额目标]"
          },
          {
            "name": "result_product_month_销售额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_product_month_销售额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_product_month_销售额实际]-[result_product_month_销售额实际_去年同期]), [result_product_month_销售额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_month_销售额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_product_month_销售额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_product_month_销售额实际]-[result_product_month_销售额实际_上月同期]),[result_product_month_销售额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_month_产品成本额目标",
            "expression": " SUMX('target_product_month','target_product_month'[target_cost_amt])"
          },
          {
            "name": "result_product_month_产品成本额实际",
            "expression": " SUMX('result_product_month','result_product_month'[cost_amt])"
          },
          {
            "name": "result_product_month_产品成本额目标达成率",
            "expression": "DIVIDE([result_product_month_产品成本额实际],[result_product_month_产品成本额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_month_产品成本额目标实际差异",
            "expression": "[result_product_month_产品成本额实际]-[result_product_month_产品成本额目标]"
          },
          {
            "name": "result_product_month_产品成本额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_product_month_产品成本额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_product_month_产品成本额实际]-[result_product_month_产品成本额实际_去年同期]), [result_product_month_产品成本额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_month_产品成本额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_product_month_产品成本额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_product_month_产品成本额实际]-[result_product_month_产品成本额实际_上月同期]),[result_product_month_产品成本额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_month_产品投入产出比目标",
            "expression": " DIVIDE([result_product_month_毛利润额目标],[result_product_month_产品成本额目标])"
          },
          {
            "name": "result_product_month_产品投入产出比实际",
            "expression": " SUMX('result_product_month','result_product_month'[input_output_ratio])"
          },
          {
            "name": "result_product_month_产品投入产出比目标达成率",
            "expression": " DIVIDE([result_product_month_产品投入产出比实际],[result_product_month_产品投入产出比目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_month_产品投入产出比目标实际差异",
            "expression": "[result_product_month_产品投入产出比实际]-[result_product_month_产品投入产出比目标]"
          },
          {
            "name": "result_product_month_产品投入产出比同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_product_month_产品投入产出比实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_product_month_产品投入产出比实际]-[result_product_month_产品投入产出比实际_去年同期]), [result_product_month_产品投入产出比实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_month_产品投入产出比环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_product_month_产品投入产出比实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_product_month_产品投入产出比实际]-[result_product_month_产品投入产出比实际_上月同期]),[result_product_month_产品投入产出比实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_month_库存周转率目标",
            "expression": " 1"
          },
          {
            "name": "result_product_month_库存周转率实际",
            "expression": "SUMX('result_product_month','result_product_month'[stock_rate])"
          },
          {
            "name": "result_product_month_库存周转率目标达成率",
            "expression": " DIVIDE([result_product_month_库存周转率实际],[result_product_month_库存周转率目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_month_库存周转率目标实际差异",
            "expression": " [result_product_month_库存周转率实际]-[result_product_month_库存周转率目标]"
          },
          {
            "name": "result_product_month_库存周转率同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_product_month_库存周转率实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_product_month_库存周转率实际]-[result_product_month_库存周转率实际_去年同期]), [result_product_month_库存周转率实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_month_库存周转率环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_product_month_库存周转率实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_product_month_库存周转率实际]-[result_product_month_库存周转率实际_上月同期]),[result_product_month_库存周转率实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_month_日销目标",
            "expression": " 1"
          },
          {
            "name": "result_product_month_日销实际",
            "expression": " SUMX('result_product_month','result_product_month'[day_sale_amt])"
          },
          {
            "name": "result_product_month_日销目标达成率",
            "expression": " DIVIDE([result_product_month_日销实际],[result_product_month_日销目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_month_日销目标实际差异",
            "expression": " [result_product_month_日销实际]-[result_product_month_日销目标]"
          },
          {
            "name": "result_product_month_日销同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_product_month_日销实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_product_month_日销实际]-[result_product_month_日销实际_去年同期]), [result_product_month_日销实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_month_日销环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_product_month_日销实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_product_month_日销实际]-[result_product_month_日销实际_上月同期]),[result_product_month_日销实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_month_库存额目标",
            "expression": " SUMX('target_product_month','target_product_month'[target_stock_amt])"
          },
          {
            "name": "result_product_month_库存额实际",
            "expression": " SUMX('result_product_month','result_product_month'[stock_amt])"
          },
          {
            "name": "result_product_month_库存额目标达成率",
            "expression": " DIVIDE([result_product_month_库存额实际],[result_product_month_库存额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_month_库存额目标实际差异",
            "expression": " [result_product_month_库存额实际]-[result_product_month_库存额目标]"
          },
          {
            "name": "result_product_month_库存额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_product_month_库存额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_product_month_库存额实际]-[result_product_month_库存额实际_去年同期]), [result_product_month_库存额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_month_库存额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_product_month_库存额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_product_month_库存额实际]-[result_product_month_库存额实际_上月同期]),[result_product_month_库存额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_month_销售额实际_去年同期",
            "expression": "CALCULATE([result_product_month_销售额实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_product_month_销售额实际_上月同期",
            "expression": "CALCULATE([result_product_month_销售额实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_product_month_毛利润额实际_去年同期",
            "expression": "CALCULATE([result_product_month_毛利润额实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_product_month_毛利润额实际_上月同期",
            "expression": "CALCULATE([result_product_month_毛利润额实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_product_month_产品成本额实际_去年同期",
            "expression": "CALCULATE([result_product_month_产品成本额实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_product_month_产品成本额实际_上月同期",
            "expression": "CALCULATE([result_product_month_产品成本额实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_product_month_产品投入产出比实际_去年同期",
            "expression": "CALCULATE([result_product_month_产品投入产出比实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_product_month_产品投入产出比实际_上月同期",
            "expression": "CALCULATE([result_product_month_产品投入产出比实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_product_month_库存周转率实际_去年同期",
            "expression": "CALCULATE([result_product_month_库存周转率实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_product_month_库存周转率实际_上月同期",
            "expression": "CALCULATE([result_product_month_库存周转率实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_product_month_日销实际_去年同期",
            "expression": "CALCULATE([result_product_month_日销实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_product_month_日销实际_上月同期",
            "expression": "CALCULATE([result_product_month_日销实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_product_month_库存额实际_去年同期",
            "expression": "CALCULATE([result_product_month_库存额实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_product_month_库存额实际_上月同期",
            "expression": "CALCULATE([result_product_month_库存额实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          }
        ]
      },
      {
        "name": "result_product_day",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "profit_amt",
            "dataType": "double",
            "sourceColumn": "profit_amt"
          },
          {
            "name": "sale_amt",
            "dataType": "double",
            "sourceColumn": "sale_amt"
          },
          {
            "name": "cost_amt",
            "dataType": "double",
            "sourceColumn": "cost_amt"
          },
          {
            "name": "stock_amt",
            "dataType": "double",
            "sourceColumn": "stock_amt"
          },
          {
            "name": "stock_rate",
            "dataType": "double",
            "sourceColumn": "stock_rate"
          },
          {
            "name": "day_sale_amt",
            "dataType": "double",
            "sourceColumn": "day_sale_amt"
          },
          {
            "name": "input_output_ratio",
            "dataType": "double",
            "sourceColumn": "input_output_ratio"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_result_product_day = Source{[Schema=\"dbo\",Item=\"result_product_day\"]}[Data]",
                "in",
                "    dbo_result_product_day"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "result_product_day_毛利润额目标",
            "expression": " [result_product_day_销售额目标]-[result_product_day_产品成本额目标]"
          },
          {
            "name": "result_product_day_毛利润额实际",
            "expression": " SUMX('result_product_day','result_product_day'[profit_amt])"
          },
          {
            "name": "result_product_day_毛利润额目标达成率",
            "expression": "DIVIDE([result_product_day_毛利润额实际],[result_product_day_毛利润额目标])",
            "formatString": "0%;-0%;0%"
          },
          {
            "name": "result_product_day_毛利润额目标实际差异",
            "expression": "  [result_product_day_毛利润额实际]-[result_product_day_毛利润额目标]"
          },
          {
            "name": "result_product_day_毛利润额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_product_day_毛利润额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_product_day_毛利润额实际]-[result_product_day_毛利润额实际_去年同期]), [result_product_day_毛利润额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_day_毛利润额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_product_day_毛利润额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_product_day_毛利润额实际]-[result_product_day_毛利润额实际_上月同期]),[result_product_day_毛利润额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_day_销售额目标",
            "expression": "SUMX('target_product_day','target_product_day'[target_sale_amt])"
          },
          {
            "name": "result_product_day_销售额实际",
            "expression": " SUMX('result_product_day','result_product_day'[sale_amt])"
          },
          {
            "name": "result_product_day_销售额目标达成率",
            "expression": " DIVIDE([result_product_day_销售额实际],[result_product_day_销售额目标])",
            "formatString": "0%;-0%;0%"
          },
          {
            "name": "result_product_day_销售额目标实际差异",
            "expression": " [result_product_day_销售额实际]-[result_product_day_销售额目标]"
          },
          {
            "name": "result_product_day_销售额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_product_day_销售额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_product_day_销售额实际]-[result_product_day_销售额实际_去年同期]), [result_product_day_销售额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_day_销售额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_product_day_销售额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_product_day_销售额实际]-[result_product_day_销售额实际_上月同期]),[result_product_day_销售额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_day_产品成本额目标",
            "expression": " SUMX('target_product_day','target_product_day'[target_cost_amt])"
          },
          {
            "name": "result_product_day_产品成本额实际",
            "expression": " SUMX('result_product_day','result_product_day'[cost_amt])"
          },
          {
            "name": "result_product_day_产品成本额目标达成率",
            "expression": " DIVIDE([result_product_day_产品成本额实际],[result_product_day_产品成本额目标])",
            "formatString": "0%;-0%;0%"
          },
          {
            "name": "result_product_day_产品成本额目标实际差异",
            "expression": " [result_product_day_产品成本额实际]-[result_product_day_产品成本额目标]"
          },
          {
            "name": "result_product_day_产品成本额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_product_day_产品成本额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_product_day_产品成本额实际]-[result_product_day_产品成本额实际_去年同期]), [result_product_day_产品成本额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_day_产品成本额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_product_day_产品成本额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_product_day_产品成本额实际]-[result_product_day_产品成本额实际_上月同期]),[result_product_day_产品成本额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_day_产品投入产出比目标",
            "expression": " DIVIDE([result_product_day_毛利润额目标],[result_product_day_产品成本额目标])"
          },
          {
            "name": "result_product_day_产品投入产出比实际",
            "expression": " SUMX('result_product_day','result_product_day'[input_output_ratio])"
          },
          {
            "name": "result_product_day_产品投入产出比目标达成率",
            "expression": " DIVIDE([result_product_day_产品投入产出比实际],[result_product_day_产品投入产出比目标])",
            "formatString": "0%;-0%;0%"
          },
          {
            "name": "result_product_day_产品投入产出比目标实际差异",
            "expression": " [result_product_day_产品投入产出比实际]-[result_product_day_产品投入产出比目标]"
          },
          {
            "name": "result_product_day_产品投入产出比同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_product_day_产品投入产出比实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_product_day_产品投入产出比实际]-[result_product_day_产品投入产出比实际_去年同期]), [result_product_day_产品投入产出比实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_day_产品投入产出比环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_product_day_产品投入产出比实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_product_day_产品投入产出比实际]-[result_product_day_产品投入产出比实际_上月同期]),[result_product_day_产品投入产出比实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_day_库存周转率目标",
            "expression": " 1"
          },
          {
            "name": "result_product_day_库存周转率实际",
            "expression": " SUMX('result_product_day','result_product_day'[stock_rate])"
          },
          {
            "name": "result_product_day_库存周转率目标达成率",
            "expression": " DIVIDE([result_product_day_库存周转率实际],[result_product_day_库存周转率目标])",
            "formatString": "0%;-0%;0%"
          },
          {
            "name": "result_product_day_库存周转率目标实际差异",
            "expression": "  [result_product_day_库存周转率实际]-[result_product_day_库存周转率目标]"
          },
          {
            "name": "result_product_day_库存周转率同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_product_day_库存周转率实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_product_day_库存周转率实际]-[result_product_day_库存周转率实际_去年同期]), [result_product_day_库存周转率实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_day_库存周转率环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_product_day_库存周转率实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_product_day_库存周转率实际]-[result_product_day_库存周转率实际_上月同期]),[result_product_day_库存周转率实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_day_日销目标",
            "expression": " 1"
          },
          {
            "name": "result_product_day_日销实际",
            "expression": " SUMX('result_product_day','result_product_day'[day_sale_amt])"
          },
          {
            "name": "result_product_day_日销目标达成率",
            "expression": "  DIVIDE([result_product_day_日销实际],[result_product_day_日销目标])",
            "formatString": "0%;-0%;0%"
          },
          {
            "name": "result_product_day_日销目标实际差异",
            "expression": " [result_product_day_日销实际]-[result_product_day_日销目标]"
          },
          {
            "name": "result_product_day_日销同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_product_day_日销实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_product_day_日销实际]-[result_product_day_日销实际_去年同期]), [result_product_day_日销实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_day_日销环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_product_day_日销实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_product_day_日销实际]-[result_product_day_日销实际_上月同期]),[result_product_day_日销实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_day_库存额目标",
            "expression": " SUMX('target_product_day','target_product_day'[target_stock_amt])"
          },
          {
            "name": "result_product_day_库存额实际",
            "expression": " SUMX('result_product_day','result_product_day'[stock_amt])"
          },
          {
            "name": "result_product_day_库存额目标达成率",
            "expression": " DIVIDE([result_product_day_库存额实际],[result_product_day_库存额目标])",
            "formatString": "0%;-0%;0%"
          },
          {
            "name": "result_product_day_库存额目标实际差异",
            "expression": " [result_product_day_库存额实际]-[result_product_day_库存额目标]"
          },
          {
            "name": "result_product_day_库存额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_product_day_库存额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_product_day_库存额实际]-[result_product_day_库存额实际_去年同期]), [result_product_day_库存额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_day_库存额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_product_day_库存额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_product_day_库存额实际]-[result_product_day_库存额实际_上月同期]),[result_product_day_库存额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_product_day_毛利润额实际_去年同期",
            "expression": "CALCULATE([result_product_day_毛利润额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "result_product_day_毛利润额实际_上月同期",
            "expression": "CALCULATE([result_product_day_毛利润额实际], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "result_product_day_库存额实际_去年同期",
            "expression": "CALCULATE([result_product_day_库存额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "result_product_day_销售额实际_去年同期",
            "expression": "CALCULATE([result_product_day_销售额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "result_product_day_销售额实际_上月同期",
            "expression": "CALCULATE([result_product_day_销售额实际], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "result_product_day_产品成本额实际_去年同期",
            "expression": "CALCULATE([result_product_day_产品成本额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "result_product_day_产品成本额实际_上月同期",
            "expression": "CALCULATE([result_product_day_产品成本额实际], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "result_product_day_产品投入产出比实际_去年同期",
            "expression": "CALCULATE([result_product_day_产品投入产出比实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "result_product_day_产品投入产出比实际_上月同期",
            "expression": "CALCULATE([result_product_day_产品投入产出比实际], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "result_product_day_库存周转率实际_去年同期",
            "expression": "CALCULATE([result_product_day_库存周转率实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "result_product_day_库存周转率实际_上月同期",
            "expression": "CALCULATE([result_product_day_库存周转率实际], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "result_product_day_日销实际_去年同期",
            "expression": "CALCULATE([result_product_day_日销实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "result_product_day_日销实际_上月同期",
            "expression": "CALCULATE([result_product_day_日销实际], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "result_product_day_库存额实际_上月同期",
            "expression": "CALCULATE([result_product_day_库存额实际], DATEADD('DimDate'[FullDate], -1, MONTH))"
          }
        ]
      },
      {
        "name": "result_org_month",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "profit_amt",
            "dataType": "double",
            "sourceColumn": "profit_amt"
          },
          {
            "name": "sale_amt",
            "dataType": "double",
            "sourceColumn": "sale_amt"
          },
          {
            "name": "cost_amt",
            "dataType": "double",
            "sourceColumn": "cost_amt"
          },
          {
            "name": "input_output_ratio",
            "dataType": "double",
            "sourceColumn": "input_output_ratio"
          },
          {
            "name": "day_sale_amt",
            "dataType": "double",
            "sourceColumn": "day_sale_amt"
          },
          {
            "name": "redundancy",
            "dataType": "double",
            "sourceColumn": "redundancy"
          },
          {
            "name": "MonthKey",
            "dataType": "int64",
            "sourceColumn": "MonthKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_result_org_month = Source{[Schema=\"dbo\",Item=\"result_org_month\"]}[Data]",
                "in",
                "    dbo_result_org_month"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "result_org_month_销售额目标",
            "expression": " SUMX('target_org_month','target_org_month'[target_sale_amt])"
          },
          {
            "name": "result_org_month_销售额实际",
            "expression": " SUMX('result_org_month','result_org_month'[sale_amt])"
          },
          {
            "name": "result_org_month_销售额目标达成率",
            "expression": "  DIVIDE([result_org_month_销售额实际],[result_org_month_销售额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_org_month_销售额目标实际差异",
            "expression": " [result_org_month_销售额实际]-[result_org_month_销售额目标]"
          },
          {
            "name": "result_org_month_销售额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_org_month_销售额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_org_month_销售额实际]-[result_org_month_销售额实际_去年同期]), [result_org_month_销售额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_org_month_销售额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_org_month_销售额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_org_month_销售额实际]-[result_org_month_销售额实际_上月同期]),[result_org_month_销售额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_org_month_净利润额目标",
            "expression": " [result_org_month_销售额目标]-[result_org_month_人力成本额目标]"
          },
          {
            "name": "result_org_month_净利润额实际",
            "expression": " SUMX('result_org_month','result_org_month'[profit_amt])"
          },
          {
            "name": "result_org_month_净利润额目标达成率",
            "expression": " DIVIDE([result_org_month_净利润额实际],[result_org_month_净利润额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_org_month_净利润额目标实际差异",
            "expression": " [result_org_month_净利润额实际]-[result_org_month_净利润额目标]"
          },
          {
            "name": "result_org_month_净利润额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_org_month_净利润额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_org_month_净利润额实际]-[result_org_month_净利润额实际_去年同期]), [result_org_month_净利润额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_org_month_净利润额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_org_month_净利润额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_org_month_净利润额实际]-[result_org_month_净利润额实际_上月同期]),[result_org_month_净利润额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_org_month_人力成本额目标",
            "expression": " SUMX('target_org_month','target_org_month'[target_cost_amt])"
          },
          {
            "name": "result_org_month_人力成本额实际",
            "expression": " SUMX('result_org_month','result_org_month'[cost_amt])"
          },
          {
            "name": "result_org_month_人力成本额目标达成率",
            "expression": " DIVIDE([result_org_month_人力成本额实际],[result_org_month_人力成本额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_org_month_人力成本额目标实际差异",
            "expression": " [result_org_month_人力成本额实际]-[result_org_month_人力成本额目标]"
          },
          {
            "name": "result_org_month_人力成本额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_org_month_人力成本额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_org_month_人力成本额实际]-[result_org_month_人力成本额实际_去年同期]), [result_org_month_人力成本额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_org_month_人力成本额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_org_month_人力成本额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_org_month_人力成本额实际]-[result_org_month_人力成本额实际_上月同期]),[result_org_month_人力成本额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_org_month_日销目标",
            "expression": " 1"
          },
          {
            "name": "result_org_month_日销实际",
            "expression": " SUMX('result_org_month','result_org_month'[day_sale_amt])"
          },
          {
            "name": "result_org_month_日销目标达成率",
            "expression": " DIVIDE([result_org_month_日销实际],[result_org_month_日销目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_org_month_日销目标实际差异",
            "expression": " [result_org_month_日销实际]-[result_org_month_日销目标]"
          },
          {
            "name": "result_org_month_日销同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_org_month_日销实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_org_month_日销实际]-[result_org_month_日销实际_去年同期]), [result_org_month_日销实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_org_month_日销环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_org_month_日销实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_org_month_日销实际]-[result_org_month_日销实际_上月同期]),[result_org_month_日销实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_org_month_组织投入产出比目标",
            "expression": "  DIVIDE([result_org_month_净利润额目标],[result_org_month_人力成本额目标])"
          },
          {
            "name": "result_org_month_组织投入产出比实际",
            "expression": " SUMX('result_org_month','result_org_month'[input_output_ratio])"
          },
          {
            "name": "result_org_month_组织投入产出比目标达成率",
            "expression": " DIVIDE([result_org_month_组织投入产出比实际],[result_org_month_组织投入产出比目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_org_month_组织投入产出比目标实际差异",
            "expression": "  [result_org_month_组织投入产出比实际]-[result_org_month_组织投入产出比目标]"
          },
          {
            "name": "result_org_month_组织投入产出比同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_org_month_组织投入产出比实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_org_month_组织投入产出比实际]-[result_org_month_组织投入产出比实际_去年同期]), [result_org_month_组织投入产出比实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_org_month_组织投入产出比环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_org_month_组织投入产出比实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_org_month_组织投入产出比实际]-[result_org_month_组织投入产出比实际_上月同期]),[result_org_month_组织投入产出比实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_org_month_人员冗余值目标",
            "expression": " SUMX('target_org_month','target_org_month'[target_redundancy])"
          },
          {
            "name": "result_org_month_人员冗余值实际",
            "expression": " SUMX('result_org_month','result_org_month'[redundancy])"
          },
          {
            "name": "result_org_month_人员冗余值目标达成率",
            "expression": " DIVIDE([result_org_month_人员冗余值实际],[result_org_month_人员冗余值目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_org_month_人员冗余值目标实际差异",
            "expression": " [result_org_month_人员冗余值实际]-[result_org_month_人员冗余值目标]"
          },
          {
            "name": "result_org_month_人员冗余值同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_org_month_人员冗余值实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_org_month_人员冗余值实际]-[result_org_month_人员冗余值实际_去年同期]), [result_org_month_人员冗余值实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_org_month_人员冗余值环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_org_month_人员冗余值实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_org_month_人员冗余值实际]-[result_org_month_人员冗余值实际_上月同期]),[result_org_month_人员冗余值实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_org_month_销售额实际_去年同期",
            "expression": "CALCULATE([result_org_month_销售额实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_org_month_销售额实际_上月同期",
            "expression": "CALCULATE([result_org_month_销售额实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_org_month_净利润额实际_去年同期",
            "expression": "CALCULATE([result_org_month_净利润额实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_org_month_净利润额实际_上月同期",
            "expression": "CALCULATE([result_org_month_净利润额实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_org_month_人力成本额实际_去年同期",
            "expression": "CALCULATE([result_org_month_人力成本额实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_org_month_人力成本额实际_上月同期",
            "expression": "CALCULATE([result_org_month_人力成本额实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_org_month_日销实际_去年同期",
            "expression": "CALCULATE([result_org_month_日销实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_org_month_日销实际_上月同期",
            "expression": "CALCULATE([result_org_month_日销实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_org_month_组织投入产出比实际_去年同期",
            "expression": "CALCULATE([result_org_month_组织投入产出比实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_org_month_组织投入产出比实际_上月同期",
            "expression": "CALCULATE([result_org_month_组织投入产出比实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_org_month_人员冗余值实际_去年同期",
            "expression": "CALCULATE([result_org_month_人员冗余值实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_org_month_人员冗余值实际_上月同期",
            "expression": "CALCULATE([result_org_month_人员冗余值实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          }
        ]
      },
      {
        "name": "result_finance_month",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "profit_amt",
            "dataType": "double",
            "sourceColumn": "profit_amt"
          },
          {
            "name": "sale_amt",
            "dataType": "double",
            "sourceColumn": "sale_amt"
          },
          {
            "name": "total_cost_amt",
            "dataType": "double",
            "sourceColumn": "total_cost_amt"
          },
          {
            "name": "return_amt",
            "dataType": "double",
            "sourceColumn": "return_amt"
          },
          {
            "name": "invest_amt",
            "dataType": "double",
            "sourceColumn": "invest_amt"
          },
          {
            "name": "total_assets_amt",
            "dataType": "double",
            "sourceColumn": "total_assets_amt"
          },
          {
            "name": "cash_flow_amt",
            "dataType": "double",
            "sourceColumn": "cash_flow_amt"
          },
          {
            "name": "net_interest_rate",
            "dataType": "double",
            "sourceColumn": "net_interest_rate"
          },
          {
            "name": "return_on_investment",
            "dataType": "double",
            "sourceColumn": "return_on_investment"
          },
          {
            "name": "capital_turnover_rate",
            "dataType": "double",
            "sourceColumn": "capital_turnover_rate"
          },
          {
            "name": "redundancy",
            "dataType": "double",
            "sourceColumn": "redundancy"
          },
          {
            "name": "MonthKey",
            "dataType": "int64",
            "sourceColumn": "MonthKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_result_finance_month = Source{[Schema=\"dbo\",Item=\"result_finance_month\"]}[Data]",
                "in",
                "    dbo_result_finance_month"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "result_finance_month_销售额目标",
            "expression": " SUMX('target_finance_month','target_finance_month'[target_sale_amt])"
          },
          {
            "name": "result_finance_month_销售额实际",
            "expression": "  SUMX('result_finance_month','result_finance_month'[sale_amt])"
          },
          {
            "name": "result_finance_month_销售额目标达成率",
            "expression": " DIVIDE([result_finance_month_销售额实际],[result_finance_month_销售额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_finance_month_销售额目标实际差异",
            "expression": " [result_finance_month_销售额实际]-[result_finance_month_销售额目标]"
          },
          {
            "name": "result_finance_month_销售额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_finance_month_销售额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_finance_month_销售额实际]-[result_finance_month_销售额实际_去年同期]), [result_finance_month_销售额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_finance_month_销售额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_finance_month_销售额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_finance_month_销售额实际]-[result_finance_month_销售额实际_上月同期]),[result_finance_month_销售额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_finance_month_净利润额目标",
            "expression": " [result_finance_month_销售额目标]-[result_finance_month_总成本费用额目标]"
          },
          {
            "name": "result_finance_month_净利润额实际",
            "expression": "  SUMX('result_finance_month','result_finance_month'[profit_amt])"
          },
          {
            "name": "result_finance_month_净利润额目标达成率",
            "expression": "  DIVIDE([result_finance_month_净利润额实际],[result_finance_month_净利润额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_finance_month_净利润额目标实际差异",
            "expression": " [result_finance_month_净利润额实际]-[result_finance_month_净利润额目标]"
          },
          {
            "name": "result_finance_month_净利润额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_finance_month_净利润额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_finance_month_净利润额实际]-[result_finance_month_净利润额实际_去年同期]), [result_finance_month_净利润额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_finance_month_净利润额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_finance_month_净利润额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_finance_month_净利润额实际]-[result_finance_month_净利润额实际_上月同期]),[result_finance_month_净利润额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_finance_month_总成本费用额目标",
            "expression": " SUMX('target_finance_month','target_finance_month'[target_total_cost_amt])"
          },
          {
            "name": "result_finance_month_总成本费用额实际",
            "expression": "  SUMX('result_finance_month','result_finance_month'[total_cost_amt])"
          },
          {
            "name": "result_finance_month_总成本费用额目标达成率",
            "expression": " DIVIDE([result_finance_month_总成本费用额实际],[result_finance_month_总成本费用额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_finance_month_总成本费用额目标实际差异",
            "expression": "  [result_finance_month_总成本费用额实际]-[result_finance_month_总成本费用额目标]"
          },
          {
            "name": "result_finance_month_总成本费用额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_finance_month_总成本费用额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_finance_month_总成本费用额实际]-[result_finance_month_总成本费用额实际_去年同期]), [result_finance_month_总成本费用额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_finance_month_总成本费用额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_finance_month_总成本费用额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_finance_month_总成本费用额实际]-[result_finance_month_总成本费用额实际_上月同期]),[result_finance_month_总成本费用额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_finance_month_回款额目标",
            "expression": " SUMX('target_finance_month','target_finance_month'[target_return_amt])"
          },
          {
            "name": "result_finance_month_回款额实际",
            "expression": "  SUMX('result_finance_month','result_finance_month'[return_amt])"
          },
          {
            "name": "result_finance_month_回款额目标达成率",
            "expression": " DIVIDE([result_finance_month_回款额实际],[result_finance_month_回款额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_finance_month_回款额目标实际差异",
            "expression": "  [result_finance_month_回款额实际]-[result_finance_month_回款额目标]"
          },
          {
            "name": "result_finance_month_回款额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_finance_month_回款额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_finance_month_回款额实际]-[result_finance_month_回款额实际_去年同期]), [result_finance_month_回款额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_finance_month_回款额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_finance_month_回款额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_finance_month_回款额实际]-[result_finance_month_回款额实际_上月同期]),[result_finance_month_回款额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_finance_month_投资回报率目标",
            "expression": " DIVIDE([result_finance_month_净利润额目标],SUMX('target_finance_month','target_finance_month'[target_invest_amt]))"
          },
          {
            "name": "result_finance_month_投资回报率实际",
            "expression": "  SUMX('result_finance_month','result_finance_month'[return_on_investment])"
          },
          {
            "name": "result_finance_month_投资回报率目标达成率",
            "expression": " DIVIDE([result_finance_month_投资回报率实际],[result_finance_month_投资回报率目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_finance_month_投资回报率目标实际差异",
            "expression": "  [result_finance_month_投资回报率实际]-[result_finance_month_投资回报率目标]"
          },
          {
            "name": "result_finance_month_投资回报率同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_finance_month_投资回报率实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_finance_month_投资回报率实际]-[result_finance_month_投资回报率实际_去年同期]), [result_finance_month_投资回报率实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_finance_month_投资回报率环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_finance_month_投资回报率实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_finance_month_投资回报率实际]-[result_finance_month_投资回报率实际_上月同期]),[result_finance_month_投资回报率实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_finance_month_净利率目标",
            "expression": " DIVIDE([result_finance_month_净利润额目标],[result_finance_month_销售额目标])"
          },
          {
            "name": "result_finance_month_净利率实际",
            "expression": " SUMX('result_finance_month','result_finance_month'[net_interest_rate])"
          },
          {
            "name": "result_finance_month_净利率目标达成率",
            "expression": " DIVIDE([result_finance_month_净利率实际],[result_finance_month_净利率目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_finance_month_净利率目标实际差异",
            "expression": "  [result_finance_month_净利率实际]-[result_finance_month_净利率目标]"
          },
          {
            "name": "result_finance_month_净利率同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_finance_month_净利率实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_finance_month_净利率实际]-[result_finance_month_净利率实际_去年同期]), [result_finance_month_净利率实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_finance_month_净利率环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_finance_month_净利率实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_finance_month_净利率实际]-[result_finance_month_净利率实际_上月同期]),[result_finance_month_净利率实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_finance_month_净现金流目标",
            "expression": " SUMX('target_finance_month','target_finance_month'[target_cash_flow_amt])"
          },
          {
            "name": "result_finance_month_净现金流实际",
            "expression": " SUMX('result_finance_month','result_finance_month'[cash_flow_amt])"
          },
          {
            "name": "result_finance_month_净现金流目标达成率",
            "expression": " DIVIDE([result_finance_month_净现金流实际],[result_finance_month_净现金流目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_finance_month_净现金流目标实际差异",
            "expression": "  [result_finance_month_净现金流实际]-[result_finance_month_净现金流目标]"
          },
          {
            "name": "result_finance_month_净现金流同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_finance_month_净现金流实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_finance_month_净现金流实际]-[result_finance_month_净现金流实际_去年同期]), [result_finance_month_净现金流实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_finance_month_净现金流环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_finance_month_净现金流实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_finance_month_净现金流实际]-[result_finance_month_净现金流实际_上月同期]),[result_finance_month_净现金流实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_finance_month_资金周转率目标",
            "expression": " 1"
          },
          {
            "name": "result_finance_month_资金周转率实际",
            "expression": " SUMX('result_finance_month','result_finance_month'[capital_turnover_rate])"
          },
          {
            "name": "result_finance_month_资金周转率目标达成率",
            "expression": " DIVIDE([result_finance_month_资金周转率实际],[result_finance_month_资金周转率目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_finance_month_资金周转率目标实际差异",
            "expression": " [result_finance_month_资金周转率实际]-[result_finance_month_资金周转率目标]"
          },
          {
            "name": "result_finance_month_资金周转率同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_finance_month_资金周转率实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_finance_month_资金周转率实际]-[result_finance_month_资金周转率实际_去年同期]), [result_finance_month_资金周转率实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_finance_month_资金周转率环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_finance_month_资金周转率实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_finance_month_资金周转率实际]-[result_finance_month_资金周转率实际_上月同期]),[result_finance_month_资金周转率实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_finance_month_资金冗余值目标",
            "expression": " SUMX('target_finance_month','target_finance_month'[target_redundancy])"
          },
          {
            "name": "result_finance_month_资金冗余值实际",
            "expression": " SUMX('result_finance_month','result_finance_month'[redundancy])"
          },
          {
            "name": "result_finance_month_资金冗余值目标达成率",
            "expression": " DIVIDE([result_finance_month_资金冗余值实际],[result_finance_month_资金冗余值目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_finance_month_资金冗余值目标实际差异",
            "expression": "  [result_finance_month_资金冗余值实际]-[result_finance_month_资金冗余值目标]"
          },
          {
            "name": "result_finance_month_资金冗余值同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_finance_month_资金冗余值实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_finance_month_资金冗余值实际]-[result_finance_month_资金冗余值实际_去年同期]), [result_finance_month_资金冗余值实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_finance_month_资金冗余值环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_finance_month_资金冗余值实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_finance_month_资金冗余值实际]-[result_finance_month_资金冗余值实际_上月同期]),[result_finance_month_资金冗余值实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_finance_month_销售额实际_去年同期",
            "expression": "CALCULATE([result_finance_month_销售额实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_finance_month_销售额实际_上月同期",
            "expression": "CALCULATE([result_finance_month_销售额实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_finance_month_净利润额实际_去年同期",
            "expression": "CALCULATE([result_finance_month_净利润额实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_finance_month_净利润额实际_上月同期",
            "expression": "CALCULATE([result_finance_month_净利润额实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_finance_month_总成本费用额实际_去年同期",
            "expression": "CALCULATE([result_finance_month_总成本费用额实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_finance_month_总成本费用额实际_上月同期",
            "expression": "CALCULATE([result_finance_month_总成本费用额实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_finance_month_回款额实际_去年同期",
            "expression": "CALCULATE([result_finance_month_回款额实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_finance_month_回款额实际_上月同期",
            "expression": "CALCULATE([result_finance_month_回款额实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_finance_month_投资回报率实际_去年同期",
            "expression": "CALCULATE([result_finance_month_投资回报率实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_finance_month_投资回报率实际_上月同期",
            "expression": "CALCULATE([result_finance_month_投资回报率实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_finance_month_净利率实际_去年同期",
            "expression": "CALCULATE([result_finance_month_净利率实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_finance_month_净利率实际_上月同期",
            "expression": "CALCULATE([result_finance_month_净利率实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_finance_month_净现金流实际_去年同期",
            "expression": "CALCULATE([result_finance_month_净现金流实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_finance_month_净现金流实际_上月同期",
            "expression": "CALCULATE([result_finance_month_净现金流实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_finance_month_资金周转率实际_去年同期",
            "expression": "CALCULATE([result_finance_month_资金周转率实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_finance_month_资金周转率实际_上月同期",
            "expression": "CALCULATE([result_finance_month_资金周转率实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_finance_month_资金冗余值实际_去年同期",
            "expression": "CALCULATE([result_finance_month_资金冗余值实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_finance_month_资金冗余值实际_上月同期",
            "expression": "CALCULATE([result_finance_month_资金冗余值实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          }
        ]
      },
      {
        "name": "result_customer_month",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "profit_amt",
            "dataType": "double",
            "sourceColumn": "profit_amt"
          },
          {
            "name": "sale_amt",
            "dataType": "double",
            "sourceColumn": "sale_amt"
          },
          {
            "name": "cost_amt",
            "dataType": "double",
            "sourceColumn": "cost_amt"
          },
          {
            "name": "input_output_ratio",
            "dataType": "double",
            "sourceColumn": "input_output_ratio"
          },
          {
            "name": "redundancy",
            "dataType": "double",
            "sourceColumn": "redundancy"
          },
          {
            "name": "day_sale_amt",
            "dataType": "double",
            "sourceColumn": "day_sale_amt"
          },
          {
            "name": "MonthKey",
            "dataType": "int64",
            "sourceColumn": "MonthKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_result_customer_month = Source{[Schema=\"dbo\",Item=\"result_customer_month\"]}[Data]",
                "in",
                "    dbo_result_customer_month"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "result_customer_month_销售额目标",
            "expression": " SUMX('target_customer_month','target_customer_month'[target_sale_amt])"
          },
          {
            "name": "result_customer_month_销售额实际",
            "expression": " SUMX('result_customer_month','result_customer_month'[sale_amt])"
          },
          {
            "name": "result_customer_month_销售额目标达成率",
            "expression": " DIVIDE([result_customer_month_销售额实际],[result_customer_month_销售额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_month_销售额目标实际差异",
            "expression": "  [result_customer_month_销售额实际]-[result_customer_month_销售额目标]"
          },
          {
            "name": "result_customer_month_销售额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_customer_month_销售额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_customer_month_销售额实际]-[result_customer_month_销售额实际_去年同期]), [result_customer_month_销售额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_month_销售额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_customer_month_销售额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_customer_month_销售额实际]-[result_customer_month_销售额实际_上月同期]),[result_customer_month_销售额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_month_客户利润额目标",
            "expression": " SUMX('target_customer_month','target_customer_month'[target_profit_amt])"
          },
          {
            "name": "result_customer_month_客户利润额实际",
            "expression": " SUMX('result_customer_month','result_customer_month'[profit_amt])"
          },
          {
            "name": "result_customer_month_客户利润额目标达成率",
            "expression": " DIVIDE([result_customer_month_客户利润额实际],[result_customer_month_客户利润额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_month_客户利润额目标实际差异",
            "expression": " [result_customer_month_客户利润额实际]-[result_customer_month_客户利润额目标]"
          },
          {
            "name": "result_customer_month_客户利润额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_customer_month_客户利润额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_customer_month_客户利润额实际]-[result_customer_month_客户利润额实际_去年同期]), [result_customer_month_客户利润额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_month_客户利润额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_customer_month_客户利润额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_customer_month_客户利润额实际]-[result_customer_month_客户利润额实际_上月同期]),[result_customer_month_客户利润额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_month_客户费用额目标",
            "expression": " SUMX('target_customer_month','target_customer_month'[target_cost_amt])"
          },
          {
            "name": "result_customer_month_客户费用额实际",
            "expression": "  SUMX('result_customer_month','result_customer_month'[cost_amt])"
          },
          {
            "name": "result_customer_month_客户费用额目标达成率",
            "expression": " DIVIDE([result_customer_month_客户费用额实际],[result_customer_month_客户费用额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_month_客户费用额目标实际差异",
            "expression": " [result_customer_month_客户费用额实际]-[result_customer_month_客户费用额目标]"
          },
          {
            "name": "result_customer_month_客户费用额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_customer_month_客户费用额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_customer_month_客户费用额实际]-[result_customer_month_客户费用额实际_去年同期]), [result_customer_month_客户费用额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_month_客户费用额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_customer_month_客户费用额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_customer_month_客户费用额实际]-[result_customer_month_客户费用额实际_上月同期]),[result_customer_month_客户费用额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_month_日销目标",
            "expression": " 1"
          },
          {
            "name": "result_customer_month_日销实际",
            "expression": " SUMX('result_customer_month','result_customer_month'[day_sale_amt])"
          },
          {
            "name": "result_customer_month_日销目标达成率",
            "expression": "  DIVIDE([result_customer_month_日销实际],[result_customer_month_日销目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_month_日销目标实际差异",
            "expression": " [result_customer_month_日销实际]-[result_customer_month_日销目标]"
          },
          {
            "name": "result_customer_month_日销同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_customer_month_日销实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_customer_month_日销实际]-[result_customer_month_日销实际_去年同期]), [result_customer_month_日销实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_month_日销环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_customer_month_日销实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_customer_month_日销实际]-[result_customer_month_日销实际_上月同期]),[result_customer_month_日销实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_month_客户投入产出比目标",
            "expression": "  DIVIDE([result_customer_month_客户利润额目标],[result_customer_month_客户费用额目标])"
          },
          {
            "name": "result_customer_month_客户投入产出比实际",
            "expression": " SUMX('result_customer_month','result_customer_month'[input_output_ratio])"
          },
          {
            "name": "result_customer_month_客户投入产出比目标达成率",
            "expression": " DIVIDE([result_customer_month_客户投入产出比实际],[result_customer_month_客户投入产出比目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_month_客户投入产出比目标实际差异",
            "expression": " [result_customer_month_客户投入产出比实际]-[result_customer_month_客户投入产出比目标]"
          },
          {
            "name": "result_customer_month_客户投入产出比同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_customer_month_客户投入产出比实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_customer_month_客户投入产出比实际]-[result_customer_month_客户投入产出比实际_去年同期]), [result_customer_month_客户投入产出比实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_month_客户投入产出比环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_customer_month_客户投入产出比实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_customer_month_客户投入产出比实际]-[result_customer_month_客户投入产出比实际_上月同期]),[result_customer_month_客户投入产出比实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_month_客户冗余值目标",
            "expression": " SUMX('target_customer_month','target_customer_month'[target_redundancy])"
          },
          {
            "name": "result_customer_month_客户冗余值实际",
            "expression": "  SUMX('result_customer_month','result_customer_month'[redundancy])"
          },
          {
            "name": "result_customer_month_客户冗余值目标达成率",
            "expression": " DIVIDE([result_customer_month_客户冗余值实际],[result_customer_month_客户冗余值目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_month_客户冗余值目标实际差异",
            "expression": " [result_customer_month_客户冗余值实际]-[result_customer_month_客户冗余值目标]"
          },
          {
            "name": "result_customer_month_客户冗余值同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_customer_month_客户冗余值实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_customer_month_客户冗余值实际]-[result_customer_month_客户冗余值实际_去年同期]), [result_customer_month_客户冗余值实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_month_客户冗余值环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_customer_month_客户冗余值实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_customer_month_客户冗余值实际]-[result_customer_month_客户冗余值实际_上月同期]),[result_customer_month_客户冗余值实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_month_销售额实际_去年同期",
            "expression": "CALCULATE([result_customer_month_销售额实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_customer_month_销售额实际_上月同期",
            "expression": "CALCULATE([result_customer_month_销售额实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_customer_month_客户利润额实际_去年同期",
            "expression": "CALCULATE([result_customer_month_客户利润额实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_customer_month_客户利润额实际_上月同期",
            "expression": "CALCULATE([result_customer_month_客户利润额实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_customer_month_客户费用额实际_去年同期",
            "expression": "CALCULATE([result_customer_month_客户费用额实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_customer_month_客户费用额实际_上月同期",
            "expression": "CALCULATE([result_customer_month_客户费用额实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_customer_month_日销实际_去年同期",
            "expression": "CALCULATE([result_customer_month_日销实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_customer_month_日销实际_上月同期",
            "expression": "CALCULATE([result_customer_month_日销实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_customer_month_客户投入产出比实际_去年同期",
            "expression": "CALCULATE([result_customer_month_客户投入产出比实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_customer_month_客户投入产出比实际_上月同期",
            "expression": "CALCULATE([result_customer_month_客户投入产出比实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_customer_month_客户冗余值实际_去年同期",
            "expression": "CALCULATE([result_customer_month_客户冗余值实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_customer_month_客户冗余值实际_上月同期",
            "expression": "CALCULATE([result_customer_month_客户冗余值实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          }
        ]
      },
      {
        "name": "result_customer_day",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "profit_amt",
            "dataType": "double",
            "sourceColumn": "profit_amt"
          },
          {
            "name": "sale_amt",
            "dataType": "double",
            "sourceColumn": "sale_amt"
          },
          {
            "name": "cost_amt",
            "dataType": "double",
            "sourceColumn": "cost_amt"
          },
          {
            "name": "input_output_ratio",
            "dataType": "double",
            "sourceColumn": "input_output_ratio"
          },
          {
            "name": "redundancy",
            "dataType": "double",
            "sourceColumn": "redundancy"
          },
          {
            "name": "day_sale_amt",
            "dataType": "double",
            "sourceColumn": "day_sale_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_result_customer_day = Source{[Schema=\"dbo\",Item=\"result_customer_day\"]}[Data]",
                "in",
                "    dbo_result_customer_day"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "result_customer_day_销售额目标",
            "expression": " SUMX('target_customer_day','target_customer_day'[target_sale_amt])"
          },
          {
            "name": "result_customer_day_销售额实际",
            "expression": " SUMX('result_customer_day','result_customer_day'[sale_amt])"
          },
          {
            "name": "result_customer_day_销售额目标达成率",
            "expression": " DIVIDE([result_customer_day_销售额实际],[result_customer_day_销售额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_day_销售额目标实际差异",
            "expression": "  [result_customer_day_销售额实际]-[result_customer_day_销售额目标]"
          },
          {
            "name": "result_customer_day_销售额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_customer_day_销售额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_customer_day_销售额实际]-[result_customer_day_销售额实际_去年同期]), [result_customer_day_销售额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_day_销售额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_customer_day_销售额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_customer_day_销售额实际]-[result_customer_day_销售额实际_上月同期]),[result_customer_day_销售额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_day_客户利润额目标",
            "expression": "  SUMX('target_customer_day','target_customer_day'[target_profit_amt])"
          },
          {
            "name": "result_customer_day_客户利润额实际",
            "expression": "  SUMX('result_customer_day','result_customer_day'[profit_amt])"
          },
          {
            "name": "result_customer_day_客户利润额目标达成率",
            "expression": " DIVIDE([result_customer_day_客户利润额实际],[result_customer_day_客户利润额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_day_客户利润额目标实际差异",
            "expression": " [result_customer_day_客户利润额实际]-[result_customer_day_客户利润额目标]"
          },
          {
            "name": "result_customer_day_客户利润额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_customer_day_客户利润额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_customer_day_客户利润额实际]-[result_customer_day_客户利润额实际_去年同期]), [result_customer_day_客户利润额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_day_客户利润额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_customer_day_客户利润额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_customer_day_客户利润额实际]-[result_customer_day_客户利润额实际_上月同期]),[result_customer_day_客户利润额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_day_客户费用额目标",
            "expression": "  SUMX('target_customer_day','target_customer_day'[target_cost_amt])"
          },
          {
            "name": "result_customer_day_客户费用额实际",
            "expression": " SUMX('result_customer_day','result_customer_day'[cost_amt])"
          },
          {
            "name": "result_customer_day_客户费用额目标达成率",
            "expression": " DIVIDE([result_customer_day_客户费用额实际],[result_customer_day_客户费用额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_day_客户费用额目标实际差异",
            "expression": " [result_customer_day_客户费用额实际]-[result_customer_day_客户费用额目标]"
          },
          {
            "name": "result_customer_day_客户费用额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_customer_day_客户费用额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_customer_day_客户费用额实际]-[result_customer_day_客户费用额实际_去年同期]), [result_customer_day_客户费用额实际_去年同期])))",
              "",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_day_客户费用额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_customer_day_客户费用额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_customer_day_客户费用额实际]-[result_customer_day_客户费用额实际_上月同期]),[result_customer_day_客户费用额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_day_日销目标",
            "expression": " 1"
          },
          {
            "name": "result_customer_day_日销实际",
            "expression": " SUMX('result_customer_day','result_customer_day'[day_sale_amt])"
          },
          {
            "name": "result_customer_day_日销目标成率",
            "expression": " DIVIDE([result_customer_day_日销实际],[result_customer_day_日销目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_day_日销目标实际差异",
            "expression": "  [result_customer_day_日销实际]-[result_customer_day_日销目标]"
          },
          {
            "name": "result_customer_day_日销同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_customer_day_日销实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_customer_day_日销实际]-[result_customer_day_日销实际_去年同期]), [result_customer_day_日销实际_去年同期])))",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_day_日销环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_customer_day_日销实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_customer_day_日销实际]-[result_customer_day_日销实际_上月同期]),[result_customer_day_日销实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_day_客户投入产出比目标",
            "expression": "  DIVIDE([result_customer_day_客户利润额目标],[result_customer_day_客户费用额目标])"
          },
          {
            "name": "result_customer_day_客户投入产出比实际",
            "expression": " SUMX('result_customer_day','result_customer_day'[input_output_ratio])"
          },
          {
            "name": "result_customer_day_客户投入产出比目标达成率",
            "expression": " DIVIDE([result_customer_day_客户投入产出比实际],[result_customer_day_客户投入产出比目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_day_客户投入产出比目标实际差异",
            "expression": " [result_customer_day_客户投入产出比实际]-[result_customer_day_客户投入产出比目标]"
          },
          {
            "name": "result_customer_day_客户投入产出比同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_customer_day_客户投入产出比实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_customer_day_客户投入产出比实际]-[result_customer_day_客户投入产出比实际_去年同期]), [result_customer_day_客户投入产出比实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_day_客户投入产出比环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_customer_day_客户投入产出比实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_customer_day_客户投入产出比实际]-[result_customer_day_客户投入产出比实际_上月同期]),[result_customer_day_客户投入产出比实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_day_客户冗余值目标",
            "expression": "  SUMX('target_customer_day','target_customer_day'[target_redundancy])"
          },
          {
            "name": "result_customer_day_客户冗余值实际",
            "expression": " SUMX('result_customer_day','result_customer_day'[redundancy])"
          },
          {
            "name": "result_customer_day_客户冗余值目标达成率",
            "expression": "  DIVIDE([result_customer_day_客户冗余值实际],[result_customer_day_客户冗余值目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_day_客户冗余值目标实际差异",
            "expression": " [result_customer_day_客户冗余值实际]-[result_customer_day_客户冗余值目标]"
          },
          {
            "name": "result_customer_day_客户冗余值同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_customer_day_客户冗余值实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_customer_day_客户冗余值实际]-[result_customer_day_客户冗余值实际_去年同期]), [result_customer_day_客户冗余值实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_day_客户冗余值环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_customer_day_客户冗余值实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_customer_day_客户冗余值实际]-[result_customer_day_客户冗余值实际_上月同期]),[result_customer_day_客户冗余值实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_customer_day_销售额实际_去年同期",
            "expression": "CALCULATE([result_customer_day_销售额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "result_customer_day_销售额实际_上月同期",
            "expression": "CALCULATE([result_customer_day_销售额实际], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "result_customer_day_客户利润额实际_去年同期",
            "expression": "CALCULATE([result_customer_day_客户利润额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "result_customer_day_客户利润额实际_上月同期",
            "expression": "CALCULATE([result_customer_day_客户利润额实际], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "result_customer_day_客户费用额实际_去年同期",
            "expression": [
              "CALCULATE([result_customer_day_客户费用额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
              "",
              ""
            ]
          },
          {
            "name": "result_customer_day_客户费用额实际_上月同期",
            "expression": "CALCULATE([result_customer_day_客户费用额实际], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "result_customer_day_日销实际_去年同期",
            "expression": [
              "CALCULATE([result_customer_day_日销实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
              ""
            ]
          },
          {
            "name": "result_customer_day_日销实际_上月同期",
            "expression": "CALCULATE([result_customer_day_日销实际], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "result_customer_day_客户投入产出比实际_去年同期",
            "expression": "CALCULATE([result_customer_day_客户投入产出比实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "result_customer_day_客户投入产出比实际_上月同期",
            "expression": "CALCULATE([result_customer_day_客户投入产出比实际], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "result_customer_day_客户冗余值实际_去年同期",
            "expression": "CALCULATE([result_customer_day_客户冗余值实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "result_customer_day_客户冗余值实际_上月同期",
            "expression": "CALCULATE([result_customer_day_客户冗余值实际], DATEADD('DimDate'[FullDate], -1, MONTH))"
          }
        ]
      },
      {
        "name": "result_channel_month",
        "columns": [
          {
            "name": "ChannelKey",
            "dataType": "int64",
            "sourceColumn": "ChannelKey"
          },
          {
            "name": "profit_amt",
            "dataType": "double",
            "sourceColumn": "profit_amt"
          },
          {
            "name": "sale_amt",
            "dataType": "double",
            "sourceColumn": "sale_amt"
          },
          {
            "name": "cost_amt",
            "dataType": "double",
            "sourceColumn": "cost_amt"
          },
          {
            "name": "input_output_ratio",
            "dataType": "double",
            "sourceColumn": "input_output_ratio"
          },
          {
            "name": "redundancy",
            "dataType": "double",
            "sourceColumn": "redundancy"
          },
          {
            "name": "day_sale_amt",
            "dataType": "double",
            "sourceColumn": "day_sale_amt"
          },
          {
            "name": "MonthKey",
            "dataType": "int64",
            "sourceColumn": "MonthKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_result_channel_month = Source{[Schema=\"dbo\",Item=\"result_channel_month\"]}[Data]",
                "in",
                "    dbo_result_channel_month"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "result_channel_month_渠道营业利润额目标",
            "expression": " SUMX('target_channel_month','target_channel_month'[target_profit_amt])"
          },
          {
            "name": "result_channel_month_渠道营业利润额实际",
            "expression": " SUMX('result_channel_month','result_channel_month'[profit_amt])"
          },
          {
            "name": "result_channel_month_渠道营业利润额目标达成率",
            "expression": "  DIVIDE([result_channel_month_渠道营业利润额实际],[result_channel_month_渠道营业利润额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_month_渠道营业利润额目标实际差异",
            "expression": "  [result_channel_month_渠道营业利润额实际]-[result_channel_month_渠道营业利润额目标]"
          },
          {
            "name": "result_channel_month_渠道营业利润额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_channel_month_渠道营业利润额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_channel_month_渠道营业利润额实际]-[result_channel_month_渠道营业利润额实际_去年同期]), [result_channel_month_渠道营业利润额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_month_渠道营业利润额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_channel_month_渠道营业利润额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_channel_month_渠道营业利润额实际]-[result_channel_month_渠道营业利润额实际_上月同期]),[result_channel_month_渠道营业利润额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_month_销售额目标",
            "expression": " SUMX('target_channel_month','target_channel_month'[target_sale_amt])"
          },
          {
            "name": "result_channel_month_销售额实际",
            "expression": " SUMX('result_channel_month','result_channel_month'[sale_amt])"
          },
          {
            "name": "result_channel_month_销售额目标达成率",
            "expression": "  DIVIDE([result_channel_month_销售额实际],[result_channel_month_销售额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_month_销售额目标实际差异",
            "expression": "  [result_channel_month_销售额实际]-[result_channel_month_销售额目标]"
          },
          {
            "name": "result_channel_month_销售额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_channel_month_销售额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_channel_month_销售额实际]-[result_channel_month_销售额实际_去年同期]), [result_channel_month_销售额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_month_销售额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_channel_month_销售额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_channel_month_销售额实际]-[result_channel_month_销售额实际_上月同期]),[result_channel_month_销售额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_month_渠道费用额目标",
            "expression": " SUMX('target_channel_month','target_channel_month'[target_cost_amt])"
          },
          {
            "name": "result_channel_month_渠道费用额实际",
            "expression": " SUMX('result_channel_month','result_channel_month'[cost_amt])"
          },
          {
            "name": "result_channel_month_渠道费用额目标达成率",
            "expression": " DIVIDE([result_channel_month_渠道费用额实际],[result_channel_month_渠道费用额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_month_渠道费用额目标实际差异",
            "expression": "  [result_channel_month_渠道费用额实际]-[result_channel_month_渠道费用额目标]"
          },
          {
            "name": "result_channel_month_渠道费用额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_channel_month_渠道费用额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_channel_month_渠道费用额实际]-[result_channel_month_渠道费用额实际_去年同期]), [result_channel_month_渠道费用额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_month_渠道费用额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_channel_month_渠道费用额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_channel_month_渠道费用额实际]-[result_channel_month_渠道费用额实际_上月同期]),[result_channel_month_渠道费用额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_month_渠道投入产出比目标",
            "expression": " DIVIDE([result_channel_month_渠道营业利润额目标],[result_channel_month_渠道费用额目标])"
          },
          {
            "name": "result_channel_month_渠道投入产出比实际",
            "expression": " SUMX('result_channel_month','result_channel_month'[input_output_ratio])"
          },
          {
            "name": "result_channel_month_渠道投入产出比目标达成率",
            "expression": " DIVIDE([result_channel_month_渠道投入产出比实际],[result_channel_month_渠道投入产出比目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_month_渠道投入产出比目标实际差异",
            "expression": "  [result_channel_month_渠道投入产出比实际]-[result_channel_month_渠道投入产出比目标]"
          },
          {
            "name": "result_channel_month_渠道投入产出比同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_channel_month_渠道投入产出比实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_channel_month_渠道投入产出比实际]-[result_channel_month_渠道投入产出比实际_去年同期]), [result_channel_month_渠道投入产出比实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_month_渠道投入产出比环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_channel_month_渠道投入产出比实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_channel_month_渠道投入产出比实际]-[result_channel_month_渠道投入产出比实际_上月同期]),[result_channel_month_渠道投入产出比实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_month_渠道冗余值目标",
            "expression": "  SUMX('target_channel_month','target_channel_month'[target_redundancy_amt])"
          },
          {
            "name": "result_channel_month_渠道冗余值实际",
            "expression": " SUMX('result_channel_month','result_channel_month'[redundancy])"
          },
          {
            "name": "result_channel_month_渠道冗余值目标达成率",
            "expression": " DIVIDE([result_channel_month_渠道冗余值实际],[result_channel_month_渠道冗余值目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_month_渠道冗余值目标实际差异",
            "expression": " [result_channel_month_渠道冗余值实际]-[result_channel_month_渠道冗余值目标]"
          },
          {
            "name": "result_channel_month_渠道冗余值同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_channel_month_渠道冗余值实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_channel_month_渠道冗余值实际]-[result_channel_month_渠道冗余值实际_去年同期]), [result_channel_month_渠道冗余值实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_month_渠道冗余值环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_channel_month_渠道冗余值实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_channel_month_渠道冗余值实际]-[result_channel_month_渠道冗余值实际_上月同期]),[result_channel_month_渠道冗余值实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_month_日销目标",
            "expression": " 1"
          },
          {
            "name": "result_channel_month_日销实际",
            "expression": " SUMX('result_channel_month','result_channel_month'[day_sale_amt])"
          },
          {
            "name": "result_channel_month_日销目标达成率",
            "expression": "  DIVIDE([result_channel_month_日销实际],[result_channel_month_日销目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_month_日销目标实际差异",
            "expression": "  [result_channel_month_日销实际]-[result_channel_month_日销目标]"
          },
          {
            "name": "result_channel_month_日销同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_channel_month_日销实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_channel_month_日销实际]-[result_channel_month_日销实际_去年同期]), [result_channel_month_日销实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_month_日销环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_channel_month_日销实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_channel_month_日销实际]-[result_channel_month_日销实际_上月同期]),[result_channel_month_日销实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_month_渠道营业利润额实际_去年同期",
            "expression": "CALCULATE([result_channel_month_渠道营业利润额实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_channel_month_渠道营业利润额实际_上月同期",
            "expression": "CALCULATE([result_channel_month_渠道营业利润额实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_channel_month_销售额实际_去年同期",
            "expression": "CALCULATE([result_channel_month_销售额实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_channel_month_销售额实际_上月同期",
            "expression": "CALCULATE([result_channel_month_销售额实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_channel_month_渠道费用额实际_去年同期",
            "expression": "CALCULATE([result_channel_month_渠道费用额实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_channel_month_渠道费用额实际_上月同期",
            "expression": "CALCULATE([result_channel_month_渠道费用额实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_channel_month_渠道投入产出比实际_去年同期",
            "expression": "CALCULATE([result_channel_month_渠道投入产出比实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_channel_month_渠道投入产出比实际_上月同期",
            "expression": "CALCULATE([result_channel_month_渠道投入产出比实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_channel_month_渠道冗余值实际_去年同期",
            "expression": "CALCULATE([result_channel_month_渠道冗余值实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_channel_month_渠道冗余值实际_上月同期",
            "expression": "CALCULATE([result_channel_month_渠道冗余值实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "result_channel_month_日销实际_去年同期",
            "expression": "CALCULATE([result_channel_month_日销实际],DATEADD('V_DimMonth'[EndDate],-1,YEAR),ALL('V_DimMonth'[YearNameEn]))"
          },
          {
            "name": "result_channel_month_日销实际_上月同期",
            "expression": "CALCULATE([result_channel_month_日销实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          }
        ]
      },
      {
        "name": "result_channel_day",
        "columns": [
          {
            "name": "ChannelKey",
            "dataType": "int64",
            "sourceColumn": "ChannelKey"
          },
          {
            "name": "profit_amt",
            "dataType": "double",
            "sourceColumn": "profit_amt"
          },
          {
            "name": "sale_amt",
            "dataType": "double",
            "sourceColumn": "sale_amt"
          },
          {
            "name": "cost_amt",
            "dataType": "double",
            "sourceColumn": "cost_amt"
          },
          {
            "name": "input_output_ratio",
            "dataType": "double",
            "sourceColumn": "input_output_ratio"
          },
          {
            "name": "redundancy",
            "dataType": "double",
            "sourceColumn": "redundancy"
          },
          {
            "name": "day_sale_amt",
            "dataType": "double",
            "sourceColumn": "day_sale_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_result_channel_day = Source{[Schema=\"dbo\",Item=\"result_channel_day\"]}[Data]",
                "in",
                "    dbo_result_channel_day"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "result_channel_day_渠道营业利润额目标",
            "expression": " SUMX('target_channel_day','target_channel_day'[target_profit_amt])"
          },
          {
            "name": "result_channel_day_渠道营业利润额实际",
            "expression": " SUMX('result_channel_day','result_channel_day'[profit_amt])"
          },
          {
            "name": "result_channel_day_渠道营业利润额目标达成率",
            "expression": " DIVIDE([result_channel_day_渠道营业利润额实际],[result_channel_day_渠道营业利润额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_day_渠道营业利润额目标实际差异",
            "expression": " [result_channel_day_渠道营业利润额实际]-[result_channel_day_渠道营业利润额目标]"
          },
          {
            "name": "result_channel_day_渠道营业利润额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_channel_day_渠道营业利润额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_channel_day_渠道营业利润额实际]-[result_channel_day_渠道营业利润额实际_去年同期]), [result_channel_day_渠道营业利润额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_day_渠道营业利润额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_channel_day_渠道营业利润额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_channel_day_渠道营业利润额实际]-[result_channel_day_渠道营业利润额实际_上月同期]),[result_channel_day_渠道营业利润额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_day_销售额目标",
            "expression": " SUMX('target_channel_day','target_channel_day'[target_sale_amt])"
          },
          {
            "name": "result_channel_day_销售额实际",
            "expression": " SUMX('result_channel_day','result_channel_day'[sale_amt])"
          },
          {
            "name": "result_channel_day_销售额目标达成率",
            "expression": " DIVIDE([result_channel_day_销售额实际],[result_channel_day_销售额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_day_销售额目标实际差异",
            "expression": "  [result_channel_day_销售额实际]-[result_channel_day_销售额目标]"
          },
          {
            "name": "result_channel_day_销售额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_channel_day_销售额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_channel_day_销售额实际]-[result_channel_day_销售额实际_去年同期]), [result_channel_day_销售额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_day_销售额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_channel_day_销售额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_channel_day_销售额实际]-[result_channel_day_销售额实际_上月同期]),[result_channel_day_销售额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_day_渠道费用额目标",
            "expression": " SUMX('target_channel_day','target_channel_day'[target_cost_amt])"
          },
          {
            "name": "result_channel_day_渠道费用额实际",
            "expression": " SUMX('result_channel_day','result_channel_day'[cost_amt])"
          },
          {
            "name": "result_channel_day_渠道费用额目标达成率",
            "expression": " DIVIDE([result_channel_day_渠道费用额实际],[result_channel_day_渠道费用额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_day_渠道费用额目标实际差异",
            "expression": " [result_channel_day_渠道费用额实际]-[result_channel_day_渠道费用额目标]"
          },
          {
            "name": "result_channel_day_渠道费用额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_channel_day_渠道费用额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_channel_day_渠道费用额实际]-[result_channel_day_渠道费用额实际_去年同期]), [result_channel_day_渠道费用额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_day_渠道费用额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_channel_day_渠道费用额实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_channel_day_渠道费用额实际]-[result_channel_day_渠道费用额实际_上月同期]),[result_channel_day_渠道费用额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_day_渠道投入产出比目标",
            "expression": " DIVIDE([result_channel_day_渠道营业利润额目标],[result_channel_day_渠道费用额目标])"
          },
          {
            "name": "result_channel_day_渠道投入产出比实际",
            "expression": "  SUMX('result_channel_day','result_channel_day'[input_output_ratio])"
          },
          {
            "name": "result_channel_day_渠道投入产出比目标达成率",
            "expression": " DIVIDE([result_channel_day_渠道投入产出比实际],[result_channel_day_渠道投入产出比目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_day_渠道投入产出比目标实际差异",
            "expression": " [result_channel_day_渠道投入产出比实际]-[result_channel_day_渠道投入产出比目标]"
          },
          {
            "name": "result_channel_day_渠道投入产出比同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_channel_day_渠道投入产出比实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_channel_day_渠道投入产出比实际]-[result_channel_day_渠道投入产出比实际_去年同期]), [result_channel_day_渠道投入产出比实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_day_渠道投入产出比环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_channel_day_渠道投入产出比实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_channel_day_渠道投入产出比实际]-[result_channel_day_渠道投入产出比实际_上月同期]),[result_channel_day_渠道投入产出比实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_day_渠道冗余值目标",
            "expression": "  SUMX('target_channel_day','target_channel_day'[target_redundancy_amt])"
          },
          {
            "name": "result_channel_day_渠道冗余值实际",
            "expression": " SUMX('result_channel_day','result_channel_day'[redundancy])"
          },
          {
            "name": "result_channel_day_渠道冗余值目标达成率",
            "expression": " DIVIDE([result_channel_day_渠道冗余值实际],[result_channel_day_渠道冗余值目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_day_渠道冗余值目标实际差异",
            "expression": "  [result_channel_day_渠道冗余值实际]-[result_channel_day_渠道冗余值目标]"
          },
          {
            "name": "result_channel_day_渠道冗余值同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_channel_day_渠道冗余值实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_channel_day_渠道冗余值实际]-[result_channel_day_渠道冗余值实际_去年同期]), [result_channel_day_渠道冗余值实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_day_渠道冗余值环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_channel_day_渠道冗余值实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_channel_day_渠道冗余值实际]-[result_channel_day_渠道冗余值实际_上月同期]),[result_channel_day_渠道冗余值实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_day_日销目标",
            "expression": " 1"
          },
          {
            "name": "result_channel_day_日销实际",
            "expression": " SUMX('result_channel_day','result_channel_day'[day_sale_amt])"
          },
          {
            "name": "result_channel_day_日销目标达成率",
            "expression": " DIVIDE([result_channel_day_日销实际],[result_channel_day_日销目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_day_日销目标实际差异",
            "expression": "  [result_channel_day_日销实际]-[result_channel_day_日销目标]"
          },
          {
            "name": "result_channel_day_日销同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([result_channel_day_日销实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([result_channel_day_日销实际]-[result_channel_day_日销实际_去年同期]), [result_channel_day_日销实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_day_日销环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([result_channel_day_日销实际]),",
              "   \t 0,",
              "\tDIVIDE(([result_channel_day_日销实际]-[result_channel_day_日销实际_上月同期]),[result_channel_day_日销实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "result_channel_day_渠道营业利润额实际_去年同期",
            "expression": "CALCULATE([result_channel_day_渠道营业利润额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "result_channel_day_渠道营业利润额实际_上月同期",
            "expression": "CALCULATE([result_channel_day_渠道营业利润额实际], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "result_channel_day_销售额实际_去年同期",
            "expression": "CALCULATE([result_channel_day_销售额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "result_channel_day_销售额实际_上月同期",
            "expression": "CALCULATE([result_channel_day_销售额实际], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "result_channel_day_渠道费用额实际_去年同期",
            "expression": "CALCULATE([result_channel_day_渠道费用额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "result_channel_day_渠道费用额实际_上月同期",
            "expression": "CALCULATE([result_channel_day_渠道费用额实际], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "result_channel_day_渠道投入产出比实际_去年同期",
            "expression": "CALCULATE([result_channel_day_渠道投入产出比实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "result_channel_day_渠道投入产出比实际_上月同期",
            "expression": "CALCULATE([result_channel_day_渠道投入产出比实际], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "result_channel_day_渠道冗余值实际_去年同期",
            "expression": "CALCULATE([result_channel_day_渠道冗余值实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "result_channel_day_渠道冗余值实际_上月同期",
            "expression": "CALCULATE([result_channel_day_渠道冗余值实际], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "result_channel_day_日销实际_去年同期",
            "expression": "CALCULATE([result_channel_day_日销实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          },
          {
            "name": "result_channel_day_日销实际_上月同期",
            "expression": "CALCULATE([result_channel_day_日销实际], DATEADD('DimDate'[FullDate], -1, MONTH))"
          }
        ]
      },
      {
        "name": "产品效率_综合评估_月",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "目标达成率",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[目标达成率]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"毛利润额\" ,   [result_product_month_毛利润额目标达成率],) , ",
                "    ( \"销售额\" , [result_product_month_销售额目标达成率], ),",
                "    ( \"产品成本额(2-目标达成率)\" , 2-[result_product_month_产品成本额目标达成率], ),",
                "    ( \"产品投入产出比\" , [result_product_month_产品投入产出比目标达成率], ),",
                "    ( \"库存周转率\" , [result_product_month_库存周转率目标达成率], ),",
                "    ( \"日销\" , [result_product_month_日销目标达成率], ),",
                "    ( \"库存额(2-目标达成率)\" , 2-[result_product_month_库存额目标达成率], )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] , \"目标达成率\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "产品效率_综合评估_日",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "目标达成率",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[目标达成率]",
            "formatString": "0.00"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"毛利润额\" ,   [result_product_day_毛利润额目标达成率],) , ",
                "    ( \"销售额\" , [result_product_day_销售额目标达成率], ),",
                "    ( \"产品成本额(2-目标达成率)\" , 2-[result_product_day_产品成本额目标达成率], ),",
                "    ( \"产品投入产出比\" , [result_product_day_产品投入产出比目标达成率], ),",
                "    ( \"库存周转率\" , [result_product_day_库存周转率目标达成率], ),",
                "    ( \"日销\" , [result_product_day_日销目标达成率], ),",
                "    ( \"库存额(2-目标达成率)\" , 2-[result_product_day_库存额目标达成率], )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] , \"目标达成率\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "target_supply_month",
        "columns": [
          {
            "name": "SupplyKey",
            "dataType": "int64",
            "sourceColumn": "SupplyKey"
          },
          {
            "name": "target_sale_amt",
            "dataType": "double",
            "sourceColumn": "target_sale_amt"
          },
          {
            "name": "target_profit_amt",
            "dataType": "double",
            "sourceColumn": "target_profit_amt"
          },
          {
            "name": "target_production_capacity",
            "dataType": "double",
            "sourceColumn": "target_production_capacity"
          },
          {
            "name": "target_production_ratio",
            "dataType": "double",
            "sourceColumn": "target_production_ratio"
          },
          {
            "name": "target_capacity_safety_value",
            "dataType": "double",
            "sourceColumn": "target_capacity_safety_value"
          },
          {
            "name": "target_delivery_rate",
            "dataType": "double",
            "sourceColumn": "target_delivery_rate"
          },
          {
            "name": "target_residual_rate",
            "dataType": "double",
            "sourceColumn": "target_residual_rate"
          },
          {
            "name": "MonthKey",
            "dataType": "int64",
            "sourceColumn": "MonthKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_target_supply_month = Source{[Schema=\"dbo\",Item=\"target_supply_month\"]}[Data]",
                "in",
                "    dbo_target_supply_month"
              ]
            }
          }
        ]
      },
      {
        "name": "target_product_month",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "target_sale_amt",
            "dataType": "double",
            "sourceColumn": "target_sale_amt"
          },
          {
            "name": "target_cost_amt",
            "dataType": "double",
            "sourceColumn": "target_cost_amt"
          },
          {
            "name": "target_stock_amt",
            "dataType": "double",
            "sourceColumn": "target_stock_amt"
          },
          {
            "name": "MonthKey",
            "dataType": "int64",
            "sourceColumn": "MonthKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_target_product_month = Source{[Schema=\"dbo\",Item=\"target_product_month\"]}[Data]",
                "in",
                "    dbo_target_product_month"
              ]
            }
          }
        ]
      },
      {
        "name": "target_product_day",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "target_sale_amt",
            "dataType": "double",
            "sourceColumn": "target_sale_amt"
          },
          {
            "name": "target_cost_amt",
            "dataType": "double",
            "sourceColumn": "target_cost_amt"
          },
          {
            "name": "target_stock_amt",
            "dataType": "double",
            "sourceColumn": "target_stock_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_target_product_day = Source{[Schema=\"dbo\",Item=\"target_product_day\"]}[Data]",
                "in",
                "    dbo_target_product_day"
              ]
            }
          }
        ]
      },
      {
        "name": "target_org_month",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "target_profit_amt",
            "dataType": "double",
            "sourceColumn": "target_profit_amt"
          },
          {
            "name": "target_sale_amt",
            "dataType": "double",
            "sourceColumn": "target_sale_amt"
          },
          {
            "name": "target_cost_amt",
            "dataType": "double",
            "sourceColumn": "target_cost_amt"
          },
          {
            "name": "target_redundancy",
            "dataType": "double",
            "sourceColumn": "target_redundancy"
          },
          {
            "name": "MonthKey",
            "dataType": "int64",
            "sourceColumn": "MonthKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_target_org_month = Source{[Schema=\"dbo\",Item=\"target_org_month\"]}[Data]",
                "in",
                "    dbo_target_org_month"
              ]
            }
          }
        ]
      },
      {
        "name": "target_finance_month",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "target_sale_amt",
            "dataType": "double",
            "sourceColumn": "target_sale_amt"
          },
          {
            "name": "target_total_cost_amt",
            "dataType": "double",
            "sourceColumn": "target_total_cost_amt"
          },
          {
            "name": "target_return_amt",
            "dataType": "double",
            "sourceColumn": "target_return_amt"
          },
          {
            "name": "target_invest_amt",
            "dataType": "double",
            "sourceColumn": "target_invest_amt"
          },
          {
            "name": "target_total_assets_amt",
            "dataType": "double",
            "sourceColumn": "target_total_assets_amt"
          },
          {
            "name": "target_cash_flow_amt",
            "dataType": "double",
            "sourceColumn": "target_cash_flow_amt"
          },
          {
            "name": "target_redundancy",
            "dataType": "double",
            "sourceColumn": "target_redundancy"
          },
          {
            "name": "MonthKey",
            "dataType": "int64",
            "sourceColumn": "MonthKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_target_finance_month = Source{[Schema=\"dbo\",Item=\"target_finance_month\"]}[Data]",
                "in",
                "    dbo_target_finance_month"
              ]
            }
          }
        ]
      },
      {
        "name": "target_customer_month",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "target_profit_amt",
            "dataType": "double",
            "sourceColumn": "target_profit_amt"
          },
          {
            "name": "target_sale_amt",
            "dataType": "double",
            "sourceColumn": "target_sale_amt"
          },
          {
            "name": "target_cost_amt",
            "dataType": "double",
            "sourceColumn": "target_cost_amt"
          },
          {
            "name": "target_redundancy",
            "dataType": "double",
            "sourceColumn": "target_redundancy"
          },
          {
            "name": "MonthKey",
            "dataType": "int64",
            "sourceColumn": "MonthKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_target_customer_month = Source{[Schema=\"dbo\",Item=\"target_customer_month\"]}[Data]",
                "in",
                "    dbo_target_customer_month"
              ]
            }
          }
        ]
      },
      {
        "name": "target_channel_month",
        "columns": [
          {
            "name": "ChannelKey",
            "dataType": "int64",
            "sourceColumn": "ChannelKey"
          },
          {
            "name": "target_sale_amt",
            "dataType": "double",
            "sourceColumn": "target_sale_amt"
          },
          {
            "name": "target_cost_amt",
            "dataType": "double",
            "sourceColumn": "target_cost_amt"
          },
          {
            "name": "target_profit_amt",
            "dataType": "double",
            "sourceColumn": "target_profit_amt"
          },
          {
            "name": "target_redundancy_amt",
            "dataType": "double",
            "sourceColumn": "target_redundancy_amt"
          },
          {
            "name": "MonthKey",
            "dataType": "int64",
            "sourceColumn": "MonthKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_target_channel_month = Source{[Schema=\"dbo\",Item=\"target_channel_month\"]}[Data]",
                "in",
                "    dbo_target_channel_month"
              ]
            }
          }
        ]
      },
      {
        "name": "target_channel_day",
        "columns": [
          {
            "name": "ChannelKey",
            "dataType": "int64",
            "sourceColumn": "ChannelKey"
          },
          {
            "name": "target_sale_amt",
            "dataType": "double",
            "sourceColumn": "target_sale_amt"
          },
          {
            "name": "target_cost_amt",
            "dataType": "double",
            "sourceColumn": "target_cost_amt"
          },
          {
            "name": "target_profit_amt",
            "dataType": "double",
            "sourceColumn": "target_profit_amt"
          },
          {
            "name": "target_redundancy_amt",
            "dataType": "double",
            "sourceColumn": "target_redundancy_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_target_channel_day = Source{[Schema=\"dbo\",Item=\"target_channel_day\"]}[Data]",
                "in",
                "    dbo_target_channel_day"
              ]
            }
          }
        ]
      },
      {
        "name": "target_customer_day",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "target_profit_amt",
            "dataType": "double",
            "sourceColumn": "target_profit_amt"
          },
          {
            "name": "target_sale_amt",
            "dataType": "double",
            "sourceColumn": "target_sale_amt"
          },
          {
            "name": "target_cost_amt",
            "dataType": "double",
            "sourceColumn": "target_cost_amt"
          },
          {
            "name": "target_redundancy",
            "dataType": "double",
            "sourceColumn": "target_redundancy"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_target_customer_day = Source{[Schema=\"dbo\",Item=\"target_customer_day\"]}[Data]",
                "in",
                "    dbo_target_customer_day"
              ]
            }
          }
        ]
      },
      {
        "name": "渠道效率_综合评估_日",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "目标达成率",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[目标达成率]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"渠道营业利润额\" ,   [result_channel_day_渠道营业利润额目标达成率],) , ",
                "    ( \"销售额\" , [result_channel_day_销售额目标达成率], ),",
                "    ( \"渠道费用额(2-目标达成率)\" , 2-[result_channel_day_渠道费用额目标达成率], ),",
                "    ( \"渠道投入产出比\" , [result_channel_day_渠道投入产出比目标达成率], ),",
                "    ( \"渠道冗余值\" ,[result_channel_day_渠道冗余值目标达成率], ),",
                "    ( \"日销\" , [result_channel_day_日销目标达成率], )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] , \"目标达成率\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "渠道效率_综合评估_月",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "目标达成率",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[目标达成率]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"渠道营业利润额\" ,   [result_channel_month_渠道营业利润额目标达成率],) , ",
                "    ( \"销售额\" , [result_channel_month_销售额目标达成率], ),",
                "    ( \"渠道费用额(2-目标达成率)\" , 2-[result_channel_month_渠道费用额目标达成率], ),",
                "    ( \"渠道投入产出比\" , [result_channel_month_渠道投入产出比目标达成率], ),",
                "    ( \"渠道冗余值\" ,[result_channel_month_渠道冗余值目标达成率], ),",
                "    ( \"日销\" , [result_channel_month_日销目标达成率], )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] , \"目标达成率\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "客户效率_综合评估_日",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "目标达成率",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[目标达成率]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"销售额\" ,   [result_customer_day_销售额目标达成率],) , ",
                "    ( \"客户利润额\" , [result_customer_day_客户利润额目标达成率], ),",
                "    ( \"客户费用额(2-目标达成率)\" , 2-[result_customer_day_客户费用额目标达成率], ),",
                "    ( \"日销\" , [result_customer_day_日销目标成率], ),",
                "    ( \"客户投入产出比\" ,[result_customer_day_客户投入产出比目标达成率], ),",
                "    ( \"客户冗余值\" , [result_customer_day_客户冗余值目标达成率], )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] , \"目标达成率\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "客户效率_综合评估_月",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "目标达成率",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[目标达成率]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"销售额\" ,   [result_customer_month_销售额目标达成率],) , ",
                "    ( \"客户利润额\" , [result_customer_month_客户利润额目标达成率], ),",
                "    ( \"客户费用额(2-目标达成率)\" , 2-[result_customer_month_客户费用额目标达成率], ),",
                "    ( \"日销\" , [result_customer_month_日销目标达成率], ),",
                "    ( \"客户投入产出比\" ,[result_customer_month_客户投入产出比目标达成率], ),",
                "    ( \"客户冗余值\" , [result_customer_month_客户冗余值目标达成率], )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] , \"目标达成率\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "供应效率_综合评估_月",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "目标达成率",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[目标达成率]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"供应销售额\" ,   [result_supply_month_供应销售额目标达成率],) , ",
                "    ( \"供应利润额\" , [result_supply_month_供应利润额目标达成率], ),",
                "    ( \"供应产能\" , [result_supply_month_供应产能目标达成率], ),",
                "    ( \"供应产供比\" , [result_supply_month_供应产供比目标达成率], ),",
                "    ( \"供应安全值\" , [result_supply_month_供应安全值目标达成率], ),",
                "    ( \"残品率(2-目标达成率)\" , 2-[result_supply_month_残品率目标达成率], ),",
                "    ( \"交期达成率\" , [result_supply_month_交期达成率目标达成率], )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] , \"目标达成率\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "组织效率_综合评估_月",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "目标达成率",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[目标达成率]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"销售额\" ,   [result_org_month_销售额目标达成率],) , ",
                "    ( \"净利润额\" , [result_org_month_净利润额目标达成率], ),",
                "    ( \"人力成本额(2-目标达成率)\" , 2-[result_org_month_人力成本额目标达成率], ),",
                "    ( \"日销\" , [result_org_month_日销目标达成率], ),",
                "    ( \"组织投入产出比\" , [result_org_month_组织投入产出比目标达成率], ),",
                "    ( \"人员冗余值\" , [result_org_month_人员冗余值目标达成率], )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] , \"目标达成率\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "资金效率-综合评估_月",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "目标达成率",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[目标达成率]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"销售额\" ,   [result_finance_month_销售额目标达成率],) , ",
                "    ( \"净利润额\" , [result_finance_month_净利润额目标达成率], ),",
                "    ( \"总成本费用额(2-目标达成率)\" , 2-[result_finance_month_总成本费用额目标达成率], ),",
                "    ( \"回款额\" , [result_finance_month_回款额目标达成率], ),",
                "    ( \"投资回报率\" , [result_finance_month_投资回报率目标达成率],),",
                "    ( \"净利率\" , [result_finance_month_净利率目标达成率], ),",
                "     ( \"净现金流\" , [result_finance_month_净现金流目标达成率], ),",
                "    ( \"资金周转率\" , [result_finance_month_资金周转率目标达成率],),",
                "    ( \"资金冗余值\" , [result_finance_month_资金冗余值目标达成率], )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] , \"目标达成率\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "lxxl_strategy",
        "columns": [
          {
            "name": "StrategyKey",
            "dataType": "int64",
            "sourceColumn": "StrategyKey"
          },
          {
            "name": "lxxl_id",
            "dataType": "int64",
            "sourceColumn": "lxxl_id"
          },
          {
            "name": "lxxl_type",
            "dataType": "int64",
            "sourceColumn": "lxxl_type"
          },
          {
            "name": "level",
            "dataType": "int64",
            "sourceColumn": "level"
          },
          {
            "name": "subject",
            "dataType": "string",
            "sourceColumn": "subject"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "rank",
            "dataType": "int64",
            "sourceColumn": "rank"
          },
          {
            "name": "strategy",
            "dataType": "string",
            "sourceColumn": "strategy"
          },
          {
            "name": "influencing_factor",
            "dataType": "string",
            "sourceColumn": "influencing_factor"
          },
          {
            "name": "use_count",
            "dataType": "int64",
            "sourceColumn": "use_count"
          },
          {
            "name": "eff_count",
            "dataType": "int64",
            "sourceColumn": "eff_count"
          },
          {
            "name": "rate",
            "dataType": "double",
            "sourceColumn": "rate"
          },
          {
            "name": "status",
            "dataType": "int64",
            "sourceColumn": "status"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_lxxl_strategy = Source{[Schema=\"dbo\",Item=\"lxxl_strategy\"]}[Data]",
                "in",
                "    dbo_lxxl_strategy"
              ]
            }
          }
        ]
      },
      {
        "name": "lxxl_strategy_log",
        "columns": [
          {
            "name": "StrategyKey",
            "dataType": "int64",
            "sourceColumn": "StrategyKey"
          },
          {
            "name": "rank_old",
            "dataType": "int64",
            "sourceColumn": "rank_old"
          },
          {
            "name": "rank_new",
            "dataType": "int64",
            "sourceColumn": "rank_new"
          },
          {
            "name": "value_old",
            "dataType": "double",
            "sourceColumn": "value_old"
          },
          {
            "name": "value_new",
            "dataType": "double",
            "sourceColumn": "value_new"
          },
          {
            "name": "MonthKey",
            "dataType": "int64",
            "sourceColumn": "MonthKey"
          },
          {
            "type": "calculated",
            "name": "环比增长率",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": " DIVIDE(('lxxl_strategy_log'[value_new]-'lxxl_strategy_log'[value_old]),'lxxl_strategy_log'[value_old])",
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_lxxl_strategy_log = Source{[Schema=\"dbo\",Item=\"lxxl_strategy_log\"]}[Data]",
                "in",
                "    dbo_lxxl_strategy_log"
              ]
            }
          }
        ]
      },
      {
        "name": "rank_channel_day",
        "columns": [
          {
            "name": "ChannelKey",
            "dataType": "int64",
            "sourceColumn": "ChannelKey"
          },
          {
            "name": "subject",
            "dataType": "string",
            "sourceColumn": "subject"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "real_value",
            "dataType": "double",
            "sourceColumn": "real_value"
          },
          {
            "name": "ring_value",
            "dataType": "double",
            "sourceColumn": "ring_value"
          },
          {
            "name": "yoy_value",
            "dataType": "double",
            "sourceColumn": "yoy_value"
          },
          {
            "name": "score",
            "dataType": "double",
            "sourceColumn": "score"
          },
          {
            "name": "rank",
            "dataType": "int64",
            "sourceColumn": "rank"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          },
          {
            "name": "rank_cn",
            "dataType": "string",
            "sourceColumn": "rank_cn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_rank_channel_day = Source{[Schema=\"dbo\",Item=\"rank_channel_day\"]}[Data],",
                "    已添加条件列 = Table.AddColumn(dbo_rank_channel_day, \"rank_cn\", each if [rank] = 1 then \"优\" else if [rank] = 2 then \"良\" else if [rank] = 3 then \"中\" else if [rank] = 4 then \"差\" else null)",
                "in",
                "    已添加条件列"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "rank_channel_day_颜色填充",
            "expression": " SWITCH(SELECTEDVALUE('rank_channel_day'[rank_cn]),\"差\",\"#A7DCFC\",\"中\",\"#70BCDE\",\"良\",\"#23A9CC\",\"优\",\"#007Eb0\")"
          }
        ]
      },
      {
        "name": "rank_channel_month",
        "columns": [
          {
            "name": "ChannelKey",
            "dataType": "int64",
            "sourceColumn": "ChannelKey"
          },
          {
            "name": "subject",
            "dataType": "string",
            "sourceColumn": "subject"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "real_value",
            "dataType": "double",
            "sourceColumn": "real_value"
          },
          {
            "name": "ring_value",
            "dataType": "double",
            "sourceColumn": "ring_value"
          },
          {
            "name": "yoy_value",
            "dataType": "double",
            "sourceColumn": "yoy_value"
          },
          {
            "name": "score",
            "dataType": "double",
            "sourceColumn": "score"
          },
          {
            "name": "rank",
            "dataType": "int64",
            "sourceColumn": "rank"
          },
          {
            "name": "MonthKey",
            "dataType": "int64",
            "sourceColumn": "MonthKey"
          },
          {
            "name": "rank_cn",
            "dataType": "string",
            "sourceColumn": "rank_cn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_rank_channel_month = Source{[Schema=\"dbo\",Item=\"rank_channel_month\"]}[Data],",
                "    已添加条件列 = Table.AddColumn(dbo_rank_channel_month, \"rank_cn\", each if [rank] = 1 then \"优\" else if [rank] = 2 then \"良\" else if [rank] = 3 then \"中\" else if [rank] = 4 then \"差\" else null)",
                "in",
                "    已添加条件列"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "rank_channel_month_颜色填充",
            "expression": " SWITCH(SELECTEDVALUE('rank_channel_month'[rank_cn]),\"差\",\"#A7DCFC\",\"中\",\"#70BCDE\",\"良\",\"#23A9CC\",\"优\",\"#007Eb0\")"
          }
        ]
      },
      {
        "name": "rank_customer_day",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "subject",
            "dataType": "string",
            "sourceColumn": "subject"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "real_value",
            "dataType": "double",
            "sourceColumn": "real_value"
          },
          {
            "name": "ring_value",
            "dataType": "double",
            "sourceColumn": "ring_value"
          },
          {
            "name": "yoy_value",
            "dataType": "double",
            "sourceColumn": "yoy_value"
          },
          {
            "name": "score",
            "dataType": "double",
            "sourceColumn": "score"
          },
          {
            "name": "rank",
            "dataType": "int64",
            "sourceColumn": "rank"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          },
          {
            "name": "rank_cn",
            "dataType": "string",
            "sourceColumn": "rank_cn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_rank_customer_day = Source{[Schema=\"dbo\",Item=\"rank_customer_day\"]}[Data],",
                "    已添加条件列 = Table.AddColumn(dbo_rank_customer_day, \"rank_cn\", each if [rank] = 1 then \"优\" else if [rank] = 2 then \"良\" else if [rank] = 3 then \"中\" else if [rank] = 4 then \"差\" else null)",
                "in",
                "    已添加条件列"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "rank_customer_day_颜色填充",
            "expression": " SWITCH(SELECTEDVALUE('rank_customer_day'[rank_cn]),\"差\",\"#A7DCFC\",\"中\",\"#70BCDE\",\"良\",\"#23A9CC\",\"优\",\"#007Eb0\")"
          }
        ]
      },
      {
        "name": "rank_customer_month",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "subject",
            "dataType": "string",
            "sourceColumn": "subject"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "real_value",
            "dataType": "double",
            "sourceColumn": "real_value"
          },
          {
            "name": "ring_value",
            "dataType": "double",
            "sourceColumn": "ring_value"
          },
          {
            "name": "yoy_value",
            "dataType": "double",
            "sourceColumn": "yoy_value"
          },
          {
            "name": "score",
            "dataType": "double",
            "sourceColumn": "score"
          },
          {
            "name": "rank",
            "dataType": "int64",
            "sourceColumn": "rank"
          },
          {
            "name": "MonthKey",
            "dataType": "int64",
            "sourceColumn": "MonthKey"
          },
          {
            "name": "rank_cn",
            "dataType": "string",
            "sourceColumn": "rank_cn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_rank_customer_month = Source{[Schema=\"dbo\",Item=\"rank_customer_month\"]}[Data],",
                "    已添加条件列 = Table.AddColumn(dbo_rank_customer_month, \"rank_cn\", each if [rank] = 1 then \"优\" else if [rank] = 2 then \"良\" else if [rank] = 3 then \"中\" else if [rank] = 4 then \"差\" else null)",
                "in",
                "    已添加条件列"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "rank_customer_month_颜色填充",
            "expression": " SWITCH(SELECTEDVALUE('rank_customer_month'[rank_cn]),\"差\",\"#A7DCFC\",\"中\",\"#70BCDE\",\"良\",\"#23A9CC\",\"优\",\"#007Eb0\")"
          }
        ]
      },
      {
        "name": "rank_finance_month",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "subject",
            "dataType": "string",
            "sourceColumn": "subject"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "real_value",
            "dataType": "double",
            "sourceColumn": "real_value"
          },
          {
            "name": "ring_value",
            "dataType": "double",
            "sourceColumn": "ring_value"
          },
          {
            "name": "yoy_value",
            "dataType": "double",
            "sourceColumn": "yoy_value"
          },
          {
            "name": "score",
            "dataType": "double",
            "sourceColumn": "score"
          },
          {
            "name": "rank",
            "dataType": "int64",
            "sourceColumn": "rank"
          },
          {
            "name": "MonthKey",
            "dataType": "int64",
            "sourceColumn": "MonthKey"
          },
          {
            "name": "rank_cn",
            "dataType": "string",
            "sourceColumn": "rank_cn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_rank_finance_month = Source{[Schema=\"dbo\",Item=\"rank_finance_month\"]}[Data],",
                "    已添加条件列 = Table.AddColumn(dbo_rank_finance_month, \"自定义\", each if [rank] = 1 then \"优\" else if [rank] = 2 then \"良\" else if [rank] = 3 then \"中\" else if [rank] = 4 then \"差\" else null),",
                "    重命名的列 = Table.RenameColumns(已添加条件列,{{\"自定义\", \"rank_cn\"}})",
                "in",
                "    重命名的列"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "rank_finance_month_颜色填充",
            "expression": " SWITCH(SELECTEDVALUE('rank_finance_month'[rank_cn]),\"差\",\"#A7DCFC\",\"中\",\"#70BCDE\",\"良\",\"#23A9CC\",\"优\",\"#007Eb0\")"
          }
        ]
      },
      {
        "name": "rank_org_month",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "subject",
            "dataType": "string",
            "sourceColumn": "subject"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "real_value",
            "dataType": "double",
            "sourceColumn": "real_value"
          },
          {
            "name": "ring_value",
            "dataType": "double",
            "sourceColumn": "ring_value"
          },
          {
            "name": "yoy_value",
            "dataType": "double",
            "sourceColumn": "yoy_value"
          },
          {
            "name": "score",
            "dataType": "double",
            "sourceColumn": "score"
          },
          {
            "name": "rank",
            "dataType": "int64",
            "sourceColumn": "rank"
          },
          {
            "name": "MonthKey",
            "dataType": "int64",
            "sourceColumn": "MonthKey"
          },
          {
            "name": "rank_cn",
            "dataType": "string",
            "sourceColumn": "rank_cn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_rank_org_month = Source{[Schema=\"dbo\",Item=\"rank_org_month\"]}[Data],",
                "    已添加条件列 = Table.AddColumn(dbo_rank_org_month, \"rank_cn\", each if [rank] = 1 then \"优\" else if [rank] = 2 then \"良\" else if [rank] = 3 then \"中\" else if [rank] = 4 then \"差\" else null)",
                "in",
                "    已添加条件列"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "rank_org_month_颜色填充",
            "expression": " SWITCH(SELECTEDVALUE('rank_org_month'[rank_cn]),\"差\",\"#A7DCFC\",\"中\",\"#70BCDE\",\"良\",\"#23A9CC\",\"优\",\"#007Eb0\")"
          }
        ]
      },
      {
        "name": "rank_product_day",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "subject",
            "dataType": "string",
            "sourceColumn": "subject"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "real_value",
            "dataType": "double",
            "sourceColumn": "real_value"
          },
          {
            "name": "ring_value",
            "dataType": "double",
            "sourceColumn": "ring_value"
          },
          {
            "name": "yoy_value",
            "dataType": "double",
            "sourceColumn": "yoy_value"
          },
          {
            "name": "score",
            "dataType": "double",
            "sourceColumn": "score"
          },
          {
            "name": "rank",
            "dataType": "int64",
            "sourceColumn": "rank"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          },
          {
            "name": "rank_cn",
            "dataType": "string",
            "sourceColumn": "rank_cn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_rank_product_day = Source{[Schema=\"dbo\",Item=\"rank_product_day\"]}[Data],",
                "    已添加条件列 = Table.AddColumn(dbo_rank_product_day, \"自定义\", each if [rank] = 1 then \"优\" else if [rank] = 2 then \"良\" else if [rank] = 3 then \"中\" else if [rank] = 4 then \"差\" else null),",
                "    重命名的列 = Table.RenameColumns(已添加条件列,{{\"自定义\", \"rank_cn\"}})",
                "in",
                "    重命名的列"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "rank_product_day_颜色填充",
            "expression": " SWITCH(SELECTEDVALUE('rank_product_day'[rank_cn]),\"差\",\"#A7DCFC\",\"中\",\"#70BCDE\",\"良\",\"#23A9CC\",\"优\",\"#007Eb0\")"
          }
        ]
      },
      {
        "name": "rank_product_month",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "subject",
            "dataType": "string",
            "sourceColumn": "subject"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "real_value",
            "dataType": "double",
            "sourceColumn": "real_value"
          },
          {
            "name": "ring_value",
            "dataType": "double",
            "sourceColumn": "ring_value"
          },
          {
            "name": "yoy_value",
            "dataType": "double",
            "sourceColumn": "yoy_value"
          },
          {
            "name": "score",
            "dataType": "double",
            "sourceColumn": "score"
          },
          {
            "name": "rank",
            "dataType": "int64",
            "sourceColumn": "rank"
          },
          {
            "name": "MonthKey",
            "dataType": "int64",
            "sourceColumn": "MonthKey"
          },
          {
            "name": "rank_cn",
            "dataType": "string",
            "sourceColumn": "rank_cn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_rank_product_month = Source{[Schema=\"dbo\",Item=\"rank_product_month\"]}[Data],",
                "    已添加条件列 = Table.AddColumn(dbo_rank_product_month, \"rank_cn\", each if [rank] = 1 then \"优\" else if [rank] = 2 then \"良\" else if [rank] = 3 then \"中\" else if [rank] = 4 then \"差\" else null)",
                "in",
                "    已添加条件列"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "rank_product_month_颜色填充",
            "expression": " SWITCH(SELECTEDVALUE('rank_product_month'[rank_cn]),\"差\",\"#A7DCFC\",\"中\",\"#70BCDE\",\"良\",\"#23A9CC\",\"优\",\"#007Eb0\")"
          }
        ]
      },
      {
        "name": "rank_supply_month",
        "columns": [
          {
            "name": "SupplyKey",
            "dataType": "int64",
            "sourceColumn": "SupplyKey"
          },
          {
            "name": "subject",
            "dataType": "string",
            "sourceColumn": "subject"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "real_value",
            "dataType": "double",
            "sourceColumn": "real_value"
          },
          {
            "name": "ring_value",
            "dataType": "double",
            "sourceColumn": "ring_value"
          },
          {
            "name": "yoy_value",
            "dataType": "double",
            "sourceColumn": "yoy_value"
          },
          {
            "name": "score",
            "dataType": "double",
            "sourceColumn": "score"
          },
          {
            "name": "rank",
            "dataType": "int64",
            "sourceColumn": "rank"
          },
          {
            "name": "MonthKey",
            "dataType": "int64",
            "sourceColumn": "MonthKey"
          },
          {
            "name": "rank_cn",
            "dataType": "string",
            "sourceColumn": "rank_cn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_rank_supply_month = Source{[Schema=\"dbo\",Item=\"rank_supply_month\"]}[Data],",
                "    已添加条件列 = Table.AddColumn(dbo_rank_supply_month, \"rank_cn\", each if [rank] = 1 then \"优\" else if [rank] = 2 then \"良\" else if [rank] = 3 then \"中\" else if [rank] = 4 then \"差\" else null)",
                "in",
                "    已添加条件列"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "rank_supply_month_颜色填充",
            "expression": " SWITCH(SELECTEDVALUE('rank_supply_month'[rank_cn]),\"差\",\"#A7DCFC\",\"中\",\"#70BCDE\",\"良\",\"#23A9CC\",\"优\",\"#007Eb0\")"
          }
        ]
      },
      {
        "name": "tree_supply",
        "columns": [
          {
            "name": "SupplyKey",
            "dataType": "int64",
            "sourceColumn": "SupplyKey"
          },
          {
            "name": "supply_id",
            "dataType": "string",
            "sourceColumn": "supply_id"
          },
          {
            "name": "supply_name",
            "dataType": "string",
            "sourceColumn": "supply_name"
          },
          {
            "name": "ParentKey",
            "dataType": "int64",
            "sourceColumn": "ParentKey"
          },
          {
            "name": "level",
            "dataType": "int64",
            "sourceColumn": "level"
          },
          {
            "name": "is_parent",
            "dataType": "int64",
            "sourceColumn": "is_parent"
          },
          {
            "name": "type",
            "dataType": "int64",
            "sourceColumn": "type"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_tree_supply = Source{[Schema=\"dbo\",Item=\"tree_supply\"]}[Data]",
                "in",
                "    dbo_tree_supply"
              ]
            }
          }
        ]
      },
      {
        "name": "tree_product",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "pro_id",
            "dataType": "string",
            "sourceColumn": "pro_id"
          },
          {
            "name": "pro_name",
            "dataType": "string",
            "sourceColumn": "pro_name"
          },
          {
            "name": "ParentKey",
            "dataType": "int64",
            "sourceColumn": "ParentKey"
          },
          {
            "name": "level",
            "dataType": "int64",
            "sourceColumn": "level"
          },
          {
            "name": "is_parent",
            "dataType": "int64",
            "sourceColumn": "is_parent"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_tree_product = Source{[Schema=\"dbo\",Item=\"tree_product\"]}[Data]",
                "in",
                "    dbo_tree_product"
              ]
            }
          }
        ]
      },
      {
        "name": "tree_org",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "org_id",
            "dataType": "string",
            "sourceColumn": "org_id"
          },
          {
            "name": "org_name",
            "dataType": "string",
            "sourceColumn": "org_name"
          },
          {
            "name": "ParentKey",
            "dataType": "int64",
            "sourceColumn": "ParentKey"
          },
          {
            "name": "level",
            "dataType": "int64",
            "sourceColumn": "level"
          },
          {
            "name": "is_parent",
            "dataType": "int64",
            "sourceColumn": "is_parent"
          },
          {
            "name": "type",
            "dataType": "int64",
            "sourceColumn": "type"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_tree_org = Source{[Schema=\"dbo\",Item=\"tree_org\"]}[Data]",
                "in",
                "    dbo_tree_org"
              ]
            }
          }
        ]
      },
      {
        "name": "tree_customer",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "cus_id",
            "dataType": "string",
            "sourceColumn": "cus_id"
          },
          {
            "name": "cus_name",
            "dataType": "string",
            "sourceColumn": "cus_name"
          },
          {
            "name": "ParentKey",
            "dataType": "int64",
            "sourceColumn": "ParentKey"
          },
          {
            "name": "level",
            "dataType": "int64",
            "sourceColumn": "level"
          },
          {
            "name": "is_parent",
            "dataType": "int64",
            "sourceColumn": "is_parent"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_tree_customer = Source{[Schema=\"dbo\",Item=\"tree_customer\"]}[Data]",
                "in",
                "    dbo_tree_customer"
              ]
            }
          }
        ]
      },
      {
        "name": "tree_channel",
        "columns": [
          {
            "name": "ChannelKey",
            "dataType": "int64",
            "sourceColumn": "ChannelKey"
          },
          {
            "name": "cha_id",
            "dataType": "string",
            "sourceColumn": "cha_id"
          },
          {
            "name": "cha_name",
            "dataType": "string",
            "sourceColumn": "cha_name"
          },
          {
            "name": "ParentKey",
            "dataType": "int64",
            "sourceColumn": "ParentKey"
          },
          {
            "name": "level",
            "dataType": "int64",
            "sourceColumn": "level"
          },
          {
            "name": "is_parent",
            "dataType": "int64",
            "sourceColumn": "is_parent"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_tree_channel = Source{[Schema=\"dbo\",Item=\"tree_channel\"]}[Data]",
                "in",
                "    dbo_tree_channel"
              ]
            }
          }
        ]
      },
      {
        "name": "度量值_外部_基本竞争力",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "列1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "外部_基本竞争力_销售额实际",
            "expression": "SUMX('result_finance_month','result_finance_month'[sale_amt])"
          },
          {
            "name": "外部_基本竞争力_销售额目标",
            "expression": "SUMX('target_finance_month','target_finance_month'[target_sale_amt])"
          },
          {
            "name": "外部_基本竞争力_销售额目标达成率",
            "expression": "DIVIDE('度量值_外部_基本竞争力'[外部_基本竞争力_销售额实际],'度量值_外部_基本竞争力'[外部_基本竞争力_销售额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_基本竞争力_销售额实际_上月同期",
            "expression": "CALCULATE([外部_基本竞争力_销售额实际],DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "外部_基本竞争力_销售增长额实际",
            "expression": "[外部_基本竞争力_销售额实际]-[外部_基本竞争力_销售额实际_上月同期]"
          },
          {
            "name": "外部_基本竞争力_销售增长率实际",
            "expression": "DIVIDE([外部_基本竞争力_销售增长额实际],[外部_基本竞争力_销售额实际_上月同期])"
          },
          {
            "name": "外部_基本竞争力_销售额目标_上月同期",
            "expression": [
              "CALCULATE([外部_基本竞争力_销售额目标],DATEADD('V_DimMonth'[EndDate], -1, MONTH))",
              ""
            ]
          },
          {
            "name": "外部_基本竞争力_销售增长额目标",
            "expression": "[外部_基本竞争力_销售额目标]-[外部_基本竞争力_销售额目标_上月同期]"
          },
          {
            "name": "外部_基本竞争力_销售增长额目标达成率",
            "expression": "DIVIDE([外部_基本竞争力_销售增长额实际],[外部_基本竞争力_销售增长额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_基本竞争力_销售增长率目标",
            "expression": "DIVIDE([外部_基本竞争力_销售增长额目标],[外部_基本竞争力_销售额目标_上月同期])"
          },
          {
            "name": "外部_基本竞争力_销售增长率目标达成率",
            "expression": "DIVIDE([外部_基本竞争力_销售增长率实际],[外部_基本竞争力_销售增长率目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_基本竞争力_销售额目标实际差异",
            "expression": "[外部_基本竞争力_销售额实际]-[外部_基本竞争力_销售额目标]"
          },
          {
            "name": "外部_基本竞争力_销售增长额目标实际差异",
            "expression": "[外部_基本竞争力_销售增长额实际]-[外部_基本竞争力_销售增长额目标]"
          },
          {
            "name": "外部_基本竞争力_销售增长率目标实际差异",
            "expression": "[外部_基本竞争力_销售增长率实际]-[外部_基本竞争力_销售增长率目标]"
          }
        ]
      },
      {
        "name": "度量值_外部_持续竞争力",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "列1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列4",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "外部_持续竞争力_净利润增长额实际",
            "expression": "[外部_持续竞争力_净利润额实际]-[外部_持续竞争力_净利润额实际_上月同期]"
          },
          {
            "name": "外部_持续竞争力_净利率目标",
            "expression": "[result_finance_month_净利率目标]"
          },
          {
            "name": "外部_持续竞争力_净利率实际",
            "expression": "[result_finance_month_净利率实际]"
          },
          {
            "name": "外部_持续竞争力_净利润增长率目标",
            "expression": "DIVIDE([外部_持续竞争力_净利润增长额目标],[外部_持续竞争力_净利润额目标_上月同期])"
          },
          {
            "name": "外部_持续竞争力_净利润增长率实际",
            "expression": "DIVIDE([外部_持续竞争力_净利润增长额实际],[外部_持续竞争力_净利润额实际_上月同期])"
          },
          {
            "name": "外部_持续竞争力_净利润额目标达成率",
            "expression": "[result_finance_month_净利润额目标达成率]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_持续竞争力_净利润增长额目标达成率",
            "expression": "DIVIDE([外部_持续竞争力_净利润增长额实际],[外部_持续竞争力_净利润增长额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_持续竞争力_净利率目标达成率",
            "expression": "[result_finance_month_净利率目标达成率]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_持续竞争力_净利润额目标实际差异",
            "expression": "[result_finance_month_净利润额目标实际差异]"
          },
          {
            "name": "外部_持续竞争力_净利润额目标",
            "expression": "[result_finance_month_净利润额目标]"
          },
          {
            "name": "外部_持续竞争力_净利润额实际",
            "expression": "[result_finance_month_净利润额实际]"
          },
          {
            "name": "外部_持续竞争力_净利润额目标_上月同期",
            "expression": "CALCULATE([外部_持续竞争力_净利润额目标], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "外部_持续竞争力_净利润额实际_上月同期",
            "expression": "CALCULATE([外部_持续竞争力_净利润额实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "外部_持续竞争力_净利润增长额目标",
            "expression": "[外部_持续竞争力_净利润额目标]-[外部_持续竞争力_净利润额目标_上月同期]"
          },
          {
            "name": "外部_持续竞争力_净利润增长额目标实际差异",
            "expression": "[外部_持续竞争力_净利润增长额实际]-[外部_持续竞争力_净利润增长额目标]"
          },
          {
            "name": "外部_持续竞争力_净利率目标实际差异",
            "expression": "[result_finance_month_净利率目标实际差异]"
          },
          {
            "name": "外部_持续竞争力_净利润增长率目标实际差异",
            "expression": "[外部_持续竞争力_净利润增长率实际]-[外部_持续竞争力_净利润增长率目标]"
          },
          {
            "name": "外部_持续竞争力_净利润增长率目标达成率",
            "expression": "DIVIDE([外部_持续竞争力_净利润增长率实际],[外部_持续竞争力_净利润增长率目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ]
      },
      {
        "name": "度量值_外部_核心竞争力_渠道效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "列1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列7",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "外部_核心竞争力_渠道效率_单店平均销售额目标达成率",
            "expression": "DIVIDE([外部_核心竞争力_渠道效率_单店平均销售额实际],[外部_核心竞争力_渠道效率_单店平均销售额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_渠道效率_单店平均销售额实际",
            "expression": "DIVIDE([result_channel_month_销售额实际],[外部_核心竞争力_渠道效率_店铺数量实际])"
          },
          {
            "name": "外部_核心竞争力_渠道效率_单店平均成本费用额目标",
            "expression": "DIVIDE([result_channel_month_渠道费用额目标],[外部_核心竞争力_渠道效率_店铺数量目标])"
          },
          {
            "name": "外部_核心竞争力_渠道效率_单店平均成本费用额目标达成率",
            "expression": "DIVIDE([外部_核心竞争力_渠道效率_单店平均成本费用额实际],[外部_核心竞争力_渠道效率_单店平均成本费用额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_渠道效率_单店平均成本费用额实际",
            "expression": "DIVIDE([result_channel_month_渠道费用额实际],[外部_核心竞争力_渠道效率_店铺数量实际])"
          },
          {
            "name": "外部_核心竞争力_渠道效率_投入产出比目标",
            "expression": "[result_channel_month_渠道投入产出比目标]"
          },
          {
            "name": "外部_核心竞争力_渠道效率_投入产出比目标达成率",
            "expression": "[result_channel_month_渠道投入产出比目标达成率]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_渠道效率_投入产出比实际",
            "expression": "[result_channel_month_渠道投入产出比实际]"
          },
          {
            "name": "外部_核心竞争力_渠道效率_渠道冗余值目标",
            "expression": [
              " ",
              "\t",
              "\tSWITCH (",
              "    \t\tTRUE (),",
              "    \t\t[外部_核心竞争力_渠道效率_投入产出比目标]<0, [result_channel_month_渠道费用额目标],",
              "\t\tAND([外部_核心竞争力_渠道效率_投入产出比目标]>0, [外部_核心竞争力_渠道效率_投入产出比目标]<1), [result_channel_month_渠道费用额目标]-[result_channel_month_渠道营业利润额目标],",
              "    \t\t[外部_核心竞争力_渠道效率_投入产出比目标]>1, 0\t)"
            ]
          },
          {
            "name": "外部_核心竞争力_渠道效率_渠道冗余值目标达成率",
            "expression": "DIVIDE([外部_核心竞争力_渠道效率_渠道冗余值实际],[外部_核心竞争力_渠道效率_渠道冗余值目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_渠道效率_渠道冗余值实际",
            "expression": [
              " ",
              "\t",
              "\tSWITCH (",
              "    \t\tTRUE (),",
              "    \t\t[外部_核心竞争力_渠道效率_投入产出比实际]<0, [result_channel_month_渠道费用额实际],",
              "\t\tAND([外部_核心竞争力_渠道效率_投入产出比实际]>0, [外部_核心竞争力_渠道效率_投入产出比实际]<1), [result_channel_month_渠道费用额实际]-[result_channel_month_渠道营业利润额实际],",
              "    \t\t[外部_核心竞争力_渠道效率_投入产出比实际]>1, 0\t)"
            ]
          },
          {
            "name": "外部_核心竞争力_渠道效率_日销目标",
            "expression": "[result_channel_month_日销目标]"
          },
          {
            "name": "外部_核心竞争力_渠道效率_日销目标达成率",
            "expression": "[result_channel_month_日销目标达成率]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_渠道效率_日销实际",
            "expression": "[result_channel_month_日销实际]"
          },
          {
            "name": "外部_核心竞争力_渠道效率_店铺数量目标",
            "expression": "10"
          },
          {
            "name": "外部_核心竞争力_渠道效率_店铺数量目标达成率",
            "expression": [
              "DIVIDE([外部_核心竞争力_渠道效率_店铺数量实际],[外部_核心竞争力_渠道效率_店铺数量目标])",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_渠道效率_店铺数量实际",
            "expression": "13"
          },
          {
            "name": "外部_核心竞争力_渠道效率_单店平均营业利润额目标",
            "expression": "DIVIDE([result_channel_month_渠道营业利润额目标],[外部_核心竞争力_渠道效率_店铺数量目标])"
          },
          {
            "name": "外部_核心竞争力_渠道效率_单店平均营业利润额目标达成率",
            "expression": "DIVIDE([外部_核心竞争力_渠道效率_单店平均营业利润额实际],[外部_核心竞争力_渠道效率_单店平均营业利润额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_渠道效率_单店平均营业利润额实际",
            "expression": "DIVIDE([result_channel_month_渠道营业利润额实际],[外部_核心竞争力_渠道效率_店铺数量实际])"
          },
          {
            "name": "外部_核心竞争力_渠道效率_单店平均销售额目标",
            "expression": "DIVIDE([result_channel_month_销售额目标],[外部_核心竞争力_渠道效率_店铺数量目标])"
          },
          {
            "name": "外部_核心竞争力_渠道效率_店铺数量目标实际差异",
            "expression": "[外部_核心竞争力_渠道效率_店铺数量实际]-[外部_核心竞争力_渠道效率_店铺数量目标]"
          },
          {
            "name": "外部_核心竞争力_渠道效率_单店平均营业利润额目标实际差异",
            "expression": "[外部_核心竞争力_渠道效率_单店平均营业利润额实际]-[外部_核心竞争力_渠道效率_单店平均营业利润额目标]"
          },
          {
            "name": "外部_核心竞争力_渠道效率_单店平均销售额目标实际差异",
            "expression": "[外部_核心竞争力_渠道效率_单店平均销售额实际]-[外部_核心竞争力_渠道效率_单店平均销售额目标]"
          },
          {
            "name": "外部_核心竞争力_渠道效率_单店平均成本费用额目标实际差异",
            "expression": "[外部_核心竞争力_渠道效率_单店平均成本费用额实际]-[外部_核心竞争力_渠道效率_单店平均成本费用额目标]"
          },
          {
            "name": "外部_核心竞争力_渠道效率_投入产出比目标实际差异",
            "expression": "[result_channel_month_渠道投入产出比目标实际差异]"
          },
          {
            "name": "外部_核心竞争力_渠道效率_渠道冗余值目标实际差异",
            "expression": "[外部_核心竞争力_渠道效率_渠道冗余值实际]-[外部_核心竞争力_渠道效率_渠道冗余值目标]"
          },
          {
            "name": "外部_核心竞争力_渠道效率_日销目标实际差异",
            "expression": "[result_channel_month_日销目标实际差异]"
          }
        ]
      },
      {
        "name": "度量值_外部_核心竞争力_客户效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "列1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列7",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "外部_核心竞争力_客户效率_消费者人均销售额实际",
            "expression": "DIVIDE([result_customer_month_销售额实际],[外部_核心竞争力_客户效率_消费者人数实际])"
          },
          {
            "name": "外部_核心竞争力_客户效率_消费者人均销售额目标达成率",
            "expression": "DIVIDE([外部_核心竞争力_客户效率_消费者人均销售额实际],[外部_核心竞争力_客户效率_消费者人均销售额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_客户效率_消费者人均成本费用额目标",
            "expression": "DIVIDE([result_customer_month_客户费用额目标],[外部_核心竞争力_客户效率_消费者人数目标])"
          },
          {
            "name": "外部_核心竞争力_客户效率_消费者人均成本费用额实际",
            "expression": "DIVIDE([result_customer_month_客户费用额实际],[外部_核心竞争力_客户效率_消费者人数实际])"
          },
          {
            "name": "外部_核心竞争力_客户效率_消费者人均成本费用额目标达成率",
            "expression": "DIVIDE([外部_核心竞争力_客户效率_消费者人均成本费用额实际],[外部_核心竞争力_客户效率_消费者人均成本费用额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_客户效率_投入产出比目标",
            "expression": "[result_customer_month_客户投入产出比目标]"
          },
          {
            "name": "外部_核心竞争力_客户效率_投入产出比实际",
            "expression": "[result_customer_month_客户投入产出比实际]"
          },
          {
            "name": "外部_核心竞争力_客户效率_投入产出比目标达成率",
            "expression": "[result_customer_month_客户投入产出比目标达成率]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_客户效率_消费者冗余值目标",
            "expression": "[result_customer_month_客户冗余值目标]"
          },
          {
            "name": "外部_核心竞争力_客户效率_消费者冗余值实际",
            "expression": "[result_customer_month_客户冗余值实际]"
          },
          {
            "name": "外部_核心竞争力_客户效率_消费者冗余值目标达成率",
            "expression": "[result_customer_month_客户冗余值目标达成率]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_客户效率_日销目标",
            "expression": "[result_customer_month_日销目标]"
          },
          {
            "name": "外部_核心竞争力_客户效率_日销实际",
            "expression": "[result_customer_month_日销实际]"
          },
          {
            "name": "外部_核心竞争力_客户效率_日销目标达成率",
            "expression": "[result_customer_month_日销目标达成率]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_客户效率_消费者人数目标",
            "expression": "2789"
          },
          {
            "name": "外部_核心竞争力_客户效率_消费者人数实际",
            "expression": "3206"
          },
          {
            "name": "外部_核心竞争力_客户效率_消费者人数目标达成率",
            "expression": "DIVIDE([外部_核心竞争力_客户效率_消费者人数实际],[外部_核心竞争力_客户效率_消费者人数目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_客户效率_消费者人均客户利润额目标",
            "expression": "DIVIDE([result_customer_month_客户利润额目标],[外部_核心竞争力_客户效率_消费者人数目标])"
          },
          {
            "name": "外部_核心竞争力_客户效率_消费者人均客户利润额实际",
            "expression": "DIVIDE([result_customer_month_客户利润额实际],[外部_核心竞争力_客户效率_消费者人数实际])"
          },
          {
            "name": "外部_核心竞争力_客户效率_消费者人均客户利润额目标达成率",
            "expression": "DIVIDE([外部_核心竞争力_客户效率_消费者人均客户利润额实际],[外部_核心竞争力_客户效率_消费者人均客户利润额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_客户效率_消费者人均销售额目标",
            "expression": "DIVIDE([result_customer_month_销售额目标],[外部_核心竞争力_客户效率_消费者人数目标])"
          },
          {
            "name": "外部_核心竞争力_客户效率_消费者人数目标实际差异",
            "expression": "[外部_核心竞争力_客户效率_消费者人数实际]-[外部_核心竞争力_客户效率_消费者人数目标]"
          },
          {
            "name": "外部_核心竞争力_客户效率_消费者人均客户利润额目标实际差异",
            "expression": "[外部_核心竞争力_客户效率_消费者人均客户利润额实际]-[外部_核心竞争力_客户效率_消费者人均客户利润额目标]"
          },
          {
            "name": "外部_核心竞争力_客户效率_消费者人均销售额目标实际差异",
            "expression": "[外部_核心竞争力_客户效率_消费者人均销售额实际]-[外部_核心竞争力_客户效率_消费者人均销售额目标]"
          },
          {
            "name": "外部_核心竞争力_客户效率_消费者人均成本费用额目标实际差异",
            "expression": "[外部_核心竞争力_客户效率_消费者人均成本费用额实际]-[外部_核心竞争力_客户效率_消费者人均成本费用额目标]"
          },
          {
            "name": "外部_核心竞争力_客户效率_投入产出比目标实际差异",
            "expression": "[result_customer_month_客户投入产出比目标实际差异]"
          },
          {
            "name": "外部_核心竞争力_客户效率_消费者冗余值目标实际差异",
            "expression": "[result_customer_month_客户冗余值目标实际差异]"
          },
          {
            "name": "外部_核心竞争力_客户效率_日销目标实际差异",
            "expression": "[result_customer_month_日销目标实际差异]"
          }
        ]
      },
      {
        "name": "度量值_外部_核心竞争力_供应效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "列1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列7",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "外部_核心竞争力_供应效率_工厂数量目标",
            "expression": "80"
          },
          {
            "name": "外部_核心竞争力_供应效率_工厂数量实际",
            "expression": "100"
          },
          {
            "name": "外部_核心竞争力_供应效率_工厂数量目标达成率",
            "expression": "DIVIDE([外部_核心竞争力_供应效率_工厂数量实际],[外部_核心竞争力_供应效率_工厂数量目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_供应效率_工厂平均销售额目标",
            "expression": " DIVIDE('result_supply_month'[result_supply_month_供应销售额目标],[外部_核心竞争力_供应效率_工厂数量目标])"
          },
          {
            "name": "外部_核心竞争力_供应效率_工厂平均销售额实际",
            "expression": " DIVIDE('result_supply_month'[result_supply_month_供应销售额实际],[外部_核心竞争力_供应效率_工厂数量实际])"
          },
          {
            "name": "外部_核心竞争力_供应效率_工厂平均销售额目标达成率",
            "expression": "DIVIDE([外部_核心竞争力_供应效率_工厂平均销售额实际],[外部_核心竞争力_供应效率_工厂平均销售额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_供应效率_工厂平均毛利额实际",
            "expression": "DIVIDE('result_supply_month'[result_supply_month_供应利润额实际],[外部_核心竞争力_供应效率_工厂数量实际])"
          },
          {
            "name": "外部_核心竞争力_供应效率_工厂平均毛利额目标达成率",
            "expression": "DIVIDE([外部_核心竞争力_供应效率_工厂平均毛利额实际],[外部_核心竞争力_供应效率_工厂平均毛利额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_供应效率_工厂平均毛利额目标",
            "expression": " DIVIDE('result_supply_month'[result_supply_month_供应利润额目标],[外部_核心竞争力_供应效率_工厂数量目标])"
          },
          {
            "name": "外部_核心竞争力_供应效率_工厂平均产能实际",
            "expression": " DIVIDE(SUMX('result_supply_month','result_supply_month'[planned_production_qty]),[外部_核心竞争力_供应效率_工厂数量实际])"
          },
          {
            "name": "外部_核心竞争力_供应效率_工厂平均产能目标达成率",
            "expression": "DIVIDE([外部_核心竞争力_供应效率_工厂平均产能实际],[外部_核心竞争力_供应效率_工厂平均产能目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_供应效率_工厂平均产能目标",
            "expression": " DIVIDE(1000000,[外部_核心竞争力_供应效率_工厂数量目标])"
          },
          {
            "name": "外部_核心竞争力_供应效率_产供比目标",
            "expression": "[result_supply_month_供应产供比目标]"
          },
          {
            "name": "外部_核心竞争力_供应效率_产供比目标达成率",
            "expression": "[result_supply_month_供应产供比目标达成率]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_供应效率_产供比实际",
            "expression": "[result_supply_month_供应产供比实际]"
          },
          {
            "name": "外部_核心竞争力_供应效率_工厂平均残品率目标",
            "expression": "[result_supply_month_残品率目标]"
          },
          {
            "name": "外部_核心竞争力_供应效率_工厂平均残品率目标达成率",
            "expression": "[result_supply_month_残品率目标达成率]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_供应效率_工厂平均残品率实际",
            "expression": "[result_supply_month_残品率实际]"
          },
          {
            "name": "外部_核心竞争力_供应效率_工厂平均交期达成率实际",
            "expression": "[result_supply_month_交期达成率实际]"
          },
          {
            "name": "外部_核心竞争力_供应效率_工厂平均交期达成率目标达成率",
            "expression": "[result_supply_month_交期达成率目标达成率]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_供应效率_工厂平均交期达成率目标",
            "expression": "[result_supply_month_交期达成率目标]"
          },
          {
            "name": "外部_核心竞争力_供应效率_工厂数量目标实际差异",
            "expression": "[外部_核心竞争力_供应效率_工厂数量实际]-[外部_核心竞争力_供应效率_工厂数量目标]"
          },
          {
            "name": "外部_核心竞争力_供应效率_工厂平均销售额目标实际差异",
            "expression": "[外部_核心竞争力_供应效率_工厂平均销售额实际]-[外部_核心竞争力_供应效率_工厂平均销售额目标]"
          },
          {
            "name": "外部_核心竞争力_供应效率_工厂平均毛利额目标实际差异",
            "expression": "[外部_核心竞争力_供应效率_工厂平均毛利额实际]-[外部_核心竞争力_供应效率_工厂平均毛利额目标]"
          },
          {
            "name": "外部_核心竞争力_供应效率_工厂平均产能目标实际差异",
            "expression": "[外部_核心竞争力_供应效率_工厂平均产能实际]-[外部_核心竞争力_供应效率_工厂平均产能目标]"
          },
          {
            "name": "外部_核心竞争力_供应效率_产供比目标实际差异",
            "expression": "[result_supply_month_供应产供比目标实际差异]"
          },
          {
            "name": "外部_核心竞争力_供应效率_工厂平均残品率目标实际差异",
            "expression": "[result_supply_month_残品率目标实际差异]"
          },
          {
            "name": "外部_核心竞争力_供应效率_工厂平均交期达成率目标实际差异",
            "expression": "[result_supply_month_交期达成率目标实际差异]"
          }
        ]
      },
      {
        "name": "度量值_外部_核心竞争力_组织效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "列1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列7",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "外部_核心竞争力_组织效率_企业人数实际",
            "expression": "3490"
          },
          {
            "name": "外部_核心竞争力_组织效率_企业人数目标",
            "expression": "4110"
          },
          {
            "name": "外部_核心竞争力_组织效率_企业人数目标达成率",
            "expression": "DIVIDE([外部_核心竞争力_组织效率_企业人数实际],[外部_核心竞争力_组织效率_企业人数目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_组织效率_企业人均净利润额实际",
            "expression": "DIVIDE([result_org_month_净利润额实际],[外部_核心竞争力_组织效率_企业人数实际])"
          },
          {
            "name": "外部_核心竞争力_组织效率_企业人均净利润额目标",
            "expression": "DIVIDE([result_org_month_净利润额目标],[外部_核心竞争力_组织效率_企业人数目标])"
          },
          {
            "name": "外部_核心竞争力_组织效率_企业人均净利润额目标达成率",
            "expression": "DIVIDE([外部_核心竞争力_组织效率_企业人均净利润额实际],[外部_核心竞争力_组织效率_企业人均净利润额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_组织效率_企业人均销售额实际",
            "expression": "DIVIDE([result_org_month_销售额实际],[外部_核心竞争力_组织效率_企业人数实际])"
          },
          {
            "name": "外部_核心竞争力_组织效率_企业人均销售额目标",
            "expression": "DIVIDE([result_org_month_销售额目标],[外部_核心竞争力_组织效率_企业人数目标])"
          },
          {
            "name": "外部_核心竞争力_组织效率_企业人均销售额目标达成率",
            "expression": "DIVIDE([外部_核心竞争力_组织效率_企业人均销售额实际],[外部_核心竞争力_组织效率_企业人均销售额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_组织效率_企业人均成本额实际",
            "expression": "DIVIDE([result_org_month_人力成本额实际],[外部_核心竞争力_组织效率_企业人数实际])"
          },
          {
            "name": "外部_核心竞争力_组织效率_企业人均成本额目标",
            "expression": "DIVIDE([result_org_month_人力成本额目标],[外部_核心竞争力_组织效率_企业人数目标])"
          },
          {
            "name": "外部_核心竞争力_组织效率_企业人均成本额目标达成率",
            "expression": "DIVIDE([外部_核心竞争力_组织效率_企业人均成本额实际],[外部_核心竞争力_组织效率_企业人均成本额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_组织效率_投入产出比实际",
            "expression": "DIVIDE([result_org_month_净利润额实际],[result_org_month_人力成本额实际])"
          },
          {
            "name": "外部_核心竞争力_组织效率_投入产出比目标",
            "expression": "DIVIDE([result_org_month_净利润额目标],[result_org_month_人力成本额目标])"
          },
          {
            "name": "外部_核心竞争力_组织效率_投入产出比目标达成率",
            "expression": "DIVIDE([外部_核心竞争力_组织效率_投入产出比实际],[外部_核心竞争力_组织效率_投入产出比目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_组织效率_日销实际",
            "expression": "[result_org_month_日销实际]"
          },
          {
            "name": "外部_核心竞争力_组织效率_日销目标",
            "expression": "[result_org_month_日销目标]"
          },
          {
            "name": "外部_核心竞争力_组织效率_日销目标达成率",
            "expression": "[result_org_month_日销目标达成率]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_组织效率_企业人均冗余值实际",
            "expression": "[result_org_month_人员冗余值实际]"
          },
          {
            "name": "外部_核心竞争力_组织效率_企业人均冗余值目标",
            "expression": "[result_org_month_人员冗余值目标]"
          },
          {
            "name": "外部_核心竞争力_组织效率_企业人均冗余值目标达成率",
            "expression": "[result_org_month_人员冗余值目标达成率]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_组织效率_企业人数目标实际差异",
            "expression": "[外部_核心竞争力_组织效率_企业人数实际]-[外部_核心竞争力_组织效率_企业人数目标]"
          },
          {
            "name": "外部_核心竞争力_组织效率_企业人均净利润额目标实际差异",
            "expression": "[外部_核心竞争力_组织效率_企业人均净利润额实际]-[外部_核心竞争力_组织效率_企业人均净利润额目标]"
          },
          {
            "name": "外部_核心竞争力_组织效率_企业人均销售额目标实际差异",
            "expression": "[外部_核心竞争力_组织效率_企业人均销售额实际]-[外部_核心竞争力_组织效率_企业人均销售额目标]"
          },
          {
            "name": "外部_核心竞争力_组织效率_企业人均成本额目标实际差异",
            "expression": "[外部_核心竞争力_组织效率_企业人均成本额实际]-[外部_核心竞争力_组织效率_企业人均成本额目标]"
          },
          {
            "name": "外部_核心竞争力_组织效率_投入产出比目标实际差异",
            "expression": "[外部_核心竞争力_组织效率_投入产出比实际]-[外部_核心竞争力_组织效率_投入产出比目标]"
          },
          {
            "name": "外部_核心竞争力_组织效率_企业人均冗余值目标实际差异",
            "expression": "[result_org_month_人员冗余值目标实际差异]"
          },
          {
            "name": "外部_核心竞争力_组织效率_日销目标实际差异",
            "expression": "[result_org_month_日销目标实际差异]"
          }
        ]
      },
      {
        "name": "度量值_外部_核心竞争力_资金效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "列1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列7",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列8",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列9",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "外部_核心竞争力_资金效率_总成本费用额目标",
            "expression": "[result_finance_month_总成本费用额目标]"
          },
          {
            "name": "外部_核心竞争力_资金效率_总成本费用额实际",
            "expression": "[result_finance_month_总成本费用额实际]"
          },
          {
            "name": "外部_核心竞争力_资金效率_总成本费用额目标达成率",
            "expression": "[result_finance_month_总成本费用额目标达成率]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_渠道效率_总成本费用额目标实际差异",
            "expression": "[result_finance_month_总成本费用额目标实际差异]"
          },
          {
            "name": "外部_核心竞争力_资金效率_销售额目标",
            "expression": "[result_finance_month_销售额目标]"
          },
          {
            "name": "外部_核心竞争力_资金效率_销售额实际",
            "expression": "[result_finance_month_销售额实际]"
          },
          {
            "name": "外部_核心竞争力_资金效率_销售额目标达成率",
            "expression": "[result_finance_month_销售额目标达成率]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_资金效率_销售额目标实际差异",
            "expression": "[result_finance_month_销售额目标实际差异]"
          },
          {
            "name": "外部_核心竞争力_资金效率_回款额目标",
            "expression": "[result_finance_month_回款额目标]"
          },
          {
            "name": "外部_核心竞争力_资金效率_回款额实际",
            "expression": "[result_finance_month_回款额实际]"
          },
          {
            "name": "外部_核心竞争力_资金效率_回款额目标达成率",
            "expression": "[result_finance_month_回款额目标达成率]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_资金效率_回款额目标实际差异",
            "expression": "[result_finance_month_回款额目标实际差异]"
          },
          {
            "name": "外部_核心竞争力_资金效率_净利润额目标",
            "expression": "[result_finance_month_净利润额目标]"
          },
          {
            "name": "外部_核心竞争力_资金效率_净利润额实际",
            "expression": "[result_finance_month_净利润额实际]"
          },
          {
            "name": "外部_核心竞争力_资金效率_净利润额目标达成率",
            "expression": "[result_finance_month_净利润额目标达成率]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_资金效率_净利润额目标实际差异",
            "expression": "[result_finance_month_净利润额目标实际差异]"
          },
          {
            "name": "外部_核心竞争力_资金效率_净利率目标",
            "expression": "[result_finance_month_净利率目标]"
          },
          {
            "name": "外部_核心竞争力_资金效率_净利率实际",
            "expression": "[result_finance_month_净利率实际]"
          },
          {
            "name": "外部_核心竞争力_资金效率_净利率目标达成率",
            "expression": "[result_finance_month_净利率目标达成率]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_资金效率_净利率目标实际差异",
            "expression": "[result_finance_month_净利率目标实际差异]"
          },
          {
            "name": "外部_核心竞争力_资金效率_净现金流目标",
            "expression": "[result_finance_month_净现金流目标]"
          },
          {
            "name": "外部_核心竞争力_资金效率_净现金流实际",
            "expression": "[result_finance_month_净现金流实际]"
          },
          {
            "name": "外部_核心竞争力_资金效率_净现金流目标达成率",
            "expression": "[result_finance_month_净现金流目标达成率]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_资金效率_净现金流目标实际差异",
            "expression": "[result_finance_month_净现金流目标实际差异]"
          },
          {
            "name": "外部_核心竞争力_资金效率_投资回报率目标",
            "expression": "[result_finance_month_投资回报率目标]"
          },
          {
            "name": "外部_核心竞争力_资金效率_投资回报率实际",
            "expression": "[result_finance_month_投资回报率实际]"
          },
          {
            "name": "外部_核心竞争力_资金效率_投资回报率目标达成率",
            "expression": "[result_finance_month_投资回报率目标达成率]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_资金效率_投资回报率目标实际差异",
            "expression": "[result_finance_month_投资回报率目标实际差异]"
          },
          {
            "name": "外部_核心竞争力_资金效率_资金周转率目标",
            "expression": "[result_finance_month_资金周转率目标]"
          },
          {
            "name": "外部_核心竞争力_资金效率_资金周转率实际",
            "expression": "[result_finance_month_资金周转率实际]"
          },
          {
            "name": "外部_核心竞争力_资金效率_资金周转率目标达成率",
            "expression": "[result_finance_month_资金周转率目标达成率]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_资金效率_资金周转率目标实际差异",
            "expression": "[result_finance_month_资金周转率目标实际差异]"
          },
          {
            "name": "外部_核心竞争力_资金效率_资金冗余值目标",
            "expression": "[result_finance_month_资金冗余值目标]"
          },
          {
            "name": "外部_核心竞争力_资金效率_资金冗余值实际",
            "expression": "[result_finance_month_资金冗余值实际]"
          },
          {
            "name": "外部_核心竞争力_资金效率_资金冗余值目标达成率",
            "expression": "[result_finance_month_资金冗余值目标达成率]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_资金效率_资金冗余值目标实际差异",
            "expression": "[result_finance_month_资金冗余值目标实际差异]"
          }
        ]
      },
      {
        "name": "度量值_外部_品牌价值",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "列1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列4",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "外部_品牌价值_品质合格率目标",
            "expression": "1-[外部_核心竞争力_供应效率_工厂平均残品率目标]"
          },
          {
            "name": "外部_品牌价值_传播网点数实际",
            "expression": "532"
          },
          {
            "name": "外部_品牌价值_传播成本目标达成率",
            "expression": "DIVIDE([外部_品牌价值_传播成本实际],[外部_品牌价值_传播成本目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_品牌价值_品质合格率实际",
            "expression": "1-[外部_核心竞争力_供应效率_工厂平均残品率实际]"
          },
          {
            "name": "外部_品牌价值_品质合格率目标达成率",
            "expression": "DIVIDE([外部_品牌价值_品质合格率实际],[外部_品牌价值_品质合格率目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_品牌价值_传播网点数目标",
            "expression": "627"
          },
          {
            "name": "外部_品牌价值_传播网点数目标达成率",
            "expression": "DIVIDE([外部_品牌价值_传播网点数实际],[外部_品牌价值_传播网点数目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_品牌价值_传播成本目标",
            "expression": "141000"
          },
          {
            "name": "外部_品牌价值_传播成本实际",
            "expression": "164000"
          },
          {
            "name": "外部_品牌价值_传播的投入产出比目标",
            "expression": "994"
          },
          {
            "name": "外部_品牌价值_传播的投入产出比实际",
            "expression": "1004"
          },
          {
            "name": "外部_品牌价值_传播的投入产出比目标达成率",
            "expression": "DIVIDE([外部_品牌价值_传播的投入产出比实际],[外部_品牌价值_传播的投入产出比目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_品牌价值_品质合格率目标实际差异",
            "expression": "[外部_品牌价值_品质合格率实际]-[外部_品牌价值_品质合格率目标]"
          },
          {
            "name": "外部_品牌价值_传播网点数目标实际差异",
            "expression": "[外部_品牌价值_传播网点数实际]-[外部_品牌价值_传播网点数目标]"
          },
          {
            "name": "外部_品牌价值_传播成本目标实际差异",
            "expression": "[外部_品牌价值_传播成本实际]-[外部_品牌价值_传播成本目标]"
          },
          {
            "name": "外部_品牌价值_传播的投入产出比目标实际差异",
            "expression": "[外部_品牌价值_传播的投入产出比实际]-[外部_品牌价值_传播的投入产出比目标]"
          }
        ]
      },
      {
        "name": "度量值_内部_盈利空间",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "列1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列7",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列8",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "内部_盈利空间_毛利率目标",
            "expression": "DIVIDE('result_product_month'[result_product_month_毛利润额目标],'result_product_month'[result_product_month_销售额目标])"
          },
          {
            "name": "内部_盈利空间_毛利率实际",
            "expression": "DIVIDE('result_product_month'[result_product_month_毛利润额实际],'result_product_month'[result_product_month_销售额实际])"
          },
          {
            "name": "内部_盈利空间_毛利率目标达成率",
            "expression": "DIVIDE([内部_盈利空间_毛利率实际],[内部_盈利空间_毛利率目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_盈利空间_回款额目标",
            "expression": "[result_finance_month_回款额目标]"
          },
          {
            "name": "内部_盈利空间_回款额实际",
            "expression": "[result_finance_month_回款额实际]"
          },
          {
            "name": "内部_盈利空间_回款额目标达成率",
            "expression": "[result_finance_month_回款额目标达成率]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_盈利空间_回款增长额目标",
            "expression": "[内部_盈利空间_回款额目标]-[内部_盈利空间_回款额目标_上月同期]"
          },
          {
            "name": "内部_盈利空间_回款增长额实际",
            "expression": "[内部_盈利空间_回款额实际]-[内部_盈利空间_回款额实际_上月同期]"
          },
          {
            "name": "内部_盈利空间_回款增长额目标达成率",
            "expression": " DIVIDE([内部_盈利空间_回款增长额实际],[内部_盈利空间_回款增长额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_盈利空间_回款增长率目标",
            "expression": "DIVIDE([内部_盈利空间_回款增长额目标],[内部_盈利空间_回款额目标_上月同期])"
          },
          {
            "name": "内部_盈利空间_回款增长率实际",
            "expression": "DIVIDE([内部_盈利空间_回款增长额实际],[内部_盈利空间_回款额实际_上月同期])"
          },
          {
            "name": "内部_盈利空间_回款增长率目标达成率",
            "expression": " DIVIDE([内部_盈利空间_回款增长率实际],[内部_盈利空间_回款增长率目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_盈利空间_总成本费用额目标",
            "expression": "[result_finance_month_总成本费用额目标]"
          },
          {
            "name": "内部_盈利空间_总成本费用额实际",
            "expression": "[result_finance_month_总成本费用额实际]"
          },
          {
            "name": "内部_盈利空间_总成本费用额目标达成率",
            "expression": "DIVIDE([内部_盈利空间_总成本费用额实际],[内部_盈利空间_总成本费用额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_盈利空间_总成本费用增长额目标",
            "expression": "[内部_盈利空间_总成本费用额目标]-[内部_盈利空间_总成本费用额目标_上月同期]"
          },
          {
            "name": "内部_盈利空间_总成本费用增长额实际",
            "expression": "[内部_盈利空间_总成本费用额实际]-[内部_盈利空间_总成本费用额实际_上月同期]"
          },
          {
            "name": "内部_盈利空间_总成本费用增长额目标达成率",
            "expression": " DIVIDE([内部_盈利空间_总成本费用增长额实际],[内部_盈利空间_总成本费用增长额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_盈利空间_总成本费用增长率目标",
            "expression": " DIVIDE([内部_盈利空间_总成本费用增长额目标],[内部_盈利空间_总成本费用额目标_上月同期])"
          },
          {
            "name": "内部_盈利空间_总成本费用增长率实际",
            "expression": " DIVIDE([内部_盈利空间_总成本费用增长额实际],[内部_盈利空间_总成本费用额实际_上月同期])"
          },
          {
            "name": "内部_盈利空间_总成本费用增长率目标达成率",
            "expression": " DIVIDE([内部_盈利空间_总成本费用增长率实际],[内部_盈利空间_总成本费用增长率目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_盈利空间_盈利空间目标",
            "expression": "DIVIDE([内部_盈利空间_回款额目标],[内部_盈利空间_总成本费用额目标])"
          },
          {
            "name": "内部_盈利空间_盈利空间实际",
            "expression": "DIVIDE([内部_盈利空间_回款额实际],[内部_盈利空间_总成本费用额实际])"
          },
          {
            "name": "内部_盈利空间_盈利空间目标达成率",
            "expression": "DIVIDE([内部_盈利空间_盈利空间实际],[内部_盈利空间_盈利空间目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_盈利空间_回款额实际_上月同期",
            "expression": "CALCULATE([result_finance_month_回款额实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "内部_盈利空间_回款额目标_上月同期",
            "expression": "CALCULATE([result_finance_month_回款额目标], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "内部_盈利空间_总成本费用额实际_上月同期",
            "expression": "CALCULATE([result_finance_month_总成本费用额实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "内部_盈利空间_总成本费用额目标_上月同期",
            "expression": "CALCULATE([result_finance_month_总成本费用额目标], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "内部_盈利空间_毛利率目标实际差异",
            "expression": "[内部_盈利空间_毛利率实际]-[内部_盈利空间_毛利率目标]"
          },
          {
            "name": "内部_盈利空间_回款额目标实际差异",
            "expression": "[result_finance_month_回款额目标实际差异]"
          },
          {
            "name": "内部_盈利空间_回款增长额目标实际差异",
            "expression": "[内部_盈利空间_回款增长额实际]-[内部_盈利空间_回款增长额目标]"
          },
          {
            "name": "内部_盈利空间_回款增长率目标实际差异",
            "expression": "[内部_盈利空间_回款增长率实际]-[内部_盈利空间_回款增长率目标]"
          },
          {
            "name": "内部_盈利空间_总成本费用额目标实际差异",
            "expression": "[内部_盈利空间_总成本费用额实际]-[内部_盈利空间_总成本费用额目标]"
          },
          {
            "name": "内部_盈利空间_总成本费用增长额目标实际差异",
            "expression": "[内部_盈利空间_总成本费用增长额实际]-[内部_盈利空间_总成本费用增长额目标]"
          },
          {
            "name": "内部_盈利空间_总成本费用增长率目标实际差异",
            "expression": "[内部_盈利空间_总成本费用增长率实际]-[内部_盈利空间_总成本费用增长率目标]"
          },
          {
            "name": "内部_盈利空间_盈利空间目标实际差异",
            "expression": "[内部_盈利空间_盈利空间实际]-[内部_盈利空间_盈利空间目标]"
          }
        ]
      },
      {
        "name": "度量值_内部_盈利能力",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "列1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列7",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列8",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列9",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "内部_盈利能力_订单额目标",
            "expression": "600000000"
          },
          {
            "name": "内部_盈利能力_订单额实际",
            "expression": "700000000"
          },
          {
            "name": "内部_盈利能力_订单额目标达成率",
            "expression": "DIVIDE([内部_盈利能力_订单额实际],[内部_盈利能力_订单额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_盈利能力_订单增长额目标",
            "expression": "[内部_盈利能力_订单额目标]-[内部_盈利能力_订单额目标_上月同期]"
          },
          {
            "name": "内部_盈利能力_订单增长额实际",
            "expression": "[内部_盈利能力_订单额实际]-[内部_盈利能力_订单额实际_上月同期]"
          },
          {
            "name": "内部_盈利能力_订单增长额目标达成率",
            "expression": "DIVIDE([内部_盈利能力_订单增长额实际],[内部_盈利能力_订单增长额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_盈利能力_订单增长率目标",
            "expression": "DIVIDE([内部_盈利能力_订单增长额目标],[内部_盈利能力_订单额目标_上月同期])"
          },
          {
            "name": "内部_盈利能力_订单增长率实际",
            "expression": "DIVIDE([内部_盈利能力_订单增长额实际],[内部_盈利能力_订单额实际_上月同期])"
          },
          {
            "name": "内部_盈利能力_订单增长率目标达成率",
            "expression": "DIVIDE([内部_盈利能力_订单增长率实际],[内部_盈利能力_订单增长率目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_盈利能力_库存额目标",
            "expression": "[result_product_month_库存额目标]"
          },
          {
            "name": "内部_盈利能力_库存额实际",
            "expression": "[result_product_month_库存额实际]"
          },
          {
            "name": "内部_盈利能力_库存额目标达成率",
            "expression": "DIVIDE([内部_盈利能力_库存额实际],[内部_盈利能力_库存额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_盈利能力_库存增长额目标",
            "expression": "[内部_盈利能力_库存额目标]-[内部_盈利能力_库存额目标_上月同期]"
          },
          {
            "name": "内部_盈利能力_库存增长额实际",
            "expression": "[内部_盈利能力_库存额实际]-[内部_盈利能力_库存额实际_上月同期]"
          },
          {
            "name": "内部_盈利能力_库存增长额目标达成率",
            "expression": "DIVIDE([内部_盈利能力_库存增长额实际],[内部_盈利能力_库存增长额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_盈利能力_库存周转率目标",
            "expression": "1"
          },
          {
            "name": "内部_盈利能力_库存周转率实际",
            "expression": "1"
          },
          {
            "name": "内部_盈利能力_库存周转率目标达成率",
            "expression": "DIVIDE([内部_盈利能力_库存周转率实际],[内部_盈利能力_库存周转率目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_盈利能力_库龄目标",
            "expression": "1"
          },
          {
            "name": "内部_盈利能力_库龄实际",
            "expression": "1"
          },
          {
            "name": "内部_盈利能力_库龄目标达成率",
            "expression": "DIVIDE([内部_盈利能力_库龄实际],[内部_盈利能力_库龄目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_盈利能力_盈利能力目标",
            "expression": "DIVIDE([内部_盈利能力_订单额目标],[内部_盈利能力_库存额目标])"
          },
          {
            "name": "内部_盈利能力_盈利能力实际",
            "expression": "DIVIDE([内部_盈利能力_订单额实际],[内部_盈利能力_库存额实际])"
          },
          {
            "name": "内部_盈利能力_盈利能力目标达成率",
            "expression": "DIVIDE([内部_盈利能力_盈利能力实际],[内部_盈利能力_盈利能力目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_盈利能力_库存额目标_上月同期",
            "expression": "CALCULATE([内部_盈利能力_库存额目标], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "内部_盈利能力_库存增长率目标",
            "expression": "DIVIDE([内部_盈利能力_库存增长额目标],[内部_盈利能力_库存额目标_上月同期])"
          },
          {
            "name": "内部_盈利能力_库存增长率实际",
            "expression": "DIVIDE([内部_盈利能力_库存增长额实际],[内部_盈利能力_库存额实际_上月同期])"
          },
          {
            "name": "内部_盈利能力_库存增长率目标达成率",
            "expression": "DIVIDE([内部_盈利能力_库存增长率实际],[内部_盈利能力_库存增长率目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_盈利能力_订单额目标实际差异",
            "expression": "[内部_盈利能力_订单额实际]-[内部_盈利能力_订单额目标]"
          },
          {
            "name": "内部_盈利能力_订单增长额目标实际差异",
            "expression": "[内部_盈利能力_订单增长额实际]-[内部_盈利能力_订单增长额目标]"
          },
          {
            "name": "内部_盈利能力_订单增长率目标实际差异",
            "expression": "[内部_盈利能力_订单增长率实际]-[内部_盈利能力_订单增长率目标]"
          },
          {
            "name": "内部_盈利能力_库存额目标实际差异",
            "expression": "[内部_盈利能力_库存额实际]-[内部_盈利能力_库存额目标]"
          },
          {
            "name": "内部_盈利能力_库存增长额目标实际差异",
            "expression": "[内部_盈利能力_库存增长额实际]-[内部_盈利能力_库存增长额目标]"
          },
          {
            "name": "内部_盈利能力_库存增长率目标实际差异",
            "expression": "[内部_盈利能力_库存增长率实际]-[内部_盈利能力_库存增长率目标]"
          },
          {
            "name": "内部_盈利能力_库存周转率目标实际差异",
            "expression": "[内部_盈利能力_库存周转率实际]-[内部_盈利能力_库存周转率目标]"
          },
          {
            "name": "内部_盈利能力_库龄目标实际差异",
            "expression": "[内部_盈利能力_库龄实际]-[内部_盈利能力_库龄目标]"
          },
          {
            "name": "内部_盈利能力_盈利能力目标实际差异",
            "expression": "[内部_盈利能力_盈利能力实际]-[内部_盈利能力_盈利能力目标]"
          },
          {
            "name": "内部_盈利能力_订单额目标_上月同期",
            "expression": "CALCULATE([内部_盈利能力_订单额目标], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "内部_盈利能力_订单额实际_上月同期",
            "expression": "CALCULATE([内部_盈利能力_订单额实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "内部_盈利能力_库存额实际_上月同期",
            "expression": "CALCULATE([内部_盈利能力_库存额实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          }
        ]
      },
      {
        "name": "度量值_内部_支付能力",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "列1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列7",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列8",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列9",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列10",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列11",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列12",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列13",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "Calculated Column 10",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "内部_支付能力_资金周转率目标",
            "expression": "[result_finance_month_资金周转率目标]"
          },
          {
            "name": "内部_支付能力_资金周转率实际",
            "expression": "[result_finance_month_资金周转率实际]"
          },
          {
            "name": "内部_支付能力_资金周转率目标达成率",
            "expression": "DIVIDE([内部_支付能力_资金周转率实际],[内部_支付能力_资金周转率目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_支付能力_固定资产占用率目标",
            "expression": "DIVIDE([内部_支付能力_固定资产目标],[内部_支付能力_总资产目标])"
          },
          {
            "name": "内部_支付能力_固定资产占用率实际",
            "expression": "DIVIDE([首页_支付能力_固定资产实际],[内部_支付能力_总资产实际])"
          },
          {
            "name": "内部_支付能力_固定资产占用率目标达成率",
            "expression": "DIVIDE([内部_支付能力_固定资产占用率实际],[内部_支付能力_固定资产占用率目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_支付能力_现金流入目标",
            "expression": "1"
          },
          {
            "name": "内部_支付能力_现金流出目标",
            "expression": "1"
          },
          {
            "name": "内部_支付能力_净现金流目标",
            "expression": "[result_finance_month_净现金流目标]"
          },
          {
            "name": "内部_支付能力_应收额目标",
            "expression": "1"
          },
          {
            "name": "内部_支付能力_应收增长额目标",
            "expression": "[内部_支付能力_应收额目标]-[内部_支付能力_应收额目标_上月同期]"
          },
          {
            "name": "内部_支付能力_应收增长率目标",
            "expression": "DIVIDE([内部_支付能力_应收增长额目标],[内部_支付能力_应收额目标_上月同期])"
          },
          {
            "name": "内部_支付能力_应付额目标",
            "expression": "1"
          },
          {
            "name": "内部_支付能力_应付增长额目标",
            "expression": "[内部_支付能力_应付额目标]-[内部_支付能力_应付额目标_上月同期]"
          },
          {
            "name": "内部_支付能力_应付增长率目标",
            "expression": "DIVIDE([内部_支付能力_应付增长额目标],[内部_支付能力_应付额目标_上月同期])"
          },
          {
            "name": "内部_支付能力_支付能力1目标",
            "expression": "1"
          },
          {
            "name": "内部_支付能力_支付能力2目标",
            "expression": "1"
          },
          {
            "name": "内部_支付能力_现金流入实际",
            "expression": "1"
          },
          {
            "name": "内部_支付能力_现金流出实际",
            "expression": "1"
          },
          {
            "name": "内部_支付能力_净现金流实际",
            "expression": "[result_finance_month_净现金流实际]"
          },
          {
            "name": "内部_支付能力_净现金流目标达成率",
            "expression": "DIVIDE([内部_支付能力_净现金流实际],[内部_支付能力_净现金流目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_支付能力_应收额实际",
            "expression": "1"
          },
          {
            "name": "内部_支付能力_应收额目标达成率",
            "expression": "DIVIDE([内部_支付能力_应收额实际],[内部_支付能力_应收额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_支付能力_应收增长额实际",
            "expression": "[内部_支付能力_应收额实际]-[内部_支付能力_应收额实际_上月同期]"
          },
          {
            "name": "内部_支付能力_应收增长额目标达成率",
            "expression": "DIVIDE([内部_支付能力_应收增长额实际],[内部_支付能力_应收增长额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_支付能力_应收增长率实际",
            "expression": "DIVIDE([内部_支付能力_应收增长额实际],[内部_支付能力_应收额实际_上月同期])"
          },
          {
            "name": "内部_支付能力_应收增长率目标达成率",
            "expression": "DIVIDE([内部_支付能力_应收增长率实际],[内部_支付能力_应收增长率目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_支付能力_应付额实际",
            "expression": "1"
          },
          {
            "name": "内部_支付能力_应付额目标达成率",
            "expression": "DIVIDE([内部_支付能力_应付额实际],[内部_支付能力_应付额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_支付能力_应付增长额实际",
            "expression": "[内部_支付能力_应付额实际]-[内部_支付能力_应付额实际_上月同期]"
          },
          {
            "name": "内部_支付能力_应付增长额目标达成率",
            "expression": "DIVIDE([内部_支付能力_应付增长额实际],[内部_支付能力_应付增长额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_支付能力_应付增长率实际",
            "expression": "DIVIDE([内部_支付能力_应付增长额实际],[内部_支付能力_应付额实际_上月同期])"
          },
          {
            "name": "内部_支付能力_应付增长率目标达成率",
            "expression": "DIVIDE([内部_支付能力_应付增长率实际],[内部_支付能力_应付增长率目标])"
          },
          {
            "name": "内部_支付能力_支付能力1实际",
            "expression": "1"
          },
          {
            "name": "内部_支付能力_支付能力1目标达成率",
            "expression": "DIVIDE([内部_支付能力_支付能力1实际],[内部_支付能力_支付能力1目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_支付能力_现金流入目标达成率",
            "expression": "DIVIDE([内部_支付能力_现金流入实际],[内部_支付能力_现金流入目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_支付能力_现金流出目标达成率",
            "expression": "DIVIDE([内部_支付能力_现金流出实际],[内部_支付能力_现金流出目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_支付能力_支付能力2实际",
            "expression": "1"
          },
          {
            "name": "内部_支付能力_支付能力2目标达成率",
            "expression": "DIVIDE([内部_支付能力_支付能力2实际],[内部_支付能力_支付能力2目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "内部_支付能力_固定资产目标",
            "expression": "1"
          },
          {
            "name": "首页_支付能力_固定资产实际",
            "expression": "1"
          },
          {
            "name": "内部_支付能力_总资产目标",
            "expression": "SUMX('target_finance_month','target_finance_month'[target_total_assets_amt])"
          },
          {
            "name": "内部_支付能力_总资产实际",
            "expression": "SUMX('result_finance_month','result_finance_month'[total_assets_amt])"
          },
          {
            "name": "内部_支付能力_资金周转率目标实际差异",
            "expression": "[内部_支付能力_资金周转率实际]-[内部_支付能力_资金周转率目标]"
          },
          {
            "name": "内部_支付能力_固定资产占用率目标实际差异",
            "expression": "[内部_支付能力_固定资产占用率实际]-[内部_支付能力_固定资产占用率目标]"
          },
          {
            "name": "内部_支付能力_现金流入目标实际差异",
            "expression": "[内部_支付能力_现金流入实际]-[内部_支付能力_现金流入目标]"
          },
          {
            "name": "内部_支付能力_现金流出目标实际差异",
            "expression": "[内部_支付能力_现金流出实际]-[内部_支付能力_现金流出目标]"
          },
          {
            "name": "内部_支付能力_净现金流目标实际差异",
            "expression": "[内部_支付能力_净现金流实际]-[内部_支付能力_净现金流目标]"
          },
          {
            "name": "内部_支付能力_应收额目标实际差异",
            "expression": "[内部_支付能力_应收额实际]-[内部_支付能力_应收额目标]"
          },
          {
            "name": "内部_支付能力_应收增长额目标实际差异",
            "expression": "[内部_支付能力_应收增长额实际]-[内部_支付能力_应收增长额目标]"
          },
          {
            "name": "内部_支付能力_应收增长率目标实际差异",
            "expression": "[内部_支付能力_应收增长率实际]-[内部_支付能力_应收增长率目标]"
          },
          {
            "name": "内部_支付能力_应付额目标实际差异",
            "expression": "[内部_支付能力_应付额实际]-[内部_支付能力_应付额目标]"
          },
          {
            "name": "内部_支付能力_应付增长额目标实际差异",
            "expression": "[内部_支付能力_应付增长额实际]-[内部_支付能力_应付增长额目标]"
          },
          {
            "name": "内部_支付能力_应付增长率目标实际差异",
            "expression": "[内部_支付能力_应付增长率实际]-[内部_支付能力_应付增长率目标]"
          },
          {
            "name": "内部_支付能力_支付能力1目标实际差异",
            "expression": "[内部_支付能力_支付能力1实际]-[内部_支付能力_支付能力1目标]"
          },
          {
            "name": "内部_支付能力_支付能力2目标实际差异",
            "expression": "[内部_支付能力_支付能力2实际]-[内部_支付能力_支付能力2目标]"
          },
          {
            "name": "内部_支付能力_应收额目标_上月同期",
            "expression": "CALCULATE([内部_支付能力_应收额目标], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "内部_支付能力_应收额实际_上月同期",
            "expression": "CALCULATE([内部_支付能力_应收额实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "内部_支付能力_应付额目标_上月同期",
            "expression": "CALCULATE([内部_支付能力_应付额目标], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          },
          {
            "name": "内部_支付能力_应付额实际_上月同期",
            "expression": "CALCULATE([内部_支付能力_应付额实际], DATEADD('V_DimMonth'[EndDate], -1, MONTH))"
          }
        ]
      },
      {
        "name": "雷达_外部_基本竞争力",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "目标达成率",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[目标达成率]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"销售额\" ,   [外部_基本竞争力_销售额目标达成率],) , ",
                "    ( \"销售增长额\" , [外部_基本竞争力_销售增长额目标达成率], ),",
                "    ( \"销售增长率\" ,[外部_基本竞争力_销售增长率目标达成率] , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] , \"目标达成率\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "雷达_外部_持续竞争力",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "目标达成率",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[目标达成率]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"净利润额\" ,   [外部_持续竞争力_净利润额目标达成率],) , ",
                "    ( \"净利润增长额\" , [外部_持续竞争力_净利润增长额目标达成率], ),",
                "    ( \"净利率\" ,[外部_持续竞争力_净利率目标达成率], ),",
                "    ( \"净利润增长率\" ,[外部_持续竞争力_净利润增长率目标达成率],)",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] , \"目标达成率\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "度量值_外部_核心竞争力_产品效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "列1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列8",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列7",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "外部_核心竞争力_产品效率_单品平均成本费用额目标",
            "expression": "DIVIDE('result_product_month'[result_product_month_产品成本额目标],[外部_核心竞争力_产品效率_SKU数量目标])"
          },
          {
            "name": "外部_核心竞争力_产品效率_单品平均成本费用额目标达成率",
            "expression": "DIVIDE([外部_核心竞争力_产品效率_单品平均成本费用额实际],[外部_核心竞争力_产品效率_单品平均成本费用额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_产品效率_单品平均成本费用额实际",
            "expression": "DIVIDE('result_product_month'[result_product_month_产品成本额实际],[外部_核心竞争力_产品效率_SKU数量实际])"
          },
          {
            "name": "外部_核心竞争力_产品效率_投入产出比目标",
            "expression": "[result_product_month_产品投入产出比目标]"
          },
          {
            "name": "外部_核心竞争力_产品效率_投入产出比目标达成率",
            "expression": "[result_product_month_产品投入产出比目标达成率]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_产品效率_投入产出比实际",
            "expression": "[result_product_month_产品投入产出比实际]"
          },
          {
            "name": "外部_核心竞争力_产品效率_库存周转率目标",
            "expression": "[result_product_month_库存周转率目标]"
          },
          {
            "name": "外部_核心竞争力_产品效率_库存周转率目标达成率",
            "expression": "[result_product_month_库存周转率目标达成率]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_产品效率_库存周转率实际",
            "expression": "[result_product_month_库存周转率实际]"
          },
          {
            "name": "外部_核心竞争力_产品效率_日销目标",
            "expression": "[result_product_month_日销目标]"
          },
          {
            "name": "外部_核心竞争力_产品效率_日销目标达成率",
            "expression": "[result_product_month_日销目标达成率]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_产品效率_日销实际",
            "expression": "[result_product_month_日销实际]"
          },
          {
            "name": "外部_核心竞争力_产品效率_产品冗余值目标",
            "expression": "[result_product_month_库存额目标]"
          },
          {
            "name": "外部_核心竞争力_产品效率_产品冗余值目标达成率",
            "expression": "[result_product_month_库存额目标达成率]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_产品效率_产品冗余值实际",
            "expression": "[result_product_month_库存额实际]"
          },
          {
            "name": "外部_核心竞争力_产品效率_SKU数量目标实际差异",
            "expression": "[外部_核心竞争力_产品效率_SKU数量实际]-[外部_核心竞争力_产品效率_SKU数量目标]"
          },
          {
            "name": "外部_核心竞争力_产品效率_SKU数量目标",
            "expression": "2300"
          },
          {
            "name": "外部_核心竞争力_产品效率_SKU数量目标达成率",
            "expression": [
              "DIVIDE([外部_核心竞争力_产品效率_SKU数量实际],[外部_核心竞争力_产品效率_SKU数量目标])",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_产品效率_SKU数量实际",
            "expression": "3000"
          },
          {
            "name": "外部_核心竞争力_产品效率_单品平均毛利润额目标",
            "expression": "DIVIDE('result_product_month'[result_product_month_毛利润额目标],[外部_核心竞争力_产品效率_SKU数量目标])"
          },
          {
            "name": "外部_核心竞争力_产品效率_单品平均毛利润额目标达成率",
            "expression": "DIVIDE([外部_核心竞争力_产品效率_单品平均毛利润额实际],[外部_核心竞争力_产品效率_单品平均毛利润额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_产品效率_单品平均毛利润额实际",
            "expression": "DIVIDE('result_product_month'[result_product_month_毛利润额实际],[外部_核心竞争力_产品效率_SKU数量实际])"
          },
          {
            "name": "外部_核心竞争力_产品效率_单品平均销售额目标",
            "expression": "DIVIDE('result_product_month'[result_product_month_销售额目标],[外部_核心竞争力_产品效率_SKU数量目标])"
          },
          {
            "name": "外部_核心竞争力_产品效率_单品平均销售额目标达成率",
            "expression": "DIVIDE([外部_核心竞争力_产品效率_单品平均销售额实际],[外部_核心竞争力_产品效率_单品平均销售额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "外部_核心竞争力_产品效率_单品平均销售额实际",
            "expression": " DIVIDE('result_product_month'[result_product_month_销售额实际],[外部_核心竞争力_产品效率_SKU数量实际])"
          },
          {
            "name": "外部_核心竞争力_产品效率_单品平均毛利润额目标实际差异",
            "expression": "[外部_核心竞争力_产品效率_单品平均毛利润额实际]-[外部_核心竞争力_产品效率_单品平均毛利润额目标]"
          },
          {
            "name": "外部_核心竞争力_产品效率_单品平均销售额目标实际差异",
            "expression": "[外部_核心竞争力_产品效率_单品平均销售额实际]-[外部_核心竞争力_产品效率_单品平均销售额目标]"
          },
          {
            "name": "外部_核心竞争力_产品效率_单品平均成本费用额目标实际差异",
            "expression": "[外部_核心竞争力_产品效率_单品平均成本费用额实际]-[外部_核心竞争力_产品效率_单品平均成本费用额目标]"
          },
          {
            "name": "外部_核心竞争力_产品效率_投入产出比目标实际差异",
            "expression": "[result_product_month_产品投入产出比目标实际差异]"
          },
          {
            "name": "外部_核心竞争力_产品效率_库存周转率目标实际差异",
            "expression": "[result_product_month_库存周转率目标实际差异]"
          },
          {
            "name": "全部_核心竞争力_产品效率_日销目标实际差异",
            "expression": "[result_product_month_日销目标实际差异]"
          },
          {
            "name": "外部_核心竞争力_产品效率_产品冗余值目标实际差异",
            "expression": "[result_product_month_库存额目标实际差异]"
          }
        ]
      },
      {
        "name": "雷达_外部_核心竞争力_产品效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "目标达成率",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[目标达成率]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"SKU数量\" ,   [外部_核心竞争力_产品效率_SKU数量目标达成率],) , ",
                "    ( \"单品平均毛利润额\" , [外部_核心竞争力_产品效率_单品平均毛利润额目标达成率], ),",
                "    ( \"单品平均销售额\" ,[外部_核心竞争力_产品效率_单品平均销售额目标达成率], ),",
                "    ( \"单品平均成本费用额(2-目标达成率)\" ,2-[外部_核心竞争力_产品效率_单品平均成本费用额目标达成率],),",
                "    ( \"投入产出比\" ,[外部_核心竞争力_产品效率_投入产出比目标达成率], ),",
                "    ( \"库存周转率\" ,[外部_核心竞争力_产品效率_库存周转率目标达成率], ),",
                "    ( \"日销\" ,[外部_核心竞争力_产品效率_日销目标达成率], ),",
                "    ( \"产品冗余值(2-目标达成率)\" ,2-[外部_核心竞争力_产品效率_产品冗余值目标达成率], )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] , \"目标达成率\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "雷达_外部_核心竞争力_渠道效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "目标达成率",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[目标达成率]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"店铺数量\" ,   [外部_核心竞争力_渠道效率_店铺数量目标达成率],) , ",
                "    ( \"单店平均营业利润额\" ,  [外部_核心竞争力_渠道效率_单店平均营业利润额目标达成率],) , ",
                "    ( \"单店平均销售额\" , [外部_核心竞争力_渠道效率_单店平均销售额目标达成率],) , ",
                "    ( \"单店平均成本费用额(2-目标达成率)\" ,2- [外部_核心竞争力_渠道效率_单店平均成本费用额目标达成率],) , ",
                "    ( \"投入产出比\" , [外部_核心竞争力_渠道效率_投入产出比目标达成率],) , ",
                "    ( \"渠道冗余值\" , [外部_核心竞争力_渠道效率_渠道冗余值目标达成率],) , ",
                "    ( \"日销\" , [外部_核心竞争力_渠道效率_日销目标达成率],)",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] , \"目标达成率\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "雷达_外部_核心竞争力_客户效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "目标达成率",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[目标达成率]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"消费者人数\" ,   [外部_核心竞争力_客户效率_消费者人数目标达成率],) , ",
                "    ( \"消费者人均销售额\" ,  [外部_核心竞争力_客户效率_消费者人均销售额目标达成率],) , ",
                "    ( \"消费者人均客户利润额\" , [外部_核心竞争力_客户效率_消费者人均客户利润额目标达成率],) , ",
                "    ( \"消费者人均成本费用额(2-目标达成率)\" ,2- [外部_核心竞争力_客户效率_消费者人均成本费用额目标达成率],) , ",
                "    ( \"日销\" , [外部_核心竞争力_客户效率_日销目标达成率],) , ",
                "    ( \"投入产出比\" , [外部_核心竞争力_客户效率_投入产出比目标达成率],) , ",
                "    ( \"消费者冗余值\" , [外部_核心竞争力_客户效率_消费者冗余值目标达成率],) ",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] , \"目标达成率\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "雷达_外部_核心竞争力_供应效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "目标达成率",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[目标达成率]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"工厂数量\" ,   [外部_核心竞争力_供应效率_工厂数量目标达成率],) , ",
                "    ( \"工厂平均销售额\" ,  [外部_核心竞争力_供应效率_工厂平均销售额目标达成率],) , ",
                "    ( \"工厂平均毛利额\" , [外部_核心竞争力_供应效率_工厂平均毛利额目标达成率],),",
                "    ( \"工厂平均产能(2-目标达成率)\" ,2- [外部_核心竞争力_供应效率_工厂平均产能目标达成率],) , ",
                "    ( \"产供比\" , [外部_核心竞争力_供应效率_产供比目标达成率],) , ",
                "    ( \"工厂平均残品率(2-目标达成率)\" , 2-[外部_核心竞争力_供应效率_工厂平均残品率目标达成率],) , ",
                "    ( \"工厂平均交期达成率\" , [外部_核心竞争力_供应效率_工厂平均交期达成率目标达成率],) ",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] , \"目标达成率\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "雷达_外部_核心竞争力_组织效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "目标达成率",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[目标达成率]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"企业人数\" ,   [外部_核心竞争力_组织效率_企业人数目标达成率],) , ",
                "    ( \"企业人均销售额\" ,   [外部_核心竞争力_组织效率_企业人均销售额目标达成率],) , ",
                "    ( \"企业人均净利润额\" , [外部_核心竞争力_组织效率_企业人均净利润额目标达成率],) , ",
                "    ( \"企业人均成本额(2-目标达成率)\" ,2- [外部_核心竞争力_组织效率_企业人均成本额目标达成率],) , ",
                "   ( \"日销\" ,  [外部_核心竞争力_组织效率_日销目标达成率],) , ",
                "    ( \"投入产出比\" , [外部_核心竞争力_组织效率_投入产出比目标达成率],) , ",
                "    ( \"企业人均冗余值\" , [外部_核心竞争力_组织效率_企业人均冗余值目标达成率],) ",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] , \"目标达成率\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "dim_channel",
        "columns": [
          {
            "name": "ChannelKey",
            "dataType": "int64",
            "sourceColumn": "ChannelKey"
          },
          {
            "name": "c1",
            "dataType": "string",
            "sourceColumn": "c1"
          },
          {
            "name": "c2",
            "dataType": "string",
            "sourceColumn": "c2"
          },
          {
            "name": "c3",
            "dataType": "string",
            "sourceColumn": "c3"
          },
          {
            "name": "c4",
            "dataType": "string",
            "sourceColumn": "c4"
          },
          {
            "name": "c5",
            "dataType": "string",
            "sourceColumn": "c5"
          },
          {
            "name": "c6",
            "dataType": "string",
            "sourceColumn": "c6"
          },
          {
            "name": "c1_name",
            "dataType": "string",
            "sourceColumn": "c1_name"
          },
          {
            "name": "c2_name",
            "dataType": "string",
            "sourceColumn": "c2_name"
          },
          {
            "name": "c3_name",
            "dataType": "string",
            "sourceColumn": "c3_name"
          },
          {
            "name": "c4_name",
            "dataType": "string",
            "sourceColumn": "c4_name"
          },
          {
            "name": "c5_name",
            "dataType": "string",
            "sourceColumn": "c5_name"
          },
          {
            "name": "c6_name",
            "dataType": "string",
            "sourceColumn": "c6_name"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_dim_channel = Source{[Schema=\"dbo\",Item=\"dim_channel\"]}[Data]",
                "in",
                "    dbo_dim_channel"
              ]
            }
          }
        ]
      },
      {
        "name": "dim_cus",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "c1",
            "dataType": "string",
            "sourceColumn": "c1"
          },
          {
            "name": "c2",
            "dataType": "string",
            "sourceColumn": "c2"
          },
          {
            "name": "c3",
            "dataType": "string",
            "sourceColumn": "c3"
          },
          {
            "name": "c4",
            "dataType": "string",
            "sourceColumn": "c4"
          },
          {
            "name": "c5",
            "dataType": "string",
            "sourceColumn": "c5"
          },
          {
            "name": "c6",
            "dataType": "string",
            "sourceColumn": "c6"
          },
          {
            "name": "c1_name",
            "dataType": "string",
            "sourceColumn": "c1_name"
          },
          {
            "name": "c2_name",
            "dataType": "string",
            "sourceColumn": "c2_name"
          },
          {
            "name": "c3_name",
            "dataType": "string",
            "sourceColumn": "c3_name"
          },
          {
            "name": "c4_name",
            "dataType": "string",
            "sourceColumn": "c4_name"
          },
          {
            "name": "c5_name",
            "dataType": "string",
            "sourceColumn": "c5_name"
          },
          {
            "name": "c6_name",
            "dataType": "string",
            "sourceColumn": "c6_name"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_dim_cus = Source{[Schema=\"dbo\",Item=\"dim_cus\"]}[Data]",
                "in",
                "    dbo_dim_cus"
              ]
            }
          }
        ]
      },
      {
        "name": "dim_org",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "c1",
            "dataType": "string",
            "sourceColumn": "c1"
          },
          {
            "name": "c2",
            "dataType": "string",
            "sourceColumn": "c2"
          },
          {
            "name": "c3",
            "dataType": "string",
            "sourceColumn": "c3"
          },
          {
            "name": "c4",
            "dataType": "string",
            "sourceColumn": "c4"
          },
          {
            "name": "c5",
            "dataType": "string",
            "sourceColumn": "c5"
          },
          {
            "name": "c6",
            "dataType": "string",
            "sourceColumn": "c6"
          },
          {
            "name": "c1_name",
            "dataType": "string",
            "sourceColumn": "c1_name"
          },
          {
            "name": "c2_name",
            "dataType": "string",
            "sourceColumn": "c2_name"
          },
          {
            "name": "c3_name",
            "dataType": "string",
            "sourceColumn": "c3_name"
          },
          {
            "name": "c4_name",
            "dataType": "string",
            "sourceColumn": "c4_name"
          },
          {
            "name": "c5_name",
            "dataType": "string",
            "sourceColumn": "c5_name"
          },
          {
            "name": "c6_name",
            "dataType": "string",
            "sourceColumn": "c6_name"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_dim_org = Source{[Schema=\"dbo\",Item=\"dim_org\"]}[Data]",
                "in",
                "    dbo_dim_org"
              ]
            }
          }
        ]
      },
      {
        "name": "dim_product",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "c1",
            "dataType": "string",
            "sourceColumn": "c1"
          },
          {
            "name": "c2",
            "dataType": "string",
            "sourceColumn": "c2"
          },
          {
            "name": "c3",
            "dataType": "string",
            "sourceColumn": "c3"
          },
          {
            "name": "c4",
            "dataType": "string",
            "sourceColumn": "c4"
          },
          {
            "name": "c5",
            "dataType": "string",
            "sourceColumn": "c5"
          },
          {
            "name": "c6",
            "dataType": "string",
            "sourceColumn": "c6"
          },
          {
            "name": "c1_name",
            "dataType": "string",
            "sourceColumn": "c1_name"
          },
          {
            "name": "c2_name",
            "dataType": "string",
            "sourceColumn": "c2_name"
          },
          {
            "name": "c3_name",
            "dataType": "string",
            "sourceColumn": "c3_name"
          },
          {
            "name": "c4_name",
            "dataType": "string",
            "sourceColumn": "c4_name"
          },
          {
            "name": "c5_name",
            "dataType": "string",
            "sourceColumn": "c5_name"
          },
          {
            "name": "c6_name",
            "dataType": "string",
            "sourceColumn": "c6_name"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_dim_product = Source{[Schema=\"dbo\",Item=\"dim_product\"]}[Data]",
                "in",
                "    dbo_dim_product"
              ]
            }
          }
        ]
      },
      {
        "name": "dim_supply",
        "columns": [
          {
            "name": "SupplyKey",
            "dataType": "int64",
            "sourceColumn": "SupplyKey"
          },
          {
            "name": "c1",
            "dataType": "string",
            "sourceColumn": "c1"
          },
          {
            "name": "c2",
            "dataType": "string",
            "sourceColumn": "c2"
          },
          {
            "name": "c3",
            "dataType": "string",
            "sourceColumn": "c3"
          },
          {
            "name": "c4",
            "dataType": "string",
            "sourceColumn": "c4"
          },
          {
            "name": "c5",
            "dataType": "string",
            "sourceColumn": "c5"
          },
          {
            "name": "c6",
            "dataType": "string",
            "sourceColumn": "c6"
          },
          {
            "name": "c1_name",
            "dataType": "string",
            "sourceColumn": "c1_name"
          },
          {
            "name": "c2_name",
            "dataType": "string",
            "sourceColumn": "c2_name"
          },
          {
            "name": "c3_name",
            "dataType": "string",
            "sourceColumn": "c3_name"
          },
          {
            "name": "c4_name",
            "dataType": "string",
            "sourceColumn": "c4_name"
          },
          {
            "name": "c5_name",
            "dataType": "string",
            "sourceColumn": "c5_name"
          },
          {
            "name": "c6_name",
            "dataType": "string",
            "sourceColumn": "c6_name"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 68;wxxl_yueying\",",
                "    dbo_dim_supply = Source{[Schema=\"dbo\",Item=\"dim_supply\"]}[Data]",
                "in",
                "    dbo_dim_supply"
              ]
            }
          }
        ]
      },
      {
        "name": "雷达_外部_核心竞争力_资金效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "目标达成率",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[目标达成率]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"销售额\" ,   [外部_核心竞争力_资金效率_销售额目标达成率],) , ",
                "    ( \"净利润额\" ,   [外部_核心竞争力_资金效率_净利润额目标达成率],) , ",
                "    ( \"总成本费用额(2-目标达成率)\" , 2-[外部_核心竞争力_资金效率_总成本费用额目标达成率],) , ",
                "    ( \"回款额\" ,[外部_核心竞争力_资金效率_回款额目标达成率],) , ",
                "    ( \"投资回报率\" , [外部_核心竞争力_资金效率_投资回报率目标达成率],) , ",
                "    ( \"净利率\" , [外部_核心竞争力_资金效率_净利率目标达成率],) , ",
                "    ( \"净现金流\" , [外部_核心竞争力_资金效率_净现金流目标达成率],) , ",
                "    ( \"资金周转率\" ,[外部_核心竞争力_资金效率_资金周转率目标达成率],) , ",
                "    ( \"资金冗余值\" , [外部_核心竞争力_资金效率_资金冗余值目标达成率],)",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] , \"目标达成率\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "雷达_外部_品牌价值",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "目标达成率",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[目标达成率]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"品质合格率\" ,   [外部_品牌价值_品质合格率目标达成率],) , ",
                "    ( \"传播网点数\" , [外部_品牌价值_传播网点数目标达成率],) , ",
                "    ( \"传播成本\" ,[外部_品牌价值_传播成本目标达成率],) , ",
                "    ( \"传播的投入产出比\" ,[外部_品牌价值_传播的投入产出比目标达成率],)",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] , \"目标达成率\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "雷达_内部_盈利空间",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "目标达成率",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[目标达成率]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"毛利率\" ,   [内部_盈利空间_毛利率目标达成率],) , ",
                "    ( \"回款额\" , [内部_盈利空间_回款额目标达成率],) , ",
                "    ( \"回款增长额\" ,[内部_盈利空间_回款增长额目标达成率],) , ",
                "    ( \"回款增长率\" ,[内部_盈利空间_回款增长率目标达成率],) , ",
                "    ( \"总成本费用额(2-目标达成率)\" , 2-[内部_盈利空间_总成本费用额目标达成率],) , ",
                "    ( \"总成本费用增长额\" , [内部_盈利空间_总成本费用增长额目标达成率],) , ",
                "    ( \"总成本费用增长率\" ,[内部_盈利空间_总成本费用增长率目标达成率],) , ",
                "    ( \"盈利空间\" ,[内部_盈利空间_盈利空间目标达成率],) ",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] , \"目标达成率\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "雷达_内部_盈利能力",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "目标达成率",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[目标达成率]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"订单额\" ,   [内部_盈利能力_订单额目标达成率],) , ",
                "    ( \"订单增长额\" , [内部_盈利能力_订单增长额目标达成率],) , ",
                "    ( \"订单增长率\" ,[内部_盈利能力_订单增长率目标达成率],) , ",
                "    ( \"库存额(2-目标达成率)\" ,2-[内部_盈利能力_库存额目标达成率],) , ",
                "    ( \"库存增长额\" , [内部_盈利能力_库存增长额目标达成率],) , ",
                "    ( \"库存增长率\" , [内部_盈利能力_库存增长率目标达成率],) , ",
                "    ( \"库存周转率\" ,[内部_盈利能力_库存周转率目标达成率],) , ",
                "    ( \"库龄\",[内部_盈利能力_库龄目标达成率],) , ",
                "    ( \"盈利能力\" ,[内部_盈利能力_盈利能力目标达成率],)",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] , \"目标达成率\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "雷达_内部_支付能力",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "目标达成率",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[目标达成率]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"资金周转率\" ,   [内部_支付能力_资金周转率目标达成率],) , ",
                "    ( \"固定资产占用率\" , [内部_支付能力_固定资产占用率目标达成率],) , ",
                "    ( \"现金流入\" ,[内部_支付能力_现金流入目标达成率],) , ",
                "    ( \"现金流出\" ,[内部_支付能力_现金流出目标达成率],) , ",
                "    ( \"净现金流\" , [内部_支付能力_净现金流目标达成率],) , ",
                "    ( \"应收额\" , [内部_支付能力_应收额目标达成率],) , ",
                "    ( \"应收增长额\" ,[内部_支付能力_应收增长额目标达成率],) , ",
                "    ( \"应收增长率\",[内部_支付能力_应收增长率目标达成率],) , ",
                "    ( \"应付额\" ,[内部_支付能力_应付额目标达成率],) , ",
                "    ( \"应付增长额\" ,[内部_支付能力_应付增长额目标达成率],) , ",
                "    ( \"应付增长率\" ,[内部_支付能力_应付增长率目标达成率],) , ",
                "    ( \"支付能力1\" ,[内部_支付能力_支付能力1目标达成率],) , ",
                "    ( \"支付能力2\" ,[内部_支付能力_支付能力2目标达成率],) ",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] , \"目标达成率\" , [Value2] )"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "2787a3ab-29da-42ec-87fa-d34b6840bc3f",
        "fromTable": "DimDate",
        "fromColumn": "MonthKey",
        "toTable": "V_DimMonth",
        "toColumn": "MonthKey"
      },
      {
        "name": "a4f4214b-2710-42e9-acf7-7c02854b8e59",
        "fromTable": "DimChannel",
        "fromColumn": "PersonKey",
        "toTable": "DimPerson",
        "toColumn": "PersonKey"
      },
      {
        "name": "5ee8dc18-ded2-40b0-b856-c2fd6b316544",
        "fromTable": "DimChannel",
        "fromColumn": "OrgKey",
        "toTable": "DimOrg",
        "toColumn": "OrgKey"
      },
      {
        "name": "2b458c9f-5339-4ba5-9297-1a21b318d4e1",
        "fromTable": "result_channel_month",
        "fromColumn": "MonthKey",
        "toTable": "V_DimMonth",
        "toColumn": "MonthKey"
      },
      {
        "name": "aecd269f-9ed3-4df4-8c20-c067e4f1812e",
        "fromTable": "result_channel_day",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "4133b9fe-b12b-409e-8065-86f775230338",
        "fromTable": "result_supply_month",
        "fromColumn": "MonthKey",
        "toTable": "V_DimMonth",
        "toColumn": "MonthKey"
      },
      {
        "name": "adb9cc87-983c-477a-801f-6c4eb6a58f43",
        "fromTable": "result_org_month",
        "fromColumn": "MonthKey",
        "toTable": "V_DimMonth",
        "toColumn": "MonthKey"
      },
      {
        "name": "f61ab559-d4d5-43ae-952c-f0467a463387",
        "fromTable": "result_finance_month",
        "fromColumn": "MonthKey",
        "toTable": "V_DimMonth",
        "toColumn": "MonthKey"
      },
      {
        "name": "4303c369-2e4e-4887-83da-45a3d0f20e61",
        "fromTable": "result_product_month",
        "fromColumn": "MonthKey",
        "toTable": "V_DimMonth",
        "toColumn": "MonthKey"
      },
      {
        "name": "894fd8b0-1adf-40ad-8cba-479f3bb4ec89",
        "fromTable": "result_product_day",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "01dc4219-189c-4c68-b1aa-41c1451ba2a2",
        "fromTable": "result_customer_month",
        "fromColumn": "MonthKey",
        "toTable": "V_DimMonth",
        "toColumn": "MonthKey"
      },
      {
        "name": "9be82b66-3f56-4892-9e84-d49dcd8fe336",
        "fromTable": "result_customer_day",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "eb8c21a5-3a61-4694-96ee-6bf5532a4c2e",
        "fromTable": "target_product_day",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "e5e9b6ed-5e43-46c0-9e2b-f1dd777ff638",
        "fromTable": "target_product_month",
        "fromColumn": "MonthKey",
        "toTable": "V_DimMonth",
        "toColumn": "MonthKey"
      },
      {
        "name": "59d8c2f3-0045-4177-9f56-9d32c3c1e062",
        "fromTable": "target_channel_day",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "6eb0d0d6-d1b6-4d61-9879-6c3c1a5cf00b",
        "fromTable": "target_channel_month",
        "fromColumn": "MonthKey",
        "toTable": "V_DimMonth",
        "toColumn": "MonthKey"
      },
      {
        "name": "7f1259c6-6219-4d9a-a664-1b4c58b78428",
        "fromTable": "target_customer_day",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "4c43a36f-e3be-45fc-bccf-f73a06260477",
        "fromTable": "target_customer_month",
        "fromColumn": "MonthKey",
        "toTable": "V_DimMonth",
        "toColumn": "MonthKey"
      },
      {
        "name": "0c60cb88-486c-4a92-8479-bddfc2c3a97a",
        "fromTable": "target_supply_month",
        "fromColumn": "MonthKey",
        "toTable": "V_DimMonth",
        "toColumn": "MonthKey"
      },
      {
        "name": "cd9ec0d0-43b6-495e-b7c5-9d94fda8bb22",
        "fromTable": "target_org_month",
        "fromColumn": "MonthKey",
        "toTable": "V_DimMonth",
        "toColumn": "MonthKey"
      },
      {
        "name": "b6163b05-a79e-44c3-a468-200b678c3a44",
        "fromTable": "target_finance_month",
        "fromColumn": "MonthKey",
        "toTable": "V_DimMonth",
        "toColumn": "MonthKey"
      },
      {
        "name": "8d62c74e-96f9-42ff-8c4d-55e0e2752dcb",
        "fromTable": "result_product_day",
        "fromColumn": "ProductKey",
        "toTable": "tree_product",
        "toColumn": "ProductKey"
      },
      {
        "name": "99760274-9c9b-4ae1-88c0-f5cba5e41a82",
        "fromTable": "target_product_day",
        "fromColumn": "ProductKey",
        "toTable": "tree_product",
        "toColumn": "ProductKey"
      },
      {
        "name": "7ceeb3ba-3d29-4476-b0ad-88a13d5d74ee",
        "fromTable": "result_product_month",
        "fromColumn": "ProductKey",
        "toTable": "tree_product",
        "toColumn": "ProductKey"
      },
      {
        "name": "51aa3039-a2cf-4042-8d9f-0d776d45ff6b",
        "fromTable": "target_product_month",
        "fromColumn": "ProductKey",
        "toTable": "tree_product",
        "toColumn": "ProductKey"
      },
      {
        "name": "9e505f5f-4519-4c9f-a755-75ad203c8d34",
        "fromTable": "result_channel_day",
        "fromColumn": "ChannelKey",
        "toTable": "tree_channel",
        "toColumn": "ChannelKey"
      },
      {
        "name": "24b6f5f8-6e3e-4830-a29d-bb3a79b10fe2",
        "fromTable": "target_channel_day",
        "fromColumn": "ChannelKey",
        "toTable": "tree_channel",
        "toColumn": "ChannelKey"
      },
      {
        "name": "0fc66056-8ca8-4df0-a8a6-a8bd9efddadb",
        "fromTable": "result_channel_month",
        "fromColumn": "ChannelKey",
        "toTable": "tree_channel",
        "toColumn": "ChannelKey"
      },
      {
        "name": "d37da887-8866-4e91-b46f-9ffac8f760cb",
        "fromTable": "target_channel_month",
        "fromColumn": "ChannelKey",
        "toTable": "tree_channel",
        "toColumn": "ChannelKey"
      },
      {
        "name": "9675dca9-5b84-44ae-8793-224aeb695a4d",
        "fromTable": "result_customer_day",
        "fromColumn": "CustomerKey",
        "toTable": "tree_customer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "21707159-8b72-40f9-8d92-5098292d4a50",
        "fromTable": "target_customer_day",
        "fromColumn": "CustomerKey",
        "toTable": "tree_customer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "7e4ac337-38d8-4e4f-8e4f-59040b10c357",
        "fromTable": "result_customer_month",
        "fromColumn": "CustomerKey",
        "toTable": "tree_customer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "284f34c8-5395-4e33-84c9-8c1c8a08fc5a",
        "fromTable": "rank_customer_month",
        "fromColumn": "CustomerKey",
        "toTable": "tree_customer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "3e4aa519-6a73-4e24-8f8c-536953b0eba1",
        "fromTable": "target_customer_month",
        "fromColumn": "CustomerKey",
        "toTable": "tree_customer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "2fc0ab6e-dcb3-415d-a4ef-0e9ab69c82e8",
        "fromTable": "target_supply_month",
        "fromColumn": "SupplyKey",
        "toTable": "tree_supply",
        "toColumn": "SupplyKey"
      },
      {
        "name": "44d8a757-7b53-406e-b317-4f09c49cfdc0",
        "fromTable": "result_supply_month",
        "fromColumn": "SupplyKey",
        "toTable": "tree_supply",
        "toColumn": "SupplyKey"
      },
      {
        "name": "329e2976-b6dd-46e2-b730-7336996743b3",
        "fromTable": "result_org_month",
        "fromColumn": "OrgKey",
        "toTable": "tree_org",
        "toColumn": "OrgKey"
      },
      {
        "name": "e0009fd0-1245-406a-9fec-08301fb7a964",
        "fromTable": "target_org_month",
        "fromColumn": "OrgKey",
        "toTable": "tree_org",
        "toColumn": "OrgKey"
      },
      {
        "name": "665e6e18-6b0f-4b9c-bc5e-c266246aec9e",
        "fromTable": "result_finance_month",
        "fromColumn": "OrgKey",
        "toTable": "tree_org",
        "toColumn": "OrgKey"
      },
      {
        "name": "25b4350e-3c33-4533-b200-96034f256345",
        "fromTable": "target_finance_month",
        "fromColumn": "OrgKey",
        "toTable": "tree_org",
        "toColumn": "OrgKey"
      },
      {
        "name": "14497af4-a2b4-4586-8c1d-24d03c8f9e4d",
        "fromTable": "lxxl_strategy_log",
        "fromColumn": "StrategyKey",
        "toTable": "lxxl_strategy",
        "toColumn": "StrategyKey"
      },
      {
        "name": "dd59d435-4b0d-4add-a25f-ba3b3895546d",
        "fromTable": "lxxl_strategy_log",
        "fromColumn": "MonthKey",
        "toTable": "V_DimMonth",
        "toColumn": "MonthKey"
      },
      {
        "name": "fe279071-45b5-41b2-8dff-aa30593ec8ed",
        "fromTable": "rank_product_day",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "1d702360-ff41-4aa9-8d40-f13ef2296de8",
        "fromTable": "rank_product_day",
        "fromColumn": "ProductKey",
        "toTable": "tree_product",
        "toColumn": "ProductKey"
      },
      {
        "name": "8bf1736b-94fb-4304-9ee6-f03379569f02",
        "fromTable": "rank_product_month",
        "fromColumn": "MonthKey",
        "toTable": "V_DimMonth",
        "toColumn": "MonthKey"
      },
      {
        "name": "3ac84a71-c65a-4644-bdea-3d384d50b591",
        "fromTable": "rank_product_month",
        "fromColumn": "ProductKey",
        "toTable": "DimProduct",
        "toColumn": "ProductKey"
      },
      {
        "name": "28368deb-cc02-46f6-9271-236b4207e5e8",
        "fromTable": "rank_channel_day",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "6656c191-6e13-42bd-a8c0-28b060c07cae",
        "fromTable": "rank_channel_day",
        "fromColumn": "ChannelKey",
        "toTable": "tree_channel",
        "toColumn": "ChannelKey"
      },
      {
        "name": "2f4afcf2-6fd4-4139-a918-53a9ed87735c",
        "fromTable": "rank_channel_month",
        "fromColumn": "ChannelKey",
        "toTable": "tree_channel",
        "toColumn": "ChannelKey"
      },
      {
        "name": "6ce752e6-6a45-49fb-af2f-feb75ae13db7",
        "fromTable": "rank_channel_month",
        "fromColumn": "MonthKey",
        "toTable": "V_DimMonth",
        "toColumn": "MonthKey"
      },
      {
        "name": "b6a91fce-d247-4fbb-878f-00275f786a08",
        "fromTable": "rank_customer_day",
        "fromColumn": "CustomerKey",
        "toTable": "tree_customer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "cef09496-bd0b-40dd-a074-5fdcc8baafb6",
        "fromTable": "rank_customer_day",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "0368cd5f-d9bc-4706-921e-55c4cc39bde8",
        "fromTable": "rank_customer_month",
        "fromColumn": "MonthKey",
        "toTable": "V_DimMonth",
        "toColumn": "MonthKey"
      },
      {
        "name": "3b8a92b6-0860-4b61-a6a6-816f340b31a0",
        "fromTable": "rank_org_month",
        "fromColumn": "MonthKey",
        "toTable": "V_DimMonth",
        "toColumn": "MonthKey"
      },
      {
        "name": "61b32b59-dfc9-4d5d-9212-b18f1a0e334c",
        "fromTable": "rank_org_month",
        "fromColumn": "OrgKey",
        "toTable": "tree_org",
        "toColumn": "OrgKey"
      },
      {
        "name": "3bacb556-d657-4aa4-89dc-0fe94ad4d537",
        "fromTable": "rank_supply_month",
        "fromColumn": "MonthKey",
        "toTable": "V_DimMonth",
        "toColumn": "MonthKey"
      },
      {
        "name": "3e5771b4-d080-4a78-8c58-9cecd46a88f2",
        "fromTable": "rank_supply_month",
        "fromColumn": "SupplyKey",
        "toTable": "tree_supply",
        "toColumn": "SupplyKey"
      },
      {
        "name": "03fc825e-868a-49cd-9be0-558489f16aad",
        "fromTable": "rank_finance_month",
        "fromColumn": "MonthKey",
        "toTable": "V_DimMonth",
        "toColumn": "MonthKey"
      },
      {
        "name": "a66d301e-e1ae-4951-950d-bca776432292",
        "fromTable": "rank_finance_month",
        "fromColumn": "OrgKey",
        "toTable": "tree_org",
        "toColumn": "OrgKey"
      },
      {
        "name": "7906e940-cf3a-45b4-a492-ced93a0370fa",
        "fromTable": "result_org_month",
        "fromColumn": "OrgKey",
        "toTable": "DimOrg",
        "toColumn": "OrgKey"
      },
      {
        "name": "826b64d0-399c-4e29-aa06-f3dc54d23db5",
        "fromTable": "rank_product_month",
        "fromColumn": "ProductKey",
        "toTable": "tree_product",
        "toColumn": "ProductKey"
      },
      {
        "name": "15dcb656-bd73-4fa2-8e39-0dfb79f5226c",
        "fromTable": "result_product_month",
        "fromColumn": "ProductKey",
        "toTable": "dim_product",
        "toColumn": "ProductKey"
      },
      {
        "name": "966f0079-1801-442d-bd23-45c9c3533903",
        "fromTable": "result_product_day",
        "fromColumn": "ProductKey",
        "toTable": "dim_product",
        "toColumn": "ProductKey"
      },
      {
        "name": "7fb58177-762f-48ba-bfd2-be519337ed86",
        "fromTable": "target_product_month",
        "fromColumn": "ProductKey",
        "toTable": "dim_product",
        "toColumn": "ProductKey"
      },
      {
        "name": "8a6f405b-ae22-4e79-8cff-0f6d3c77f46e",
        "fromTable": "target_product_day",
        "fromColumn": "ProductKey",
        "toTable": "dim_product",
        "toColumn": "ProductKey"
      },
      {
        "name": "ee3aa8fe-9e0c-46f7-acf7-501864cf9dab",
        "fromTable": "rank_product_day",
        "fromColumn": "ProductKey",
        "toTable": "dim_product",
        "toColumn": "ProductKey"
      },
      {
        "name": "bec04f14-23cd-4368-a0d1-ba2c652f47a8",
        "fromTable": "rank_product_month",
        "fromColumn": "ProductKey",
        "toTable": "dim_product",
        "toColumn": "ProductKey"
      },
      {
        "name": "6994d77c-e414-4409-9274-5470a09787f2",
        "fromTable": "result_channel_month",
        "fromColumn": "ChannelKey",
        "toTable": "dim_channel",
        "toColumn": "ChannelKey"
      },
      {
        "name": "7f96a3e3-3c37-4a0c-9dc3-432e87d1b874",
        "fromTable": "result_channel_day",
        "fromColumn": "ChannelKey",
        "toTable": "dim_channel",
        "toColumn": "ChannelKey"
      },
      {
        "name": "287b5730-4fdc-43dc-8ab5-c86ca8f7e5f4",
        "fromTable": "target_channel_month",
        "fromColumn": "ChannelKey",
        "toTable": "dim_channel",
        "toColumn": "ChannelKey"
      },
      {
        "name": "2f45e7a5-451a-46c1-9e0d-4efab7ce4628",
        "fromTable": "target_channel_day",
        "fromColumn": "ChannelKey",
        "toTable": "dim_channel",
        "toColumn": "ChannelKey"
      },
      {
        "name": "69401c90-6449-423c-9aad-6ef980fb86be",
        "fromTable": "rank_channel_day",
        "fromColumn": "ChannelKey",
        "toTable": "dim_channel",
        "toColumn": "ChannelKey"
      },
      {
        "name": "2a017b8f-bbfd-4866-b772-860c3e7b1e7f",
        "fromTable": "rank_channel_month",
        "fromColumn": "ChannelKey",
        "toTable": "dim_channel",
        "toColumn": "ChannelKey"
      },
      {
        "name": "700a370b-7772-4434-aa3a-643c109dc1af",
        "fromTable": "result_customer_month",
        "fromColumn": "CustomerKey",
        "toTable": "dim_cus",
        "toColumn": "CustomerKey"
      },
      {
        "name": "184a95c0-e574-4258-8ca2-1e91841f7eb4",
        "fromTable": "result_customer_day",
        "fromColumn": "CustomerKey",
        "toTable": "dim_cus",
        "toColumn": "CustomerKey"
      },
      {
        "name": "76dc132c-2362-4b2a-9f53-9b0dbc7b74d3",
        "fromTable": "target_customer_month",
        "fromColumn": "CustomerKey",
        "toTable": "dim_cus",
        "toColumn": "CustomerKey"
      },
      {
        "name": "028b43a4-4346-42aa-b4e8-2cab52230697",
        "fromTable": "target_customer_day",
        "fromColumn": "CustomerKey",
        "toTable": "dim_cus",
        "toColumn": "CustomerKey"
      },
      {
        "name": "8dbf91ba-240a-471b-8a64-388a49bb83e6",
        "fromTable": "rank_customer_day",
        "fromColumn": "CustomerKey",
        "toTable": "dim_cus",
        "toColumn": "CustomerKey"
      },
      {
        "name": "099e5da2-2b66-4b56-b8cb-16e8273ab1a9",
        "fromTable": "rank_customer_month",
        "fromColumn": "CustomerKey",
        "toTable": "dim_cus",
        "toColumn": "CustomerKey"
      },
      {
        "name": "cb7d1820-0b8e-468c-ac6b-bc66c92362d4",
        "fromTable": "result_supply_month",
        "fromColumn": "SupplyKey",
        "toTable": "dim_supply",
        "toColumn": "SupplyKey"
      },
      {
        "name": "86433b3a-0a48-420d-8466-b17945fd5ee8",
        "fromTable": "target_supply_month",
        "fromColumn": "SupplyKey",
        "toTable": "dim_supply",
        "toColumn": "SupplyKey"
      },
      {
        "name": "fb5d79aa-73e5-4696-a2e6-e65fcf2f4da3",
        "fromTable": "rank_supply_month",
        "fromColumn": "SupplyKey",
        "toTable": "dim_supply",
        "toColumn": "SupplyKey"
      },
      {
        "name": "f6da5284-4489-4397-9840-54adbd660e66",
        "fromTable": "result_org_month",
        "fromColumn": "OrgKey",
        "toTable": "dim_org",
        "toColumn": "OrgKey"
      },
      {
        "name": "72d68eb7-fe1b-4f2a-83fe-e49985ae9c56",
        "fromTable": "target_org_month",
        "fromColumn": "OrgKey",
        "toTable": "dim_org",
        "toColumn": "OrgKey"
      },
      {
        "name": "b1400e6f-c8ff-4b0f-bcb1-281340ab412b",
        "fromTable": "rank_org_month",
        "fromColumn": "OrgKey",
        "toTable": "dim_org",
        "toColumn": "OrgKey"
      },
      {
        "name": "981a80ce-e629-4711-ad07-d131f2055c03",
        "fromTable": "result_finance_month",
        "fromColumn": "OrgKey",
        "toTable": "dim_org",
        "toColumn": "OrgKey"
      },
      {
        "name": "72574cd7-7d89-4310-9f45-d43c00467786",
        "fromTable": "target_finance_month",
        "fromColumn": "OrgKey",
        "toTable": "dim_org",
        "toColumn": "OrgKey"
      },
      {
        "name": "fa1ee102-6172-4ba1-884b-9d3f572122af",
        "fromTable": "rank_finance_month",
        "fromColumn": "OrgKey",
        "toTable": "dim_org",
        "toColumn": "OrgKey"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "500"
      }
    ]
  },
  "id": "SemanticModel"
}