{
  "name": "SemanticModel",
  "compatibilityLevel": 1400,
  "model": {
    "culture": "zh-CN",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/10 8 1 66;test_yueying",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "10.8.1.66",
            "database": "test_yueying"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "kind": "SQL",
          "path": "10.8.1.66;test_yueying",
          "Username": "sa",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "dim_budget",
        "columns": [
          {
            "name": "c1",
            "dataType": "string",
            "sourceColumn": "c1"
          },
          {
            "name": "c2",
            "dataType": "string",
            "sourceColumn": "c2"
          },
          {
            "name": "c3",
            "dataType": "string",
            "sourceColumn": "c3"
          },
          {
            "name": "c1_name",
            "dataType": "string",
            "sourceColumn": "c1_name"
          },
          {
            "name": "c2_name",
            "dataType": "string",
            "sourceColumn": "c2_name"
          },
          {
            "name": "c3_name",
            "dataType": "string",
            "sourceColumn": "c3_name"
          },
          {
            "name": "lxxl_type",
            "dataType": "int64",
            "sourceColumn": "lxxl_type"
          },
          {
            "name": "BudgetKey",
            "dataType": "int64",
            "sourceColumn": "BudgetKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_dim_budget = Source{[Schema=\"dbo\",Item=\"dim_budget\"]}[Data],",
                "    替换的值 = Table.ReplaceValue(dbo_dim_budget,null,\"其他\",Replacer.ReplaceValue,{\"c2_name\"}),",
                "    替换的值1 = Table.ReplaceValue(替换的值,null,\"其他\",Replacer.ReplaceValue,{\"c3_name\"})",
                "in",
                "    替换的值1"
              ]
            }
          }
        ]
      },
      {
        "name": "dim_channel",
        "columns": [
          {
            "name": "c1",
            "dataType": "int64",
            "sourceColumn": "c1"
          },
          {
            "name": "c2",
            "dataType": "int64",
            "sourceColumn": "c2"
          },
          {
            "name": "c3",
            "dataType": "int64",
            "sourceColumn": "c3"
          },
          {
            "name": "c4",
            "dataType": "int64",
            "sourceColumn": "c4"
          },
          {
            "name": "c5",
            "dataType": "int64",
            "sourceColumn": "c5"
          },
          {
            "name": "c1_name",
            "dataType": "string",
            "sourceColumn": "c1_name"
          },
          {
            "name": "c2_name",
            "dataType": "string",
            "sourceColumn": "c2_name"
          },
          {
            "name": "c3_name",
            "dataType": "string",
            "sourceColumn": "c3_name"
          },
          {
            "name": "c4_name",
            "dataType": "string",
            "sourceColumn": "c4_name"
          },
          {
            "name": "c5_name",
            "dataType": "string",
            "sourceColumn": "c5_name"
          },
          {
            "name": "ChannelKey",
            "dataType": "int64",
            "sourceColumn": "ChannelKey"
          },
          {
            "name": "c6",
            "dataType": "int64",
            "sourceColumn": "c6"
          },
          {
            "name": "c6_name",
            "dataType": "string",
            "sourceColumn": "c6_name"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_dim_channel = Source{[Schema=\"dbo\",Item=\"dim_channel\"]}[Data],",
                "    替换的值 = Table.ReplaceValue(dbo_dim_channel,null,\"其他\",Replacer.ReplaceValue,{\"c2_name\"}),",
                "    替换的值1 = Table.ReplaceValue(替换的值,null,\"其他\",Replacer.ReplaceValue,{\"c3_name\"}),",
                "    替换的值2 = Table.ReplaceValue(替换的值1,null,\"其他\",Replacer.ReplaceValue,{\"c4_name\"}),",
                "    替换的值3 = Table.ReplaceValue(替换的值2,null,\"其他\",Replacer.ReplaceValue,{\"c5_name\"}),",
                "    替换的值4 = Table.ReplaceValue(替换的值3,null,\"其他\",Replacer.ReplaceValue,{\"c6_name\"})",
                "in",
                "    替换的值4"
              ]
            }
          }
        ]
      },
      {
        "name": "dim_cus",
        "columns": [
          {
            "name": "c1",
            "dataType": "int64",
            "sourceColumn": "c1"
          },
          {
            "name": "c2",
            "dataType": "int64",
            "sourceColumn": "c2"
          },
          {
            "name": "c3",
            "dataType": "int64",
            "sourceColumn": "c3"
          },
          {
            "name": "c4",
            "dataType": "int64",
            "sourceColumn": "c4"
          },
          {
            "name": "c5",
            "dataType": "int64",
            "sourceColumn": "c5"
          },
          {
            "name": "c1_name",
            "dataType": "string",
            "sourceColumn": "c1_name"
          },
          {
            "name": "c2_name",
            "dataType": "string",
            "sourceColumn": "c2_name"
          },
          {
            "name": "c3_name",
            "dataType": "string",
            "sourceColumn": "c3_name"
          },
          {
            "name": "c4_name",
            "dataType": "string",
            "sourceColumn": "c4_name"
          },
          {
            "name": "c5_name",
            "dataType": "string",
            "sourceColumn": "c5_name"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "c6",
            "dataType": "int64",
            "sourceColumn": "c6"
          },
          {
            "name": "c6_name",
            "dataType": "string",
            "sourceColumn": "c6_name"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_dim_cus = Source{[Schema=\"dbo\",Item=\"dim_cus\"]}[Data],",
                "    替换的值 = Table.ReplaceValue(dbo_dim_cus,null,\"其他\",Replacer.ReplaceValue,{\"c2_name\"}),",
                "    替换的值1 = Table.ReplaceValue(替换的值,null,\"其他\",Replacer.ReplaceValue,{\"c3_name\"}),",
                "    替换的值2 = Table.ReplaceValue(替换的值1,null,\"其他\",Replacer.ReplaceValue,{\"c4_name\"}),",
                "    替换的值3 = Table.ReplaceValue(替换的值2,null,\"其他\",Replacer.ReplaceValue,{\"c5_name\"}),",
                "    替换的值4 = Table.ReplaceValue(替换的值3,null,\"其他\",Replacer.ReplaceValue,{\"c6_name\"})",
                "in",
                "    替换的值4"
              ]
            }
          }
        ]
      },
      {
        "name": "dim_org",
        "columns": [
          {
            "name": "c1",
            "dataType": "int64",
            "sourceColumn": "c1"
          },
          {
            "name": "c2",
            "dataType": "int64",
            "sourceColumn": "c2"
          },
          {
            "name": "c3",
            "dataType": "int64",
            "sourceColumn": "c3"
          },
          {
            "name": "c4",
            "dataType": "int64",
            "sourceColumn": "c4"
          },
          {
            "name": "c5",
            "dataType": "int64",
            "sourceColumn": "c5"
          },
          {
            "name": "c1_name",
            "dataType": "string",
            "sourceColumn": "c1_name"
          },
          {
            "name": "c2_name",
            "dataType": "string",
            "sourceColumn": "c2_name"
          },
          {
            "name": "c3_name",
            "dataType": "string",
            "sourceColumn": "c3_name"
          },
          {
            "name": "c4_name",
            "dataType": "string",
            "sourceColumn": "c4_name"
          },
          {
            "name": "c5_name",
            "dataType": "string",
            "sourceColumn": "c5_name"
          },
          {
            "name": "type",
            "dataType": "int64",
            "sourceColumn": "type"
          },
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "c6",
            "dataType": "int64",
            "sourceColumn": "c6"
          },
          {
            "name": "c6_name",
            "dataType": "string",
            "sourceColumn": "c6_name"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_dim_org = Source{[Schema=\"dbo\",Item=\"dim_org\"]}[Data],",
                "    替换的值 = Table.ReplaceValue(dbo_dim_org,null,\"其他\",Replacer.ReplaceValue,{\"c2_name\"}),",
                "    替换的值1 = Table.ReplaceValue(替换的值,null,\"其他\",Replacer.ReplaceValue,{\"c3_name\"}),",
                "    替换的值2 = Table.ReplaceValue(替换的值1,null,\"其他\",Replacer.ReplaceValue,{\"c4_name\"}),",
                "    替换的值3 = Table.ReplaceValue(替换的值2,null,\"其他\",Replacer.ReplaceValue,{\"c5_name\"}),",
                "    替换的值4 = Table.ReplaceValue(替换的值3,null,\"其他\",Replacer.ReplaceValue,{\"c6_name\"})",
                "in",
                "    替换的值4"
              ]
            }
          }
        ]
      },
      {
        "name": "dim_product",
        "columns": [
          {
            "name": "c1",
            "dataType": "int64",
            "sourceColumn": "c1"
          },
          {
            "name": "c2",
            "dataType": "int64",
            "sourceColumn": "c2"
          },
          {
            "name": "c3",
            "dataType": "int64",
            "sourceColumn": "c3"
          },
          {
            "name": "c4",
            "dataType": "int64",
            "sourceColumn": "c4"
          },
          {
            "name": "c5",
            "dataType": "int64",
            "sourceColumn": "c5"
          },
          {
            "name": "c6",
            "dataType": "int64",
            "sourceColumn": "c6"
          },
          {
            "name": "c1_name",
            "dataType": "string",
            "sourceColumn": "c1_name"
          },
          {
            "name": "c2_name",
            "dataType": "string",
            "sourceColumn": "c2_name"
          },
          {
            "name": "c3_name",
            "dataType": "string",
            "sourceColumn": "c3_name"
          },
          {
            "name": "c4_name",
            "dataType": "string",
            "sourceColumn": "c4_name"
          },
          {
            "name": "c5_name",
            "dataType": "string",
            "sourceColumn": "c5_name"
          },
          {
            "name": "c6_name",
            "dataType": "string",
            "sourceColumn": "c6_name"
          },
          {
            "name": "avg_unit_cost_amt",
            "dataType": "double",
            "sourceColumn": "avg_unit_cost_amt"
          },
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_dim_product = Source{[Schema=\"dbo\",Item=\"dim_product\"]}[Data],",
                "    替换的值 = Table.ReplaceValue(dbo_dim_product,null,\"其他\",Replacer.ReplaceValue,{\"c2_name\"}),",
                "    替换的值1 = Table.ReplaceValue(替换的值,null,\"其他\",Replacer.ReplaceValue,{\"c3_name\"}),",
                "    替换的值2 = Table.ReplaceValue(替换的值1,null,\"其他\",Replacer.ReplaceValue,{\"c4_name\"}),",
                "    替换的值3 = Table.ReplaceValue(替换的值2,null,\"其他\",Replacer.ReplaceValue,{\"c5_name\"}),",
                "    替换的值4 = Table.ReplaceValue(替换的值3,null,\"其他\",Replacer.ReplaceValue,{\"c6_name\"})",
                "in",
                "    替换的值4"
              ]
            }
          }
        ]
      },
      {
        "name": "dim_supply",
        "columns": [
          {
            "name": "c1",
            "dataType": "int64",
            "sourceColumn": "c1"
          },
          {
            "name": "c2",
            "dataType": "int64",
            "sourceColumn": "c2"
          },
          {
            "name": "c3",
            "dataType": "int64",
            "sourceColumn": "c3"
          },
          {
            "name": "c4",
            "dataType": "int64",
            "sourceColumn": "c4"
          },
          {
            "name": "c5",
            "dataType": "int64",
            "sourceColumn": "c5"
          },
          {
            "name": "c1_name",
            "dataType": "string",
            "sourceColumn": "c1_name"
          },
          {
            "name": "c2_name",
            "dataType": "string",
            "sourceColumn": "c2_name"
          },
          {
            "name": "c3_name",
            "dataType": "string",
            "sourceColumn": "c3_name"
          },
          {
            "name": "c4_name",
            "dataType": "string",
            "sourceColumn": "c4_name"
          },
          {
            "name": "c5_name",
            "dataType": "string",
            "sourceColumn": "c5_name"
          },
          {
            "name": "type",
            "dataType": "int64",
            "sourceColumn": "type"
          },
          {
            "name": "SupplyKey",
            "dataType": "int64",
            "sourceColumn": "SupplyKey"
          },
          {
            "name": "c6",
            "dataType": "int64",
            "sourceColumn": "c6"
          },
          {
            "name": "c6_name",
            "dataType": "string",
            "sourceColumn": "c6_name"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_dim_supply = Source{[Schema=\"dbo\",Item=\"dim_supply\"]}[Data],",
                "    替换的值 = Table.ReplaceValue(dbo_dim_supply,null,\"其他\",Replacer.ReplaceValue,{\"c2_name\"}),",
                "    替换的值1 = Table.ReplaceValue(替换的值,null,\"其他\",Replacer.ReplaceValue,{\"c3_name\"}),",
                "    替换的值2 = Table.ReplaceValue(替换的值1,null,\"其他\",Replacer.ReplaceValue,{\"c4_name\"}),",
                "    替换的值3 = Table.ReplaceValue(替换的值2,null,\"其他\",Replacer.ReplaceValue,{\"c5_name\"}),",
                "    替换的值4 = Table.ReplaceValue(替换的值3,null,\"其他\",Replacer.ReplaceValue,{\"c6_name\"})",
                "in",
                "    替换的值4"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_amount_repaid",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "ChannelKey",
            "dataType": "int64",
            "sourceColumn": "ChannelKey"
          },
          {
            "name": "repaid_amt",
            "dataType": "double",
            "sourceColumn": "repaid_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_amount_repaid = Source{[Schema=\"dbo\",Item=\"fact_amount_repaid\"]}[Data]",
                "in",
                "    dbo_fact_amount_repaid"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_application_fee",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "ChannelKey",
            "dataType": "int64",
            "sourceColumn": "ChannelKey"
          },
          {
            "name": "BudgetKey",
            "dataType": "int64",
            "sourceColumn": "BudgetKey"
          },
          {
            "name": "cost_amt",
            "dataType": "double",
            "sourceColumn": "cost_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_application_fee = Source{[Schema=\"dbo\",Item=\"fact_application_fee\"]}[Data]",
                "in",
                "    dbo_fact_application_fee"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_channel_costs",
        "columns": [
          {
            "name": "ChannelKey",
            "dataType": "int64",
            "sourceColumn": "ChannelKey"
          },
          {
            "name": "BudgetKey",
            "dataType": "int64",
            "sourceColumn": "BudgetKey"
          },
          {
            "name": "cost_amt",
            "dataType": "double",
            "sourceColumn": "cost_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_channel_costs = Source{[Schema=\"dbo\",Item=\"fact_channel_costs\"]}[Data]",
                "in",
                "    dbo_fact_channel_costs"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_company",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "dot_count",
            "dataType": "int64",
            "sourceColumn": "dot_count"
          },
          {
            "name": "dot_amt",
            "dataType": "double",
            "sourceColumn": "dot_amt"
          },
          {
            "name": "fixed_assets_amt",
            "dataType": "double",
            "sourceColumn": "fixed_assets_amt"
          },
          {
            "name": "cash_inflow_amt",
            "dataType": "double",
            "sourceColumn": "cash_inflow_amt"
          },
          {
            "name": "cash_out_amt",
            "dataType": "double",
            "sourceColumn": "cash_out_amt"
          },
          {
            "name": "receivable_amt",
            "dataType": "double",
            "sourceColumn": "receivable_amt"
          },
          {
            "name": "payable_amt",
            "dataType": "double",
            "sourceColumn": "payable_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          },
          {
            "name": "consumer_count",
            "dataType": "int64",
            "sourceColumn": "consumer_count"
          },
          {
            "name": "enterprise_count",
            "dataType": "int64",
            "sourceColumn": "enterprise_count"
          },
          {
            "name": "age",
            "dataType": "double",
            "sourceColumn": "age"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_company = Source{[Schema=\"dbo\",Item=\"fact_company\"]}[Data]",
                "in",
                "    dbo_fact_company"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_external_performance",
        "columns": [
          {
            "name": "SupplyKey",
            "dataType": "int64",
            "sourceColumn": "SupplyKey"
          },
          {
            "name": "capacity_score",
            "dataType": "double",
            "sourceColumn": "capacity_score"
          },
          {
            "name": "quality_score",
            "dataType": "double",
            "sourceColumn": "quality_score"
          },
          {
            "name": "value_for_money_score",
            "dataType": "double",
            "sourceColumn": "value_for_money_score"
          },
          {
            "name": "delivery_score",
            "dataType": "double",
            "sourceColumn": "delivery_score"
          },
          {
            "name": "efficiency_score",
            "dataType": "double",
            "sourceColumn": "efficiency_score"
          },
          {
            "name": "service_score",
            "dataType": "double",
            "sourceColumn": "service_score"
          },
          {
            "name": "finance_score",
            "dataType": "double",
            "sourceColumn": "finance_score"
          },
          {
            "name": "development_score",
            "dataType": "double",
            "sourceColumn": "development_score"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_external_performance = Source{[Schema=\"dbo\",Item=\"fact_external_performance\"]}[Data]",
                "in",
                "    dbo_fact_external_performance"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_fin_costs",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "cash_flow_amt",
            "dataType": "double",
            "sourceColumn": "cash_flow_amt"
          },
          {
            "name": "invest_amt",
            "dataType": "double",
            "sourceColumn": "invest_amt"
          },
          {
            "name": "total_assets_amt",
            "dataType": "double",
            "sourceColumn": "total_assets_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_fin_costs = Source{[Schema=\"dbo\",Item=\"fact_fin_costs\"]}[Data]",
                "in",
                "    dbo_fact_fin_costs"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_internal_plan",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "program_subjects",
            "dataType": "string",
            "sourceColumn": "program_subjects"
          },
          {
            "name": "StageStartDateKey",
            "dataType": "int64",
            "sourceColumn": "StageStartDateKey"
          },
          {
            "name": "StageEndDateKey",
            "dataType": "int64",
            "sourceColumn": "StageEndDateKey"
          },
          {
            "name": "result",
            "dataType": "string",
            "sourceColumn": "result"
          },
          {
            "name": "person",
            "dataType": "string",
            "sourceColumn": "person"
          },
          {
            "name": "FinishDateKey",
            "dataType": "int64",
            "sourceColumn": "FinishDateKey"
          },
          {
            "name": "is_finish",
            "dataType": "int64",
            "sourceColumn": "is_finish"
          },
          {
            "type": "calculated",
            "name": "StageStartDateKey_date",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": " DATE(INT(LEFT([StageStartDateKey],4)),INT(MID([StageStartDateKey],5,2)),INT(RIGHT([StageStartDateKey],2)))"
          },
          {
            "type": "calculated",
            "name": "StageEndDateKey_date",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": " DATE(INT(LEFT([StageEndDateKey],4)),INT(MID([StageEndDateKey],5,2)),INT(RIGHT([StageEndDateKey],2)))"
          },
          {
            "type": "calculated",
            "name": "时间间隔",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": " DATEDIFF('fact_internal_plan'[StageStartDateKey_date],'fact_internal_plan'[StageEndDateKey_date],DAY)"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_internal_plan = Source{[Schema=\"dbo\",Item=\"fact_internal_plan\"]}[Data]",
                "in",
                "    dbo_fact_internal_plan"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "负责人",
            "expression": [
              "",
              "IF (",
              "    HASONEVALUE (fact_internal_plan[OrgKey] ),",
              "    CALCULATE (",
              "        SELECTEDVALUE(fact_internal_plan[person]),",
              "        tree_org[OrgKey] = VALUES (fact_internal_plan[OrgKey])",
              "    ))"
            ]
          },
          {
            "name": "部门完成率",
            "expression": "DIVIDE(SUMX('fact_internal_plan','fact_internal_plan'[is_finish]),COUNT('fact_internal_plan'[is_finish]))",
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ]
      },
      {
        "name": "fact_order",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "ChannelKey",
            "dataType": "int64",
            "sourceColumn": "ChannelKey"
          },
          {
            "name": "OrgProductKey",
            "dataType": "int64",
            "sourceColumn": "OrgProductKey"
          },
          {
            "name": "OrgChannelKey",
            "dataType": "int64",
            "sourceColumn": "OrgChannelKey"
          },
          {
            "name": "qty",
            "dataType": "double",
            "sourceColumn": "qty"
          },
          {
            "name": "order_amt",
            "dataType": "double",
            "sourceColumn": "order_amt"
          },
          {
            "name": "pay_amt",
            "dataType": "double",
            "sourceColumn": "pay_amt"
          },
          {
            "name": "PayDateKey",
            "dataType": "int64",
            "sourceColumn": "PayDateKey"
          },
          {
            "name": "OrgShopKey",
            "dataType": "int64",
            "sourceColumn": "OrgShopKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_order = Source{[Schema=\"dbo\",Item=\"fact_order\"]}[Data]",
                "in",
                "    dbo_fact_order"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_org_costs",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "BudgetKey",
            "dataType": "int64",
            "sourceColumn": "BudgetKey"
          },
          {
            "name": "cost_amt",
            "dataType": "double",
            "sourceColumn": "cost_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_org_costs = Source{[Schema=\"dbo\",Item=\"fact_org_costs\"]}[Data]",
                "in",
                "    dbo_fact_org_costs"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_performance",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "type",
            "dataType": "int64",
            "sourceColumn": "type",
            "formatString": "0"
          },
          {
            "name": "weights",
            "dataType": "double",
            "sourceColumn": "weights"
          },
          {
            "name": "score",
            "dataType": "int64",
            "sourceColumn": "score"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          },
          {
            "name": "lxxl_type",
            "dataType": "int64",
            "sourceColumn": "lxxl_type"
          },
          {
            "name": "指标类型",
            "dataType": "string",
            "sourceColumn": "指标类型"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_performance = Source{[Schema=\"dbo\",Item=\"fact_performance\"]}[Data],",
                "    已添加条件列 = Table.AddColumn(dbo_fact_performance, \"指标类型\", each if [type] = 1 then \"过程\" else if [type] = 2 then \"结果\" else null)",
                "in",
                "    已添加条件列"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "绩效指标类型",
            "expression": "IF(SELECTEDVALUE('fact_performance'[lxxl_type])=1,\"产品\",IF(SELECTEDVALUE('fact_performance'[lxxl_type])=2,\"渠道\",IF(SELECTEDVALUE('fact_performance'[lxxl_type])=3,\"组织\",IF(SELECTEDVALUE('fact_performance'[lxxl_type])=4,\"资金\",IF(SELECTEDVALUE('fact_performance'[lxxl_type])=5,\"客户\",IF(SELECTEDVALUE('fact_performance'[lxxl_type])=6,\"供应链\",IF(SELECTEDVALUE('fact_performance'[lxxl_type])=15,\"十五项经营指标\",\"自定义指标\")))))))"
          },
          {
            "name": "内部绩效得分",
            "expression": [
              "",
              "IF(",
              "   HASONEVALUE(dim_org[c5_name]),",
              "   CALCULATE (",
              "           SELECTEDVALUE('fact_performance'[score]),",
              "            fact_performance[OrgKey] = VALUES (dim_org[c5])",
              "        ),",
              "        IF(",
              "\t   HASONEVALUE(dim_org[c4_name]),",
              "\t   CALCULATE (",
              "\t           SELECTEDVALUE('fact_performance'[score]),",
              "\t            fact_performance[OrgKey] = VALUES (dim_org[c4])",
              "\t        ),",
              "\t        IF(",
              "\t\t   HASONEVALUE(dim_org[c3_name]),",
              "\t\t   CALCULATE (",
              "\t\t           SELECTEDVALUE('fact_performance'[score]),",
              "\t\t            fact_performance[OrgKey] = VALUES (dim_org[c3])",
              "\t\t        )\t",
              "        )))"
            ]
          },
          {
            "name": "内权重得分",
            "expression": [
              "",
              "IF(",
              "   HASONEVALUE(dim_org[c5_name]),",
              "   CALCULATE (",
              "           SELECTEDVALUE('fact_performance'[weights]),",
              "            fact_performance[OrgKey] = VALUES (dim_org[c5])",
              "        ),",
              "        IF(",
              "\t   HASONEVALUE(dim_org[c4_name]),",
              "\t   CALCULATE (",
              "\t           SELECTEDVALUE('fact_performance'[weights]),",
              "\t            fact_performance[OrgKey] = VALUES (dim_org[c4])",
              "\t        ),",
              "\t        IF(",
              "\t\t   HASONEVALUE(dim_org[c3_name]),",
              "\t\t   CALCULATE (",
              "\t\t           SELECTEDVALUE('fact_performance'[weights]),",
              "\t\t            fact_performance[OrgKey] = VALUES (dim_org[c3])",
              "\t\t        )\t",
              "        )))"
            ]
          }
        ]
      },
      {
        "name": "fact_person_costs",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "BudgetKey",
            "dataType": "int64",
            "sourceColumn": "BudgetKey"
          },
          {
            "name": "cost_amt",
            "dataType": "double",
            "sourceColumn": "cost_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_person_costs = Source{[Schema=\"dbo\",Item=\"fact_person_costs\"]}[Data]",
                "in",
                "    dbo_fact_person_costs"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_stock",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "stock_qty",
            "dataType": "double",
            "sourceColumn": "stock_qty"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_stock = Source{[Schema=\"dbo\",Item=\"fact_stock\"]}[Data]",
                "in",
                "    dbo_fact_stock"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_strategy_log",
        "columns": [
          {
            "name": "rank_old",
            "dataType": "int64",
            "sourceColumn": "rank_old"
          },
          {
            "name": "rank_new",
            "dataType": "int64",
            "sourceColumn": "rank_new"
          },
          {
            "name": "value_old",
            "dataType": "double",
            "sourceColumn": "value_old"
          },
          {
            "name": "value_new",
            "dataType": "double",
            "sourceColumn": "value_new"
          },
          {
            "name": "useful",
            "dataType": "int64",
            "sourceColumn": "useful"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          },
          {
            "name": "strategy_id",
            "dataType": "int64",
            "sourceColumn": "strategy_id"
          },
          {
            "name": "LxxlKey",
            "dataType": "int64",
            "sourceColumn": "LxxlKey"
          },
          {
            "name": "score_old",
            "dataType": "double",
            "sourceColumn": "score_old"
          },
          {
            "name": "score_new",
            "dataType": "double",
            "sourceColumn": "score_new"
          },
          {
            "name": "cycle_type",
            "dataType": "int64",
            "sourceColumn": "cycle_type"
          },
          {
            "type": "calculated",
            "name": "环比增长率",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": " DIVIDE(('fact_strategy_log'[value_new]-'fact_strategy_log'[value_old]),'fact_strategy_log'[value_old])"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_strategy_log = Source{[Schema=\"dbo\",Item=\"fact_strategy_log\"]}[Data]",
                "in",
                "    dbo_fact_strategy_log"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "六项_有效次数1",
            "expression": " CALCULATE(COUNTA(fact_strategy_log[useful]),'fact_strategy_log'[useful]=1)"
          }
        ]
      },
      {
        "name": "fact_supply_order",
        "columns": [
          {
            "name": "SupplyKey",
            "dataType": "int64",
            "sourceColumn": "SupplyKey"
          },
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "order_prd_qty",
            "dataType": "double",
            "sourceColumn": "order_prd_qty"
          },
          {
            "name": "type",
            "dataType": "int64",
            "sourceColumn": "type"
          },
          {
            "name": "OrderDateKey",
            "dataType": "int64",
            "sourceColumn": "OrderDateKey"
          },
          {
            "name": "PlanDateKey",
            "dataType": "int64",
            "sourceColumn": "PlanDateKey"
          },
          {
            "name": "unit_cost_amt",
            "dataType": "double",
            "sourceColumn": "unit_cost_amt"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_fact_supply_order = Source{[Schema=\"dbo\",Item=\"fact_supply_order\"]}[Data]",
                "in",
                "    dbo_fact_supply_order"
              ]
            }
          }
        ]
      },
      {
        "name": "target_budget",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "BudgetKey",
            "dataType": "int64",
            "sourceColumn": "BudgetKey"
          },
          {
            "name": "target_cost_amt",
            "dataType": "double",
            "sourceColumn": "target_cost_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_target_budget = Source{[Schema=\"dbo\",Item=\"target_budget\"]}[Data]",
                "in",
                "    dbo_target_budget"
              ]
            }
          }
        ]
      },
      {
        "name": "target_channel",
        "columns": [
          {
            "name": "ChannelKey",
            "dataType": "int64",
            "sourceColumn": "ChannelKey"
          },
          {
            "name": "target_sale_amt",
            "dataType": "double",
            "sourceColumn": "target_sale_amt"
          },
          {
            "name": "target_cost_amt",
            "dataType": "double",
            "sourceColumn": "target_cost_amt"
          },
          {
            "name": "target_profit_amt",
            "dataType": "double",
            "sourceColumn": "target_profit_amt"
          },
          {
            "name": "target_redundancy_amt",
            "dataType": "double",
            "sourceColumn": "target_redundancy_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_target_channel = Source{[Schema=\"dbo\",Item=\"target_channel\"]}[Data]",
                "in",
                "    dbo_target_channel"
              ]
            }
          }
        ]
      },
      {
        "name": "target_company",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "target_dot_count",
            "dataType": "double",
            "sourceColumn": "target_dot_count"
          },
          {
            "name": "target_dot_amt",
            "dataType": "double",
            "sourceColumn": "target_dot_amt"
          },
          {
            "name": "target_fixed_assets_amt",
            "dataType": "double",
            "sourceColumn": "target_fixed_assets_amt"
          },
          {
            "name": "target_cash_inflow_amt",
            "dataType": "double",
            "sourceColumn": "target_cash_inflow_amt"
          },
          {
            "name": "target_cash_out_amt",
            "dataType": "double",
            "sourceColumn": "target_cash_out_amt"
          },
          {
            "name": "target_receivable_amt",
            "dataType": "double",
            "sourceColumn": "target_receivable_amt"
          },
          {
            "name": "target_payable_amt",
            "dataType": "double",
            "sourceColumn": "target_payable_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          },
          {
            "name": "target_age",
            "dataType": "double",
            "sourceColumn": "target_age"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_target_company = Source{[Schema=\"dbo\",Item=\"target_company\"]}[Data]",
                "in",
                "    dbo_target_company"
              ]
            }
          }
        ]
      },
      {
        "name": "target_customer",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "target_sale_amt",
            "dataType": "double",
            "sourceColumn": "target_sale_amt"
          },
          {
            "name": "target_cost_amt",
            "dataType": "double",
            "sourceColumn": "target_cost_amt"
          },
          {
            "name": "target_profit_amt",
            "dataType": "double",
            "sourceColumn": "target_profit_amt"
          },
          {
            "name": "target_redundancy",
            "dataType": "double",
            "sourceColumn": "target_redundancy"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_target_customer = Source{[Schema=\"dbo\",Item=\"target_customer\"]}[Data]",
                "in",
                "    dbo_target_customer"
              ]
            }
          }
        ]
      },
      {
        "name": "target_finance",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "target_sale_amt",
            "dataType": "double",
            "sourceColumn": "target_sale_amt"
          },
          {
            "name": "target_total_cost_amt",
            "dataType": "double",
            "sourceColumn": "target_total_cost_amt"
          },
          {
            "name": "target_return_amt",
            "dataType": "double",
            "sourceColumn": "target_return_amt"
          },
          {
            "name": "target_invest_amt",
            "dataType": "double",
            "sourceColumn": "target_invest_amt"
          },
          {
            "name": "target_total_assets_amt",
            "dataType": "double",
            "sourceColumn": "target_total_assets_amt"
          },
          {
            "name": "target_cash_flow_amt",
            "dataType": "double",
            "sourceColumn": "target_cash_flow_amt"
          },
          {
            "name": "target_redundancy",
            "dataType": "double",
            "sourceColumn": "target_redundancy"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_target_finance = Source{[Schema=\"dbo\",Item=\"target_finance\"]}[Data]",
                "in",
                "    dbo_target_finance"
              ]
            }
          }
        ]
      },
      {
        "name": "target_org",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "target_sale_amt",
            "dataType": "double",
            "sourceColumn": "target_sale_amt"
          },
          {
            "name": "target_cost_amt",
            "dataType": "double",
            "sourceColumn": "target_cost_amt"
          },
          {
            "name": "target_profit_amt",
            "dataType": "double",
            "sourceColumn": "target_profit_amt"
          },
          {
            "name": "target_redundancy",
            "dataType": "double",
            "sourceColumn": "target_redundancy"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_target_org = Source{[Schema=\"dbo\",Item=\"target_org\"]}[Data]",
                "in",
                "    dbo_target_org"
              ]
            }
          }
        ]
      },
      {
        "name": "target_product",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "target_sale_amt",
            "dataType": "double",
            "sourceColumn": "target_sale_amt"
          },
          {
            "name": "target_cost_amt",
            "dataType": "double",
            "sourceColumn": "target_cost_amt"
          },
          {
            "name": "target_stock_amt",
            "dataType": "double",
            "sourceColumn": "target_stock_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_target_product = Source{[Schema=\"dbo\",Item=\"target_product\"]}[Data]",
                "in",
                "    dbo_target_product"
              ]
            }
          }
        ]
      },
      {
        "name": "target_supply",
        "columns": [
          {
            "name": "SupplyKey",
            "dataType": "int64",
            "sourceColumn": "SupplyKey"
          },
          {
            "name": "target_sale_amt",
            "dataType": "double",
            "sourceColumn": "target_sale_amt"
          },
          {
            "name": "target_profit_amt",
            "dataType": "double",
            "sourceColumn": "target_profit_amt"
          },
          {
            "name": "target_production_capacity",
            "dataType": "double",
            "sourceColumn": "target_production_capacity"
          },
          {
            "name": "target_production_ratio",
            "dataType": "double",
            "sourceColumn": "target_production_ratio"
          },
          {
            "name": "target_delivery_rate",
            "dataType": "double",
            "sourceColumn": "target_delivery_rate"
          },
          {
            "name": "target_residual_rate",
            "dataType": "double",
            "sourceColumn": "target_residual_rate"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_target_supply = Source{[Schema=\"dbo\",Item=\"target_supply\"]}[Data]",
                "in",
                "    dbo_target_supply"
              ]
            }
          }
        ]
      },
      {
        "name": "target_supply_order",
        "columns": [
          {
            "name": "SupplyKey",
            "dataType": "int64",
            "sourceColumn": "SupplyKey"
          },
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "target_order_prd_qty",
            "dataType": "double",
            "sourceColumn": "target_order_prd_qty"
          },
          {
            "name": "target_amt",
            "dataType": "double",
            "sourceColumn": "target_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_target_supply_order = Source{[Schema=\"dbo\",Item=\"target_supply_order\"]}[Data]",
                "in",
                "    dbo_target_supply_order"
              ]
            }
          }
        ]
      },
      {
        "name": "度量值_产品效率",
        "columns": [
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列7",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculatedTableColumn",
            "name": "subject_name",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[subject_name]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \"价格\",\"\" ),",
                "    ( \"库存件数\",\"\" ),",
                "     ( \"销售件数\",\"\" ),",
                "      ( \"销售额\",\"\" ),",
                "       ( \"毛利额\",\"\" ),",
                "        ( \"毛利率\",\"\" )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"subject_name\" , [Value1] )"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "产品_销售额目标",
            "expression": [
              "",
              "IF (",
              "    HASONEVALUE ( dim_product[c6_name] ),",
              "    CALCULATE (",
              "        SUM ( target_product[target_sale_amt] ),",
              "        target_product[ProductKey] = VALUES ( dim_product[c6] )",
              "    ),",
              "    IF (",
              "        HASONEVALUE ( dim_product[c5_name] ),",
              "        CALCULATE (",
              "            SUM ( target_product[target_sale_amt] ),",
              "            target_product[ProductKey] = VALUES ( dim_product[c5] )",
              "        ),",
              "        IF (",
              "            HASONEVALUE ( dim_product[c4_name] ),",
              "            CALCULATE (",
              "                SUM ( target_product[target_sale_amt] ),",
              "                target_product[ProductKey] = VALUES ( dim_product[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_product[c3_name] ),",
              "                CALCULATE (",
              "                    SUM ( target_product[target_sale_amt] ),",
              "                    target_product[ProductKey] = VALUES ( dim_product[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE ( dim_product[c2_name] ),",
              "                    CALCULATE (",
              "                        SUM ( target_product[target_sale_amt] ),",
              "                        target_product[ProductKey] = VALUES ( dim_product[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE ( dim_product[c1_name] ),",
              "                        CALCULATE (",
              "                            SUM ( target_product[target_sale_amt] ),",
              "                            target_product[ProductKey] = VALUES ( dim_product[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00"
          },
          {
            "name": "产品_销售额实际",
            "expression": " SUMX('fact_order','fact_order'[pay_amt])",
            "formatString": "0.00"
          },
          {
            "name": "产品_销售额目标达成率",
            "expression": " DIVIDE([产品_销售额实际],[产品_销售额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "产品_销售额目标实际差异",
            "expression": " [产品_销售额实际]-[产品_销售额目标]",
            "formatString": "0.00"
          },
          {
            "name": "产品_销售额实际_去年同期",
            "expression": "CALCULATE([产品_销售额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00"
          },
          {
            "name": "产品_销售额实际_上月同期",
            "expression": "CALCULATE([产品_销售额实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "产品_销售额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([产品_销售额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([产品_销售额实际]-[产品_销售额实际_去年同期]), [产品_销售额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "产品_销售额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([产品_销售额实际]),",
              "   \t 0,",
              "\tDIVIDE(([产品_销售额实际]-[产品_销售额实际_上月同期]),[产品_销售额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "产品_产品成本额目标",
            "expression": [
              "",
              "IF (",
              "    HASONEVALUE ( dim_product[c6_name] ),",
              "    CALCULATE (",
              "        SUM ( target_product[target_cost_amt] ),",
              "        target_product[ProductKey] = VALUES ( dim_product[c6] )",
              "    ),",
              "    IF (",
              "        HASONEVALUE ( dim_product[c5_name] ),",
              "        CALCULATE (",
              "            SUM ( target_product[target_cost_amt] ),",
              "            target_product[ProductKey] = VALUES ( dim_product[c5] )",
              "        ),",
              "        IF (",
              "            HASONEVALUE ( dim_product[c4_name] ),",
              "            CALCULATE (",
              "                SUM ( target_product[target_cost_amt] ),",
              "                target_product[ProductKey] = VALUES ( dim_product[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_product[c3_name] ),",
              "                CALCULATE (",
              "                    SUM ( target_product[target_cost_amt] ),",
              "                    target_product[ProductKey] = VALUES ( dim_product[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE ( dim_product[c2_name] ),",
              "                    CALCULATE (",
              "                        SUM ( target_product[target_cost_amt] ),",
              "                        target_product[ProductKey] = VALUES ( dim_product[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE ( dim_product[c1_name] ),",
              "                        CALCULATE (",
              "                            SUM ( target_product[target_cost_amt] ),",
              "                            target_product[ProductKey] = VALUES ( dim_product[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00"
          },
          {
            "name": "产品_产品成本额实际",
            "expression": " SUMX('fact_order','fact_order'[qty]*RELATED(dim_product[avg_unit_cost_amt]))",
            "formatString": "0.00"
          },
          {
            "name": "产品_产品成本额目标达成率",
            "expression": " DIVIDE([产品_产品成本额实际],[产品_产品成本额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "产品_产品成本额目标实际差异",
            "expression": " [产品_产品成本额实际]-[产品_产品成本额目标]",
            "formatString": "0.00"
          },
          {
            "name": "产品_产品成本额实际_去年同期",
            "expression": "CALCULATE([产品_产品成本额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00"
          },
          {
            "name": "产品_产品成本额实际_上月同期",
            "expression": "CALCULATE([产品_产品成本额实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "产品_产品成本额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([产品_产品成本额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([产品_产品成本额实际]-[产品_产品成本额实际_去年同期]), [产品_产品成本额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "产品_产品成本额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([产品_产品成本额实际]),",
              "   \t 0,",
              "\tDIVIDE(([产品_产品成本额实际]-[产品_产品成本额实际_上月同期]),[产品_产品成本额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "产品_产品投入产出比目标",
            "expression": " DIVIDE([产品_毛利润额目标],[产品_产品成本额目标])",
            "formatString": "0.00"
          },
          {
            "name": "产品_产品投入产出比实际",
            "expression": " DIVIDE([产品_毛利润额实际],[产品_产品成本额实际])",
            "formatString": "0.00"
          },
          {
            "name": "产品_产品投入产出比目标达成率",
            "expression": " DIVIDE([产品_产品投入产出比实际],[产品_产品投入产出比目标])",
            "formatString": "0.00"
          },
          {
            "name": "产品_产品投入产出比目标实际差异",
            "expression": " [产品_产品投入产出比实际]-[产品_产品投入产出比目标]",
            "formatString": "0.00"
          },
          {
            "name": "产品_产品投入产出比实际_去年同期",
            "expression": "CALCULATE([产品_产品投入产出比实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00"
          },
          {
            "name": "产品_产品投入产出比实际_上月同期",
            "expression": "CALCULATE([产品_产品投入产出比实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "产品_产品投入产出比同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([产品_产品投入产出比实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([产品_产品投入产出比实际]-[产品_产品投入产出比实际_去年同期]), [产品_产品投入产出比实际_去年同期])))"
            ],
            "formatString": "0.00"
          },
          {
            "name": "产品_产品投入产出比环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([产品_产品投入产出比实际]),",
              "   \t 0,",
              "\tDIVIDE(([产品_产品投入产出比实际]-[产品_产品投入产出比实际_上月同期]),[产品_产品投入产出比实际_上月同期]))"
            ],
            "formatString": "0.00"
          },
          {
            "name": "产品_库存周转率目标",
            "expression": " DIVIDE([产品_产品成本额目标], DIVIDE(([期初库存额目标]+[期末库存额目标]),2))",
            "formatString": "0.00"
          },
          {
            "name": "产品_库存周转率实际",
            "expression": " DIVIDE([产品_产品成本额实际], DIVIDE(([期初库存额实际]+[期末库存额实际]),2))",
            "formatString": "0.00"
          },
          {
            "name": "产品_库存周转率目标达成率",
            "expression": " DIVIDE([产品_库存周转率实际],[产品_库存周转率目标])",
            "formatString": "0.00"
          },
          {
            "name": "产品_库存周转率目标实际差异",
            "expression": "  [产品_库存周转率实际]-[产品_库存周转率目标]",
            "formatString": "0.00"
          },
          {
            "name": "产品_库存周转率实际_去年同期",
            "expression": "CALCULATE([产品_库存周转率实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00"
          },
          {
            "name": "产品_库存周转率实际_上月同期",
            "expression": "CALCULATE([产品_库存周转率实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "产品_库存周转率同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([产品_库存周转率实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([产品_库存周转率实际]-[产品_库存周转率实际_去年同期]), [产品_库存周转率实际_去年同期])))"
            ],
            "formatString": "0.00"
          },
          {
            "name": "产品_库存周转率环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([产品_库存周转率实际]),",
              "   \t 0,",
              "\tDIVIDE(([产品_库存周转率实际]-[产品_库存周转率实际_上月同期]),[产品_库存周转率实际_上月同期]))"
            ],
            "formatString": "0.00"
          },
          {
            "name": "产品_日销目标",
            "expression": " DIVIDE([产品_销售额目标],'日期_天数'[天数])",
            "formatString": "0.00"
          },
          {
            "name": "产品_日销实际",
            "expression": " DIVIDE([产品_销售额实际],'日期_天数'[天数])",
            "formatString": "0.00"
          },
          {
            "name": "产品_日销目标达成率",
            "expression": "  DIVIDE([产品_日销实际],[产品_日销目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "产品_日销目标实际差异",
            "expression": " [产品_日销实际]-[产品_日销目标]",
            "formatString": "0.00"
          },
          {
            "name": "产品_日销实际_去年同期",
            "expression": "CALCULATE([产品_日销实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00"
          },
          {
            "name": "产品_日销实际_上月同期",
            "expression": "CALCULATE([产品_日销实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "产品_日销同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([产品_日销实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([产品_日销实际]-[产品_日销实际_去年同期]), [产品_日销实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "产品_日销环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([产品_日销实际]),",
              "   \t 0,",
              "\tDIVIDE(([产品_日销实际]-[产品_日销实际_上月同期]),[产品_日销实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "产品_库存额目标",
            "expression": [
              " ",
              "IF (",
              "    HASONEVALUE ( dim_product[c6_name] ),",
              "    CALCULATE (",
              "        SUM ( target_product[target_stock_amt] ),",
              "        target_product[ProductKey] = VALUES ( dim_product[c6] )",
              "    ),",
              "    IF (",
              "        HASONEVALUE ( dim_product[c5_name] ),",
              "        CALCULATE (",
              "            SUM ( target_product[target_stock_amt] ),",
              "            target_product[ProductKey] = VALUES ( dim_product[c5] )",
              "        ),",
              "        IF (",
              "            HASONEVALUE ( dim_product[c4_name] ),",
              "            CALCULATE (",
              "                SUM ( target_product[target_stock_amt] ),",
              "                target_product[ProductKey] = VALUES ( dim_product[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_product[c3_name] ),",
              "                CALCULATE (",
              "                    SUM ( target_product[target_stock_amt] ),",
              "                    target_product[ProductKey] = VALUES ( dim_product[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE ( dim_product[c2_name] ),",
              "                    CALCULATE (",
              "                        SUM ( target_product[target_stock_amt] ),",
              "                        target_product[ProductKey] = VALUES ( dim_product[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE ( dim_product[c1_name] ),",
              "                        CALCULATE (",
              "                            SUM ( target_product[target_stock_amt] ),",
              "                            target_product[ProductKey] = VALUES ( dim_product[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00"
          },
          {
            "name": "产品_库存额实际",
            "expression": " SUMX('fact_stock','fact_stock'[stock_qty]*RELATED('dim_product'[avg_unit_cost_amt]))",
            "formatString": "0.00"
          },
          {
            "name": "产品_库存额目标达成率",
            "expression": " DIVIDE([产品_库存额实际],[产品_库存额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "产品_库存额目标实际差异",
            "expression": " [产品_库存额实际]-[产品_库存额目标]",
            "formatString": "0.00"
          },
          {
            "name": "产品_库存额实际_去年同期",
            "expression": "CALCULATE([产品_库存额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00"
          },
          {
            "name": "产品_库存额实际_上月同期",
            "expression": "CALCULATE([产品_库存额实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "产品_库存额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([产品_库存额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([产品_库存额实际]-[产品_库存额实际_去年同期]), [产品_库存额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "产品_库存额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([产品_库存额实际]),",
              "   \t 0,",
              "\tDIVIDE(([产品_库存额实际]-[产品_库存额实际_上月同期]),[产品_库存额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "期末库存额目标",
            "expression": [
              "",
              "VAR LAST = LASTDATE('DimDate'[FullDate])",
              "RETURN",
              "CALCULATE ([产品_库存额目标], 'DimDate'[FullDate] = LAST)"
            ],
            "formatString": "0.00"
          },
          {
            "name": "期末库存额实际",
            "expression": [
              "",
              "",
              "VAR LAST = LASTDATE('DimDate'[FullDate])",
              "RETURN ",
              "CALCULATE ([产品_库存额实际], 'DimDate'[FullDate] = LAST)"
            ],
            "formatString": "0.00"
          },
          {
            "name": "库存件数目标",
            "expression": "3",
            "formatString": "0"
          },
          {
            "name": "库存件数实际",
            "expression": "SUMX('fact_stock','fact_stock'[stock_qty])",
            "formatString": "0"
          },
          {
            "name": "产品_毛利率",
            "expression": "1-DIVIDE([产品_毛利润额实际],[产品_销售额实际])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "产品平均售价",
            "expression": "DIVIDE('度量值_产品效率'[产品_销售额实际],[销售件数])",
            "formatString": "0.00"
          },
          {
            "name": "供应_下单件数",
            "expression": "SUMX('fact_supply_order','fact_supply_order'[order_prd_qty])",
            "formatString": "0"
          },
          {
            "name": "test_销售额目标",
            "expression": [
              "",
              "IF (",
              "    HASONEVALUE ( dim_product[c6_name] ),",
              "    CALCULATE (",
              "        SUM ( target_product[target_sale_amt] ),",
              "        target_product[ProductKey] = VALUES ( dim_product[c6] )",
              "    ),",
              "    IF (",
              "        HASONEVALUE ( dim_product[c5_name] ),",
              "        CALCULATE (",
              "            SUM ( target_product[target_sale_amt] ),",
              "            target_product[ProductKey] = VALUES ( dim_product[c5] )",
              "        ),",
              "        IF (",
              "            HASONEVALUE ( dim_product[c4_name] ),",
              "            CALCULATE (",
              "                SUM ( target_product[target_sale_amt] ),",
              "                target_product[ProductKey] = VALUES ( dim_product[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_product[c3_name] ),",
              "                CALCULATE (",
              "                    SUM ( target_product[target_sale_amt] ),",
              "                    target_product[ProductKey] = VALUES ( dim_product[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE ( dim_product[c2_name] ),",
              "                    CALCULATE (",
              "                        SUM ( target_product[target_sale_amt] ),",
              "                        target_product[ProductKey] = VALUES ( dim_product[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE ( dim_product[c1_name] ),",
              "                        CALCULATE (",
              "                            SUM ( target_product[target_sale_amt] ),",
              "                            target_product[ProductKey] = VALUES ( dim_product[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00"
          },
          {
            "name": "test_成本额目标",
            "expression": [
              "",
              "IF (",
              "    HASONEVALUE ( dim_product[c6_name] ),",
              "    CALCULATE (",
              "        SUM ( target_product[target_cost_amt] ),",
              "        target_product[ProductKey] = VALUES ( dim_product[c6] )",
              "    ),",
              "    IF (",
              "        HASONEVALUE ( dim_product[c5_name] ),",
              "        CALCULATE (",
              "            SUM ( target_product[target_cost_amt] ),",
              "            target_product[ProductKey] = VALUES ( dim_product[c5] )",
              "        ),",
              "        IF (",
              "            HASONEVALUE ( dim_product[c4_name] ),",
              "            CALCULATE (",
              "                SUM ( target_product[target_cost_amt] ),",
              "                target_product[ProductKey] = VALUES ( dim_product[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_product[c3_name] ),",
              "                CALCULATE (",
              "                    SUM ( target_product[target_cost_amt] ),",
              "                    target_product[ProductKey] = VALUES ( dim_product[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE ( dim_product[c2_name] ),",
              "                    CALCULATE (",
              "                        SUM ( target_product[target_cost_amt] ),",
              "                        target_product[ProductKey] = VALUES ( dim_product[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE ( dim_product[c1_name] ),",
              "                        CALCULATE (",
              "                            SUM ( target_product[target_cost_amt] ),",
              "                            target_product[ProductKey] = VALUES ( dim_product[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00"
          },
          {
            "name": "test_毛利润额目标",
            "expression": "[test_销售额目标]-[test_成本额目标]",
            "formatString": "0.00"
          },
          {
            "name": "test_投入产出",
            "expression": " DIVIDE([test_毛利润额目标],[test_成本额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "产品_毛利润额目标",
            "expression": [
              "[产品_销售额目标]-[产品_产品成本额目标]",
              ""
            ]
          },
          {
            "name": "产品_毛利润额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([产品_毛利润额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([产品_毛利润额实际]-[产品_毛利润额实际_去年同期]), [产品_毛利润额实际_去年同期])))"
            ]
          },
          {
            "name": "产品_毛利润额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([产品_毛利润额实际]),",
              "   \t 0,",
              "\tDIVIDE(([产品_毛利润额实际]-[产品_毛利润额实际_上月同期]),[产品_毛利润额实际_上月同期]))"
            ]
          },
          {
            "name": "期初库存额目标",
            "expression": [
              "",
              "VAR FIRST = FIRSTDATE('DimDate'[FullDate])",
              "RETURN",
              "CALCULATE ([产品_库存额目标], 'DimDate'[FullDate] = FIRST)"
            ]
          },
          {
            "name": "期初库存额实际",
            "expression": [
              "",
              "VAR FIRST = FIRSTDATE('DimDate'[FullDate])",
              "RETURN",
              "CALCULATE ([产品_库存额实际], 'DimDate'[FullDate] = FIRST)"
            ]
          },
          {
            "name": "产品_毛利润额实际",
            "expression": "[产品_销售额实际]-[产品_产品成本额实际]"
          },
          {
            "name": "产品_毛利润额目标达成率",
            "expression": "DIVIDE([产品_毛利润额实际],[产品_毛利润额目标])"
          },
          {
            "name": "产品_毛利润额实际_上月同期",
            "expression": "CALCULATE([产品_毛利润额实际], DATEADD('DimDate'[FullDate], -1, MONTH))"
          },
          {
            "name": "产品_毛利润额目标实际差异",
            "expression": "  [产品_毛利润额实际]-[产品_毛利润额目标]"
          },
          {
            "name": "产品_毛利润额实际_去年同期",
            "expression": "CALCULATE([产品_毛利润额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))"
          }
        ]
      },
      {
        "name": "DimDate",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "FullDate",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "FullDate"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          },
          {
            "name": "DateNameEn",
            "dataType": "string",
            "sourceColumn": "DateNameEn"
          },
          {
            "name": "DateNameCn",
            "dataType": "string",
            "sourceColumn": "DateNameCn"
          },
          {
            "name": "WeekKey",
            "dataType": "int64",
            "sourceColumn": "WeekKey"
          },
          {
            "name": "WeekNameEn",
            "dataType": "string",
            "sourceColumn": "WeekNameEn"
          },
          {
            "name": "WeekNameEnShort",
            "dataType": "string",
            "sourceColumn": "WeekNameEnShort"
          },
          {
            "name": "WeekNameCn",
            "dataType": "string",
            "sourceColumn": "WeekNameCn"
          },
          {
            "name": "WeekNameCnShort",
            "dataType": "string",
            "sourceColumn": "WeekNameCnShort"
          },
          {
            "name": "WeekOfYear",
            "dataType": "int64",
            "sourceColumn": "WeekOfYear"
          },
          {
            "name": "WeekDayNameEn",
            "dataType": "string",
            "sourceColumn": "WeekDayNameEn"
          },
          {
            "name": "WeekDayNameEnShort",
            "dataType": "string",
            "sourceColumn": "WeekDayNameEnShort"
          },
          {
            "name": "WeekDayNameCn",
            "dataType": "string",
            "sourceColumn": "WeekDayNameCn"
          },
          {
            "name": "WeekDayNameCnShort",
            "dataType": "string",
            "sourceColumn": "WeekDayNameCnShort"
          },
          {
            "name": "MonthKey",
            "dataType": "int64",
            "sourceColumn": "MonthKey"
          },
          {
            "name": "MonthOfYear",
            "dataType": "int64",
            "sourceColumn": "MonthOfYear"
          },
          {
            "name": "MonthNameEn",
            "dataType": "string",
            "sourceColumn": "MonthNameEn"
          },
          {
            "name": "MonthNameEnShort",
            "dataType": "string",
            "sourceColumn": "MonthNameEnShort"
          },
          {
            "name": "MonthNameCn",
            "dataType": "string",
            "sourceColumn": "MonthNameCn"
          },
          {
            "name": "MonthNameCnShort",
            "dataType": "string",
            "sourceColumn": "MonthNameCnShort"
          },
          {
            "name": "QuarterKey",
            "dataType": "int64",
            "sourceColumn": "QuarterKey"
          },
          {
            "name": "QuarterOfYear",
            "dataType": "int64",
            "sourceColumn": "QuarterOfYear"
          },
          {
            "name": "QuarterNameEn",
            "dataType": "string",
            "sourceColumn": "QuarterNameEn"
          },
          {
            "name": "QuarterNameEnShort",
            "dataType": "string",
            "sourceColumn": "QuarterNameEnShort"
          },
          {
            "name": "QuarterNameCn",
            "dataType": "string",
            "sourceColumn": "QuarterNameCn"
          },
          {
            "name": "QuarterNameCnShort",
            "dataType": "string",
            "sourceColumn": "QuarterNameCnShort"
          },
          {
            "name": "YearKey",
            "dataType": "int64",
            "sourceColumn": "YearKey"
          },
          {
            "name": "YearNameEn",
            "dataType": "string",
            "sourceColumn": "YearNameEn"
          },
          {
            "name": "YearNameCn",
            "dataType": "string",
            "sourceColumn": "YearNameCn"
          },
          {
            "name": "DayOfWeek",
            "dataType": "int64",
            "sourceColumn": "DayOfWeek"
          },
          {
            "name": "DayOfMonth",
            "dataType": "int64",
            "sourceColumn": "DayOfMonth"
          },
          {
            "name": "DayOfQuarter",
            "dataType": "int64",
            "sourceColumn": "DayOfQuarter"
          },
          {
            "name": "DayOfYear",
            "dataType": "int64",
            "sourceColumn": "DayOfYear"
          },
          {
            "name": "InsertDatetime",
            "dataType": "dateTime",
            "sourceColumn": "InsertDatetime"
          },
          {
            "name": "UpdateDatetime",
            "dataType": "dateTime",
            "sourceColumn": "UpdateDatetime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_DimDate = Source{[Schema=\"dbo\",Item=\"DimDate\"]}[Data]",
                "in",
                "    dbo_DimDate"
              ]
            }
          }
        ]
      },
      {
        "name": "雷达_产品效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \"毛利润额\",\"\" ),",
                "    ( \"销售额\"  ,\"\" ),",
                "     ( \"产品成本额(2-目标达成率)\" ,\"\" ),",
                "      ( \"产品投入产出比\" ,\"\" ),",
                "       ( \"库存周转率\" ,\"\" ),",
                "        ( \"日销\" ,\"\" ),",
                "         ( \"库存额(2-目标达成率)\"  ,\"\")",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] )"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "产品目标达成率_雷达",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('雷达_产品效率'[指标])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"产品成本额(2-目标达成率)\",IF([产品_产品成本额目标达成率]>2,0,2-[产品_产品成本额目标达成率]),",
              " \"毛利润额\",IF([产品_毛利润额目标达成率]>1.5,1.5,IF([产品_毛利润额目标达成率]<=0,0,[产品_毛利润额目标达成率])),",
              " \"销售额\",IF([产品_销售额目标达成率]<1.5,[产品_销售额目标达成率],1.5),",
              " \"产品投入产出比\",IF([产品_产品投入产出比目标达成率]>1.5,1.5,IF([产品_产品投入产出比目标达成率]<0,0,[产品_产品投入产出比目标达成率])),",
              " \"日销\",IF([产品_日销目标达成率]<1.5,[产品_日销目标达成率],1.5),",
              " \"库存周转率\",IF([产品_库存周转率目标达成率]<1.5,[产品_库存周转率目标达成率],1.5),",
              " \"库存额(2-目标达成率)\",IF([产品_库存额目标达成率]>2,0,2-[产品_库存额目标达成率])",
              " )"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ]
      },
      {
        "name": "度量值_渠道效率",
        "columns": [
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculatedTableColumn",
            "name": "subject_name",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[subject_name]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \"价格\",\"\" ),",
                "     ( \"销售件数\",\"\" ),",
                "      ( \"销售额\",\"\" ),",
                "       ( \"毛利额\",\"\" ),",
                "        ( \"毛利率\",\"\" )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"subject_name\" , [Value1] )"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "渠道_渠道营业利润额目标",
            "expression": [
              " ",
              "        IF (",
              "            HASONEVALUE (dim_channel[c4_name] ),",
              "            CALCULATE (",
              "                SUM ( target_channel[target_profit_amt]),",
              "               target_channel[ChannelKey] = VALUES (dim_channel[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE (dim_channel[c3_name]),",
              "                CALCULATE (",
              "                    SUM ( target_channel[target_profit_amt]),",
              "                   target_channel[ChannelKey] = VALUES (dim_channel[c3])",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_channel[c2_name]),",
              "                    CALCULATE (",
              "                        SUM ( target_channel[target_profit_amt]),",
              "                       target_channel[ChannelKey] = VALUES (dim_channel[c2])",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_channel[c1_name]),",
              "                        CALCULATE (",
              "                            SUM ( target_channel[target_profit_amt]),",
              "                            target_channel[ChannelKey] = VALUES (dim_channel[c1])",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    ",
              "    ",
              "   "
            ]
          },
          {
            "name": "渠道_渠道营业利润额实际",
            "expression": " [渠道_销售额实际]-[渠道_渠道费用额实际]-[产品_产品成本额实际]",
            "formatString": "0.00"
          },
          {
            "name": "渠道_渠道营业利润额目标达成率",
            "expression": " DIVIDE([渠道_渠道营业利润额实际],[渠道_渠道营业利润额目标])",
            "formatString": "0.00"
          },
          {
            "name": "渠道_渠道营业利润额目标实际差异",
            "expression": " [渠道_渠道营业利润额实际]-[渠道_渠道营业利润额目标]",
            "formatString": "0.00"
          },
          {
            "name": "渠道_渠道营业利润额实际_去年同期",
            "expression": "CALCULATE([渠道_渠道营业利润额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00"
          },
          {
            "name": "渠道_渠道营业利润额实际_上月同期",
            "expression": "CALCULATE([渠道_渠道营业利润额实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "渠道_渠道营业利润额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([渠道_渠道营业利润额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([渠道_渠道营业利润额实际]-[渠道_渠道营业利润额实际_去年同期]), [渠道_渠道营业利润额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "渠道_渠道营业利润额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([渠道_渠道营业利润额实际]),",
              "   \t 0,",
              "\tDIVIDE(([渠道_渠道营业利润额实际]-[渠道_渠道营业利润额实际_上月同期]),[渠道_渠道营业利润额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "渠道_销售额目标",
            "expression": [
              "",
              "        IF (",
              "            HASONEVALUE (dim_channel[c4_name] ),",
              "            CALCULATE (",
              "                SUM ( target_channel[target_sale_amt]),",
              "               target_channel[ChannelKey] = VALUES (dim_channel[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE (dim_channel[c3_name]),",
              "                CALCULATE (",
              "                    SUM ( target_channel[target_sale_amt] ),",
              "                   target_channel[ChannelKey] = VALUES (dim_channel[c3])",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_channel[c2_name]),",
              "                    CALCULATE (",
              "                        SUM ( target_channel[target_sale_amt]),",
              "                       target_channel[ChannelKey] = VALUES (dim_channel[c2])",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_channel[c1_name]),",
              "                        CALCULATE (",
              "                            SUM ( target_channel[target_sale_amt]),",
              "                            target_channel[ChannelKey] = VALUES (dim_channel[c1])",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "渠道_销售额实际",
            "expression": " SUMX('fact_order','fact_order'[pay_amt])",
            "formatString": "0.00"
          },
          {
            "name": "渠道_销售额目标达成率",
            "expression": " DIVIDE([渠道_销售额实际],[渠道_销售额目标])",
            "formatString": "0.00"
          },
          {
            "name": "渠道_销售额目标实际差异",
            "expression": "  [渠道_销售额实际]-[渠道_销售额目标]",
            "formatString": "0.00"
          },
          {
            "name": "渠道_销售额实际_去年同期",
            "expression": "CALCULATE([渠道_销售额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00"
          },
          {
            "name": "渠道_销售额实际_上月同期",
            "expression": "CALCULATE([渠道_销售额实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "渠道_销售额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([渠道_销售额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([渠道_销售额实际]-[渠道_销售额实际_去年同期]), [渠道_销售额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "渠道_销售额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([渠道_销售额实际]),",
              "   \t 0,",
              "\tDIVIDE(([渠道_销售额实际]-[渠道_销售额实际_上月同期]),[渠道_销售额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "渠道_渠道费用额目标",
            "expression": [
              "",
              "        IF (",
              "            HASONEVALUE (dim_channel[c4_name] ),",
              "            CALCULATE (",
              "                SUM ( target_channel[target_cost_amt]),",
              "               target_channel[ChannelKey] = VALUES (dim_channel[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE (dim_channel[c3_name]),",
              "                CALCULATE (",
              "                    SUM ( target_channel[target_cost_amt] ),",
              "                   target_channel[ChannelKey] = VALUES (dim_channel[c3])",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_channel[c2_name]),",
              "                    CALCULATE (",
              "                        SUM ( target_channel[target_cost_amt]),",
              "                       target_channel[ChannelKey] = VALUES (dim_channel[c2])",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_channel[c1_name]),",
              "                        CALCULATE (",
              "                            SUM ( target_channel[target_cost_amt]),",
              "                            target_channel[ChannelKey] = VALUES (dim_channel[c1])",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    ",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "渠道_渠道费用额实际",
            "expression": "  SUMX('fact_channel_costs','fact_channel_costs'[cost_amt])",
            "formatString": "0.00"
          },
          {
            "name": "渠道_渠道费用额目标达成率",
            "expression": " DIVIDE([渠道_渠道费用额实际],[渠道_渠道费用额目标])",
            "formatString": "0.00"
          },
          {
            "name": "渠道_渠道费用额目标实际差异",
            "expression": " [渠道_渠道费用额实际]-[渠道_渠道费用额目标]",
            "formatString": "0.00"
          },
          {
            "name": "渠道_渠道费用额实际_去年同期",
            "expression": "CALCULATE([渠道_渠道费用额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00"
          },
          {
            "name": "渠道_渠道费用额实际_上月同期",
            "expression": "CALCULATE([渠道_渠道费用额实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "渠道_渠道费用额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([渠道_渠道费用额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([渠道_渠道费用额实际]-[渠道_渠道费用额实际_去年同期]), [渠道_渠道费用额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "渠道_渠道费用额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([渠道_渠道费用额实际]),",
              "   \t 0,",
              "\tDIVIDE(([渠道_渠道费用额实际]-[渠道_渠道费用额实际_上月同期]),[渠道_渠道费用额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "渠道_渠道投入产出比目标",
            "expression": " DIVIDE([渠道_渠道营业利润额目标],[渠道_渠道费用额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "渠道_渠道投入产出比实际",
            "expression": " DIVIDE([渠道_渠道营业利润额实际],[渠道_渠道费用额实际])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "渠道_渠道投入产出比目标达成率",
            "expression": " DIVIDE([渠道_渠道投入产出比实际],[渠道_渠道投入产出比目标])",
            "formatString": "0.00"
          },
          {
            "name": "渠道_渠道投入产出比目标实际差异",
            "expression": " [渠道_渠道投入产出比实际]-[渠道_渠道投入产出比目标]",
            "formatString": "0.00"
          },
          {
            "name": "渠道_渠道投入产出比实际_去年同期",
            "expression": "CALCULATE([渠道_渠道投入产出比实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "渠道_渠道投入产出比实际_上月同期",
            "expression": "CALCULATE([渠道_渠道投入产出比实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "渠道_渠道投入产出比同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([渠道_渠道投入产出比实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([渠道_渠道投入产出比实际]-[渠道_渠道投入产出比实际_去年同期]), [渠道_渠道投入产出比实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "渠道_渠道投入产出比环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([渠道_渠道投入产出比实际]),",
              "   \t 0,",
              "\tDIVIDE(([渠道_渠道投入产出比实际]-[渠道_渠道投入产出比实际_上月同期]),[渠道_渠道投入产出比实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "渠道_渠道冗余值目标",
            "expression": [
              " ",
              "        IF (",
              "            HASONEVALUE (dim_channel[c4_name] ),",
              "            CALCULATE (",
              "                SUM ( target_channel[target_redundancy_amt]),",
              "               target_channel[ChannelKey] = VALUES (dim_channel[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE (dim_channel[c3_name]),",
              "                CALCULATE (",
              "                    SUM ( target_channel[target_redundancy_amt]),",
              "                   target_channel[ChannelKey] = VALUES (dim_channel[c3])",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_channel[c2_name]),",
              "                    CALCULATE (",
              "                        SUM ( target_channel[target_redundancy_amt]),",
              "                       target_channel[ChannelKey] = VALUES (dim_channel[c2])",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_channel[c1_name]),",
              "                        CALCULATE (",
              "                            SUM ( target_channel[target_redundancy_amt]),",
              "                            target_channel[ChannelKey] = VALUES (dim_channel[c1])",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "渠道_渠道冗余值实际",
            "expression": "  IF([渠道_渠道投入产出比实际]>0,0,[渠道_渠道费用额实际])",
            "formatString": "0.00"
          },
          {
            "name": "渠道_渠道冗余值目标达成率",
            "expression": " DIVIDE([渠道_渠道冗余值实际],[渠道_渠道冗余值目标])",
            "formatString": "0.00"
          },
          {
            "name": "渠道_渠道冗余值目标实际差异",
            "expression": "  [渠道_渠道冗余值实际]-[渠道_渠道冗余值目标]",
            "formatString": "0.00"
          },
          {
            "name": "渠道_渠道冗余值实际_去年同期",
            "expression": "CALCULATE([渠道_渠道冗余值实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00"
          },
          {
            "name": "渠道_渠道冗余值实际_上月同期",
            "expression": "CALCULATE([渠道_渠道冗余值实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "渠道_渠道冗余值同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([渠道_渠道冗余值实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([渠道_渠道冗余值实际]-[渠道_渠道冗余值实际_去年同期]), [渠道_渠道冗余值实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "渠道_渠道冗余值环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([渠道_渠道冗余值实际]),",
              "   \t 0,",
              "\tDIVIDE(([渠道_渠道冗余值实际]-[渠道_渠道冗余值实际_上月同期]),[渠道_渠道冗余值实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "渠道_日销目标",
            "expression": " DIVIDE([渠道_销售额目标],'日期_天数'[天数])",
            "formatString": "0.00"
          },
          {
            "name": "渠道_日销实际",
            "expression": " DIVIDE([渠道_销售额实际],'日期_天数'[天数])",
            "formatString": "0.00"
          },
          {
            "name": "渠道_日销目标达成率",
            "expression": " DIVIDE([渠道_日销实际],[渠道_日销目标])",
            "formatString": "0.00"
          },
          {
            "name": "渠道_日销目标实际差异",
            "expression": "  [渠道_日销实际]-[渠道_日销目标]",
            "formatString": "0.00"
          },
          {
            "name": "渠道_日销实际_去年同期",
            "expression": "CALCULATE([渠道_日销实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00"
          },
          {
            "name": "渠道_日销实际_上月同期",
            "expression": "CALCULATE([渠道_日销实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "渠道_日销同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([渠道_日销实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([渠道_日销实际]-[渠道_日销实际_去年同期]), [渠道_日销实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "渠道_日销环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([渠道_日销实际]),",
              "   \t 0,",
              "\tDIVIDE(([渠道_日销实际]-[渠道_日销实际_上月同期]),[渠道_日销实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "渠道平均售价",
            "expression": "DIVIDE('度量值_渠道效率'[渠道_销售额实际],[销售件数])",
            "formatString": "0.00"
          },
          {
            "name": "渠道_毛利率",
            "expression": "1-DIVIDE(SUMX('fact_order','fact_order'[qty]*RELATED(dim_product[avg_unit_cost_amt])),[渠道_销售额实际])",
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ]
      },
      {
        "name": "雷达_渠道效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"渠道营业利润额\" , \"\",) , ",
                "    ( \"销售额\" , \"\", ),",
                "    ( \"渠道费用额(2-目标达成率)\" , \"\", ),",
                "    ( \"渠道投入产出比\" , \"\", ),",
                "    ( \"渠道冗余值\" ,\"\", ),",
                "    ( \"日销\" ,\"\", )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1]  )"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "渠道目标达成率_雷达",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('雷达_渠道效率'[指标])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"渠道营业利润额\",IF( [渠道_渠道营业利润额目标达成率]>1.5,1.5,IF([渠道_渠道营业利润额目标达成率]<=0,0,[渠道_渠道营业利润额目标达成率])),",
              " \"销售额\",IF([渠道_销售额目标达成率]<1.5,[渠道_销售额目标达成率],1.5),",
              " \"渠道费用额(2-目标达成率)\",IF([渠道_渠道费用额目标达成率]>2,0,2-[渠道_渠道费用额目标达成率]),",
              " \"渠道投入产出比\",IF([渠道_渠道投入产出比目标达成率]>1.5,1.5,IF([渠道_渠道投入产出比目标达成率]<=0,0,[渠道_渠道投入产出比目标达成率])),",
              " \"渠道冗余值\",IF([渠道_渠道冗余值目标达成率]>1.5,1.5,IF([渠道_渠道冗余值目标达成率]<=0,0,[渠道_渠道冗余值目标达成率])),",
              " \"日销\",IF([渠道_日销目标达成率]<1.5,[渠道_日销目标达成率],1.5)",
              " )"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ]
      },
      {
        "name": "度量值_客户效率",
        "columns": [
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculatedTableColumn",
            "name": "subject_name",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[subject_name]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "      ( \"销售额\",\"\" ),",
                "       ( \"利润额\",\"\" ),",
                "        ( \"毛利率\",\"\" )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"subject_name\" , [Value1] )"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "客户_客户利润额目标",
            "expression": [
              "",
              "    IF (",
              "        HASONEVALUE ( dim_cus[c5_name] ),",
              "        CALCULATE (",
              "            SUM (target_customer[target_profit_amt]),",
              "            target_customer[CustomerKey] = VALUES (dim_cus[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_cus[c4_name] ),",
              "            CALCULATE (",
              "               SUM (target_customer[target_profit_amt]),",
              "               target_customer[CustomerKey] = VALUES (dim_cus[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_cus[c3_name] ),",
              "                CALCULATE (",
              "                     SUM (target_customer[target_profit_amt]),",
              "                    target_customer[CustomerKey] = VALUES (dim_cus[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_cus[c2_name] ),",
              "                    CALCULATE (",
              "                      SUM (target_customer[target_profit_amt]),",
              "                      target_customer[CustomerKey] = VALUES (dim_cus[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_cus[c1_name] ),",
              "                        CALCULATE (",
              "                            SUM (target_customer[target_profit_amt]),",
              "                           target_customer[CustomerKey] = VALUES ( dim_cus[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "客户_客户利润额实际",
            "expression": [
              "  ",
              "    IF (",
              "        HASONEVALUE ( dim_cus[c5_name] ),",
              "        CALCULATE (",
              "            SUM (result_customer[profit_amt]),",
              "            result_customer[CustomerKey]= VALUES (dim_cus[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_cus[c4_name] ),",
              "            CALCULATE (",
              "                SUM (result_customer[profit_amt]),",
              "                 result_customer[CustomerKey] = VALUES (dim_cus[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_cus[c3_name] ),",
              "                CALCULATE (",
              "                     SUM (result_customer[profit_amt]),",
              "                      result_customer[CustomerKey] = VALUES (dim_cus[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_cus[c2_name] ),",
              "                    CALCULATE (",
              "                       SUM (result_customer[profit_amt]),",
              "                        result_customer[CustomerKey] = VALUES (dim_cus[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_cus[c1_name] ),",
              "                        CALCULATE (",
              "                            SUM (result_customer[profit_amt]),",
              "                             result_customer[CustomerKey] = VALUES ( dim_cus[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "客户_客户利润额目标达成率",
            "expression": " DIVIDE([客户_客户利润额实际],[客户_客户利润额目标])",
            "formatString": "0.00"
          },
          {
            "name": "客户_客户利润额目标实际差异",
            "expression": " [客户_客户利润额实际]-[客户_客户利润额目标]",
            "formatString": "0.00"
          },
          {
            "name": "客户_客户利润额实际_去年同期",
            "expression": "CALCULATE([客户_客户利润额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00"
          },
          {
            "name": "客户_客户利润额实际_上月同期",
            "expression": "CALCULATE([客户_客户利润额实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "客户_客户利润额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([客户_客户利润额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([客户_客户利润额实际]-[客户_客户利润额实际_去年同期]), [客户_客户利润额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "客户_客户利润额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([客户_客户利润额实际]),",
              "   \t 0,",
              "\tDIVIDE(([客户_客户利润额实际]-[客户_客户利润额实际_上月同期]),[客户_客户利润额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "客户_销售额目标",
            "expression": [
              "",
              "    IF (",
              "        HASONEVALUE ( dim_cus[c5_name] ),",
              "        CALCULATE (",
              "            SUM (target_customer[target_sale_amt]),",
              "            target_customer[CustomerKey] = VALUES (dim_cus[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_cus[c4_name] ),",
              "            CALCULATE (",
              "                SUM ( target_customer[target_sale_amt] ),",
              "               target_customer[CustomerKey] = VALUES (dim_cus[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_cus[c3_name] ),",
              "                CALCULATE (",
              "                    SUM ( target_customer[target_sale_amt] ),",
              "                    target_customer[CustomerKey] = VALUES (dim_cus[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_cus[c2_name] ),",
              "                    CALCULATE (",
              "                        SUM ( target_customer[target_sale_amt]),",
              "                      target_customer[CustomerKey] = VALUES (dim_cus[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_cus[c1_name] ),",
              "                        CALCULATE (",
              "                            SUM ( target_customer[target_sale_amt]),",
              "                           target_customer[CustomerKey] = VALUES ( dim_cus[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "客户_销售额实际",
            "expression": [
              " ",
              "    IF (",
              "        HASONEVALUE ( dim_cus[c5_name] ),",
              "        CALCULATE (",
              "            SUM (result_customer[sale_amt]),",
              "            result_customer[CustomerKey]= VALUES (dim_cus[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_cus[c4_name] ),",
              "            CALCULATE (",
              "                SUM (result_customer[sale_amt]),",
              "                 result_customer[CustomerKey] = VALUES (dim_cus[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_cus[c3_name] ),",
              "                CALCULATE (",
              "                    SUM (result_customer[sale_amt]),",
              "                      result_customer[CustomerKey] = VALUES (dim_cus[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_cus[c2_name] ),",
              "                    CALCULATE (",
              "                      SUM (result_customer[sale_amt]),",
              "                        result_customer[CustomerKey] = VALUES (dim_cus[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_cus[c1_name] ),",
              "                        CALCULATE (",
              "                          SUM (result_customer[sale_amt]),",
              "                             result_customer[CustomerKey] = VALUES ( dim_cus[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "客户_销售额目标达成率",
            "expression": " DIVIDE([客户_销售额实际],[客户_销售额目标])",
            "formatString": "0.00"
          },
          {
            "name": "客户_销售额目标实际差异",
            "expression": "  [客户_销售额实际]-[客户_销售额目标]",
            "formatString": "0.00"
          },
          {
            "name": "客户_销售额实际_去年同期",
            "expression": "CALCULATE([客户_销售额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00"
          },
          {
            "name": "客户_销售额实际_上月同期",
            "expression": "CALCULATE([客户_销售额实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "客户_销售额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([客户_销售额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([客户_销售额实际]-[客户_销售额实际_去年同期]), [客户_销售额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "客户_销售额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([客户_销售额实际]),",
              "   \t 0,",
              "\tDIVIDE(([客户_销售额实际]-[客户_销售额实际_上月同期]),[客户_销售额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "客户_客户费用额目标",
            "expression": [
              "",
              "    IF (",
              "        HASONEVALUE ( dim_cus[c5_name] ),",
              "        CALCULATE (",
              "            SUM (target_customer[target_cost_amt]),",
              "            target_customer[CustomerKey] = VALUES (dim_cus[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_cus[c4_name] ),",
              "            CALCULATE (",
              "               SUM (target_customer[target_cost_amt]),",
              "               target_customer[CustomerKey] = VALUES (dim_cus[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_cus[c3_name] ),",
              "                CALCULATE (",
              "                    SUM (target_customer[target_cost_amt]),",
              "                    target_customer[CustomerKey] = VALUES (dim_cus[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_cus[c2_name] ),",
              "                    CALCULATE (",
              "                       SUM (target_customer[target_cost_amt]),",
              "                      target_customer[CustomerKey] = VALUES (dim_cus[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_cus[c1_name] ),",
              "                        CALCULATE (",
              "                            SUM (target_customer[target_cost_amt]),",
              "                           target_customer[CustomerKey] = VALUES ( dim_cus[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "客户_客户费用额实际",
            "expression": [
              "",
              "    IF (",
              "        HASONEVALUE ( dim_cus[c5_name] ),",
              "        CALCULATE (",
              "            SUM (result_customer[cus_cost_amt]),",
              "            result_customer[CustomerKey]= VALUES (dim_cus[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_cus[c4_name] ),",
              "            CALCULATE (",
              "              SUM (result_customer[cus_cost_amt]),",
              "                 result_customer[CustomerKey] = VALUES (dim_cus[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_cus[c3_name] ),",
              "                CALCULATE (",
              "                    SUM (result_customer[cus_cost_amt]),",
              "                      result_customer[CustomerKey] = VALUES (dim_cus[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_cus[c2_name] ),",
              "                    CALCULATE (",
              "                     SUM (result_customer[cus_cost_amt]),",
              "                        result_customer[CustomerKey] = VALUES (dim_cus[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_cus[c1_name] ),",
              "                        CALCULATE (",
              "                         SUM (result_customer[cus_cost_amt]),",
              "                             result_customer[CustomerKey] = VALUES ( dim_cus[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "客户_客户费用额目标达成率",
            "expression": " DIVIDE([客户_客户费用额实际],[客户_客户费用额目标])",
            "formatString": "0.00"
          },
          {
            "name": "客户_客户费用额目标实际差异",
            "expression": " [客户_客户费用额实际]-[客户_客户费用额目标]",
            "formatString": "0.00"
          },
          {
            "name": "客户_客户费用额实际_去年同期",
            "expression": [
              "CALCULATE([客户_客户费用额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
              "",
              ""
            ],
            "formatString": "0.00"
          },
          {
            "name": "客户_客户费用额实际_上月同期",
            "expression": "CALCULATE([客户_客户费用额实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "客户_客户费用额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([客户_客户费用额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([客户_客户费用额实际]-[客户_客户费用额实际_去年同期]), [客户_客户费用额实际_去年同期])))",
              "",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "客户_客户费用额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([客户_客户费用额实际]),",
              "   \t 0,",
              "\tDIVIDE(([客户_客户费用额实际]-[客户_客户费用额实际_上月同期]),[客户_客户费用额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "客户_客户投入产出比目标",
            "expression": "  DIVIDE([客户_客户利润额目标],[客户_客户费用额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "客户_客户投入产出比实际",
            "expression": "  DIVIDE([客户_客户利润额实际],[客户_客户费用额实际])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "客户_客户投入产出比目标达成率",
            "expression": " DIVIDE([客户_客户投入产出比实际],[客户_客户投入产出比目标])",
            "formatString": "0.00"
          },
          {
            "name": "客户_客户投入产出比目标实际差异",
            "expression": " [客户_客户投入产出比实际]-[客户_客户投入产出比目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "客户_客户投入产出比实际_去年同期",
            "expression": "CALCULATE([客户_客户投入产出比实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "客户_客户投入产出比实际_上月同期",
            "expression": "CALCULATE([客户_客户投入产出比实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "客户_客户投入产出比同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([客户_客户投入产出比实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([客户_客户投入产出比实际]-[客户_客户投入产出比实际_去年同期]), [客户_客户投入产出比实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "客户_客户投入产出比环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([客户_客户投入产出比实际]),",
              "   \t 0,",
              "\tDIVIDE(([客户_客户投入产出比实际]-[客户_客户投入产出比实际_上月同期]),[客户_客户投入产出比实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "客户_客户冗余值目标",
            "expression": [
              "",
              "",
              "    IF (",
              "        HASONEVALUE ( dim_cus[c5_name] ),",
              "        CALCULATE (",
              "             SUM (target_customer[target_redundancy]),",
              "            target_customer[CustomerKey] = VALUES (dim_cus[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_cus[c4_name] ),",
              "            CALCULATE (",
              "               SUM (target_customer[target_redundancy]),",
              "               target_customer[CustomerKey] = VALUES (dim_cus[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_cus[c3_name] ),",
              "                CALCULATE (",
              "                   SUM (target_customer[target_redundancy]),",
              "                    target_customer[CustomerKey] = VALUES (dim_cus[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_cus[c2_name] ),",
              "                    CALCULATE (",
              "                       SUM (target_customer[target_redundancy]),",
              "                      target_customer[CustomerKey] = VALUES (dim_cus[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_cus[c1_name] ),",
              "                        CALCULATE (",
              "                           SUM (target_customer[target_redundancy]),",
              "                           target_customer[CustomerKey] = VALUES ( dim_cus[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "客户_客户冗余值实际",
            "expression": [
              "  ",
              "    IF (",
              "        HASONEVALUE ( dim_cus[c5_name] ),",
              "        CALCULATE (",
              "            SUM (result_customer[redundancy]),",
              "            result_customer[CustomerKey]= VALUES (dim_cus[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_cus[c4_name] ),",
              "            CALCULATE (",
              "              SUM (result_customer[redundancy]),",
              "                 result_customer[CustomerKey] = VALUES (dim_cus[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_cus[c3_name] ),",
              "                CALCULATE (",
              "                    SUM (result_customer[redundancy]),",
              "                      result_customer[CustomerKey] = VALUES (dim_cus[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_cus[c2_name] ),",
              "                    CALCULATE (",
              "                     SUM (result_customer[redundancy]),",
              "                        result_customer[CustomerKey] = VALUES (dim_cus[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_cus[c1_name] ),",
              "                        CALCULATE (",
              "                         SUM (result_customer[redundancy]),",
              "                             result_customer[CustomerKey] = VALUES ( dim_cus[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "客户_客户冗余值目标达成率",
            "expression": "  DIVIDE([客户_客户冗余值实际],[客户_客户冗余值目标])",
            "formatString": "0.00"
          },
          {
            "name": "客户_客户冗余值目标实际差异",
            "expression": " [客户_客户冗余值实际]-[客户_客户冗余值目标]",
            "formatString": "0.00"
          },
          {
            "name": "客户_客户冗余值实际_去年同期",
            "expression": "CALCULATE([客户_客户冗余值实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00"
          },
          {
            "name": "客户_客户冗余值实际_上月同期",
            "expression": "CALCULATE([客户_客户冗余值实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "客户_客户冗余值同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([客户_客户冗余值实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([客户_客户冗余值实际]-[客户_客户冗余值实际_去年同期]), [客户_客户冗余值实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "客户_客户冗余值环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([客户_客户冗余值实际]),",
              "   \t 0,",
              "\tDIVIDE(([客户_客户冗余值实际]-[客户_客户冗余值实际_上月同期]),[客户_客户冗余值实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "客户_日销目标",
            "expression": " DIVIDE([客户_销售额目标],'日期_天数'[天数])",
            "formatString": "0.00"
          },
          {
            "name": "客户_日销实际",
            "expression": " DIVIDE([客户_销售额实际],'日期_天数'[天数])",
            "formatString": "0.00"
          },
          {
            "name": "客户_日销目标成率",
            "expression": " DIVIDE([客户_日销实际],[客户_日销目标])",
            "formatString": "0.00"
          },
          {
            "name": "客户_日销目标实际差异",
            "expression": "  [客户_日销实际]-[客户_日销目标]",
            "formatString": "0.00"
          },
          {
            "name": "客户_日销实际_去年同期",
            "expression": [
              "CALCULATE([客户_日销实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
              ""
            ],
            "formatString": "0.00"
          },
          {
            "name": "客户_日销实际_上月同期",
            "expression": "CALCULATE([客户_日销实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "客户_日销同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([客户_日销实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([客户_日销实际]-[客户_日销实际_去年同期]), [客户_日销实际_去年同期])))",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "客户_日销环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([客户_日销实际]),",
              "   \t 0,",
              "\tDIVIDE(([客户_日销实际]-[客户_日销实际_上月同期]),[客户_日销实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "客户_毛利率",
            "expression": "DIVIDE([客户_客户利润额实际],[客户_销售额实际])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "客户_利润额实际",
            "expression": [
              "",
              "    IF (",
              "        HASONEVALUE ( dim_cus[c5_name] ),",
              "        CALCULATE (",
              "            SUM (result_customer[profit_amt]),",
              "            result_customer[CustomerKey]= VALUES (dim_cus[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_cus[c4_name] ),",
              "            CALCULATE (",
              "                SUM (result_customer[profit_amt]),",
              "                 result_customer[CustomerKey] = VALUES (dim_cus[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_cus[c3_name] ),",
              "                CALCULATE (",
              "                     SUM (result_customer[profit_amt]),",
              "                      result_customer[CustomerKey] = VALUES (dim_cus[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_cus[c2_name] ),",
              "                    CALCULATE (",
              "                       SUM (result_customer[profit_amt]),",
              "                        result_customer[CustomerKey] = VALUES (dim_cus[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_cus[c1_name] ),",
              "                        CALCULATE (",
              "                            SUM (result_customer[profit_amt]),",
              "                             result_customer[CustomerKey] = VALUES ( dim_cus[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "   "
            ],
            "formatString": "0.00"
          }
        ]
      },
      {
        "name": "雷达_客户效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"客户利润额\" , \"\", ),",
                "    ( \"销售额\" ,   \"\",) , ",
                "    ( \"客户费用额(2-目标达成率)\" , \"\", ),",
                "    ( \"客户投入产出比\" ,\"\", ),",
                "    ( \"客户冗余值\" ,\"\", ),",
                "    ( \"日销\" , \"\", )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1]  )"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "客户目标达成率_雷达",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('雷达_客户效率'[指标])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              "     \"客户利润额\" , IF([客户_客户利润额目标达成率]>1.5,1.5,IF([客户_客户利润额目标达成率]<0,0,[客户_客户利润额目标达成率])), ",
              "    \"销售额\" ,  IF( [客户_销售额目标达成率]<1.5,[客户_销售额目标达成率],1.5),",
              "    \"客户费用额(2-目标达成率)\" , IF([客户_客户费用额目标达成率]>2,0,2-[客户_客户费用额目标达成率]), ",
              "    \"客户投入产出比\" ,IF([客户_客户投入产出比目标达成率]>1.5,1.5,IF([客户_客户投入产出比目标达成率]<0,0,[客户_客户投入产出比目标达成率])), ",
              "    \"客户冗余值\" ,IF( [客户_客户冗余值目标达成率]>1.5,1.5,IF([客户_客户冗余值目标达成率]<0,0,[客户_客户冗余值目标达成率])), ",
              "    \"日销\" , IF([客户_日销目标成率]>1.5,1.5,IF( [客户_日销目标成率]<0,0,[客户_日销目标成率]))",
              "",
              " )"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ]
      },
      {
        "name": "度量值_供应效率",
        "columns": [
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列7",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculatedTableColumn",
            "name": "subject_name",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[subject_name]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "      ( \"下单件数\",\"\" ),",
                "      ( \"销售额\",\"\" ),",
                "       ( \"毛利额\",\"\" ),",
                "        ( \"毛利率\",\"\" )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"subject_name\" , [Value1] )"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "供应_供应销售额目标",
            "expression": [
              " ",
              "    IF (",
              "        HASONEVALUE ( dim_supply[c5_name]),",
              "        CALCULATE (",
              "            SUM (target_supply[target_sale_amt]),",
              "             target_supply[SupplyKey] = VALUES (dim_supply[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_supply[c4_name]),",
              "            CALCULATE (",
              "                SUM (target_supply[target_sale_amt]),",
              "                target_supply[SupplyKey] = VALUES (dim_supply[c4])",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_supply[c3_name]),",
              "                CALCULATE (",
              "                    SUM (target_supply[target_sale_amt]),",
              "                    target_supply[SupplyKey] = VALUES (dim_supply[c3])",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_supply[c2_name]),",
              "                    CALCULATE (",
              "                       SUM (target_supply[target_sale_amt]),",
              "                      target_supply[SupplyKey] = VALUES (dim_supply[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_supply[c1_name]),",
              "                        CALCULATE (",
              "                            SUM (target_supply[target_sale_amt]),",
              "                            target_supply[SupplyKey] = VALUES ( dim_supply[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "供应_供应销售额实际",
            "expression": [
              "",
              "    IF (",
              "        HASONEVALUE ( dim_supply[c5_name]),",
              "        CALCULATE (",
              "            SUM (result_supply[sale_amt]),",
              "             result_supply[SupplyKey] = VALUES (dim_supply[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_supply[c4_name]),",
              "            CALCULATE (",
              "                SUM (result_supply[sale_amt]),",
              "                 result_supply[SupplyKey]= VALUES (dim_supply[c4])",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_supply[c3_name]),",
              "                CALCULATE (",
              "                    SUM (result_supply[sale_amt]),",
              "                    result_supply[SupplyKey] = VALUES (dim_supply[c3])",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_supply[c2_name]),",
              "                    CALCULATE (",
              "                      SUM (result_supply[sale_amt]),",
              "                       result_supply[SupplyKey] = VALUES (dim_supply[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_supply[c1_name]),",
              "                        CALCULATE (",
              "                            SUM (result_supply[sale_amt]),",
              "                             result_supply[SupplyKey] = VALUES ( dim_supply[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "供应_供应销售额目标达成率",
            "expression": " DIVIDE([供应_供应销售额实际],[供应_供应销售额目标])",
            "formatString": "0.00"
          },
          {
            "name": "供应_供应销售额目标实际差异",
            "expression": " [供应_供应销售额实际]-[供应_供应销售额目标]",
            "formatString": "0.00"
          },
          {
            "name": "供应_供应销售额实际_去年同期",
            "expression": [
              "CALCULATE([供应_供应销售额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
              ""
            ],
            "formatString": "0.00"
          },
          {
            "name": "供应_供应销售额实际_上月同期",
            "expression": "CALCULATE([供应_供应销售额实际],  DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "供应_供应销售额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([供应_供应销售额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([供应_供应销售额实际]-[供应_供应销售额实际_去年同期]), [供应_供应销售额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应_供应销售额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([供应_供应销售额实际]),",
              "   \t 0,",
              "\tDIVIDE(([供应_供应销售额实际]-[供应_供应销售额实际_上月同期]),[供应_供应销售额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应_供应利润额目标",
            "expression": [
              " ",
              "",
              "    IF (",
              "        HASONEVALUE ( dim_supply[c5_name]),",
              "        CALCULATE (",
              "            SUM (target_supply[target_profit_amt]),",
              "             target_supply[SupplyKey] = VALUES (dim_supply[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_supply[c4_name]),",
              "            CALCULATE (",
              "                SUM (target_supply[target_profit_amt]),",
              "                target_supply[SupplyKey] = VALUES (dim_supply[c4])",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_supply[c3_name]),",
              "                CALCULATE (",
              "                    SUM (target_supply[target_profit_amt]),",
              "                    target_supply[SupplyKey] = VALUES (dim_supply[c3])",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_supply[c2_name]),",
              "                    CALCULATE (",
              "                       SUM (target_supply[target_profit_amt]),",
              "                      target_supply[SupplyKey] = VALUES (dim_supply[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_supply[c1_name]),",
              "                        CALCULATE (",
              "                            SUM (target_supply[target_profit_amt]),",
              "                            target_supply[SupplyKey] = VALUES ( dim_supply[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "供应_供应利润额实际",
            "expression": " [供应_供应销售额实际]-[供应下单金额实际]",
            "formatString": "0.00"
          },
          {
            "name": "供应_供应利润额目标达成率",
            "expression": " DIVIDE([供应_供应利润额实际],[供应_供应利润额目标])",
            "formatString": "0.00"
          },
          {
            "name": "供应_供应利润额目标实际差异",
            "expression": " [供应_供应利润额实际]-[供应_供应利润额目标]",
            "formatString": "0.00"
          },
          {
            "name": "供应_供应利润额实际_去年同期",
            "expression": [
              "CALCULATE([供应_供应利润额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
              ""
            ],
            "formatString": "0.00"
          },
          {
            "name": "供应_供应利润额实际_上月同期",
            "expression": "CALCULATE([供应_供应利润额实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "供应_供应利润额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([供应_供应利润额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([供应_供应利润额实际]-[供应_供应利润额实际_去年同期]), [供应_供应利润额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应_供应利润额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([供应_供应利润额实际]),",
              "   \t 0,",
              "\tDIVIDE(([供应_供应利润额实际]-[供应_供应利润额实际_上月同期]),[供应_供应利润额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应_供应产能目标",
            "expression": [
              " ",
              "    IF (",
              "        HASONEVALUE ( dim_supply[c5_name]),",
              "        CALCULATE (",
              "           SUM (target_supply[target_production_capacity]),",
              "             target_supply[SupplyKey] = VALUES (dim_supply[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_supply[c4_name]),",
              "            CALCULATE (",
              "               SUM (target_supply[target_production_capacity]),",
              "                target_supply[SupplyKey] = VALUES (dim_supply[c4])",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_supply[c3_name]),",
              "                CALCULATE (",
              "                   SUM (target_supply[target_production_capacity]),",
              "                    target_supply[SupplyKey] = VALUES (dim_supply[c3])",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_supply[c2_name]),",
              "                    CALCULATE (",
              "                      SUM (target_supply[target_production_capacity]),",
              "                      target_supply[SupplyKey] = VALUES (dim_supply[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_supply[c1_name]),",
              "                        CALCULATE (",
              "                           SUM (target_supply[target_production_capacity]),",
              "                            target_supply[SupplyKey] = VALUES ( dim_supply[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "供应_供应产能实际",
            "expression": "  [计划生产件数]",
            "formatString": "0.00"
          },
          {
            "name": "供应_供应产能目标达成率",
            "expression": " DIVIDE([供应_供应产能实际],[供应_供应产能目标])",
            "formatString": "0.00"
          },
          {
            "name": "供应_供应产能目标实际差异",
            "expression": "  [供应_供应产能实际]-[供应_供应产能目标]",
            "formatString": "0.00"
          },
          {
            "name": "供应_供应产能实际_去年同期",
            "expression": [
              "CALCULATE([供应_供应产能实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
              "",
              ""
            ],
            "formatString": "0.00"
          },
          {
            "name": "供应_供应产能实际_上月同期",
            "expression": "CALCULATE([供应_供应产能实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "供应_供应产能同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([供应_供应产能实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([供应_供应产能实际]-[供应_供应产能实际_去年同期]), [供应_供应产能实际_去年同期])))",
              "",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应_供应产能环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([供应_供应产能实际]),",
              "   \t 0,",
              "\tDIVIDE(([供应_供应产能实际]-[供应_供应产能实际_上月同期]),[供应_供应产能实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应_供应产供比目标",
            "expression": [
              "",
              "    IF (",
              "        HASONEVALUE ( dim_supply[c5_name]),",
              "        CALCULATE (",
              "            SUM (target_supply[target_production_ratio]),",
              "             target_supply[SupplyKey] = VALUES (dim_supply[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_supply[c4_name]),",
              "            CALCULATE (",
              "                SUM (target_supply[target_production_ratio]),",
              "                target_supply[SupplyKey] = VALUES (dim_supply[c4])",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_supply[c3_name]),",
              "                CALCULATE (",
              "                    SUM (target_supply[target_production_ratio]),",
              "                    target_supply[SupplyKey] = VALUES (dim_supply[c3])",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_supply[c2_name]),",
              "                    CALCULATE (",
              "                       SUM (target_supply[target_production_ratio]),",
              "                      target_supply[SupplyKey] = VALUES (dim_supply[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_supply[c1_name]),",
              "                        CALCULATE (",
              "                            SUM (target_supply[target_production_ratio]),",
              "                            target_supply[SupplyKey] = VALUES ( dim_supply[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应_供应产供比实际",
            "expression": " DIVIDE([实际生产件数],[供应_供应产能实际])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应_供应产供比目标达成率",
            "expression": " DIVIDE([供应_供应产供比实际],[供应_供应产供比目标])",
            "formatString": "0.00"
          },
          {
            "name": "供应_供应产供比目标实际差异",
            "expression": "  [供应_供应产供比实际]-[供应_供应产供比目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应_供应产供比实际_去年同期",
            "expression": [
              "CALCULATE([供应_供应产供比实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
              "",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应_供应产供比实际_上月同期",
            "expression": "CALCULATE([供应_供应产供比实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应_供应产供比同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([供应_供应产供比实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([供应_供应产供比实际]-[供应_供应产供比实际_去年同期]), [供应_供应产供比实际_去年同期])))",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应_供应产供比环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([供应_供应产供比实际]),",
              "   \t 0,",
              "\tDIVIDE(([供应_供应产供比实际]-[供应_供应产供比实际_上月同期]),[供应_供应产供比实际_上月同期]))",
              "",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应_供应安全值目标",
            "expression": " [供应_供应产能目标]-[实际生产件数]",
            "formatString": "0.00"
          },
          {
            "name": "供应_供应安全值实际",
            "expression": " [供应_供应产能实际]-[实际生产件数]",
            "formatString": "0.00"
          },
          {
            "name": "供应_供应安全值目标达成率",
            "expression": " DIVIDE([供应_供应安全值实际],[供应_供应安全值目标])",
            "formatString": "0.00"
          },
          {
            "name": "供应_供应安全值目标实际差异",
            "expression": "  [供应_供应安全值实际]-[供应_供应安全值目标]",
            "formatString": "0.00"
          },
          {
            "name": "供应_供应安全值实际_去年同期",
            "expression": [
              "CALCULATE([供应_供应安全值实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
              ""
            ],
            "formatString": "0.00"
          },
          {
            "name": "供应_供应安全值实际_上月同期",
            "expression": "CALCULATE([供应_供应安全值实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "供应_供应安全值同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([供应_供应安全值实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([供应_供应安全值实际]-[供应_供应安全值实际_去年同期]), [供应_供应安全值实际_去年同期])))",
              "",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应_供应安全值环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([供应_供应安全值实际]),",
              "   \t 0,",
              "\tDIVIDE(([供应_供应安全值实际]-[供应_供应安全值实际_上月同期]),[供应_供应安全值实际_上月同期]))",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应_残品率目标",
            "expression": [
              " ",
              "    IF (",
              "        HASONEVALUE ( dim_supply[c5_name]),",
              "        CALCULATE (",
              "            SUM (target_supply[target_residual_rate]),",
              "             target_supply[SupplyKey] = VALUES (dim_supply[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_supply[c4_name]),",
              "            CALCULATE (",
              "                SUM (target_supply[target_residual_rate]),",
              "                target_supply[SupplyKey] = VALUES (dim_supply[c4])",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_supply[c3_name]),",
              "                CALCULATE (",
              "                    SUM (target_supply[target_residual_rate]),",
              "                    target_supply[SupplyKey] = VALUES (dim_supply[c3])",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_supply[c2_name]),",
              "                    CALCULATE (",
              "                       SUM (target_supply[target_residual_rate]),",
              "                      target_supply[SupplyKey] = VALUES (dim_supply[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_supply[c1_name]),",
              "                        CALCULATE (",
              "                            SUM (target_supply[target_residual_rate]),",
              "                            target_supply[SupplyKey] = VALUES ( dim_supply[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应_残品率实际",
            "expression": " DIVIDE([残次品实际],[实际生产件数])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应_残品率目标达成率",
            "expression": "  DIVIDE([供应_残品率实际],[供应_残品率目标])",
            "formatString": "0.00"
          },
          {
            "name": "供应_残品率目标实际差异",
            "expression": " [供应_残品率实际]-[供应_残品率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应_残品率实际_去年同期",
            "expression": [
              "CALCULATE([供应_残品率实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应_残品率实际_上月同期",
            "expression": "CALCULATE([供应_残品率实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应_残品率同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([供应_残品率实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([供应_残品率实际]-[供应_残品率实际_去年同期]), [供应_残品率实际_去年同期])))",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应_残品率环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([供应_残品率实际]),",
              "   \t 0,",
              "\tDIVIDE(([供应_残品率实际]-[供应_残品率实际_上月同期]),[供应_残品率实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应_交期达成率目标",
            "expression": [
              "",
              "    IF (",
              "        HASONEVALUE ( dim_supply[c5_name]),",
              "        CALCULATE (",
              "           DIVIDE( SUM (target_supply[target_delivery_rate]),'日期_天数'[天数]),",
              "             target_supply[SupplyKey] = VALUES (dim_supply[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_supply[c4_name]),",
              "            CALCULATE (",
              "               DIVIDE( SUM (target_supply[target_delivery_rate]),'日期_天数'[天数]),",
              "                target_supply[SupplyKey] = VALUES (dim_supply[c4])",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_supply[c3_name]),",
              "                CALCULATE (",
              "                    DIVIDE( SUM (target_supply[target_delivery_rate]),'日期_天数'[天数]),",
              "                    target_supply[SupplyKey] = VALUES (dim_supply[c3])",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_supply[c2_name]),",
              "                    CALCULATE (",
              "                      DIVIDE( SUM (target_supply[target_delivery_rate]),'日期_天数'[天数]),",
              "                      target_supply[SupplyKey] = VALUES (dim_supply[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_supply[c1_name]),",
              "                        CALCULATE (",
              "                           DIVIDE( SUM (target_supply[target_delivery_rate]),'日期_天数'[天数]),",
              "                            target_supply[SupplyKey] = VALUES ( dim_supply[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应_交期达成率实际",
            "expression": [
              "",
              "    IF (",
              "        HASONEVALUE ( dim_supply[c5_name]),",
              "        CALCULATE (",
              "           DIVIDE( SUM (result_supply[delivery_rate]),'日期_天数'[天数]),",
              "             result_supply[SupplyKey] = VALUES (dim_supply[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_supply[c4_name]),",
              "            CALCULATE (",
              "                 DIVIDE( SUM (result_supply[delivery_rate]),'日期_天数'[天数]),",
              "                 result_supply[SupplyKey]= VALUES (dim_supply[c4])",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_supply[c3_name]),",
              "                CALCULATE (",
              "                     DIVIDE( SUM (result_supply[delivery_rate]),'日期_天数'[天数]),",
              "                    result_supply[SupplyKey] = VALUES (dim_supply[c3])",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_supply[c2_name]),",
              "                    CALCULATE (",
              "                       DIVIDE( SUM (result_supply[delivery_rate]),'日期_天数'[天数]),",
              "                       result_supply[SupplyKey] = VALUES (dim_supply[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_supply[c1_name]),",
              "                        CALCULATE (",
              "                             DIVIDE( SUM (result_supply[delivery_rate]),'日期_天数'[天数]),",
              "                             result_supply[SupplyKey] = VALUES ( dim_supply[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应_交期达成率目标达成率",
            "expression": " DIVIDE([供应_交期达成率实际],[供应_交期达成率目标])",
            "formatString": "0.00"
          },
          {
            "name": "供应_交期达成率目标实际差异",
            "expression": "  [供应_交期达成率实际]-[供应_交期达成率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应_交期达成率实际_去年同期",
            "expression": [
              "CALCULATE([供应_交期达成率实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应_交期达成率实际_上月同期",
            "expression": "CALCULATE([供应_交期达成率实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应_交期达成率同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([供应_交期达成率实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([供应_交期达成率实际]-[供应_交期达成率实际_去年同期]), [供应_交期达成率实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应_交期达成率环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([供应_交期达成率实际]),",
              "   \t 0,",
              "\tDIVIDE(([供应_交期达成率实际]-[供应_交期达成率实际_上月同期]),[供应_交期达成率实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应下单金额实际",
            "expression": [
              "",
              "    IF (",
              "        HASONEVALUE ( dim_supply[c5_name]),",
              "        CALCULATE (",
              "            SUM (result_supply[order_amt]),",
              "             result_supply[SupplyKey] = VALUES (dim_supply[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_supply[c4_name]),",
              "            CALCULATE (",
              "                SUM (result_supply[order_amt]),",
              "                 result_supply[SupplyKey]= VALUES (dim_supply[c4])",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_supply[c3_name]),",
              "                CALCULATE (",
              "                    SUM (result_supply[order_amt]),",
              "                    result_supply[SupplyKey] = VALUES (dim_supply[c3])",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_supply[c2_name]),",
              "                    CALCULATE (",
              "                      SUM (result_supply[order_amt]),",
              "                       result_supply[SupplyKey] = VALUES (dim_supply[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_supply[c1_name]),",
              "                        CALCULATE (",
              "                            SUM (result_supply[order_amt]),",
              "                             result_supply[SupplyKey] = VALUES ( dim_supply[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "实际生产件数",
            "expression": [
              "",
              "    IF (",
              "        HASONEVALUE ( dim_supply[c5_name]),",
              "        CALCULATE (",
              "           SUM (result_supply[actual_production_qty]),",
              "            result_supply[SupplyKey] = VALUES (dim_supply[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_supply[c4_name]),",
              "            CALCULATE (",
              "               SUM (result_supply[actual_production_qty]),",
              "                result_supply[SupplyKey] = VALUES (dim_supply[c4])",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_supply[c3_name]),",
              "                CALCULATE (",
              "                    SUM (result_supply[actual_production_qty]),",
              "                     result_supply[SupplyKey] = VALUES (dim_supply[c3])",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_supply[c2_name]),",
              "                    CALCULATE (",
              "                      SUM (result_supply[actual_production_qty]),",
              "                        result_supply[SupplyKey] = VALUES (dim_supply[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_supply[c1_name]),",
              "                        CALCULATE (",
              "                           SUM (result_supply[actual_production_qty]),",
              "                             result_supply[SupplyKey] = VALUES ( dim_supply[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0"
          },
          {
            "name": "计划生产件数",
            "expression": [
              " ",
              "    IF (",
              "        HASONEVALUE ( dim_supply[c5_name]),",
              "        CALCULATE (",
              "          SUM (result_supply[planned_production_qty]),",
              "              result_supply[SupplyKey] = VALUES (dim_supply[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_supply[c4_name]),",
              "            CALCULATE (",
              "               SUM (result_supply[planned_production_qty]),",
              "                result_supply[SupplyKey] = VALUES (dim_supply[c4])",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_supply[c3_name]),",
              "                CALCULATE (",
              "                  SUM (result_supply[planned_production_qty]),",
              "                     result_supply[SupplyKey] = VALUES (dim_supply[c3])",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_supply[c2_name]),",
              "                    CALCULATE (",
              "                     SUM (result_supply[planned_production_qty]),",
              "                      result_supply[SupplyKey] = VALUES (dim_supply[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_supply[c1_name]),",
              "                        CALCULATE (",
              "                          SUM (result_supply[planned_production_qty]),",
              "                            result_supply[SupplyKey] = VALUES ( dim_supply[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0"
          },
          {
            "name": "供应_毛利率",
            "expression": "DIVIDE([供应_供应利润额实际],[供应_供应销售额实际])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "残次品实际",
            "expression": [
              " ",
              "    IF (",
              "        HASONEVALUE ( dim_supply[c5_name]),",
              "        CALCULATE (",
              "          SUM (result_supply[defective_qty]),",
              "            result_supply[SupplyKey] = VALUES (dim_supply[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_supply[c4_name]),",
              "            CALCULATE (",
              "               SUM (result_supply[defective_qty]),",
              "                 result_supply[SupplyKey] = VALUES (dim_supply[c4])",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_supply[c3_name]),",
              "                CALCULATE (",
              "                 SUM (result_supply[defective_qty]),",
              "                   result_supply[SupplyKey] = VALUES (dim_supply[c3])",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_supply[c2_name]),",
              "                    CALCULATE (",
              "                    SUM (result_supply[defective_qty]),",
              "                      result_supply[SupplyKey] = VALUES (dim_supply[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_supply[c1_name]),",
              "                        CALCULATE (",
              "                         SUM (result_supply[defective_qty]),",
              "                           result_supply[SupplyKey] = VALUES ( dim_supply[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "十五项_供应_实际生产件数",
            "expression": "SUMX('result_supply','result_supply'[actual_production_qty])"
          },
          {
            "name": "十五项_供应_计划生产件数",
            "expression": "SUMX('result_supply','result_supply'[planned_production_qty])"
          },
          {
            "name": "十五项_供应_残次品实际",
            "expression": "SUMX('result_supply','result_supply'[defective_qty])"
          }
        ]
      },
      {
        "name": "雷达_供应效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"供应销售额\" ,   \"\",) , ",
                "    ( \"供应利润额\" , \"\", ),",
                "    ( \"供应产能\" , \"\", ),",
                "    ( \"供应产供比\" , \"\", ),",
                "    ( \"供应安全值\" , \"\", ),",
                "    ( \"残品率(2-目标达成率)\" ,\"\", ),",
                "    ( \"交期达成率\" , \"\", )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1]  )"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "供应目标达成率_雷达",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('雷达_供应效率'[指标])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              "     \"供应销售额\" ,  IF( [供应_供应销售额目标达成率]<1.5,[供应_供应销售额目标达成率] ,1.5) , ",
              "    \"供应利润额\" , IF([供应_供应利润额目标达成率]<1.5 ,[供应_供应利润额目标达成率],1.5),",
              "    \"供应产能\" ,IF( [供应_供应产能目标达成率]<1.5,[供应_供应产能目标达成率], 1.5), ",
              "    \"供应产供比\" ,IF( [供应_供应产供比目标达成率]<1.5,[供应_供应产供比目标达成率], 1.5), ",
              "    \"供应安全值\" , IF([供应_供应安全值目标达成率]<1.5,[供应_供应安全值目标达成率],1.5), ",
              "    \"残品率(2-目标达成率)\" , IF([供应_残品率目标达成率]>2,0,2-[供应_残品率目标达成率]), ",
              "    \"交期达成率\" ,IF( [供应_交期达成率目标达成率]<1.5,[供应_交期达成率目标达成率],1.5)",
              "",
              " )"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ]
      },
      {
        "name": "度量值_组织效率",
        "columns": [
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": "[组织_人力成本额目标]"
          },
          {
            "type": "calculated",
            "name": "列4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculatedTableColumn",
            "name": "subject_name",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[subject_name]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \"价格\",\"\" ),",
                "     ( \"销售件数\",\"\" ),",
                "      ( \"销售额\",\"\" ),",
                "       ( \"净利润额\",\"\" ),",
                "        ( \"毛利率\",\"\" )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"subject_name\" , [Value1] )"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "组织_销售额目标",
            "expression": [
              " ",
              "    IF (",
              "        HASONEVALUE ( dim_org[c5_name] ),",
              "        CALCULATE (",
              "            SUM (target_org[target_sale_amt]),",
              "             target_org[OrgKey] = VALUES (dim_org[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_org[c4_name] ),",
              "            CALCULATE (",
              "                SUM (target_org[target_sale_amt]),",
              "                target_org[OrgKey] = VALUES (dim_org[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_org[c3_name]),",
              "                CALCULATE (",
              "                    SUM (target_org[target_sale_amt]),",
              "                    target_org[OrgKey] = VALUES (dim_org[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_org[c2_name] ),",
              "                    CALCULATE (",
              "                       SUM (target_org[target_sale_amt]),",
              "                      target_org[OrgKey] = VALUES (dim_org[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_org[c1_name] ),",
              "                        CALCULATE (",
              "                            SUM (target_org[target_sale_amt]),",
              "                            target_org[OrgKey] = VALUES ( dim_org[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "组织_销售额实际",
            "expression": [
              "  ",
              "    IF (",
              "        HASONEVALUE ( dim_org[c5_name] ),",
              "        CALCULATE (",
              "            SUM (result_org[sale_amt]),",
              "             result_org[OrgKey] = VALUES (dim_org[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_org[c4_name] ),",
              "            CALCULATE (",
              "               SUM (result_org[sale_amt]),",
              "                result_org[OrgKey] = VALUES (dim_org[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_org[c3_name]),",
              "                CALCULATE (",
              "                    SUM (result_org[sale_amt]),",
              "                    result_org[OrgKey] = VALUES (dim_org[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_org[c2_name] ),",
              "                    CALCULATE (",
              "                      SUM (result_org[sale_amt]),",
              "                       result_org[OrgKey] = VALUES (dim_org[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_org[c1_name] ),",
              "                        CALCULATE (",
              "                           SUM (result_org[sale_amt]),",
              "                            result_org[OrgKey] = VALUES ( dim_org[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "组织_销售额目标达成率",
            "expression": "  DIVIDE([组织_销售额实际],[组织_销售额目标])",
            "formatString": "0.00"
          },
          {
            "name": "组织_销售额目标实际差异",
            "expression": " [组织_销售额实际]-[组织_销售额目标]",
            "formatString": "0.00"
          },
          {
            "name": "组织_销售额实际_去年同期",
            "expression": "CALCULATE([组织_销售额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00"
          },
          {
            "name": "组织_销售额实际_上月同期",
            "expression": "CALCULATE([组织_销售额实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "组织_销售额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([组织_销售额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([组织_销售额实际]-[组织_销售额实际_去年同期]), [组织_销售额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "组织_销售额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([组织_销售额实际]),",
              "   \t 0,",
              "\tDIVIDE(([组织_销售额实际]-[组织_销售额实际_上月同期]),[组织_销售额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "组织_人力成本额目标",
            "expression": [
              " ",
              "    IF (",
              "        HASONEVALUE ( dim_org[c5_name] ),",
              "        CALCULATE (",
              "            SUM (target_org[target_cost_amt]),",
              "             target_org[OrgKey] = VALUES (dim_org[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_org[c4_name] ),",
              "            CALCULATE (",
              "                SUM (target_org[target_cost_amt]),",
              "                target_org[OrgKey] = VALUES (dim_org[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_org[c3_name] ),",
              "                CALCULATE (",
              "                    SUM (target_org[target_cost_amt]),",
              "                    target_org[OrgKey] = VALUES (dim_org[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_org[c2_name] ),",
              "                    CALCULATE (",
              "                       SUM (target_org[target_cost_amt]),",
              "                      target_org[OrgKey] = VALUES (dim_org[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_org[c1_name] ),",
              "                        CALCULATE (",
              "                            SUM (target_org[target_cost_amt]),",
              "                            target_org[OrgKey] = VALUES ( dim_org[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "组织_人力成本额实际",
            "expression": [
              "",
              "    IF (",
              "        HASONEVALUE ( dim_org[c5_name] ),",
              "        CALCULATE (",
              "            SUM (result_org[cost_amt]),",
              "             result_org[OrgKey] = VALUES (dim_org[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_org[c4_name] ),",
              "            CALCULATE (",
              "               SUM (result_org[cost_amt]),",
              "                result_org[OrgKey] = VALUES (dim_org[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_org[c3_name]),",
              "                CALCULATE (",
              "                    SUM (result_org[cost_amt]),",
              "                    result_org[OrgKey] = VALUES (dim_org[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_org[c2_name] ),",
              "                    CALCULATE (",
              "                      SUM (result_org[cost_amt]),",
              "                       result_org[OrgKey] = VALUES (dim_org[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_org[c1_name] ),",
              "                        CALCULATE (",
              "                           SUM (result_org[cost_amt]),",
              "                            result_org[OrgKey] = VALUES ( dim_org[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "组织_人力成本额目标达成率",
            "expression": " DIVIDE([组织_人力成本额实际],[组织_人力成本额目标])",
            "formatString": "0.00"
          },
          {
            "name": "组织_人力成本额目标实际差异",
            "expression": " [组织_人力成本额实际]-[组织_人力成本额目标]",
            "formatString": "0.00"
          },
          {
            "name": "组织_人力成本额实际_去年同期",
            "expression": "CALCULATE([组织_人力成本额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00"
          },
          {
            "name": "组织_人力成本额实际_上月同期",
            "expression": "CALCULATE([组织_人力成本额实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "组织_人力成本额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([组织_人力成本额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([组织_人力成本额实际]-[组织_人力成本额实际_去年同期]), [组织_人力成本额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "组织_人力成本额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([组织_人力成本额实际]),",
              "   \t 0,",
              "\tDIVIDE(([组织_人力成本额实际]-[组织_人力成本额实际_上月同期]),[组织_人力成本额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "组织_净利润额目标",
            "expression": [
              " ",
              "    IF (",
              "        HASONEVALUE ( dim_org[c5_name] ),",
              "        CALCULATE (",
              "            SUM (target_org[target_profit_amt]),",
              "             target_org[OrgKey] = VALUES (dim_org[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_org[c4_name] ),",
              "            CALCULATE (",
              "                SUM (target_org[target_profit_amt]),",
              "                target_org[OrgKey] = VALUES (dim_org[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_org[c3_name]),",
              "                CALCULATE (",
              "                    SUM (target_org[target_profit_amt]),",
              "                    target_org[OrgKey] = VALUES (dim_org[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_org[c2_name] ),",
              "                    CALCULATE (",
              "                       SUM (target_org[target_profit_amt]),",
              "                      target_org[OrgKey] = VALUES (dim_org[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_org[c1_name] ),",
              "                        CALCULATE (",
              "                            SUM (target_org[target_profit_amt]),",
              "                            target_org[OrgKey] = VALUES ( dim_org[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "组织_净利润额实际",
            "expression": [
              "",
              "    IF (",
              "        HASONEVALUE ( dim_org[c5_name] ),",
              "        CALCULATE (",
              "            SUM (result_org[profit_amt]),",
              "             result_org[OrgKey] = VALUES (dim_org[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_org[c4_name] ),",
              "            CALCULATE (",
              "              SUM (result_org[profit_amt]),",
              "                result_org[OrgKey] = VALUES (dim_org[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_org[c3_name]),",
              "                CALCULATE (",
              "                    SUM (result_org[profit_amt]),",
              "                    result_org[OrgKey] = VALUES (dim_org[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_org[c2_name] ),",
              "                    CALCULATE (",
              "                      SUM (result_org[profit_amt]),",
              "                       result_org[OrgKey] = VALUES (dim_org[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_org[c1_name] ),",
              "                        CALCULATE (",
              "                           SUM (result_org[profit_amt]),",
              "                            result_org[OrgKey] = VALUES ( dim_org[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "组织_净利润额目标达成率",
            "expression": " DIVIDE([组织_净利润额实际],[组织_净利润额目标])",
            "formatString": "0.00"
          },
          {
            "name": "组织_净利润额目标实际差异",
            "expression": " [组织_净利润额实际]-[组织_净利润额目标]",
            "formatString": "0.00"
          },
          {
            "name": "组织_净利润额实际_去年同期",
            "expression": "CALCULATE([组织_净利润额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00"
          },
          {
            "name": "组织_净利润额实际_上月同期",
            "expression": "CALCULATE([组织_净利润额实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "组织_净利润额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([组织_净利润额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([组织_净利润额实际]-[组织_净利润额实际_去年同期]), [组织_净利润额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "组织_净利润额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([组织_净利润额实际]),",
              "   \t 0,",
              "\tDIVIDE(([组织_净利润额实际]-[组织_净利润额实际_上月同期]),[组织_净利润额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "组织_组织投入产出比目标",
            "expression": "  DIVIDE([组织_净利润额目标],[组织_人力成本额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "组织_组织投入产出比实际",
            "expression": "  DIVIDE([组织_净利润额实际],[组织_人力成本额实际])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "组织_组织投入产出比目标达成率",
            "expression": " DIVIDE([组织_组织投入产出比实际],[组织_组织投入产出比目标])",
            "formatString": "0.00"
          },
          {
            "name": "组织_组织投入产出比目标实际差异",
            "expression": "  [组织_组织投入产出比实际]-[组织_组织投入产出比目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "组织_组织投入产出比实际_去年同期",
            "expression": "CALCULATE([组织_组织投入产出比实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "组织_组织投入产出比实际_上月同期",
            "expression": "CALCULATE([组织_组织投入产出比实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "组织_组织投入产出比同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([组织_组织投入产出比实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([组织_组织投入产出比实际]-[组织_组织投入产出比实际_去年同期]), [组织_组织投入产出比实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "组织_组织投入产出比环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([组织_组织投入产出比实际]),",
              "   \t 0,",
              "\tDIVIDE(([组织_组织投入产出比实际]-[组织_组织投入产出比实际_上月同期]),[组织_组织投入产出比实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "组织_日销目标",
            "expression": "  DIVIDE([组织_销售额目标],'日期_天数'[天数])",
            "formatString": "0.00"
          },
          {
            "name": "组织_日销实际",
            "expression": "  DIVIDE([组织_销售额实际],'日期_天数'[天数])",
            "formatString": "0.00"
          },
          {
            "name": "组织_日销目标达成率",
            "expression": " DIVIDE([组织_日销实际],[组织_日销目标])",
            "formatString": "0.00"
          },
          {
            "name": "组织_日销目标实际差异",
            "expression": " [组织_日销实际]-[组织_日销目标]",
            "formatString": "0.00"
          },
          {
            "name": "组织_日销实际_去年同期",
            "expression": "CALCULATE([组织_日销实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00"
          },
          {
            "name": "组织_日销实际_上月同期",
            "expression": "CALCULATE([组织_日销实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "组织_日销同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([组织_日销实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([组织_日销实际]-[组织_日销实际_去年同期]), [组织_日销实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "组织_日销环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([组织_日销实际]),",
              "   \t 0,",
              "\tDIVIDE(([组织_日销实际]-[组织_日销实际_上月同期]),[组织_日销实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "组织_人员冗余值目标",
            "expression": [
              " ",
              "    IF (",
              "        HASONEVALUE ( dim_org[c5_name] ),",
              "        CALCULATE (",
              "            SUM (target_org[target_redundancy]),",
              "             target_org[OrgKey] = VALUES (dim_org[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_org[c4_name] ),",
              "            CALCULATE (",
              "                SUM (target_org[target_redundancy]),",
              "                target_org[OrgKey] = VALUES (dim_org[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_org[c3_name]),",
              "                CALCULATE (",
              "                    SUM (target_org[target_redundancy]),",
              "                    target_org[OrgKey] = VALUES (dim_org[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_org[c2_name] ),",
              "                    CALCULATE (",
              "                       SUM (target_org[target_redundancy]),",
              "                      target_org[OrgKey] = VALUES (dim_org[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_org[c1_name] ),",
              "                        CALCULATE (",
              "                            SUM (target_org[target_redundancy]),",
              "                            target_org[OrgKey] = VALUES ( dim_org[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "组织_人员冗余值实际",
            "expression": [
              "",
              "    IF (",
              "        HASONEVALUE ( dim_org[c5_name] ),",
              "        CALCULATE (",
              "            SUM (result_org[redundancy]),",
              "             result_org[OrgKey] = VALUES (dim_org[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_org[c4_name] ),",
              "            CALCULATE (",
              "                 SUM (result_org[redundancy]),",
              "                 result_org[OrgKey] = VALUES (dim_org[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_org[c3_name]),",
              "                CALCULATE (",
              "                     SUM (result_org[redundancy]),",
              "                     result_org[OrgKey] = VALUES (dim_org[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_org[c2_name] ),",
              "                    CALCULATE (",
              "                        SUM (result_org[redundancy]),",
              "                        result_org[OrgKey] = VALUES (dim_org[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_org[c1_name] ),",
              "                        CALCULATE (",
              "                             SUM (result_org[redundancy]),",
              "                             result_org[OrgKey] = VALUES ( dim_org[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "组织_人员冗余值目标达成率",
            "expression": " DIVIDE([组织_人员冗余值实际],[组织_人员冗余值目标])",
            "formatString": "0.00"
          },
          {
            "name": "组织_人员冗余值目标实际差异",
            "expression": " [组织_人员冗余值实际]-[组织_人员冗余值目标]",
            "formatString": "0.00"
          },
          {
            "name": "组织_人员冗余值实际_去年同期",
            "expression": "CALCULATE([组织_人员冗余值实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00"
          },
          {
            "name": "组织_人员冗余值实际_上月同期",
            "expression": "CALCULATE([组织_人员冗余值实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "组织_人员冗余值同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([组织_人员冗余值实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([组织_人员冗余值实际]-[组织_人员冗余值实际_去年同期]), [组织_人员冗余值实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "组织_人员冗余值环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([组织_人员冗余值实际]),",
              "   \t 0,",
              "\tDIVIDE(([组织_人员冗余值实际]-[组织_人员冗余值实际_上月同期]),[组织_人员冗余值实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "组织_平均售价",
            "expression": "DIVIDE('度量值_组织效率'[组织_销售额实际],[销售件数])",
            "formatString": "0.00"
          },
          {
            "name": "组织_毛利率",
            "expression": "1-DIVIDE(SUMX('fact_order','fact_order'[qty]*RELATED(dim_product[avg_unit_cost_amt])),[组织_销售额实际])",
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ]
      },
      {
        "name": "雷达_组织效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"净利润额\" , \"\", ),",
                "    ( \"销售额\" , \"\",) , ",
                "    ( \"人力成本额(2-目标达成率)\" , \"\", ),",
                "    ( \"组织投入产出比\" , \"\", ),",
                "    ( \"日销\" ,\"\", ),",
                "    ( \"人员冗余值\" , \"\", )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1]  )"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "组织目标达成率_雷达",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('雷达_组织效率'[指标])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              "   \"净利润额\",IF([组织_净利润额目标达成率]<1.5,[组织_净利润额目标达成率],1.5), ",
              "    \"销售额\" ,  IF( [组织_销售额目标达成率]<1.5,[组织_销售额目标达成率],1.5),",
              "     \"人力成本额(2-目标达成率)\" , IF([组织_人力成本额目标达成率]>2,0,2-[组织_人力成本额目标达成率]),",
              "    \"组织投入产出比\" ,IF( [组织_组织投入产出比目标达成率]<1.5,[组织_组织投入产出比目标达成率],1.5),",
              "    \"日销\" , IF([组织_日销目标达成率]<1.5,[组织_日销目标达成率],1.5),",
              "    \"人员冗余值\" ,IF( [组织_人员冗余值目标达成率]<1.5,[组织_人员冗余值目标达成率],1.5)",
              "",
              " )"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ]
      },
      {
        "name": "度量值_资金效率",
        "columns": [
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列7",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列8",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列9",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculatedTableColumn",
            "name": "subject_name",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[subject_name]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "       ( \"销售额\",\"\" ),",
                "       ( \"净利润额\",\"\" ),",
                "        ( \"净利率\",\"\" )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"subject_name\" , [Value1] )"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "资金_总成本费用额目标",
            "expression": [
              "",
              "    IF (",
              "        HASONEVALUE ( dim_org[c5_name] ),",
              "        CALCULATE (",
              "            SUM (target_finance[target_total_cost_amt]),",
              "             target_finance[OrgKey] = VALUES (dim_org[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_org[c4_name] ),",
              "            CALCULATE (",
              "                SUM ( target_finance[target_total_cost_amt]),",
              "                target_finance[OrgKey]= VALUES (dim_org[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_org[c3_name] ),",
              "                CALCULATE (",
              "                    SUM ( target_finance[target_total_cost_amt] ),",
              "                    target_finance[OrgKey] = VALUES (dim_org[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_org[c2_name] ),",
              "                    CALCULATE (",
              "                        SUM ( target_finance[target_total_cost_amt]),",
              "                      target_finance[OrgKey]= VALUES (dim_org[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_org[c1_name] ),",
              "                        CALCULATE (",
              "                            SUM ( target_finance[target_total_cost_amt]),",
              "                            target_finance[OrgKey] = VALUES ( dim_org[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "资金_销售额目标",
            "expression": [
              "",
              "    IF (",
              "        HASONEVALUE ( dim_org[c5_name] ),",
              "        CALCULATE (",
              "            SUM (target_finance[target_sale_amt]),",
              "             target_finance[OrgKey] = VALUES (dim_org[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_org[c4_name] ),",
              "            CALCULATE (",
              "                SUM (target_finance[target_sale_amt]),",
              "                target_finance[OrgKey]= VALUES (dim_org[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_org[c3_name] ),",
              "                CALCULATE (",
              "                     SUM (target_finance[target_sale_amt]),",
              "                    target_finance[OrgKey] = VALUES (dim_org[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_org[c2_name] ),",
              "                    CALCULATE (",
              "                         SUM (target_finance[target_sale_amt]),",
              "                      target_finance[OrgKey]= VALUES (dim_org[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_org[c1_name] ),",
              "                        CALCULATE (",
              "                            SUM (target_finance[target_sale_amt]),",
              "                            target_finance[OrgKey] = VALUES ( dim_org[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "资金_回款额目标",
            "expression": [
              " ",
              "    IF (",
              "        HASONEVALUE ( dim_org[c5_name] ),",
              "        CALCULATE (",
              "             SUM (target_finance[target_return_amt]),",
              "             target_finance[OrgKey] = VALUES (dim_org[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_org[c4_name] ),",
              "            CALCULATE (",
              "                 SUM (target_finance[target_return_amt]),",
              "                target_finance[OrgKey]= VALUES (dim_org[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_org[c3_name] ),",
              "                CALCULATE (",
              "                     SUM (target_finance[target_return_amt]),",
              "                    target_finance[OrgKey] = VALUES (dim_org[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_org[c2_name] ),",
              "                    CALCULATE (",
              "                       SUM (target_finance[target_return_amt]),",
              "                      target_finance[OrgKey]= VALUES (dim_org[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_org[c1_name] ),",
              "                        CALCULATE (",
              "                             SUM (target_finance[target_return_amt]),",
              "                            target_finance[OrgKey] = VALUES ( dim_org[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "资金_净利润额目标",
            "expression": " [资金_销售额目标]-[资金_总成本费用额目标]",
            "formatString": "0.00"
          },
          {
            "name": "资金_净利率目标",
            "expression": "  DIVIDE( [资金_净利润额目标],[资金_销售额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_净现金流目标",
            "expression": [
              "",
              "    IF (",
              "        HASONEVALUE ( dim_org[c5_name] ),",
              "        CALCULATE (",
              "            SUM (target_finance[target_cash_flow_amt]),",
              "             target_finance[OrgKey] = VALUES (dim_org[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_org[c4_name] ),",
              "            CALCULATE (",
              "                SUM (target_finance[target_cash_flow_amt]),",
              "                target_finance[OrgKey]= VALUES (dim_org[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_org[c3_name] ),",
              "                CALCULATE (",
              "                    SUM (target_finance[target_cash_flow_amt]),",
              "                    target_finance[OrgKey] = VALUES (dim_org[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_org[c2_name] ),",
              "                    CALCULATE (",
              "                        SUM (target_finance[target_cash_flow_amt]),",
              "                      target_finance[OrgKey]= VALUES (dim_org[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_org[c1_name] ),",
              "                        CALCULATE (",
              "                            SUM (target_finance[target_cash_flow_amt]),",
              "                            target_finance[OrgKey] = VALUES ( dim_org[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "资金_投资回报率目标",
            "expression": " DIVIDE([资金_净利润额目标],[资金_投入资金目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_资金周转率目标",
            "expression": "  DIVIDE([资金_销售额目标], DIVIDE(([资金_期初总资产目标]+[资金_期末总资产目标]),2))",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_资金冗余值目标",
            "expression": [
              "",
              "    IF (",
              "        HASONEVALUE ( dim_org[c5_name] ),",
              "        CALCULATE (",
              "            SUM (target_finance[target_redundancy]),",
              "             target_finance[OrgKey] = VALUES (dim_org[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_org[c4_name] ),",
              "            CALCULATE (",
              "                 SUM (target_finance[target_redundancy]),",
              "                 target_finance[OrgKey]= VALUES (dim_org[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_org[c3_name] ),",
              "                CALCULATE (",
              "                     SUM (target_finance[target_redundancy]),",
              "                    target_finance[OrgKey] = VALUES (dim_org[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_org[c2_name] ),",
              "                    CALCULATE (",
              "                       SUM (target_finance[target_redundancy]),",
              "                      target_finance[OrgKey]= VALUES (dim_org[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_org[c1_name] ),",
              "                        CALCULATE (",
              "                             SUM (target_finance[target_redundancy]),",
              "                            target_finance[OrgKey] = VALUES ( dim_org[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "资金_总成本费用额实际",
            "expression": [
              " ",
              "    IF (",
              "        HASONEVALUE ( dim_org[c5_name] ),",
              "        CALCULATE (",
              "           SUM (result_finance[total_cost_amt]),",
              "           result_finance[OrgKey] = VALUES (dim_org[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_org[c4_name] ),",
              "            CALCULATE (",
              "                SUM (result_finance[total_cost_amt]),",
              "               result_finance[OrgKey] = VALUES (dim_org[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_org[c3_name] ),",
              "                CALCULATE (",
              "                   SUM (result_finance[total_cost_amt]),",
              "                   result_finance[OrgKey]  = VALUES (dim_org[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_org[c2_name] ),",
              "                    CALCULATE (",
              "                       SUM (result_finance[total_cost_amt]),",
              "                      result_finance[OrgKey] = VALUES (dim_org[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_org[c1_name] ),",
              "                        CALCULATE (",
              "                            SUM (result_finance[total_cost_amt]),",
              "                            result_finance[OrgKey]  = VALUES ( dim_org[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "资金_销售额实际",
            "expression": [
              "",
              "    IF (",
              "        HASONEVALUE ( dim_org[c5_name] ),",
              "        CALCULATE (",
              "           SUM (result_finance[sale_amt]),",
              "             result_finance[OrgKey] = VALUES (dim_org[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_org[c4_name] ),",
              "            CALCULATE (",
              "               SUM (result_finance[sale_amt]),",
              "                result_finance[OrgKey] = VALUES (dim_org[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_org[c3_name] ),",
              "                CALCULATE (",
              "                   SUM (result_finance[sale_amt]),",
              "                    result_finance[OrgKey] = VALUES (dim_org[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_org[c2_name] ),",
              "                    CALCULATE (",
              "                      SUM (result_finance[sale_amt]),",
              "                       result_finance[OrgKey] = VALUES (dim_org[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_org[c1_name] ),",
              "                        CALCULATE (",
              "                           SUM (result_finance[sale_amt]),",
              "                            result_finance[OrgKey] = VALUES ( dim_org[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "资金_回款额实际",
            "expression": [
              "",
              "    IF (",
              "        HASONEVALUE ( dim_org[c5_name] ),",
              "        CALCULATE (",
              "           SUM (result_finance[return_amt]),",
              "             result_finance[OrgKey]  = VALUES (dim_org[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_org[c4_name] ),",
              "            CALCULATE (",
              "               SUM (result_finance[return_amt]),",
              "                result_finance[OrgKey] = VALUES (dim_org[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_org[c3_name] ),",
              "                CALCULATE (",
              "                    SUM (result_finance[return_amt]),",
              "                     result_finance[OrgKey]  = VALUES (dim_org[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_org[c2_name] ),",
              "                    CALCULATE (",
              "                       SUM (result_finance[return_amt]),",
              "                       result_finance[OrgKey] = VALUES (dim_org[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_org[c1_name] ),",
              "                        CALCULATE (",
              "                           SUM (result_finance[return_amt]),",
              "                            result_finance[OrgKey]  = VALUES ( dim_org[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "资金_净利润额实际",
            "expression": [
              "",
              "    IF (",
              "        HASONEVALUE ( dim_org[c5_name] ),",
              "        CALCULATE (",
              "           SUM (result_finance[profit_amt]),",
              "             result_finance[OrgKey]  = VALUES (dim_org[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_org[c4_name] ),",
              "            CALCULATE (",
              "               SUM (result_finance[profit_amt]),",
              "                result_finance[OrgKey] = VALUES (dim_org[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_org[c3_name] ),",
              "                CALCULATE (",
              "                    SUM (result_finance[profit_amt]),",
              "                     result_finance[OrgKey]  = VALUES (dim_org[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_org[c2_name] ),",
              "                    CALCULATE (",
              "                       SUM (result_finance[profit_amt]),",
              "                       result_finance[OrgKey] = VALUES (dim_org[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_org[c1_name] ),",
              "                        CALCULATE (",
              "                           SUM (result_finance[profit_amt]),",
              "                            result_finance[OrgKey]  = VALUES ( dim_org[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "资金_净利率实际",
            "expression": [
              "  DIVIDE([资金_净利润额实际],[资金_销售额实际])",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_净现金流实际",
            "expression": [
              "",
              "    IF (",
              "        HASONEVALUE ( dim_org[c5_name] ),",
              "        CALCULATE (",
              "           SUM (result_finance[cash_flow_amt]),",
              "             result_finance[OrgKey]  = VALUES (dim_org[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_org[c4_name] ),",
              "            CALCULATE (",
              "               SUM (result_finance[cash_flow_amt]),",
              "                result_finance[OrgKey] = VALUES (dim_org[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_org[c3_name] ),",
              "                CALCULATE (",
              "                    SUM (result_finance[cash_flow_amt]),",
              "                     result_finance[OrgKey]  = VALUES (dim_org[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_org[c2_name] ),",
              "                    CALCULATE (",
              "                       SUM (result_finance[cash_flow_amt]),",
              "                       result_finance[OrgKey] = VALUES (dim_org[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_org[c1_name] ),",
              "                        CALCULATE (",
              "                           SUM (result_finance[cash_flow_amt]),",
              "                            result_finance[OrgKey]  = VALUES ( dim_org[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "资金_投资回报率实际",
            "expression": " DIVIDE([资金_净利润额实际],[资金_投入资金实际])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_资金周转率实际",
            "expression": " DIVIDE([资金_销售额实际], DIVIDE(([资金_期初总资产实际]+[资金_期末总资产实际]),2))",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_资金冗余值实际",
            "expression": [
              "",
              "    IF (",
              "        HASONEVALUE ( dim_org[c5_name] ),",
              "        CALCULATE (",
              "           SUM (result_finance[redundancy]),",
              "             result_finance[OrgKey]  = VALUES (dim_org[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_org[c4_name] ),",
              "            CALCULATE (",
              "               SUM (result_finance[redundancy]),",
              "                result_finance[OrgKey] = VALUES (dim_org[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_org[c3_name] ),",
              "                CALCULATE (",
              "                    SUM (result_finance[redundancy]),",
              "                     result_finance[OrgKey]  = VALUES (dim_org[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_org[c2_name] ),",
              "                    CALCULATE (",
              "                       SUM (result_finance[redundancy]),",
              "                       result_finance[OrgKey] = VALUES (dim_org[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_org[c1_name] ),",
              "                        CALCULATE (",
              "                           SUM (result_finance[redundancy]),",
              "                            result_finance[OrgKey]  = VALUES ( dim_org[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "资金_总成本费用额目标达成率",
            "expression": " DIVIDE([资金_总成本费用额实际],[资金_总成本费用额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_销售额目标达成率",
            "expression": " DIVIDE([资金_销售额实际],[资金_销售额目标])",
            "formatString": "0.00"
          },
          {
            "name": "资金_回款额目标达成率",
            "expression": " DIVIDE([资金_回款额实际],[资金_回款额目标])",
            "formatString": "0.00"
          },
          {
            "name": "资金_净利润额目标达成率",
            "expression": "  DIVIDE([资金_净利润额实际],[资金_净利润额目标])",
            "formatString": "0.00"
          },
          {
            "name": "资金_净利率目标达成率",
            "expression": " DIVIDE([资金_净利率实际],[资金_净利率目标])",
            "formatString": "0.00"
          },
          {
            "name": "资金_净现金流目标达成率",
            "expression": " DIVIDE([资金_净现金流实际],[资金_净现金流目标])",
            "formatString": "0.00"
          },
          {
            "name": "资金_投资回报率目标达成率",
            "expression": " DIVIDE([资金_投资回报率实际],[资金_投资回报率目标])",
            "formatString": "0.00"
          },
          {
            "name": "资金_资金周转率目标达成率",
            "expression": " DIVIDE([资金_资金周转率实际],[资金_资金周转率目标])",
            "formatString": "0.00"
          },
          {
            "name": "资金_资金冗余值目标达成率",
            "expression": " DIVIDE([资金_资金冗余值实际],[资金_资金冗余值目标])",
            "formatString": "0.00"
          },
          {
            "name": "资金_总成本费用额目标实际差异",
            "expression": "  [资金_总成本费用额实际]-[资金_总成本费用额目标]",
            "formatString": "0.00"
          },
          {
            "name": "资金_销售额目标实际差异",
            "expression": " [资金_销售额实际]-[资金_销售额目标]",
            "formatString": "0.00"
          },
          {
            "name": "资金_回款额目标实际差异",
            "expression": "  [资金_回款额实际]-[资金_回款额目标]",
            "formatString": "0.00"
          },
          {
            "name": "资金_净利润额目标实际差异",
            "expression": " [资金_净利润额实际]-[资金_净利润额目标]",
            "formatString": "0.00"
          },
          {
            "name": "资金_净利率目标实际差异",
            "expression": "  [资金_净利率实际]-[资金_净利率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_净现金流目标实际差异",
            "expression": "  [资金_净现金流实际]-[资金_净现金流目标]",
            "formatString": "0.00"
          },
          {
            "name": "资金_投资回报率目标实际差异",
            "expression": "  [资金_投资回报率实际]-[资金_投资回报率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_资金周转率目标实际差异",
            "expression": " [资金_资金周转率实际]-[资金_资金周转率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_资金冗余值目标实际差异",
            "expression": "  [资金_资金冗余值实际]-[资金_资金冗余值目标]",
            "formatString": "0.00"
          },
          {
            "name": "资金_总成本费用额实际_去年同期",
            "expression": "CALCULATE([资金_总成本费用额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00"
          },
          {
            "name": "资金_总成本费用额实际_上月同期",
            "expression": "CALCULATE([资金_总成本费用额实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "资金_销售额实际_去年同期",
            "expression": "CALCULATE([资金_销售额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00"
          },
          {
            "name": "资金_销售额实际_上月同期",
            "expression": "CALCULATE([资金_销售额实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "资金_回款额实际_去年同期",
            "expression": "CALCULATE([资金_回款额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00"
          },
          {
            "name": "资金_回款额实际_上月同期",
            "expression": "CALCULATE([资金_回款额实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "资金_净利润额实际_去年同期",
            "expression": "CALCULATE([资金_净利润额实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00"
          },
          {
            "name": "资金_净利润额实际_上月同期",
            "expression": "CALCULATE([资金_净利润额实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "资金_净利率实际_去年同期",
            "expression": "CALCULATE([资金_净利率实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_净利率实际_上月同期",
            "expression": "CALCULATE([资金_净利率实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_净现金流实际_去年同期",
            "expression": "CALCULATE([资金_净现金流实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00"
          },
          {
            "name": "资金_净现金流实际_上月同期",
            "expression": "CALCULATE([资金_净现金流实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "资金_投资回报率实际_去年同期",
            "expression": "CALCULATE([资金_投资回报率实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_投资回报率实际_上月同期",
            "expression": "CALCULATE([资金_投资回报率实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_资金周转率实际_去年同期",
            "expression": "CALCULATE([资金_资金周转率实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_资金周转率实际_上月同期",
            "expression": "CALCULATE([资金_资金周转率实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_资金冗余值实际_去年同期",
            "expression": "CALCULATE([资金_资金冗余值实际],DATEADD('DimDate'[FullDate],-1,YEAR),ALL('DimDate'[YearNameEn]))",
            "formatString": "0.00"
          },
          {
            "name": "资金_资金冗余值实际_上月同期",
            "expression": "CALCULATE([资金_资金冗余值实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "资金_总成本费用额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([资金_总成本费用额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([资金_总成本费用额实际]-[资金_总成本费用额实际_去年同期]), [资金_总成本费用额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_总成本费用额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([资金_总成本费用额实际]),",
              "   \t 0,",
              "\tDIVIDE(([资金_总成本费用额实际]-[资金_总成本费用额实际_上月同期]),[资金_总成本费用额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_销售额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([资金_销售额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([资金_销售额实际]-[资金_销售额实际_去年同期]), [资金_销售额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_销售额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([资金_销售额实际]),",
              "   \t 0,",
              "\tDIVIDE(([资金_销售额实际]-[资金_销售额实际_上月同期]),[资金_销售额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_回款额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([资金_回款额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([资金_回款额实际]-[资金_回款额实际_去年同期]), [资金_回款额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_回款额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([资金_回款额实际]),",
              "   \t 0,",
              "\tDIVIDE(([资金_回款额实际]-[资金_回款额实际_上月同期]),[资金_回款额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_净利润额同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([资金_净利润额实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([资金_净利润额实际]-[资金_净利润额实际_去年同期]), [资金_净利润额实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_净利润额环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([资金_净利润额实际]),",
              "   \t 0,",
              "\tDIVIDE(([资金_净利润额实际]-[资金_净利润额实际_上月同期]),[资金_净利润额实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_净利率同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([资金_净利率实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([资金_净利率实际]-[资金_净利率实际_去年同期]), [资金_净利率实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_净利率环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([资金_净利率实际]),",
              "   \t 0,",
              "\tDIVIDE(([资金_净利率实际]-[资金_净利率实际_上月同期]),[资金_净利率实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_净现金流同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([资金_净现金流实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([资金_净现金流实际]-[资金_净现金流实际_去年同期]), [资金_净现金流实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_净现金流环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([资金_净现金流实际]),",
              "   \t 0,",
              "\tDIVIDE(([资金_净现金流实际]-[资金_净现金流实际_上月同期]),[资金_净现金流实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_投资回报率同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([资金_投资回报率实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([资金_投资回报率实际]-[资金_投资回报率实际_去年同期]), [资金_投资回报率实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_投资回报率环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([资金_投资回报率实际]),",
              "   \t 0,",
              "\tDIVIDE(([资金_投资回报率实际]-[资金_投资回报率实际_上月同期]),[资金_投资回报率实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_资金周转率同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([资金_资金周转率实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([资金_资金周转率实际]-[资金_资金周转率实际_去年同期]), [资金_资金周转率实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_资金周转率环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([资金_资金周转率实际]),",
              "   \t 0,",
              "\tDIVIDE(([资金_资金周转率实际]-[资金_资金周转率实际_上月同期]),[资金_资金周转率实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_资金冗余值同比增长率 %",
            "expression": [
              " IF(",
              "\tISBLANK([资金_资金冗余值实际]),\t",
              "\t0,",
              "   \t(DIVIDE(([资金_资金冗余值实际]-[资金_资金冗余值实际_去年同期]), [资金_资金冗余值实际_去年同期])))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_资金冗余值环比增长率 %",
            "expression": [
              " IF(",
              "    \tISBLANK([资金_资金冗余值实际]),",
              "   \t 0,",
              "\tDIVIDE(([资金_资金冗余值实际]-[资金_资金冗余值实际_上月同期]),[资金_资金冗余值实际_上月同期]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "资金_现金流入实际",
            "expression": "SUMX('fact_company','fact_company'[cash_inflow_amt])",
            "formatString": "0.00"
          },
          {
            "name": "资金_现金流出实际",
            "expression": "SUMX('fact_company','fact_company'[cash_out_amt])",
            "formatString": "0.00"
          },
          {
            "name": "资金_现金流入目标",
            "expression": " SUMX('target_company','target_company'[target_cash_inflow_amt])",
            "formatString": "0.00"
          },
          {
            "name": "资金_现金流出目标",
            "expression": "SUMX('target_company','target_company'[target_cash_out_amt] )",
            "formatString": "0.00"
          },
          {
            "name": "资金_投入资金目标",
            "expression": [
              " ",
              "    IF (",
              "        HASONEVALUE ( dim_org[c5_name] ),",
              "        CALCULATE (",
              "            SUM (target_finance[target_invest_amt]),",
              "             target_finance[OrgKey] = VALUES (dim_org[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_org[c4_name] ),",
              "            CALCULATE (",
              "                SUM ( target_finance[target_invest_amt]),",
              "                target_finance[OrgKey]= VALUES (dim_org[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_org[c3_name] ),",
              "                CALCULATE (",
              "                    SUM ( target_finance[target_invest_amt] ),",
              "                    target_finance[OrgKey] = VALUES (dim_org[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_org[c2_name] ),",
              "                    CALCULATE (",
              "                        SUM ( target_finance[target_invest_amt]),",
              "                      target_finance[OrgKey]= VALUES (dim_org[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_org[c1_name] ),",
              "                        CALCULATE (",
              "                            SUM ( target_finance[target_invest_amt]),",
              "                            target_finance[OrgKey] = VALUES ( dim_org[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "资金_投入资金实际",
            "expression": [
              "",
              "    IF (",
              "        HASONEVALUE ( dim_org[c5_name] ),",
              "        CALCULATE (",
              "          SUM (result_finance[invest_amt]),",
              "             result_finance[OrgKey] = VALUES (dim_org[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_org[c4_name] ),",
              "            CALCULATE (",
              "              SUM (result_finance[invest_amt]),",
              "                result_finance[OrgKey] = VALUES (dim_org[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_org[c3_name] ),",
              "                CALCULATE (",
              "                  SUM (result_finance[invest_amt]),",
              "                    result_finance[OrgKey] = VALUES (dim_org[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_org[c2_name] ),",
              "                    CALCULATE (",
              "                      SUM (result_finance[invest_amt]),",
              "                       result_finance[OrgKey] = VALUES (dim_org[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_org[c1_name] ),",
              "                        CALCULATE (",
              "                          SUM (result_finance[invest_amt]),",
              "                            result_finance[OrgKey] = VALUES ( dim_org[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "资金_总资产目标",
            "expression": [
              " ",
              "    IF (",
              "        HASONEVALUE ( dim_org[c5_name] ),",
              "        CALCULATE (",
              "            SUM (target_finance[target_total_assets_amt]),",
              "             target_finance[OrgKey] = VALUES (dim_org[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_org[c4_name] ),",
              "            CALCULATE (",
              "                SUM (target_finance[target_total_assets_amt]),",
              "                target_finance[OrgKey]= VALUES (dim_org[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_org[c3_name] ),",
              "                CALCULATE (",
              "                    SUM (target_finance[target_total_assets_amt]),",
              "                    target_finance[OrgKey] = VALUES (dim_org[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_org[c2_name] ),",
              "                    CALCULATE (",
              "                       SUM (target_finance[target_total_assets_amt]),",
              "                      target_finance[OrgKey]= VALUES (dim_org[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_org[c1_name] ),",
              "                        CALCULATE (",
              "                            SUM (target_finance[target_total_assets_amt]),",
              "                            target_finance[OrgKey] = VALUES ( dim_org[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              " ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "资金_期初总资产实际",
            "expression": [
              "",
              "VAR FIRST = STARTOFMONTH('DimDate'[FullDate])",
              "RETURN",
              "CALCULATE ([资金_总资产实际], 'DimDate'[FullDate] = FIRST)"
            ],
            "formatString": "0.00"
          },
          {
            "name": "资金_总资产实际",
            "expression": [
              "",
              "    IF (",
              "        HASONEVALUE ( dim_org[c5_name] ),",
              "        CALCULATE (",
              "           SUM (result_finance[total_assets_amt]),",
              "             result_finance[OrgKey] = VALUES (dim_org[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_org[c4_name] ),",
              "            CALCULATE (",
              "               SUM (result_finance[total_assets_amt]),",
              "                result_finance[OrgKey] = VALUES (dim_org[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_org[c3_name] ),",
              "                CALCULATE (",
              "                   SUM (result_finance[total_assets_amt]),",
              "                    result_finance[OrgKey] = VALUES (dim_org[c3] )",
              "                ),",
              "                IF (",
              "                    HASONEVALUE (dim_org[c2_name] ),",
              "                    CALCULATE (",
              "                      SUM (result_finance[total_assets_amt]),",
              "                       result_finance[OrgKey] = VALUES (dim_org[c2] )",
              "                    ),",
              "                    IF (",
              "                        HASONEVALUE (dim_org[c1_name] ),",
              "                        CALCULATE (",
              "                           SUM (result_finance[total_assets_amt]),",
              "                            result_finance[OrgKey] = VALUES ( dim_org[c1] )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "  ",
              "    ",
              "   "
            ]
          },
          {
            "name": "资金_期末总资产实际",
            "expression": [
              "",
              "VAR LAST = ENDOFMONTH('DimDate'[FullDate])",
              "VAR LASTMONTH  = STARTOFMONTH(LAST)",
              "RETURN",
              "CALCULATE ([资金_总资产实际], 'DimDate'[FullDate] = LASTMONTH)"
            ]
          },
          {
            "name": "资金_期末总资产目标",
            "expression": [
              "",
              "VAR LAST = ENDOFMONTH('DimDate'[FullDate])",
              "VAR LASTMONTH  = STARTOFMONTH(LAST)",
              "RETURN",
              "CALCULATE ([资金_总资产目标], 'DimDate'[FullDate] =  LASTMONTH)"
            ]
          },
          {
            "name": "资金_期初总资产目标",
            "expression": [
              "",
              "VAR FIRST = STARTOFMONTH('DimDate'[FullDate])",
              "RETURN",
              "CALCULATE ([资金_总资产目标], 'DimDate'[FullDate] = FIRST)"
            ]
          }
        ]
      },
      {
        "name": "雷达_资金效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"总成本费用额(2-目标达成率)\" , \"\", ),",
                "    ( \"销售额\" ,  \"\",) , ",
                "    ( \"回款额\" , \"\", ),",
                "    ( \"净利润额\" ,\"\", ),",
                "    ( \"净利率\" , \"\", ),",
                "    ( \"净现金流\" , \"\", ),",
                "    ( \"投资回报率\" ,\"\",),",
                "    ( \"资金周转率\" , \"\",),",
                "    ( \"资金冗余值\" , \"\", )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1]  )"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "资金目标达成率_雷达",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('雷达_资金效率'[指标])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              "  \"总成本费用额(2-目标达成率)\" , IF([资金_总成本费用额目标达成率]>2,0,2-[资金_总成本费用额目标达成率]),",
              " \"销售额\",IF([资金_销售额目标达成率]<1.5,[资金_销售额目标达成率],1.5),",
              " \"回款额\",IF([资金_回款额目标达成率]<1.5,[资金_回款额目标达成率],1.5),",
              " \"净利润额\",IF([资金_净利润额目标达成率]<1.5,[资金_净利润额目标达成率],1.5),",
              " \"净利率\",IF([资金_净利率目标达成率]<1.5,[资金_净利润额目标达成率],1.5),",
              " \"净现金流\",IF([资金_净现金流目标达成率]<1.5,[资金_净现金流目标达成率],1.5),",
              "  \"投资回报率\",IF( [资金_投资回报率目标达成率]<1.5,[资金_投资回报率目标达成率],1.5),",
              "   \"资金周转率\",IF([资金_资金周转率目标达成率]<1.5,[资金_资金周转率目标达成率],1.5),",
              "    \"资金冗余值\",IF([资金_资金冗余值目标达成率]<1.5,[资金_资金冗余值目标达成率],1.5)",
              " )"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ]
      },
      {
        "name": "度量值_基本竞争力",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "列1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "基本竞争力_销售额目标",
            "expression": [
              "[资金_销售额目标]",
              "                      "
            ],
            "formatString": "0.00"
          },
          {
            "name": "基本竞争力_销售额实际",
            "expression": "[资金_销售额实际]",
            "formatString": "0.00"
          },
          {
            "name": "基本竞争力_销售额目标实际差异",
            "expression": "[基本竞争力_销售额实际]-[基本竞争力_销售额目标]",
            "formatString": "0.00"
          },
          {
            "name": "基本竞争力_销售额目标达成率",
            "expression": "DIVIDE('度量值_基本竞争力'[基本竞争力_销售额实际],'度量值_基本竞争力'[基本竞争力_销售额目标])",
            "formatString": "0.00"
          },
          {
            "name": "基本竞争力_销售额目标_上月同期",
            "expression": [
              "IF(ISBLANK([基本竞争力_销售额目标]),BLANK(), CALCULATE([基本竞争力_销售额目标], DATEADD('DimDate'[FullDate], -1, MONTH))",
              ")"
            ],
            "formatString": "0.00"
          },
          {
            "name": "基本竞争力_销售额实际_上月同期",
            "expression": [
              "IF(ISBLANK([基本竞争力_销售额实际]),BLANK(),CALCULATE([基本竞争力_销售额实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
              ")"
            ],
            "formatString": "0.00"
          },
          {
            "name": "基本竞争力_销售增长额目标",
            "expression": "IF(ISBLANK( [基本竞争力_销售额目标]),BLANK(),[基本竞争力_销售额目标]-[基本竞争力_销售额目标_上月同期])",
            "formatString": "0.00"
          },
          {
            "name": "基本竞争力_销售增长额实际",
            "expression": "IF(ISBLANK( [基本竞争力_销售额实际]),BLANK(),([基本竞争力_销售额实际] -[基本竞争力_销售额实际_上月同期]))",
            "formatString": "0.00"
          },
          {
            "name": "基本竞争力_销售增长额目标实际差异",
            "expression": "[基本竞争力_销售增长额实际]-[基本竞争力_销售增长额目标]",
            "formatString": "0.00"
          },
          {
            "name": "基本竞争力_销售增长额目标达成率",
            "expression": "DIVIDE([基本竞争力_销售增长额实际],[基本竞争力_销售增长额目标])",
            "formatString": "0.00"
          },
          {
            "name": "基本竞争力_销售增长率目标",
            "expression": "DIVIDE([基本竞争力_销售增长额目标],[基本竞争力_销售额目标_上月同期])",
            "formatString": "0.00"
          },
          {
            "name": "基本竞争力_销售增长率实际",
            "expression": "DIVIDE([基本竞争力_销售增长额实际],[基本竞争力_销售额实际_上月同期])",
            "formatString": "0.00"
          },
          {
            "name": "基本竞争力_销售增长率目标实际差异",
            "expression": "[基本竞争力_销售增长率实际]-[基本竞争力_销售增长率目标]",
            "formatString": "0.00"
          },
          {
            "name": "基本竞争力_销售增长率目标达成率",
            "expression": "DIVIDE([基本竞争力_销售增长率实际],[基本竞争力_销售增长率目标])",
            "formatString": "0.00"
          }
        ]
      },
      {
        "name": "雷达_基本竞争力",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"销售额\" ,  \"\",) , ",
                "    ( \"销售增长额\" ,\"\", ),",
                "    ( \"销售增长率\" ,\"\", )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1]  )"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "基本竞争力_雷达",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('雷达_基本竞争力'[指标])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              "    \"销售额\" ,   IF([基本竞争力_销售额目标达成率]<1.5,[基本竞争力_销售额目标达成率],1.5),",
              "     \"销售增长额\" ,IF( [基本竞争力_销售增长额目标达成率]>1.5,1.5,IF([基本竞争力_销售增长额目标达成率]<=0,0,[基本竞争力_销售增长额目标达成率])),",
              "    \"销售增长率\" ,IF([基本竞争力_销售增长率目标达成率]>1.5,1.5,IF([基本竞争力_销售增长率目标达成率]<=0,0,[基本竞争力_销售增长率目标达成率])) ",
              " )"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ]
      },
      {
        "name": "度量值_持续竞争力",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "列1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列4",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "持续竞争力_净利润额目标",
            "expression": "[资金_净利润额目标]",
            "formatString": "0.00"
          },
          {
            "name": "持续竞争力_净利润额实际",
            "expression": "[资金_净利润额实际]",
            "formatString": "0.00"
          },
          {
            "name": "持续竞争力_净利润额目标实际差异",
            "expression": "[持续竞争力_净利润额实际]-[持续竞争力_净利润额目标]",
            "formatString": "0.00"
          },
          {
            "name": "持续竞争力_净利润额目标达成率",
            "expression": "DIVIDE([持续竞争力_净利润额实际],[持续竞争力_净利润额目标])",
            "formatString": "0.00"
          },
          {
            "name": "持续竞争力_净利润额目标_上月同期",
            "expression": [
              "CALCULATE([持续竞争力_净利润额目标], DATEADD('DimDate'[FullDate], -1, MONTH))",
              ""
            ],
            "formatString": "0.00"
          },
          {
            "name": "持续竞争力_净利润额实际_上月同期",
            "expression": [
              "CALCULATE([持续竞争力_净利润额实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
              ""
            ],
            "formatString": "0.00"
          },
          {
            "name": "持续竞争力_净利润增长额目标",
            "expression": "[持续竞争力_净利润额目标]-[持续竞争力_净利润额目标_上月同期]",
            "formatString": "0.00"
          },
          {
            "name": "持续竞争力_净利润增长额实际",
            "expression": "[持续竞争力_净利润额实际]-[持续竞争力_净利润额实际_上月同期]",
            "formatString": "0.00"
          },
          {
            "name": "持续竞争力_净利润增长额目标实际差异",
            "expression": "[持续竞争力_净利润增长额实际]-[持续竞争力_净利润增长额目标]",
            "formatString": "0.00"
          },
          {
            "name": "持续竞争力_净利润增长额目标达成率",
            "expression": "DIVIDE([持续竞争力_净利润增长额实际],[持续竞争力_净利润增长额目标])",
            "formatString": "0.00"
          },
          {
            "name": "持续竞争力_净利率目标",
            "expression": "[资金_净利率目标]",
            "formatString": "0.00"
          },
          {
            "name": "持续竞争力_净利率实际",
            "expression": "[资金_净利率实际]",
            "formatString": "0.00"
          },
          {
            "name": "持续竞争力_净利率目标实际差异",
            "expression": "[持续竞争力_净利率实际]-[持续竞争力_净利率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "持续竞争力_净利率目标达成率",
            "expression": "DIVIDE([持续竞争力_净利率实际],[持续竞争力_净利率目标])",
            "formatString": "0.00"
          },
          {
            "name": "持续竞争力_净利润增长率目标",
            "expression": "DIVIDE([持续竞争力_净利润增长额目标],[持续竞争力_净利润额目标_上月同期])",
            "formatString": "0.00"
          },
          {
            "name": "持续竞争力_净利润增长率实际",
            "expression": "DIVIDE([持续竞争力_净利润增长额实际],[持续竞争力_净利润额实际_上月同期])",
            "formatString": "0.00"
          },
          {
            "name": "持续竞争力_净利润增长率目标实际差异",
            "expression": "[持续竞争力_净利润增长率实际]-[持续竞争力_净利润增长率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "持续竞争力_净利润增长率目标达成率",
            "expression": "DIVIDE([持续竞争力_净利润增长率实际],[持续竞争力_净利润增长率目标])",
            "formatString": "0.00"
          }
        ]
      },
      {
        "name": "雷达_持续竞争力",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"净利润额\" , \"\",) , ",
                "    ( \"净利润增长额\" , \"\", ),",
                "    ( \"净利率\" ,\"\", ),",
                "    ( \"净利润增长率\" ,\"\",)",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] )"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "持续竞争力_雷达",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('雷达_持续竞争力'[指标])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              "   \"净利润额\" ,   IF([持续竞争力_净利润额目标达成率]<1.5, [持续竞争力_净利润额目标达成率],1.5),",
              "    \"净利润增长额\" , IF([持续竞争力_净利润增长额目标达成率]>1.5,1.5,IF([持续竞争力_净利润增长额目标达成率]<0,0,[持续竞争力_净利润增长额目标达成率])),",
              "    \"净利率\" ,IF([持续竞争力_净利率目标达成率]<1.5,[持续竞争力_净利率目标达成率], 1.5), ",
              "    \"净利润增长率\" ,IF([持续竞争力_净利润增长率目标达成率]>1.5,1.5,IF([持续竞争力_净利润增长率目标达成率]<0,0,[持续竞争力_净利润增长率目标达成率]))",
              " )"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ]
      },
      {
        "name": "度量值_核心竞争力_产品效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "列1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列7",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列8",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "核心竞争力_产品效率_SKU数量目标",
            "expression": " CALCULATE(COUNT(tree_product[level]),FILTER('tree_product','tree_product'[level]=6))",
            "formatString": "0"
          },
          {
            "name": "核心竞争力_产品效率_SKU数量实际",
            "expression": "CALCULATE(COUNT(tree_product[level]),FILTER('tree_product','tree_product'[level]=6))",
            "formatString": "0"
          },
          {
            "name": "核心竞争力_产品效率_SKU数量目标实际差异",
            "expression": "[核心竞争力_产品效率_SKU数量实际]-[核心竞争力_产品效率_SKU数量目标]",
            "formatString": "0"
          },
          {
            "name": "核心竞争力_产品效率_SKU数量目标达成率",
            "expression": [
              "DIVIDE([核心竞争力_产品效率_SKU数量实际],[核心竞争力_产品效率_SKU数量实际])",
              ""
            ],
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_毛利润额目标",
            "expression": "[核心竞争力_产品效率_销售额目标]-[核心竞争力_产品效率_产品成本额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_毛利润额实际",
            "expression": "[核心竞争力_产品效率_销售额实际]-[核心竞争力_产品效率_产品成本额实际]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_单品平均毛利润额目标",
            "expression": "DIVIDE([核心竞争力_产品效率_毛利润额目标],[核心竞争力_产品效率_SKU数量目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_单品平均毛利润额实际",
            "expression": "DIVIDE([核心竞争力_产品效率_毛利润额实际],[核心竞争力_产品效率_SKU数量实际])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_单品平均毛利润额目标实际差异",
            "expression": "[核心竞争力_产品效率_单品平均毛利润额实际]-[核心竞争力_产品效率_单品平均毛利润额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_单品平均毛利润额目标达成率",
            "expression": "DIVIDE([核心竞争力_产品效率_单品平均毛利润额实际],[核心竞争力_产品效率_单品平均毛利润额目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_销售额目标",
            "expression": " [产品_销售额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_销售额实际",
            "expression": " [产品_销售额实际]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_单品平均销售额目标",
            "expression": "DIVIDE([核心竞争力_产品效率_销售额目标],[核心竞争力_产品效率_SKU数量目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_单品平均销售额实际",
            "expression": "DIVIDE([核心竞争力_产品效率_销售额实际],[核心竞争力_产品效率_SKU数量实际])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_单品平均销售额目标实际差异",
            "expression": "[核心竞争力_产品效率_单品平均销售额实际]-[核心竞争力_产品效率_单品平均销售额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_单品平均销售额目标达成率",
            "expression": "DIVIDE([核心竞争力_产品效率_单品平均销售额实际],[核心竞争力_产品效率_单品平均销售额目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_产品成本额目标",
            "expression": " [产品_产品成本额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_产品成本额实际",
            "expression": " [产品_产品成本额实际]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_单品平均成本费用额目标",
            "expression": "DIVIDE([核心竞争力_产品效率_产品成本额目标],[核心竞争力_产品效率_SKU数量目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_单品平均成本费用额实际",
            "expression": "DIVIDE([核心竞争力_产品效率_产品成本额实际],[核心竞争力_产品效率_SKU数量实际])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_单品平均成本费用额目标实际差异",
            "expression": "[核心竞争力_产品效率_单品平均成本费用额实际]-[核心竞争力_产品效率_单品平均成本费用额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_单品平均成本费用额目标达成率",
            "expression": "DIVIDE([核心竞争力_产品效率_单品平均成本费用额实际],[核心竞争力_产品效率_单品平均成本费用额目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_投入产出比目标",
            "expression": "[产品_产品投入产出比目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_产品效率_投入产出比实际",
            "expression": "[产品_产品投入产出比实际]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_产品效率_投入产出比目标实际差异",
            "expression": "[核心竞争力_产品效率_投入产出比实际]-[核心竞争力_产品效率_投入产出比目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_产品效率_投入产出比目标达成率",
            "expression": "DIVIDE([核心竞争力_产品效率_投入产出比实际],[核心竞争力_产品效率_投入产出比目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_库存周转率目标",
            "expression": "[产品_库存周转率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_产品效率_库存周转率实际",
            "expression": "[产品_库存周转率实际]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_产品效率_库存周转率目标实际差异",
            "expression": "[核心竞争力_产品效率_库存周转率实际]-[核心竞争力_产品效率_库存周转率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_产品效率_库存周转率目标达成率",
            "expression": "DIVIDE([核心竞争力_产品效率_库存周转率实际],[核心竞争力_产品效率_库存周转率目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_日销目标",
            "expression": "DIVIDE( DIVIDE([核心竞争力_产品效率_销售额目标],'日期_天数'[天数]),[核心竞争力_产品效率_SKU数量实际])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_日销实际",
            "expression": "DIVIDE( [产品_日销实际],[核心竞争力_产品效率_SKU数量实际])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_日销目标实际差异",
            "expression": "[核心竞争力_产品效率_日销实际]-[核心竞争力_产品效率_日销目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_日销目标达成率",
            "expression": "DIVIDE([核心竞争力_产品效率_日销实际],[核心竞争力_产品效率_日销目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_产品冗余值目标",
            "expression": "[产品_库存额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_产品冗余值实际",
            "expression": "[产品_库存额实际]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_产品冗余值目标实际差异",
            "expression": "[核心竞争力_产品效率_产品冗余值实际]-[核心竞争力_产品效率_产品冗余值目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_产品冗余值目标达成率",
            "expression": "DIVIDE([核心竞争力_产品效率_产品冗余值实际],[核心竞争力_产品效率_产品冗余值目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_产品效率_SKU数量目标_未设定",
            "expression": "0",
            "formatString": "未设定"
          }
        ]
      },
      {
        "name": "雷达_核心竞争力_产品效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"SKU数量\" ,   \"\",) , ",
                "    ( \"单品平均毛利润额\" ,\"\", ),",
                "    ( \"单品平均销售额\" ,\"\", ),",
                "    ( \"单品平均成本费用额(2-目标达成率)\" ,\"\",),",
                "    ( \"投入产出比\" ,\"\", ),",
                "    ( \"库存周转率\" ,\"\", ),",
                "    ( \"日销\" ,\"\", ),",
                "    ( \"产品冗余值(2-目标达成率)\" ,\"\", )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "核心_产品效率_雷达",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('雷达_核心竞争力_产品效率'[指标])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              "      \"SKU数量\" , IF( [核心竞争力_产品效率_SKU数量目标达成率]<1.5,[核心竞争力_产品效率_SKU数量目标达成率],1.5),",
              "    \"单品平均毛利润额\" ,IF( [核心竞争力_产品效率_单品平均毛利润额目标达成率]>1.5,1.5,IF([核心竞争力_产品效率_单品平均毛利润额目标达成率]<0,0,[核心竞争力_产品效率_单品平均毛利润额目标达成率])),",
              "    \"单品平均销售额\" ,IF([核心竞争力_产品效率_单品平均销售额目标达成率]<1.5,[核心竞争力_产品效率_单品平均销售额目标达成率],1.5),",
              "    \"单品平均成本费用额(2-目标达成率)\" ,IF([核心竞争力_产品效率_单品平均成本费用额目标达成率]>2,0,2-[核心竞争力_产品效率_单品平均成本费用额目标达成率]),",
              "    \"投入产出比\" ,IF([核心竞争力_产品效率_投入产出比目标达成率]<1.5,[核心竞争力_产品效率_投入产出比目标达成率],1.5),",
              "    \"库存周转率\" ,IF([核心竞争力_产品效率_库存周转率目标达成率]<1.5,[核心竞争力_产品效率_库存周转率目标达成率], 1.5),",
              "    \"日销\" ,IF([核心竞争力_产品效率_日销目标达成率]<1.5,[核心竞争力_产品效率_日销目标达成率], 1.5), ",
              "    \"产品冗余值(2-目标达成率)\" ,IF([核心竞争力_产品效率_产品冗余值目标达成率]>2,0,2-[核心竞争力_产品效率_产品冗余值目标达成率])",
              " )"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ]
      },
      {
        "name": "度量值_核心竞争力_渠道效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "列1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列7",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "核心竞争力_渠道效率_店铺数量目标",
            "expression": "CALCULATE(COUNT(tree_channel[level]),FILTER('tree_channel','tree_channel'[level]=4))",
            "formatString": "0"
          },
          {
            "name": "核心竞争力_渠道效率_店铺数量实际",
            "expression": [
              "CALCULATE(COUNT(tree_channel[level]),FILTER('tree_channel','tree_channel'[level]=4))",
              ""
            ],
            "formatString": "0"
          },
          {
            "name": "核心竞争力_渠道效率_店铺数量目标实际差异",
            "expression": "[核心竞争力_渠道效率_店铺数量实际]-[核心竞争力_渠道效率_店铺数量目标]",
            "formatString": "0"
          },
          {
            "name": "核心竞争力_渠道效率_店铺数量目标达成率",
            "expression": [
              "DIVIDE([核心竞争力_渠道效率_店铺数量实际],[核心竞争力_渠道效率_店铺数量目标])",
              ""
            ],
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_渠道效率_销售额目标",
            "expression": "[渠道_销售额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_渠道效率_销售额实际",
            "expression": "[渠道_销售额实际]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_渠道效率_单店平均销售额目标",
            "expression": "DIVIDE([核心竞争力_渠道效率_销售额目标],[核心竞争力_渠道效率_店铺数量目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_渠道效率_单店平均销售额实际",
            "expression": "DIVIDE([核心竞争力_渠道效率_销售额实际],[核心竞争力_渠道效率_店铺数量目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_渠道效率_单店平均销售额目标实际差异",
            "expression": "[核心竞争力_渠道效率_单店平均销售额实际]-[核心竞争力_渠道效率_单店平均销售额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_渠道效率_单店平均销售额目标达成率",
            "expression": "DIVIDE([核心竞争力_渠道效率_单店平均销售额实际],[核心竞争力_渠道效率_单店平均销售额目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_渠道效率_成本费用额目标",
            "expression": "[渠道_渠道费用额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_渠道效率_成本费用额实际",
            "expression": "[渠道_渠道费用额实际]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_渠道效率_单店平均成本费用额目标",
            "expression": "DIVIDE([核心竞争力_渠道效率_成本费用额目标],[核心竞争力_渠道效率_店铺数量目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_渠道效率_单店平均成本费用额实际",
            "expression": "DIVIDE([核心竞争力_渠道效率_成本费用额实际],[核心竞争力_渠道效率_店铺数量实际])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_渠道效率_单店平均成本费用额目标实际差异",
            "expression": "[核心竞争力_渠道效率_单店平均成本费用额实际]-[核心竞争力_渠道效率_单店平均成本费用额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_渠道效率_单店平均成本费用额目标达成率",
            "expression": "DIVIDE([核心竞争力_渠道效率_单店平均成本费用额实际],[核心竞争力_渠道效率_单店平均成本费用额目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_渠道效率_营业利润额目标",
            "expression": "[渠道_渠道营业利润额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_渠道效率_营业利润额实际",
            "expression": "[渠道_渠道营业利润额实际]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_渠道效率_单店平均营业利润额目标",
            "expression": "DIVIDE([核心竞争力_渠道效率_营业利润额目标],[核心竞争力_渠道效率_店铺数量目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_渠道效率_单店平均营业利润额实际",
            "expression": "DIVIDE([核心竞争力_渠道效率_营业利润额实际],[核心竞争力_渠道效率_店铺数量目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_渠道效率_单店平均营业利润额目标实际差异",
            "expression": "[核心竞争力_渠道效率_单店平均营业利润额实际]-[核心竞争力_渠道效率_单店平均营业利润额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_渠道效率_单店平均营业利润额目标达成率",
            "expression": "DIVIDE([核心竞争力_渠道效率_单店平均营业利润额实际],[核心竞争力_渠道效率_单店平均营业利润额目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_渠道效率_投入产出比目标",
            "expression": "[渠道_渠道投入产出比目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_渠道效率_投入产出比实际",
            "expression": "[渠道_渠道投入产出比实际]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_渠道效率_投入产出比目标实际差异",
            "expression": "[核心竞争力_渠道效率_投入产出比实际]-[核心竞争力_渠道效率_投入产出比目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_渠道效率_投入产出比目标达成率",
            "expression": "DIVIDE([核心竞争力_渠道效率_投入产出比实际],[核心竞争力_渠道效率_投入产出比目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_渠道效率_渠道冗余值目标",
            "expression": [
              " ",
              "\t",
              "\tSWITCH (",
              "    \t\tTRUE (),",
              "    \t\t[核心竞争力_渠道效率_投入产出比目标]<0, [核心竞争力_渠道效率_成本费用额目标],",
              "\t\tAND([核心竞争力_渠道效率_投入产出比目标]>0, [核心竞争力_渠道效率_投入产出比目标]<1), [核心竞争力_渠道效率_成本费用额目标]-[核心竞争力_渠道效率_营业利润额目标],",
              "    \t\t[核心竞争力_渠道效率_投入产出比目标]>1, 0\t)"
            ],
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_渠道效率_渠道冗余值实际",
            "expression": [
              " ",
              "\t",
              "\tSWITCH (",
              "    \t\tTRUE (),",
              "    \t\t[核心竞争力_渠道效率_投入产出比实际]<0, [核心竞争力_渠道效率_成本费用额实际],",
              "\t\tAND([核心竞争力_渠道效率_投入产出比实际]>0, [核心竞争力_渠道效率_投入产出比实际]<1), [核心竞争力_渠道效率_成本费用额实际]-[核心竞争力_渠道效率_营业利润额实际],",
              "    \t\t[核心竞争力_渠道效率_投入产出比实际]>1, 0\t)"
            ],
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_渠道效率_渠道冗余值目标实际差异",
            "expression": "[核心竞争力_渠道效率_渠道冗余值实际]-[核心竞争力_渠道效率_渠道冗余值目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_渠道效率_渠道冗余值目标达成率",
            "expression": "DIVIDE([核心竞争力_渠道效率_渠道冗余值实际],[核心竞争力_渠道效率_渠道冗余值目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_渠道效率_日销目标",
            "expression": "DIVIDE( [渠道_日销目标],'日期_天数'[天数])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_渠道效率_日销实际",
            "expression": "DIVIDE( [渠道_日销实际],'日期_天数'[天数])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_渠道效率_日销目标实际差异",
            "expression": "[核心竞争力_渠道效率_日销实际]-[核心竞争力_渠道效率_日销目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_渠道效率_日销目标达成率",
            "expression": "DIVIDE([核心竞争力_渠道效率_日销实际],[核心竞争力_渠道效率_日销目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_渠道效率_店铺数量目标_未设定",
            "expression": "0",
            "formatString": "未设定"
          }
        ]
      },
      {
        "name": "雷达_核心竞争力_渠道效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"店铺数量\" , \"\",) , ",
                "    ( \"单店平均营业利润额\" ,\"\",) , ",
                "    ( \"单店平均销售额\" ,\"\",) , ",
                "    ( \"单店平均成本费用额(2-目标达成率)\" ,\"\",) , ",
                "    ( \"投入产出比\" , \"\",) , ",
                "    ( \"渠道冗余值\" , \"\",) , ",
                "    ( \"日销\" , \"\",)",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] )"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "核心_渠道效率_雷达",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('雷达_核心竞争力_渠道效率'[指标])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              "       \"店铺数量\" , IF([核心竞争力_渠道效率_店铺数量目标达成率]<1.5, [核心竞争力_渠道效率_店铺数量目标达成率],1.5),",
              "     \"单店平均营业利润额\" , IF( [核心竞争力_渠道效率_单店平均营业利润额目标达成率]>1.5,1.5,IF([核心竞争力_渠道效率_单店平均营业利润额目标达成率]<0,0,[核心竞争力_渠道效率_单店平均营业利润额目标达成率])),",
              "     \"单店平均销售额\" , IF([核心竞争力_渠道效率_单店平均销售额目标达成率]<1.5, [核心竞争力_渠道效率_单店平均销售额目标达成率],1.5),",
              "     \"单店平均成本费用额(2-目标达成率)\" ,IF([核心竞争力_渠道效率_单店平均成本费用额目标达成率]>2,0,2- [核心竞争力_渠道效率_单店平均成本费用额目标达成率]),",
              "     \"投入产出比\" ,IF( [核心竞争力_渠道效率_投入产出比目标达成率]<1.5,[核心竞争力_渠道效率_投入产出比目标达成率],1.5),",
              "    \"渠道冗余值\" ,IF( [核心竞争力_渠道效率_渠道冗余值目标达成率]<1.5, [核心竞争力_渠道效率_渠道冗余值目标达成率],1.5),",
              "     \"日销\" ,IF( [核心竞争力_渠道效率_日销目标达成率]<1.5,[核心竞争力_渠道效率_日销目标达成率],1.5)",
              " )"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ]
      },
      {
        "name": "度量值_核心竞争力_客户效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "列1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列7",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "核心竞争力_客户效率_消费者人数目标",
            "expression": " SUMX('fact_company','fact_company'[consumer_count])",
            "formatString": "0"
          },
          {
            "name": "核心竞争力_客户效率_消费者人数实际",
            "expression": "SUMX('fact_company','fact_company'[consumer_count])",
            "formatString": "0"
          },
          {
            "name": "核心竞争力_客户效率_消费者人数目标实际差异",
            "expression": "[核心竞争力_客户效率_消费者人数实际]-[核心竞争力_客户效率_消费者人数目标]",
            "formatString": "0"
          },
          {
            "name": "核心竞争力_客户效率_消费者人数目标达成率",
            "expression": "DIVIDE([核心竞争力_客户效率_消费者人数实际],[核心竞争力_客户效率_消费者人数目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_客户效率_销售额目标",
            "expression": " [客户_销售额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_客户效率_销售额实际",
            "expression": "[客户_销售额实际]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_客户效率_消费者人均销售额目标",
            "expression": "DIVIDE([核心竞争力_客户效率_销售额目标],[核心竞争力_客户效率_消费者人数目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_客户效率_消费者人均销售额实际",
            "expression": "DIVIDE([核心竞争力_客户效率_销售额实际],[核心竞争力_客户效率_消费者人数实际])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_客户效率_消费者人均销售额目标实际差异",
            "expression": "[核心竞争力_客户效率_消费者人均销售额实际]-[核心竞争力_客户效率_消费者人均销售额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_客户效率_消费者人均销售额目标达成率",
            "expression": "DIVIDE([核心竞争力_客户效率_消费者人均销售额实际],[核心竞争力_客户效率_消费者人均销售额目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_客户效率_客户费用额目标",
            "expression": "[客户_客户费用额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_客户效率_客户费用额实际",
            "expression": "[客户_客户费用额实际]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_客户效率_消费者人均成本费用额目标",
            "expression": "DIVIDE([核心竞争力_客户效率_客户费用额目标],[核心竞争力_客户效率_消费者人数目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_客户效率_消费者人均成本费用额实际",
            "expression": "DIVIDE([核心竞争力_客户效率_客户费用额实际],[核心竞争力_客户效率_消费者人数实际])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_客户效率_消费者人均成本费用额目标实际差异",
            "expression": "[核心竞争力_客户效率_消费者人均成本费用额实际]-[核心竞争力_客户效率_消费者人均成本费用额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_客户效率_消费者人均成本费用额目标达成率",
            "expression": "DIVIDE([核心竞争力_客户效率_消费者人均成本费用额实际],[核心竞争力_客户效率_消费者人均成本费用额目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_客户效率_客户利润额目标",
            "expression": " [客户_客户利润额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_客户效率_客户利润额实际",
            "expression": "[客户_客户利润额实际]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_客户效率_消费者人均客户利润额目标",
            "expression": "DIVIDE([核心竞争力_客户效率_客户利润额目标],[核心竞争力_客户效率_消费者人数目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_客户效率_消费者人均客户利润额实际",
            "expression": "DIVIDE([核心竞争力_客户效率_客户利润额实际],[核心竞争力_客户效率_消费者人数实际])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_客户效率_消费者人均客户利润额目标达成率",
            "expression": "DIVIDE([核心竞争力_客户效率_消费者人均客户利润额实际],[核心竞争力_客户效率_消费者人均客户利润额目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_客户效率_消费者人均客户利润额目标实际差异",
            "expression": "[核心竞争力_客户效率_消费者人均客户利润额实际]-[核心竞争力_客户效率_消费者人均客户利润额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_客户效率_日销目标",
            "expression": "DIVIDE( DIVIDE([核心竞争力_客户效率_销售额目标],'日期_天数'[天数]),[核心竞争力_客户效率_消费者人数目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_客户效率_日销实际",
            "expression": "DIVIDE( DIVIDE([核心竞争力_客户效率_销售额实际],'日期_天数'[天数]),[核心竞争力_客户效率_消费者人数实际])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_客户效率_日销目标实际差异",
            "expression": "[核心竞争力_客户效率_日销实际]-[核心竞争力_客户效率_日销目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_客户效率_日销目标达成率",
            "expression": "DIVIDE([核心竞争力_客户效率_日销实际],[核心竞争力_客户效率_日销目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_客户效率_投入产出比目标",
            "expression": "[客户_客户投入产出比目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_客户效率_投入产出比实际",
            "expression": "[客户_客户投入产出比实际]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_客户效率_投入产出比目标实际差异",
            "expression": "[核心竞争力_客户效率_投入产出比实际]-[核心竞争力_客户效率_投入产出比目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_客户效率_投入产出比目标达成率",
            "expression": "DIVIDE([核心竞争力_客户效率_投入产出比实际],[核心竞争力_客户效率_投入产出比目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_客户效率_消费者冗余值目标",
            "expression": "[客户_客户冗余值目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_客户效率_消费者冗余值实际",
            "expression": "[客户_客户冗余值实际]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_客户效率_消费者冗余值目标实际差异",
            "expression": "[核心竞争力_客户效率_消费者冗余值实际]-[核心竞争力_客户效率_消费者冗余值目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_客户效率_消费者冗余值目标达成率",
            "expression": "DIVIDE([核心竞争力_客户效率_消费者冗余值实际],[核心竞争力_客户效率_消费者冗余值目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_客户效率_消费者人数目标_未设定",
            "expression": "0",
            "formatString": "未设定"
          }
        ]
      },
      {
        "name": "雷达_核心竞争力_客户效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"消费者人数\" , \"\",) , ",
                "    ( \"消费者人均销售额\" ,  \"\",) , ",
                "    ( \"消费者人均客户利润额\" , \"\",) , ",
                "    ( \"消费者人均成本费用额(2-目标达成率)\" ,\"\",) , ",
                "    ( \"日销\" , \"\",) , ",
                "    ( \"投入产出比\" , \"\",) , ",
                "    ( \"消费者冗余值\" , \"\",) ",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1]  )"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "核心_客户效率_雷达",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('雷达_核心竞争力_客户效率'[指标])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              "     \"消费者人数\" , IF( [核心竞争力_客户效率_消费者人数目标达成率]<1.5,[核心竞争力_客户效率_消费者人数目标达成率],1.5),",
              "     \"消费者人均销售额\" , IF( [核心竞争力_客户效率_消费者人均销售额目标达成率]<1.5,[核心竞争力_客户效率_消费者人均销售额目标达成率],1.5),",
              "     \"消费者人均客户利润额\" ,IF( [核心竞争力_客户效率_消费者人均客户利润额目标达成率]<1.5,[核心竞争力_客户效率_消费者人均客户利润额目标达成率],1.5),",
              "     \"消费者人均成本费用额(2-目标达成率)\" ,IF( [核心竞争力_客户效率_消费者人均成本费用额目标达成率]>2,0,2- [核心竞争力_客户效率_消费者人均成本费用额目标达成率]),",
              "     \"日销\" ,IF( [核心竞争力_客户效率_日销目标达成率]<1.5,[核心竞争力_客户效率_日销目标达成率],1.5),",
              "     \"投入产出比\" , IF([核心竞争力_客户效率_投入产出比目标达成率]<1.5,[核心竞争力_客户效率_投入产出比目标达成率],1.5),",
              "    \"消费者冗余值\" ,IF( [核心竞争力_客户效率_消费者冗余值目标达成率]<1.5,[核心竞争力_客户效率_消费者冗余值目标达成率],1.5)",
              " )"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ]
      },
      {
        "name": "度量值_核心竞争力_供应效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "列1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列7",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "核心竞争力_供应效率_工厂数量目标",
            "expression": "CALCULATE(COUNT(tree_supply[level]),FILTER('tree_supply','tree_supply'[level]=3))",
            "formatString": "0"
          },
          {
            "name": "核心竞争力_供应效率_工厂数量实际",
            "expression": "CALCULATE(COUNT(tree_supply[level]),FILTER('tree_supply','tree_supply'[level]=3))",
            "formatString": "0"
          },
          {
            "name": "核心竞争力_供应效率_工厂数量目标实际差异",
            "expression": "[核心竞争力_供应效率_工厂数量实际]-[核心竞争力_供应效率_工厂数量目标]",
            "formatString": "0"
          },
          {
            "name": "核心竞争力_供应效率_工厂数量目标达成率",
            "expression": "DIVIDE([核心竞争力_供应效率_工厂数量实际],[核心竞争力_供应效率_工厂数量目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_供应效率_销售额目标",
            "expression": " [供应_供应销售额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_供应效率_销售额实际",
            "expression": " [供应_供应销售额实际]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_供应效率_工厂平均销售额目标",
            "expression": " DIVIDE([核心竞争力_产品效率_销售额目标],[核心竞争力_供应效率_工厂数量目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_供应效率_工厂平均销售额实际",
            "expression": " DIVIDE([核心竞争力_产品效率_销售额实际],[核心竞争力_供应效率_工厂数量实际])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_供应效率_工厂平均销售额目标实际差异",
            "expression": "[核心竞争力_供应效率_工厂平均销售额实际]-[核心竞争力_供应效率_工厂平均销售额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_供应效率_工厂平均销售额目标达成率",
            "expression": "DIVIDE([核心竞争力_供应效率_工厂平均销售额实际],[核心竞争力_供应效率_工厂平均销售额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_供应效率_毛利额目标",
            "expression": "[供应_供应利润额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_供应效率_毛利额实际",
            "expression": "[供应_供应利润额实际]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_供应效率_工厂平均毛利额目标",
            "expression": " DIVIDE([核心竞争力_供应效率_毛利额目标],[核心竞争力_供应效率_工厂数量目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_供应效率_工厂平均毛利额实际",
            "expression": " DIVIDE([核心竞争力_供应效率_毛利额实际],[核心竞争力_供应效率_工厂数量实际])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_供应效率_工厂平均毛利额目标实际差异",
            "expression": "[核心竞争力_供应效率_工厂平均毛利额实际]-[核心竞争力_供应效率_工厂平均毛利额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_供应效率_工厂平均毛利额目标达成率",
            "expression": "DIVIDE([核心竞争力_供应效率_工厂平均毛利额实际],[核心竞争力_供应效率_工厂平均毛利额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_供应效率_计划生产件数目标",
            "expression": "[核心竞争力_供应效率_计划生产件数实际]",
            "formatString": "0"
          },
          {
            "name": "核心竞争力_供应效率_计划生产件数实际",
            "expression": "[计划生产件数]",
            "formatString": "0"
          },
          {
            "name": "核心竞争力_供应效率_工厂平均产能目标",
            "expression": " DIVIDE([供应_供应产能目标],[核心竞争力_供应效率_工厂数量目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_供应效率_工厂平均产能实际",
            "expression": " DIVIDE([核心竞争力_供应效率_计划生产件数实际],[核心竞争力_供应效率_工厂数量实际])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_供应效率_工厂平均产能目标实际差异",
            "expression": "[核心竞争力_供应效率_工厂平均产能实际]-[核心竞争力_供应效率_工厂平均产能目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_供应效率_工厂平均产能目标达成率",
            "expression": "DIVIDE([核心竞争力_供应效率_工厂平均产能实际],[核心竞争力_供应效率_工厂平均产能目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_供应效率_产供比目标",
            "expression": "[供应_供应产供比目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_供应效率_产供比实际",
            "expression": "[供应_供应产供比实际]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_供应效率_产供比目标实际差异",
            "expression": "[核心竞争力_供应效率_产供比实际]-[核心竞争力_供应效率_产供比目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_供应效率_产供比目标达成率",
            "expression": "DIVIDE([核心竞争力_供应效率_产供比实际],[核心竞争力_供应效率_产供比目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_供应效率_工厂平均残品率目标",
            "expression": "[供应_残品率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_供应效率_工厂平均残品率实际",
            "expression": "[供应_残品率实际]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_供应效率_工厂平均残品率目标实际差异",
            "expression": "[核心竞争力_供应效率_工厂平均残品率实际]-[核心竞争力_供应效率_工厂平均残品率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_供应效率_工厂平均残品率目标达成率",
            "expression": "DIVIDE([核心竞争力_供应效率_工厂平均残品率实际],[核心竞争力_供应效率_工厂平均残品率目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_供应效率_工厂平均交期达成率目标",
            "expression": "[供应_交期达成率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_供应效率_工厂平均交期达成率实际",
            "expression": "[供应_交期达成率实际]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_供应效率_工厂平均交期达成率目标实际差异",
            "expression": "[核心竞争力_供应效率_工厂平均交期达成率实际]-[核心竞争力_供应效率_工厂平均交期达成率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_供应效率_工厂平均交期达成率目标达成率",
            "expression": "DIVIDE([核心竞争力_供应效率_工厂平均交期达成率实际],[核心竞争力_供应效率_工厂平均交期达成率目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_供应效率_工厂数量目标_未设定",
            "expression": "0",
            "formatString": "未设定"
          }
        ]
      },
      {
        "name": "雷达_核心竞争力_供应效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"工厂数量\" ,  \"\",) , ",
                "    ( \"工厂平均销售额\" ,  \"\",) , ",
                "    ( \"工厂平均毛利额\" , \"\",),",
                "    ( \"工厂平均产能(2-目标达成率)\" ,\"\",) , ",
                "    ( \"产供比\" ,\"\",) , ",
                "    ( \"工厂平均残品率(2-目标达成率)\" , \"\",) , ",
                "    ( \"工厂平均交期达成率\" , \"\",) ",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] )"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "核心_供应效率_雷达",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('雷达_核心竞争力_供应效率'[指标])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              "    \"工厂数量\" , IF( [核心竞争力_供应效率_工厂数量目标达成率]<1.5,[核心竞争力_供应效率_工厂数量目标达成率],1.5),",
              "     \"工厂平均销售额\" , IF( [核心竞争力_供应效率_工厂平均销售额目标达成率]<1.5, [核心竞争力_供应效率_工厂平均销售额目标达成率],1.5),",
              "     \"工厂平均毛利额\" ,IF( [核心竞争力_供应效率_工厂平均毛利额目标达成率]<1.5, [核心竞争力_供应效率_工厂平均毛利额目标达成率],1.5),",
              "     \"工厂平均产能(2-目标达成率)\" ,IF([核心竞争力_供应效率_工厂平均产能目标达成率]>2,0,2- [核心竞争力_供应效率_工厂平均产能目标达成率]),",
              "     \"产供比\" ,IF( [核心竞争力_供应效率_产供比目标达成率]<1.5, [核心竞争力_供应效率_产供比目标达成率],1.5),",
              "     \"工厂平均残品率(2-目标达成率)\" , IF([核心竞争力_供应效率_工厂平均残品率目标达成率]>2,0,2-[核心竞争力_供应效率_工厂平均残品率目标达成率]),",
              "     \"工厂平均交期达成率\" , IF([核心竞争力_供应效率_工厂平均交期达成率目标达成率]<1.5,[核心竞争力_供应效率_工厂平均交期达成率目标达成率],1.5)",
              " )"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ]
      },
      {
        "name": "度量值_核心竞争力_组织效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "列1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列7",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "核心竞争力_组织效率_企业人数目标",
            "expression": "SUMX('fact_company','fact_company'[enterprise_count])",
            "formatString": "0"
          },
          {
            "name": "核心竞争力_组织效率_企业人数实际",
            "expression": "SUMX('fact_company','fact_company'[enterprise_count])",
            "formatString": "0"
          },
          {
            "name": "核心竞争力_组织效率_企业人数目标实际差异",
            "expression": "[核心竞争力_组织效率_企业人数实际]-[核心竞争力_组织效率_企业人数目标]",
            "formatString": "0"
          },
          {
            "name": "核心竞争力_组织效率_企业人数目标达成率",
            "expression": "DIVIDE([核心竞争力_组织效率_企业人数实际],[核心竞争力_组织效率_企业人数目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_组织效率_销售额目标",
            "expression": " [组织_销售额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_组织效率_销售额实际",
            "expression": " [组织_销售额实际]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_组织效率_企业人均销售额目标",
            "expression": "DIVIDE([核心竞争力_组织效率_销售额目标],[核心竞争力_组织效率_企业人数目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_组织效率_企业人均销售额实际",
            "expression": "DIVIDE([核心竞争力_组织效率_销售额实际],[核心竞争力_组织效率_企业人数实际])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_组织效率_企业人均销售额目标达成率",
            "expression": "DIVIDE([核心竞争力_组织效率_企业人均销售额实际],[核心竞争力_组织效率_企业人均销售额目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_组织效率_企业人均销售额目标实际差异",
            "expression": "[核心竞争力_组织效率_企业人均销售额实际]-[核心竞争力_组织效率_企业人均销售额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_组织效率_人力成本额目标",
            "expression": " [组织_人力成本额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_组织效率_人力成本额实际",
            "expression": "[组织_人力成本额实际]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_组织效率_企业人均成本额目标",
            "expression": "DIVIDE([核心竞争力_组织效率_人力成本额目标],[核心竞争力_组织效率_企业人数目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_组织效率_企业人均成本额实际",
            "expression": "DIVIDE([核心竞争力_组织效率_人力成本额实际],[核心竞争力_组织效率_企业人数实际])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_组织效率_企业人均成本额目标实际差异",
            "expression": "[核心竞争力_组织效率_企业人均成本额实际]-[核心竞争力_组织效率_企业人均成本额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_组织效率_企业人均成本额目标达成率",
            "expression": "DIVIDE([核心竞争力_组织效率_企业人均成本额实际],[核心竞争力_组织效率_企业人均成本额目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_组织效率_净利润额目标",
            "expression": "[组织_净利润额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_组织效率_净利润额实际",
            "expression": " [组织_净利润额实际]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_组织效率_企业人均净利润额目标",
            "expression": "DIVIDE([核心竞争力_组织效率_净利润额目标],[核心竞争力_组织效率_企业人数目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_组织效率_企业人均净利润额实际",
            "expression": "DIVIDE([核心竞争力_组织效率_净利润额实际],[核心竞争力_组织效率_企业人数实际])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_组织效率_企业人均净利润额目标实际差异",
            "expression": "[核心竞争力_组织效率_企业人均净利润额实际]-[核心竞争力_组织效率_企业人均净利润额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_组织效率_企业人均净利润额目标达成率",
            "expression": "DIVIDE([核心竞争力_组织效率_企业人均净利润额实际],[核心竞争力_组织效率_企业人均净利润额目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_组织效率_投入产出比目标",
            "expression": "DIVIDE([核心竞争力_组织效率_净利润额目标],[核心竞争力_组织效率_人力成本额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_组织效率_投入产出比实际",
            "expression": "DIVIDE([核心竞争力_组织效率_净利润额实际],[核心竞争力_组织效率_人力成本额实际])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_组织效率_投入产出比目标实际差异",
            "expression": "[核心竞争力_组织效率_投入产出比实际]-[核心竞争力_组织效率_投入产出比目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_组织效率_投入产出比目标达成率",
            "expression": "DIVIDE([核心竞争力_组织效率_投入产出比实际],[核心竞争力_组织效率_投入产出比目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_组织效率_日销目标",
            "expression": "DIVIDE( DIVIDE([核心竞争力_组织效率_销售额目标],'日期_天数'[天数]),[核心竞争力_组织效率_企业人数目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_组织效率_日销实际",
            "expression": "DIVIDE( DIVIDE([核心竞争力_组织效率_销售额实际],'日期_天数'[天数]),[核心竞争力_组织效率_企业人数实际])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_组织效率_日销目标实际差异",
            "expression": "[核心竞争力_组织效率_日销实际]-[核心竞争力_组织效率_日销目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_组织效率_日销目标达成率",
            "expression": "DIVIDE([核心竞争力_组织效率_日销实际],[核心竞争力_组织效率_日销目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_组织效率_企业人均冗余值目标",
            "expression": "[组织_人员冗余值目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_组织效率_企业人均冗余值实际",
            "expression": "[组织_人员冗余值实际]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_组织效率_企业人均冗余值目标实际差异",
            "expression": "[核心竞争力_组织效率_企业人均冗余值实际]-[核心竞争力_组织效率_企业人均冗余值目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_组织效率_企业人均冗余值目标达成率",
            "expression": "DIVIDE([核心竞争力_组织效率_企业人均冗余值实际],[核心竞争力_组织效率_企业人均冗余值目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_组织效率_企业人数目标_未设定",
            "expression": "0",
            "formatString": "未设定"
          }
        ]
      },
      {
        "name": "雷达_核心竞争力_组织效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"企业人数\" ,  \"\",) , ",
                "    ( \"企业人均净利润额\" , \"\",) , ",
                "    ( \"企业人均销售额\" , \"\",) , ",
                "    ( \"企业人均成本额(2-目标达成率)\" ,\"\",) , ",
                "    ( \"投入产出比\" , \"\",) , ",
                "    ( \"日销\" , \"\",) , ",
                "    ( \"企业人均冗余值\" , \"\",) ",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1]  )"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "核心_组织效率_雷达",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('雷达_核心竞争力_组织效率'[指标])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              "        \"企业人数\" ,  IF([核心竞争力_组织效率_企业人数目标达成率]<1.5, [核心竞争力_组织效率_企业人数目标达成率],1.5),",
              "     \"企业人均净利润额\" ,IF( [核心竞争力_组织效率_企业人均净利润额目标达成率]<1.5,[核心竞争力_组织效率_企业人均净利润额目标达成率],1.5),",
              "    \"企业人均销售额\" ,  IF( [核心竞争力_组织效率_企业人均销售额目标达成率]<1.5,[核心竞争力_组织效率_企业人均销售额目标达成率],1.5),",
              "     \"企业人均成本额(2-目标达成率)\" ,IF( [核心竞争力_组织效率_企业人均成本额目标达成率]>2,0,2- [核心竞争力_组织效率_企业人均成本额目标达成率]),",
              "     \"投入产出比\" ,IF( [核心竞争力_组织效率_投入产出比目标达成率]<1.5, [核心竞争力_组织效率_投入产出比目标达成率],1.5),",
              "     \"日销\" , IF( [核心竞争力_组织效率_日销目标达成率]<1.5,[核心竞争力_组织效率_日销目标达成率],1.5),",
              "    \"企业人均冗余值\" ,IF( [核心竞争力_组织效率_企业人均冗余值目标达成率]<1.5,[核心竞争力_组织效率_企业人均冗余值目标达成率],1.5)",
              " )"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ]
      },
      {
        "name": "度量值_核心竞争力_资金效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "列1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列7",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列8",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列9",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "核心竞争力_资金效率_总成本费用额目标",
            "expression": "[资金_总成本费用额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_资金效率_总成本费用额实际",
            "expression": "[资金_总成本费用额实际]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_资金效率_总成本费用额目标实际差异",
            "expression": "[核心竞争力_资金效率_总成本费用额实际]-[核心竞争力_资金效率_总成本费用额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_资金效率_总成本费用额目标达成率",
            "expression": "DIVIDE([核心竞争力_资金效率_总成本费用额实际],[核心竞争力_资金效率_总成本费用额目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_资金效率_销售额目标",
            "expression": "[资金_销售额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_资金效率_销售额实际",
            "expression": "[资金_销售额实际]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_资金效率_销售额目标实际差异",
            "expression": "[核心竞争力_资金效率_销售额实际]-[核心竞争力_资金效率_销售额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_资金效率_销售额目标达成率",
            "expression": "DIVIDE([核心竞争力_资金效率_销售额实际],[核心竞争力_资金效率_销售额目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_资金效率_回款额目标",
            "expression": "[资金_回款额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_资金效率_回款额实际",
            "expression": "[资金_回款额实际]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_资金效率_回款额目标实际差异",
            "expression": "[核心竞争力_资金效率_回款额实际]-[核心竞争力_资金效率_回款额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_资金效率_回款额目标达成率",
            "expression": "DIVIDE([核心竞争力_资金效率_回款额实际],[核心竞争力_资金效率_回款额目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_资金效率_净利润额目标",
            "expression": "[资金_净利润额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_资金效率_净利润额实际",
            "expression": "[资金_净利润额实际]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_资金效率_净利润额目标实际差异",
            "expression": "[核心竞争力_资金效率_净利润额实际]-[核心竞争力_资金效率_净利润额目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_资金效率_净利润额目标达成率",
            "expression": "DIVIDE([核心竞争力_资金效率_净利润额实际],[核心竞争力_资金效率_净利润额目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_资金效率_净利率目标",
            "expression": "[资金_净利率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_资金效率_净利率实际",
            "expression": "[资金_净利率实际]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_资金效率_净利率目标实际差异",
            "expression": "[核心竞争力_资金效率_净利率实际]-[核心竞争力_资金效率_净利率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_资金效率_净利率目标达成率",
            "expression": "DIVIDE([核心竞争力_资金效率_净利率实际],[核心竞争力_资金效率_净利率目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_资金效率_净现金流目标",
            "expression": "[资金_净现金流目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_资金效率_净现金流实际",
            "expression": "[资金_净现金流实际]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_资金效率_净现金流目标实际差异",
            "expression": "[核心竞争力_资金效率_净现金流实际]-[核心竞争力_资金效率_净现金流目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_资金效率_净现金流目标达成率",
            "expression": "DIVIDE([核心竞争力_资金效率_净现金流实际],[核心竞争力_资金效率_净现金流目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_资金效率_投资回报率目标",
            "expression": "[资金_投资回报率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_资金效率_投资回报率实际",
            "expression": "[资金_投资回报率实际]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_资金效率_投资回报率目标实际差异",
            "expression": "[核心竞争力_资金效率_投资回报率实际]-[核心竞争力_资金效率_投资回报率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_资金效率_投资回报率目标达成率",
            "expression": "DIVIDE([核心竞争力_资金效率_投资回报率实际],[核心竞争力_资金效率_投资回报率目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_资金效率_资金周转率目标",
            "expression": "[资金_资金周转率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_资金效率_资金周转率实际",
            "expression": "[资金_资金周转率实际]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_资金效率_资金周转率目标实际差异",
            "expression": "[核心竞争力_资金效率_资金周转率实际]-[核心竞争力_资金效率_资金周转率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "核心竞争力_资金效率_资金周转率目标达成率",
            "expression": "DIVIDE([核心竞争力_资金效率_资金周转率实际],[核心竞争力_资金效率_资金周转率目标])",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_资金效率_资金冗余值目标",
            "expression": "[资金_资金冗余值目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_资金效率_资金冗余值实际",
            "expression": "[资金_资金冗余值实际]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_资金效率_资金冗余值目标实际差异",
            "expression": "[核心竞争力_资金效率_资金冗余值实际]-[核心竞争力_资金效率_资金冗余值目标]",
            "formatString": "0.00"
          },
          {
            "name": "核心竞争力_资金效率_资金冗余值目标达成率",
            "expression": "DIVIDE([核心竞争力_资金效率_资金冗余值实际],[核心竞争力_资金效率_资金冗余值目标])",
            "formatString": "0.00"
          }
        ]
      },
      {
        "name": "雷达_核心竞争力_资金效率",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"总成本费用额(2-目标达成率)\" , \"\",) , ",
                "    ( \"销售额\" ,  \"\",) , ",
                "    ( \"回款额\" ,\"\",) , ",
                "    ( \"净利润额\" ,  \"\",) , ",
                "    ( \"净利率\" , \"\",) , ",
                "    ( \"净现金流\" , \"\",) , ",
                "    ( \"投资回报率\" , \"\",) , ",
                "    ( \"资金周转率\" ,\"\",) , ",
                "    ( \"资金冗余值\" , \"\",)",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] )"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "核心_资金效率_雷达",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('雷达_核心竞争力_资金效率'[指标])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              "      \"总成本费用额(2-目标达成率)\" , IF([核心竞争力_资金效率_总成本费用额目标达成率]>2,0,2-[核心竞争力_资金效率_总成本费用额目标达成率]),",
              "     \"销售额\" ,   IF([核心竞争力_资金效率_销售额目标达成率]<1.5, [核心竞争力_资金效率_销售额目标达成率],1.5),",
              "     \"回款额\" ,IF([核心竞争力_资金效率_回款额目标达成率]<1.5,[核心竞争力_资金效率_回款额目标达成率],1.5),",
              "    \"净利润额\" ,  IF( [核心竞争力_资金效率_净利润额目标达成率]<1.5,[核心竞争力_资金效率_净利润额目标达成率],1.5),",
              "     \"净利率\" ,IF( [核心竞争力_资金效率_净利率目标达成率]<1.5,[核心竞争力_资金效率_净利率目标达成率],1.5),",
              "    \"净现金流\" ,IF( [核心竞争力_资金效率_净现金流目标达成率]<1.5, [核心竞争力_资金效率_净现金流目标达成率],1.5),",
              "     \"投资回报率\" , IF([核心竞争力_资金效率_投资回报率目标达成率]<1.5,[核心竞争力_资金效率_投资回报率目标达成率],1.5),",
              "     \"资金周转率\" ,IF([核心竞争力_资金效率_资金周转率目标达成率]<1.5,[核心竞争力_资金效率_资金周转率目标达成率],1.5),",
              "     \"资金冗余值\" ,IF( [核心竞争力_资金效率_资金冗余值目标达成率]<1.5, [核心竞争力_资金效率_资金冗余值目标达成率],1.5)",
              " )"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ]
      },
      {
        "name": "度量值_品牌价值",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "列1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列4",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "品牌价值_品质合格率目标",
            "expression": "1-[供应_残品率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "品牌价值_品质合格率实际",
            "expression": "1-[供应_残品率实际]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "品牌价值_品质合格率目标实际差异",
            "expression": "[品牌价值_品质合格率实际]-[品牌价值_品质合格率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "品牌价值_品质合格率目标达成率",
            "expression": "DIVIDE([品牌价值_品质合格率实际],[品牌价值_品质合格率目标])",
            "formatString": "0.00"
          },
          {
            "name": "品牌价值_传播网点数目标",
            "expression": "SUMX('target_company','target_company'[target_dot_count])",
            "formatString": "0"
          },
          {
            "name": "品牌价值_传播网点数实际",
            "expression": "SUMX('fact_company','fact_company'[dot_count])",
            "formatString": "0"
          },
          {
            "name": "品牌价值_传播网点数目标实际差异",
            "expression": "[品牌价值_传播网点数实际]-[品牌价值_传播网点数目标]",
            "formatString": "0"
          },
          {
            "name": "品牌价值_传播网点数目标达成率",
            "expression": "DIVIDE([品牌价值_传播网点数实际],[品牌价值_传播网点数目标])",
            "formatString": "0.00"
          },
          {
            "name": "品牌价值_传播成本目标",
            "expression": "SUMX('target_company','target_company'[target_dot_amt])",
            "formatString": "0.00"
          },
          {
            "name": "品牌价值_传播成本实际",
            "expression": "SUMX('fact_company','fact_company'[dot_amt])",
            "formatString": "0.00"
          },
          {
            "name": "品牌价值_传播成本目标实际差异",
            "expression": "[品牌价值_传播成本实际]-[品牌价值_传播成本目标]",
            "formatString": "0.00"
          },
          {
            "name": "品牌价值_传播成本目标达成率",
            "expression": "DIVIDE([品牌价值_传播成本实际],[品牌价值_传播成本目标])",
            "formatString": "0.00"
          },
          {
            "name": "品牌价值_传播的投入产出比目标",
            "expression": "DIVIDE('度量值_资金效率'[资金_净利润额目标],'度量值_品牌价值'[品牌价值_传播成本目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "品牌价值_传播的投入产出比实际",
            "expression": "DIVIDE('度量值_资金效率'[资金_净利润额实际],'度量值_品牌价值'[品牌价值_传播成本实际])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "品牌价值_传播的投入产出比目标实际差异",
            "expression": "[品牌价值_传播的投入产出比实际]-[品牌价值_传播的投入产出比目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "品牌价值_传播的投入产出比目标达成率",
            "expression": "DIVIDE([品牌价值_传播的投入产出比实际],[品牌价值_传播的投入产出比目标])",
            "formatString": "0.00"
          }
        ]
      },
      {
        "name": "雷达_品牌价值",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"品质合格率\" , \"\",) , ",
                "    ( \"传播网点数\" , \"\",) , ",
                "    ( \"传播成本\" ,\"\",) , ",
                "    ( \"传播的投入产出比\" ,\"\",)",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] )"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "品牌价值_雷达",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('雷达_品牌价值'[指标])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              "     \"品质合格率\" ,  IF( [品牌价值_品质合格率目标达成率]<1.5, [品牌价值_品质合格率目标达成率],1.5),",
              "    \"传播网点数\" ,IF( [品牌价值_传播网点数目标达成率]<1.5,[品牌价值_传播网点数目标达成率],1.5),",
              "    \"传播成本\" ,IF([品牌价值_传播成本目标达成率]<1.5,[品牌价值_传播成本目标达成率],1.5),",
              "    \"传播的投入产出比\" ,IF([品牌价值_传播的投入产出比目标达成率]<1.5,[品牌价值_传播的投入产出比目标达成率],1.5)",
              " )"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ]
      },
      {
        "name": "度量值_盈利空间",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "列1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列7",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列8",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "盈利空间_毛利率目标",
            "expression": "DIVIDE('度量值_产品效率'[产品_毛利润额目标],'度量值_产品效率'[产品_销售额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "盈利空间_毛利率实际",
            "expression": "DIVIDE('度量值_产品效率'[产品_毛利润额实际],'度量值_产品效率'[产品_销售额实际])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "盈利空间_毛利率目标实际差异",
            "expression": "[盈利空间_毛利率实际]-[盈利空间_毛利率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "盈利空间_毛利率目标达成率",
            "expression": "DIVIDE([盈利空间_毛利率实际],[盈利空间_毛利率目标])",
            "formatString": "0.00"
          },
          {
            "name": "盈利空间_回款额目标",
            "expression": "[资金_回款额目标]",
            "formatString": "0.00"
          },
          {
            "name": "盈利空间_回款额实际",
            "expression": "[资金_回款额实际]",
            "formatString": "0.00"
          },
          {
            "name": "盈利空间_回款额目标实际差异",
            "expression": "[盈利空间_回款额实际]-[盈利空间_回款额目标]",
            "formatString": "0.00"
          },
          {
            "name": "盈利空间_回款额目标达成率",
            "expression": "DIVIDE([盈利空间_回款额实际],[盈利空间_回款额目标])",
            "formatString": "0.00"
          },
          {
            "name": "盈利空间_回款额目标_上月同期",
            "expression": [
              "CALCULATE([盈利空间_回款额目标], DATEADD('DimDate'[FullDate], -1, MONTH))",
              ""
            ],
            "formatString": "0.00"
          },
          {
            "name": "盈利空间_回款额实际_上月同期",
            "expression": [
              "CALCULATE([盈利空间_回款额实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
              ""
            ],
            "formatString": "0.00"
          },
          {
            "name": "盈利空间_回款增长额目标",
            "expression": "[盈利空间_回款额目标]-[盈利空间_回款额目标_上月同期]",
            "formatString": "0.00"
          },
          {
            "name": "盈利空间_回款增长额实际",
            "expression": "[盈利空间_回款额实际]-[盈利空间_回款额实际_上月同期]",
            "formatString": "0.00"
          },
          {
            "name": "盈利空间_回款增长额目标实际差异",
            "expression": "[盈利空间_回款增长额实际]-[盈利空间_回款增长额目标]",
            "formatString": "0.00"
          },
          {
            "name": "盈利空间_回款增长额目标达成率",
            "expression": " DIVIDE([盈利空间_回款增长额实际],[盈利空间_回款增长额目标])",
            "formatString": "0.00"
          },
          {
            "name": "盈利空间_回款增长率目标",
            "expression": "DIVIDE([盈利空间_回款增长额目标],[盈利空间_回款额目标_上月同期])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "盈利空间_回款增长率实际",
            "expression": "DIVIDE([盈利空间_回款增长额实际],[盈利空间_回款额实际_上月同期])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "盈利空间_回款增长率目标实际差异",
            "expression": "[盈利空间_回款增长率实际]-[盈利空间_回款增长率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "盈利空间_回款增长率目标达成率",
            "expression": " DIVIDE([盈利空间_回款增长率实际],[盈利空间_回款增长率目标])",
            "formatString": "0.00"
          },
          {
            "name": "盈利空间_总成本费用额目标",
            "expression": "[资金_总成本费用额目标]",
            "formatString": "0.00"
          },
          {
            "name": "盈利空间_总成本费用额实际",
            "expression": "[资金_总成本费用额实际]",
            "formatString": "0.00"
          },
          {
            "name": "盈利空间_总成本费用额目标实际差异",
            "expression": "[盈利空间_总成本费用额实际]-[盈利空间_总成本费用额目标]",
            "formatString": "0.00"
          },
          {
            "name": "盈利空间_总成本费用额目标达成率",
            "expression": "DIVIDE([盈利空间_总成本费用额实际],[盈利空间_总成本费用额目标])",
            "formatString": "0.00"
          },
          {
            "name": "盈利空间_总成本费用额目标_上月同期",
            "expression": "CALCULATE([盈利空间_总成本费用额目标], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "盈利空间_总成本费用额实际_上月同期",
            "expression": "CALCULATE([盈利空间_总成本费用额实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "盈利空间_总成本费用增长额目标",
            "expression": "[盈利空间_总成本费用额目标]-[盈利空间_总成本费用额目标_上月同期]",
            "formatString": "0.00"
          },
          {
            "name": "盈利空间_总成本费用增长额实际",
            "expression": "[盈利空间_总成本费用额实际]-[盈利空间_总成本费用额实际_上月同期]",
            "formatString": "0.00"
          },
          {
            "name": "盈利空间_总成本费用增长额目标实际差异",
            "expression": "[盈利空间_总成本费用增长额实际]-[盈利空间_总成本费用增长额目标]",
            "formatString": "0.00"
          },
          {
            "name": "盈利空间_总成本费用增长额目标达成率",
            "expression": " DIVIDE([盈利空间_总成本费用增长额实际],[盈利空间_总成本费用增长额目标])",
            "formatString": "0.00"
          },
          {
            "name": "盈利空间_总成本费用增长率目标",
            "expression": " DIVIDE([盈利空间_总成本费用增长额目标],[盈利空间_总成本费用额目标_上月同期])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "盈利空间_总成本费用增长率实际",
            "expression": " DIVIDE([盈利空间_总成本费用增长额实际],[盈利空间_总成本费用额实际_上月同期])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "盈利空间_总成本费用增长率目标实际差异",
            "expression": "[盈利空间_总成本费用增长率实际]-[盈利空间_总成本费用增长率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "盈利空间_总成本费用增长率目标达成率",
            "expression": " DIVIDE([盈利空间_总成本费用增长率实际],[盈利空间_总成本费用增长率目标])",
            "formatString": "0.00"
          },
          {
            "name": "盈利空间_盈利空间目标",
            "expression": "DIVIDE([盈利空间_回款额目标],[盈利空间_总成本费用额目标])",
            "formatString": "0.00"
          },
          {
            "name": "盈利空间_盈利空间实际",
            "expression": "DIVIDE([盈利空间_回款额实际],[盈利空间_总成本费用额实际])",
            "formatString": "0.00"
          },
          {
            "name": "盈利空间_盈利空间目标实际差异",
            "expression": "[盈利空间_盈利空间实际]-[盈利空间_盈利空间目标]",
            "formatString": "0.00"
          },
          {
            "name": "盈利空间_盈利空间目标达成率",
            "expression": "DIVIDE([盈利空间_盈利空间实际],[盈利空间_盈利空间目标])",
            "formatString": "0.00"
          }
        ]
      },
      {
        "name": "雷达_盈利空间",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"毛利率\" ,   \"\",) , ",
                "    ( \"回款额\" ,\"\",) , ",
                "    ( \"回款增长额\" ,\"\",) , ",
                "    ( \"回款增长率\" ,\"\",) , ",
                "    ( \"总成本费用额(2-目标达成率)\" , \"\",) , ",
                "    ( \"总成本费用增长额\" ,\"\",) , ",
                "    ( \"总成本费用增长率\" ,\"\",) , ",
                "    ( \"盈利空间\" ,\"\",) ",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1]  )"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "盈利空间_雷达",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('雷达_盈利空间'[指标])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              "      \"毛利率\" , IF( [盈利空间_毛利率目标达成率]<1.5, [盈利空间_毛利率目标达成率],1.5),",
              "     \"回款额\" ,IF( [盈利空间_回款额目标达成率]<1.5, [盈利空间_回款额目标达成率],1.5),",
              "     \"回款增长额\" ,IF([盈利空间_回款增长额目标达成率]<1.5,[盈利空间_回款增长额目标达成率],1.5),",
              "     \"回款增长率\" ,IF([盈利空间_回款增长率目标达成率]<1.5,[盈利空间_回款增长率目标达成率],1.5),",
              "     \"总成本费用额(2-目标达成率)\" , IF([盈利空间_总成本费用额目标达成率]>2,0, 2-[盈利空间_总成本费用额目标达成率]),",
              "     \"总成本费用增长额\" ,IF( [盈利空间_总成本费用增长额目标达成率]<1.5,[盈利空间_总成本费用增长额目标达成率],1.5),",
              "     \"总成本费用增长率\" ,IF([盈利空间_总成本费用增长率目标达成率]<1.5,[盈利空间_总成本费用增长率目标达成率],1.5),",
              "     \"盈利空间\" ,IF([盈利空间_盈利空间目标达成率]<1.5,[盈利空间_盈利空间目标达成率],1.5)",
              " )"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ]
      },
      {
        "name": "度量值_盈利能力",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "列1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列7",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列8",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列9",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "盈利能力_订单额目标",
            "expression": "[资金_销售额目标]",
            "formatString": "0.00"
          },
          {
            "name": "盈利能力_订单额实际",
            "expression": "[资金_销售额实际]",
            "formatString": "0.00"
          },
          {
            "name": "盈利能力_订单额目标实际差异",
            "expression": "[盈利能力_订单额实际]-[盈利能力_订单额目标]",
            "formatString": "0.00"
          },
          {
            "name": "盈利能力_订单额目标达成率",
            "expression": "DIVIDE([盈利能力_订单额实际],[盈利能力_订单额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "盈利能力_订单额目标_上月同期",
            "expression": "CALCULATE([盈利能力_订单额目标], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "盈利能力_订单额实际_上月同期",
            "expression": "CALCULATE([盈利能力_订单额实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "盈利能力_订单增长额目标",
            "expression": "[盈利能力_订单额目标]-[盈利能力_订单额目标_上月同期]",
            "formatString": "0.00"
          },
          {
            "name": "盈利能力_订单增长额实际",
            "expression": "[盈利能力_订单额实际]-[盈利能力_订单额实际_上月同期]",
            "formatString": "0.00"
          },
          {
            "name": "盈利能力_订单增长额目标实际差异",
            "expression": "[盈利能力_订单增长额实际]-[盈利能力_订单增长额目标]",
            "formatString": "0.00"
          },
          {
            "name": "盈利能力_订单增长额目标达成率",
            "expression": "DIVIDE([盈利能力_订单增长额实际],[盈利能力_订单增长额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "盈利能力_订单增长率目标",
            "expression": "DIVIDE([盈利能力_订单增长额目标],[盈利能力_订单额目标_上月同期])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "盈利能力_订单增长率实际",
            "expression": " DIVIDE([盈利能力_订单增长额实际],[盈利能力_订单额实际_上月同期])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "盈利能力_订单增长率目标实际差异",
            "expression": "[盈利能力_订单增长率实际]-[盈利能力_订单增长率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "盈利能力_订单增长率目标达成率",
            "expression": "DIVIDE([盈利能力_订单增长率实际],[盈利能力_订单增长率目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "盈利能力_库存额目标",
            "expression": "[产品_库存额目标]",
            "formatString": "0.00"
          },
          {
            "name": "盈利能力_库存额实际",
            "expression": "[产品_库存额实际]",
            "formatString": "0.00"
          },
          {
            "name": "盈利能力_库存额目标实际差异",
            "expression": "[盈利能力_库存额实际]-[盈利能力_库存额目标]",
            "formatString": "0.00"
          },
          {
            "name": "盈利能力_库存额目标达成率",
            "expression": "DIVIDE([盈利能力_库存额实际],[盈利能力_库存额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "盈利能力_库存额目标_上月同期",
            "expression": "CALCULATE([盈利能力_库存额目标], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "盈利能力_库存额实际_上月同期",
            "expression": "CALCULATE([盈利能力_库存额实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "盈利能力_库存增长额目标",
            "expression": "[盈利能力_库存额目标]-[盈利能力_库存额目标_上月同期]",
            "formatString": "0.00"
          },
          {
            "name": "盈利能力_库存增长额实际",
            "expression": "[盈利能力_库存额实际]-[盈利能力_库存额实际_上月同期]",
            "formatString": "0.00"
          },
          {
            "name": "盈利能力_库存增长额目标实际差异",
            "expression": "[盈利能力_库存增长额实际]-[盈利能力_库存增长额目标]",
            "formatString": "0.00"
          },
          {
            "name": "盈利能力_库存增长额目标达成率",
            "expression": "DIVIDE([盈利能力_库存增长额实际],[盈利能力_库存增长额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "盈利能力_库存增长率目标",
            "expression": "DIVIDE([盈利能力_库存增长额目标],[盈利能力_库存额目标_上月同期])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "盈利能力_库存增长率实际",
            "expression": "DIVIDE([盈利能力_库存增长额实际],[盈利能力_库存额实际_上月同期])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "盈利能力_库存增长率目标实际差异",
            "expression": "[盈利能力_库存增长率实际]-[盈利能力_库存增长率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "盈利能力_库存增长率目标达成率",
            "expression": "DIVIDE([盈利能力_库存增长率实际],[盈利能力_库存增长率目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "盈利能力_库存周转率目标",
            "expression": "[产品_库存周转率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "盈利能力_库存周转率实际",
            "expression": "[产品_库存周转率实际]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "盈利能力_库存周转率目标实际差异",
            "expression": "[盈利能力_库存周转率实际]-[盈利能力_库存周转率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "盈利能力_库存周转率目标达成率",
            "expression": "DIVIDE([盈利能力_库存周转率实际],[盈利能力_库存周转率目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "盈利能力_库龄目标",
            "expression": "SUMX('target_company','target_company'[target_age])",
            "formatString": "0.00"
          },
          {
            "name": "盈利能力_库龄实际",
            "expression": "SUMX('fact_company','fact_company'[age])",
            "formatString": "0.00"
          },
          {
            "name": "盈利能力_库龄目标实际差异",
            "expression": "[盈利能力_库龄实际]-[盈利能力_库龄目标]",
            "formatString": "0.00"
          },
          {
            "name": "盈利能力_库龄目标达成率",
            "expression": "DIVIDE([盈利能力_库龄实际],[盈利能力_库龄目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "盈利能力_盈利能力目标",
            "expression": "DIVIDE([盈利能力_订单额目标],[盈利能力_库存额目标])",
            "formatString": "0.00"
          },
          {
            "name": "盈利能力_盈利能力实际",
            "expression": "DIVIDE([盈利能力_订单额实际],[盈利能力_库存额实际])",
            "formatString": "0.00"
          },
          {
            "name": "盈利能力_盈利能力目标实际差异",
            "expression": "[盈利能力_盈利能力实际]-[盈利能力_盈利能力目标]",
            "formatString": "0.00"
          },
          {
            "name": "盈利能力_盈利能力目标达成率",
            "expression": "DIVIDE([盈利能力_盈利能力实际],[盈利能力_盈利能力目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ]
      },
      {
        "name": "雷达_盈利能力",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"订单额\" ,  \"\",) , ",
                "    ( \"订单增长额\" ,\"\",) , ",
                "    ( \"订单增长率\" ,\"\",) , ",
                "    ( \"库存额(2-目标达成率)\" ,\"\",) , ",
                "    ( \"库存增长额\" , \"\",) , ",
                "    ( \"库存增长率\" , \"\",) , ",
                "    ( \"库存周转率\" ,\"\",) , ",
                "    ( \"库龄\",\"\",) , ",
                "    ( \"盈利能力\" ,\"\",)",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] )"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "盈利能力_雷达",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('雷达_盈利能力'[指标])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              "       \"订单额\" , IF( [盈利能力_订单额目标达成率]<1.5,[盈利能力_订单额目标达成率],1.5),",
              "     \"订单增长额\" ,IF( [盈利能力_订单增长额目标达成率]<1.5,[盈利能力_订单增长额目标达成率],1.5),",
              "     \"订单增长率\" ,IF([盈利能力_订单增长率目标达成率]<1.5,[盈利能力_订单增长率目标达成率],1.5),",
              "    \"库存额(2-目标达成率)\" ,IF([盈利能力_库存额目标达成率]>2,0,2-[盈利能力_库存额目标达成率]),",
              "    \"库存增长额\" ,IF( [盈利能力_库存增长额目标达成率]<1.5, [盈利能力_库存增长额目标达成率],1.5),",
              "    \"库存增长率\" ,IF( [盈利能力_库存增长率目标达成率]<1.5,[盈利能力_库存增长率目标达成率],1.5),",
              "    \"库存周转率\" ,IF([盈利能力_库存周转率目标达成率]<1.5,[盈利能力_库存周转率目标达成率],1.5),",
              "    \"库龄\",IF([盈利能力_库龄目标达成率]<1.5,[盈利能力_库龄目标达成率],1.5),",
              "     \"盈利能力\" ,IF([盈利能力_盈利能力目标达成率]<1.5,[盈利能力_盈利能力目标达成率],1.5)",
              " )"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ]
      },
      {
        "name": "度量值_支付能力",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "列1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          },
          {
            "type": "calculated",
            "name": "列2",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列3",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列4",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列5",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列6",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列7",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列8",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列9",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列10",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列11",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列12",
            "dataType": "int64",
            "isDataTypeInferred": true
          },
          {
            "type": "calculated",
            "name": "列13",
            "dataType": "int64",
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "支付能力_资金周转率目标",
            "expression": "[资金_资金周转率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "支付能力_资金周转率实际",
            "expression": "[资金_资金周转率实际]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "支付能力_资金周转率目标实际差异",
            "expression": "[支付能力_资金周转率实际]-[支付能力_资金周转率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "支付能力_资金周转率目标达成率",
            "expression": "DIVIDE([支付能力_资金周转率实际],[支付能力_资金周转率目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "支付能力_固定资产目标",
            "expression": [
              "",
              "                    IF (",
              "                        HASONEVALUE (dim_org[c1_name] ),",
              "                        CALCULATE (",
              "                            SUM (target_company[target_fixed_assets_amt]),",
              "                            target_finance[OrgKey] = VALUES ( dim_org[c1] )",
              "                        )",
              "                    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "支付能力_固定资产实际",
            "expression": "SUMX('fact_company','fact_company'[fixed_assets_amt])",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_总资产目标",
            "expression": "[资金_总资产目标]",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_总资产实际",
            "expression": "[资金_总资产实际]",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_固定资产占用率目标",
            "expression": "DIVIDE([支付能力_固定资产目标],[支付能力_总资产目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "支付能力_固定资产占用率实际",
            "expression": "DIVIDE([支付能力_固定资产实际],[支付能力_总资产实际])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "支付能力_固定资产占用率目标实际差异",
            "expression": "[支付能力_固定资产占用率实际]-[支付能力_固定资产占用率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "支付能力_固定资产占用率目标达成率",
            "expression": "DIVIDE([支付能力_固定资产占用率实际],[支付能力_固定资产占用率目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "支付能力_现金流入目标",
            "expression": "[资金_现金流入目标]",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_现金流入实际",
            "expression": "[资金_现金流入实际]",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_现金流入目标实际差异",
            "expression": "[支付能力_现金流入实际]-[支付能力_现金流入目标]",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_现金流入目标达成率",
            "expression": "DIVIDE([支付能力_现金流入实际],[支付能力_现金流入目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "支付能力_现金流出目标",
            "expression": "[资金_现金流出目标]",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_现金流出实际",
            "expression": "[资金_现金流出实际]",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_现金流出目标实际差异",
            "expression": "[支付能力_现金流出实际]-[支付能力_现金流出目标]",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_现金流出目标达成率",
            "expression": "DIVIDE([支付能力_现金流出实际],[支付能力_现金流出目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "支付能力_净现金流目标",
            "expression": "[资金_净现金流目标]",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_净现金流实际",
            "expression": "[资金_净现金流实际]",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_净现金流目标实际差异",
            "expression": "[支付能力_净现金流实际]-[支付能力_净现金流目标]",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_净现金流目标达成率",
            "expression": "DIVIDE([支付能力_净现金流实际],[支付能力_净现金流目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "支付能力_应收额目标",
            "expression": [
              "",
              "                    IF (",
              "                        HASONEVALUE (dim_org[c1_name] ),",
              "                        CALCULATE (",
              "                            SUM (target_company[target_receivable_amt]),",
              "                            target_finance[OrgKey] = VALUES ( dim_org[c1] )",
              "                        )",
              "                    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "支付能力_应收额实际",
            "expression": "SUMX('fact_company','fact_company'[receivable_amt])",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_应收额目标实际差异",
            "expression": "[支付能力_应收额实际]-[支付能力_应收额目标]",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_应收额目标达成率",
            "expression": "DIVIDE([支付能力_应收额实际],[支付能力_应收额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "支付能力_应收额目标_上月同期",
            "expression": "CALCULATE([支付能力_应收额目标], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_应收额实际_上月同期",
            "expression": "CALCULATE([支付能力_应收额实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_应收增长额目标",
            "expression": "[支付能力_应收额目标]-[支付能力_应收额目标_上月同期]",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_应收增长额实际",
            "expression": "[支付能力_应收额实际]-[支付能力_应收额实际_上月同期]",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_应收增长额目标实际差异",
            "expression": "[支付能力_应收增长额实际]-[支付能力_应收增长额目标]",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_应收增长额目标达成率",
            "expression": "DIVIDE([支付能力_应收增长额实际],[支付能力_应收增长额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "支付能力_应收增长率目标",
            "expression": "DIVIDE([支付能力_应收增长额目标],[支付能力_应收额目标_上月同期])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "支付能力_应收增长率实际",
            "expression": "DIVIDE([支付能力_应收增长额实际],[支付能力_应收额实际_上月同期])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "支付能力_应收增长率目标实际差异",
            "expression": "[支付能力_应收增长率实际]-[支付能力_应收增长率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "支付能力_应收增长率目标达成率",
            "expression": "DIVIDE([支付能力_应收增长率实际],[支付能力_应收增长率目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "支付能力_应付额目标",
            "expression": [
              "",
              "                    IF (",
              "                        HASONEVALUE (dim_org[c1_name] ),",
              "                        CALCULATE (",
              "                            SUM (target_company[target_payable_amt]),",
              "                            target_finance[OrgKey] = VALUES ( dim_org[c1] )",
              "                        )",
              "                    )",
              "  ",
              "    ",
              "   "
            ],
            "formatString": "0.00"
          },
          {
            "name": "支付能力_应付额实际",
            "expression": "SUMX('fact_company','fact_company'[payable_amt])",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_应付额目标实际差异",
            "expression": "[支付能力_应付额实际]-[支付能力_应付额目标]",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_应付额目标达成率",
            "expression": "DIVIDE([支付能力_应付额实际],[支付能力_应付额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "支付能力_应付额目标_上月同期",
            "expression": "CALCULATE([支付能力_应付额目标], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_应付额实际_上月同期",
            "expression": "CALCULATE([支付能力_应付额实际], DATEADD('DimDate'[FullDate], -1, MONTH))",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_应付增长额目标",
            "expression": "[支付能力_应付额目标]-[支付能力_应付额目标_上月同期]",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_应付增长额实际",
            "expression": "[支付能力_应付额实际]-[支付能力_应付额实际_上月同期]",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_应付增长额目标实际差异",
            "expression": "[支付能力_应付增长额实际]-[支付能力_应付增长额目标]",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_应付增长额目标达成率",
            "expression": "DIVIDE([支付能力_应付增长额实际],[支付能力_应付增长额目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "支付能力_应付增长率目标",
            "expression": "DIVIDE([支付能力_应付增长额目标],[支付能力_应付额目标_上月同期])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "支付能力_应付增长率实际",
            "expression": "DIVIDE([支付能力_应付增长额实际],[支付能力_应付额实际_上月同期])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "支付能力_应付增长率目标实际差异",
            "expression": "[支付能力_应付增长率实际]-[支付能力_应付增长率目标]",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "支付能力_应付增长率目标达成率",
            "expression": "DIVIDE([支付能力_应付增长率实际],[支付能力_应付增长率目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "支付能力_支付能力1目标",
            "expression": "DIVIDE([支付能力_应收额目标],[支付能力_净现金流目标])",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_支付能力1实际",
            "expression": "DIVIDE([支付能力_应收额实际],[支付能力_净现金流实际])",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_支付能力1目标实际差异",
            "expression": "[支付能力_支付能力1实际]-[支付能力_支付能力1目标]",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_支付能力1目标达成率",
            "expression": "DIVIDE([支付能力_支付能力1实际],[支付能力_支付能力1目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "支付能力_支付能力2目标",
            "expression": "DIVIDE([支付能力_应付额目标],[支付能力_净现金流目标])",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_支付能力2实际",
            "expression": "DIVIDE([支付能力_应付额实际],[支付能力_净现金流实际])",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_支付能力2目标实际差异",
            "expression": "[支付能力_支付能力2实际]-[支付能力_支付能力2目标]",
            "formatString": "0.00"
          },
          {
            "name": "支付能力_支付能力2目标达成率",
            "expression": "DIVIDE([支付能力_支付能力2实际],[支付能力_支付能力2目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ]
      },
      {
        "name": "雷达_支付能力",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"资金周转率\" ,   \"\",) , ",
                "    ( \"固定资产占用率\" , \"\",) , ",
                "    ( \"现金流入\" ,\"\",) , ",
                "    ( \"现金流出\" ,\"\",) , ",
                "    ( \"净现金流\" , \"\",) , ",
                "    ( \"应收额\" , \"\",) , ",
                "    ( \"应收增长额\" ,\"\",) , ",
                "    ( \"应收增长率\",\"\",) , ",
                "    ( \"应付额\" ,\"\",) , ",
                "    ( \"应付增长额\" ,\"\",) , ",
                "    ( \"应付增长率\" ,\"\",) , ",
                "    ( \"支付能力1\" ,\"\",) , ",
                "    ( \"支付能力2\" ,\"\",) ",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] )"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "支付能力_雷达",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('雷达_支付能力'[指标])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              "      \"资金周转率\" ,  IF( [支付能力_资金周转率目标达成率]<1.5, [支付能力_资金周转率目标达成率],1.5),",
              "     \"固定资产占用率\" , IF([支付能力_固定资产占用率目标达成率]<1.5, [支付能力_固定资产占用率目标达成率],1.5),",
              "    \"现金流入\" ,IF([支付能力_现金流入目标达成率]<1.5,[支付能力_现金流入目标达成率],1.5),",
              "    \"现金流出\" ,IF([支付能力_现金流出目标达成率]<1.5,[支付能力_现金流出目标达成率],1.5),",
              "     \"净现金流\" ,IF( [支付能力_净现金流目标达成率]>1.5,1.5,IF([支付能力_净现金流目标达成率]<0,0,[支付能力_净现金流目标达成率])),",
              "     \"应收额\" ,IF( [支付能力_应收额目标达成率]<1.5,[支付能力_应收额目标达成率],1.5),",
              "     \"应收增长额\" ,IF([支付能力_应收增长额目标达成率]<1.5 ,[支付能力_应收增长额目标达成率],1.5),",
              "     \"应收增长率\",IF([支付能力_应收增长率目标达成率]<1.5,[支付能力_应收增长率目标达成率],1.5),",
              "    \"应付额\" ,IF([支付能力_应付额目标达成率]<1.5 ,[支付能力_应付额目标达成率],1.5),",
              "     \"应付增长额\" ,IF([支付能力_应付增长额目标达成率]<1.5,[支付能力_应付增长额目标达成率],1.5),",
              "     \"应付增长率\" ,IF([支付能力_应付增长率目标达成率]<1.5,[支付能力_应付增长率目标达成率],1.5),",
              "     \"支付能力1\" ,IF([支付能力_支付能力1目标达成率]<1.5,[支付能力_支付能力1目标达成率],1.5),",
              "    \"支付能力2\" ,IF([支付能力_支付能力2目标达成率]<1.5 ,[支付能力_支付能力2目标达成率],1.5)",
              " )"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ]
      },
      {
        "name": "日期_天数",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": " ",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "天数",
            "expression": " DATEDIFF(MIN('DimDate'[FullDate]),MAX('DimDate'[FullDate]),DAY) +1",
            "formatString": "0"
          },
          {
            "name": "销售件数",
            "expression": "SUMX('fact_order','fact_order'[qty])",
            "formatString": "0.00"
          }
        ]
      },
      {
        "name": "result_customer",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "sale_amt",
            "dataType": "double",
            "sourceColumn": "sale_amt"
          },
          {
            "name": "cost_amt",
            "dataType": "double",
            "sourceColumn": "cost_amt"
          },
          {
            "name": "cus_cost_amt",
            "dataType": "double",
            "sourceColumn": "cus_cost_amt"
          },
          {
            "name": "redundancy",
            "dataType": "double",
            "sourceColumn": "redundancy"
          },
          {
            "name": "input_output_ratio",
            "dataType": "double",
            "sourceColumn": "input_output_ratio"
          },
          {
            "name": "day_sale_amt",
            "dataType": "double",
            "sourceColumn": "day_sale_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          },
          {
            "name": "profit_amt",
            "dataType": "double",
            "sourceColumn": "profit_amt"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_result_customer = Source{[Schema=\"dbo\",Item=\"result_customer\"]}[Data]",
                "in",
                "    dbo_result_customer"
              ]
            }
          }
        ]
      },
      {
        "name": "result_supply",
        "columns": [
          {
            "name": "SupplyKey",
            "dataType": "int64",
            "sourceColumn": "SupplyKey"
          },
          {
            "name": "sale_amt",
            "dataType": "double",
            "sourceColumn": "sale_amt"
          },
          {
            "name": "cost_amt",
            "dataType": "double",
            "sourceColumn": "cost_amt"
          },
          {
            "name": "order_amt",
            "dataType": "double",
            "sourceColumn": "order_amt"
          },
          {
            "name": "planned_production_qty",
            "dataType": "double",
            "sourceColumn": "planned_production_qty"
          },
          {
            "name": "actual_production_qty",
            "dataType": "double",
            "sourceColumn": "actual_production_qty"
          },
          {
            "name": "defective_qty",
            "dataType": "double",
            "sourceColumn": "defective_qty"
          },
          {
            "name": "profit_amt",
            "dataType": "double",
            "sourceColumn": "profit_amt"
          },
          {
            "name": "production_ratio",
            "dataType": "double",
            "sourceColumn": "production_ratio"
          },
          {
            "name": "residual_rate",
            "dataType": "double",
            "sourceColumn": "residual_rate"
          },
          {
            "name": "delivery_rate",
            "dataType": "double",
            "sourceColumn": "delivery_rate"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_result_supply = Source{[Schema=\"dbo\",Item=\"result_supply\"]}[Data]",
                "in",
                "    dbo_result_supply"
              ]
            }
          }
        ]
      },
      {
        "name": "产品_指标动态维度",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "subject_name",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[subject_name]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \"毛利润额\",\"\" ),",
                "    ( \"销售额\"  ,\"\" ),",
                "     ( \"产品成本额\" ,\"\" ),",
                "      ( \"产品投入产出比\" ,\"\" ),",
                "       ( \"库存周转率\" ,\"\" ),",
                "        ( \"日销\" ,\"\" ),",
                "         ( \"库存额\"  ,\"\")",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"subject_name\" , [Value1] )"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "产品实际",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('产品_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"产品成本额\", [产品_产品成本额实际],",
              " \"毛利润额\",[产品_毛利润额实际],",
              " \"销售额\",[产品_销售额实际],",
              " \"产品投入产出比\",[产品_产品投入产出比实际],",
              " \"日销\",[产品_日销实际],",
              " \"库存周转率\",[产品_库存周转率实际],",
              " \"库存额\",[产品_库存额实际]",
              " )"
            ]
          },
          {
            "name": "产品目标",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('产品_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"产品成本额\", [产品_产品成本额目标],",
              " \"毛利润额\",[产品_毛利润额目标],",
              " \"销售额\",[产品_销售额目标],",
              " \"产品投入产出比\",[产品_产品投入产出比目标],",
              " \"日销\",[产品_日销目标],",
              " \"库存周转率\",[产品_库存周转率目标],",
              " \"库存额\",[产品_库存额目标]",
              " )"
            ]
          },
          {
            "name": "产品差异",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('产品_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"产品成本额\", [产品_产品成本额目标实际差异],",
              " \"毛利润额\",[产品_毛利润额目标实际差异],",
              " \"销售额\",[产品_销售额目标实际差异],",
              " \"产品投入产出比\",[产品_产品成本额目标实际差异],",
              " \"日销\",[产品_日销目标实际差异],",
              " \"库存周转率\",[产品_库存周转率目标实际差异],",
              " \"库存额\",[产品_库存额目标实际差异]",
              " )"
            ]
          },
          {
            "name": "产品同比",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('产品_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"产品成本额\", [产品_产品成本额同比增长率 %],",
              " \"毛利润额\",[产品_毛利润额同比增长率 %],",
              " \"销售额\",[产品_销售额同比增长率 %],",
              " \"产品投入产出比\",[产品_产品投入产出比同比增长率 %],",
              " \"日销\",[产品_日销同比增长率 %],",
              " \"库存周转率\",[产品_库存周转率同比增长率 %],",
              " \"库存额\",[产品_库存额同比增长率 %]",
              " )"
            ]
          },
          {
            "name": "产品环比",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('产品_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"产品成本额\", [产品_产品成本额环比增长率 %],",
              " \"毛利润额\",[产品_毛利润额环比增长率 %],",
              " \"销售额\",[产品_销售额环比增长率 %],",
              " \"产品投入产出比\",[产品_产品投入产出比环比增长率 %],",
              " \"日销\",[产品_日销环比增长率 %],",
              " \"库存周转率\",[产品_库存周转率环比增长率 %],",
              " \"库存额\",[产品_库存额环比增长率 %]",
              " )"
            ]
          },
          {
            "name": "产品目标达成率",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('产品_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"产品成本额\", [产品_产品成本额目标达成率],",
              " \"毛利润额\",[产品_毛利润额目标达成率],",
              " \"销售额\",[产品_销售额目标达成率],",
              " \"产品投入产出比\",[产品_产品投入产出比目标达成率],",
              " \"日销\",[产品_日销目标达成率],",
              " \"库存周转率\",[产品_库存周转率目标达成率],",
              " \"库存额\",[产品_库存额目标达成率]",
              " )"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "产品散点图",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('度量值_产品效率'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"价格\", [产品平均售价],",
              " \"库存件数\",[库存件数实际],",
              " \"销售件数\",[销售件数],",
              " \"销售额\",[产品_销售额实际],",
              " \"毛利额\",[产品_毛利润额实际],",
              " \"毛利率\",[产品_毛利率] )"
            ]
          },
          {
            "name": "比例结构树状图_产品实际",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('产品_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"产品成本额\", [产品_产品成本额实际],",
              " \"毛利润额\",[产品_毛利润额实际],",
              " \"销售额\",[产品_销售额实际],",
              " \"日销\",[产品_日销实际],",
              " \"库存额\",[产品_库存额实际]",
              " )"
            ]
          }
        ]
      },
      {
        "name": "渠道_指标动态维度",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "subject_name",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \"渠道营业利润额\" , ),",
                "    ( \"销售额\" , ),",
                "     ( \"渠道费用额\" , ),",
                "      ( \"渠道投入产出比\" , ),",
                "       ( \"渠道冗余值\" , ),",
                "        ( \"日销\" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "渠道实际",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('渠道_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"渠道营业利润额\", [渠道_渠道营业利润额实际],",
              " \"销售额\",[渠道_销售额实际],",
              " \"渠道费用额\",[渠道_渠道费用额实际],",
              " \"渠道投入产出比\",[渠道_渠道投入产出比实际],",
              " \"渠道冗余值\",[渠道_渠道冗余值实际],",
              " \"日销\",[渠道_日销实际]",
              " )"
            ]
          },
          {
            "name": "渠道目标",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('渠道_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"渠道营业利润额\", [渠道_渠道营业利润额目标],",
              " \"销售额\",[渠道_销售额目标],",
              " \"渠道费用额\",[渠道_渠道费用额目标],",
              " \"渠道投入产出比\",[渠道_渠道投入产出比目标],",
              " \"渠道冗余值\",[渠道_渠道冗余值目标],",
              " \"日销\",[渠道_日销目标]",
              " )"
            ]
          },
          {
            "name": "渠道目标实际差异",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('渠道_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"渠道营业利润额\", [渠道_渠道营业利润额目标实际差异],",
              " \"销售额\",[渠道_销售额目标实际差异],",
              " \"渠道费用额\",[渠道_渠道费用额目标实际差异],",
              " \"渠道投入产出比\",[渠道_渠道投入产出比目标实际差异],",
              " \"渠道冗余值\",[渠道_渠道冗余值目标实际差异],",
              " \"日销\",[渠道_日销目标实际差异]",
              " )"
            ]
          },
          {
            "name": "渠道环比",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('渠道_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"渠道营业利润额\", [渠道_渠道营业利润额环比增长率 %],",
              " \"销售额\",[渠道_销售额环比增长率 %],",
              " \"渠道费用额\",[渠道_渠道费用额环比增长率 %],",
              " \"渠道投入产出比\",[渠道_渠道投入产出比环比增长率 %],",
              " \"渠道冗余值\",[渠道_渠道冗余值环比增长率 %],",
              " \"日销\",[渠道_日销环比增长率 %]",
              " )"
            ]
          },
          {
            "name": "渠道同比",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('渠道_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"渠道营业利润额\", [渠道_渠道营业利润额同比增长率 %],",
              " \"销售额\",[渠道_销售额同比增长率 %],",
              " \"渠道费用额\",[渠道_渠道费用额同比增长率 %],",
              " \"渠道投入产出比\",[渠道_渠道投入产出比同比增长率 %],",
              " \"渠道冗余值\",[渠道_渠道冗余值同比增长率 %],",
              " \"日销\",[渠道_日销同比增长率 %]",
              " )"
            ]
          },
          {
            "name": "渠道目标达成率",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('渠道_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"渠道营业利润额\", [渠道_渠道营业利润额目标达成率],",
              " \"销售额\",[渠道_销售额目标达成率],",
              " \"渠道费用额\",[渠道_渠道费用额目标达成率],",
              " \"渠道投入产出比\",[渠道_渠道投入产出比目标达成率],",
              " \"渠道冗余值\",[渠道_渠道冗余值目标达成率],",
              " \"日销\",[渠道_日销目标达成率]",
              " )"
            ]
          },
          {
            "name": "渠道散点图",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('度量值_渠道效率'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"价格\", [渠道平均售价],",
              " \"销售件数\",[销售件数],",
              " \"销售额\",[渠道_销售额实际],",
              " \"利润额\",[渠道_渠道营业利润额实际],",
              " \"毛利率\",[渠道_毛利率] )"
            ]
          },
          {
            "name": "比例结构树状图_渠道实际",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('渠道_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"渠道营业利润额\", [渠道_渠道营业利润额实际],",
              " \"销售额\",[渠道_销售额实际],",
              " \"渠道费用额\",[渠道_渠道费用额实际],",
              " \"渠道冗余值\",[渠道_渠道冗余值实际],",
              " \"日销\",[渠道_日销实际]",
              " )"
            ]
          }
        ]
      },
      {
        "name": "客户_指标动态维度",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "subject_name",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \"客户利润额\" , ),",
                "    ( \"销售额\" , ),",
                "     ( \"客户费用额\" , ),",
                "      ( \"客户投入产出比\" , ),",
                "       ( \"客户冗余值\" , ),",
                "        ( \"日销\" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "客户实际",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('客户_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"客户利润额\", [客户_客户利润额实际],",
              " \"销售额\",[客户_销售额实际],",
              " \"客户费用额\",[客户_客户费用额实际],",
              " \"客户投入产出比\",[客户_客户投入产出比实际],",
              " \"客户冗余值\",[客户_客户冗余值实际],",
              " \"日销\",[客户_日销实际]",
              " )"
            ]
          },
          {
            "name": "客户目标",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('客户_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"客户利润额\", [客户_客户利润额目标],",
              " \"销售额\",[客户_销售额目标],",
              " \"客户费用额\",[客户_客户费用额目标],",
              " \"客户投入产出比\",[客户_客户投入产出比目标],",
              " \"客户冗余值\",[客户_客户冗余值目标],",
              " \"日销\",[客户_日销目标]",
              " )"
            ]
          },
          {
            "name": "客户目标实际差异",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('客户_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"客户利润额\", [客户_客户利润额目标实际差异],",
              " \"销售额\",[客户_销售额目标实际差异],",
              " \"客户费用额\",[客户_客户费用额目标实际差异],",
              " \"客户投入产出比\",[客户_客户投入产出比目标实际差异],",
              " \"客户冗余值\",[客户_客户冗余值目标实际差异],",
              " \"日销\",[客户_日销目标实际差异]",
              " )"
            ]
          },
          {
            "name": "客户同比",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('客户_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"客户利润额\", [客户_客户利润额同比增长率 %],",
              " \"销售额\",[客户_销售额同比增长率 %],",
              " \"客户费用额\",[客户_客户费用额同比增长率 %],",
              " \"客户投入产出比\",[客户_客户投入产出比同比增长率 %],",
              " \"客户冗余值\",[客户_客户冗余值同比增长率 %],",
              " \"日销\",[客户_日销同比增长率 %]",
              " )"
            ]
          },
          {
            "name": "客户环比",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('客户_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"客户利润额\", [客户_客户利润额环比增长率 %],",
              " \"销售额\",[客户_销售额环比增长率 %],",
              " \"客户费用额\",[客户_客户费用额环比增长率 %],",
              " \"客户投入产出比\",[客户_客户投入产出比环比增长率 %],",
              " \"客户冗余值\",[客户_客户冗余值环比增长率 %],",
              " \"日销\",[客户_日销环比增长率 %]",
              " )"
            ]
          },
          {
            "name": "客户目标达成率",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('客户_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"客户利润额\", [客户_客户利润额目标达成率],",
              " \"销售额\",[客户_销售额目标达成率],",
              " \"客户费用额\",[客户_客户费用额目标达成率],",
              " \"客户投入产出比\",[客户_客户投入产出比目标达成率],",
              " \"客户冗余值\",[客户_客户冗余值目标达成率],",
              " \"日销\",[客户_日销目标成率]",
              " )"
            ]
          },
          {
            "name": "客户散点图",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('度量值_客户效率'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"销售额\",[客户_销售额实际],",
              " \"利润额\",[客户_客户利润额实际],",
              " \"毛利率\",[客户_毛利率] )"
            ]
          },
          {
            "name": "比例结构树状图_客户实际",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('客户_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"客户利润额\", [客户_客户利润额实际],",
              " \"销售额\",[客户_销售额实际],",
              " \"客户费用额\",[客户_客户费用额实际],",
              " \"客户冗余值\",[客户_客户冗余值实际],",
              " \"日销\",[客户_日销实际]",
              " )"
            ]
          }
        ]
      },
      {
        "name": "供应_指标动态维度",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "subject_name",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \"供应销售额\" , ),",
                "    ( \"供应利润额\" , ),",
                "     ( \"供应产能\" , ),",
                "      ( \"供应产供比\" , ),",
                "       ( \"残品率\" , ),",
                "        ( \"交期达成率\" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "供应实际",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('供应_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"供应销售额\", [供应_供应销售额实际],",
              " \"供应利润额\",[供应_供应利润额实际],",
              " \"供应产能\",[供应_供应产能实际],",
              " \"供应产供比\",[供应_供应产供比实际],",
              " \"残品率\",[供应_残品率实际],",
              " \"交期达成率\",[供应_交期达成率实际]",
              " )"
            ]
          },
          {
            "name": "供应目标",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('供应_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"供应销售额\", [供应_供应销售额目标],",
              " \"供应利润额\",[供应_供应利润额目标],",
              " \"供应产能\",[供应_供应产能目标],",
              " \"供应产供比\",[供应_供应产供比目标],",
              " \"残品率\",[供应_残品率目标],",
              " \"交期达成率\",[供应_交期达成率目标]",
              " )"
            ]
          },
          {
            "name": "供应目标实际差异",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('供应_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"供应销售额\", [供应_供应销售额目标实际差异],",
              " \"供应利润额\",[供应_供应利润额目标实际差异],",
              " \"供应产能\",[供应_供应产能目标实际差异],",
              " \"供应产供比\",[供应_供应产供比目标实际差异],",
              " \"残品率\",[供应_残品率目标实际差异],",
              " \"交期达成率\",[供应_交期达成率目标实际差异]",
              " )"
            ]
          },
          {
            "name": "供应同比",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('供应_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"供应销售额\", [供应_供应销售额同比增长率 %],",
              " \"供应利润额\",[供应_供应利润额同比增长率 %],",
              " \"供应产能\",[供应_供应产能同比增长率 %],",
              " \"供应产供比\",[供应_供应产供比同比增长率 %],",
              " \"残品率\",[供应_残品率同比增长率 %],",
              " \"交期达成率\",[供应_交期达成率同比增长率 %]",
              " )"
            ]
          },
          {
            "name": "供应环比",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('供应_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"供应销售额\", [供应_供应销售额环比增长率 %],",
              " \"供应利润额\",[供应_供应利润额环比增长率 %],",
              " \"供应产能\",[供应_供应产能环比增长率 %],",
              " \"供应产供比\",[供应_供应产供比环比增长率 %],",
              " \"残品率\",[供应_残品率环比增长率 %],",
              " \"交期达成率\",[供应_交期达成率环比增长率 %]",
              " )"
            ]
          },
          {
            "name": "供应目标达成率",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('供应_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"供应销售额\", [供应_供应销售额目标达成率],",
              " \"供应利润额\",[供应_供应利润额目标达成率],",
              " \"供应产能\",[供应_供应产能目标达成率],",
              " \"供应产供比\",[供应_供应产供比目标达成率],",
              " \"残品率\",[供应_残品率目标达成率],",
              " \"交期达成率\",[供应_交期达成率目标达成率]",
              " )"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "供应散点图",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('度量值_供应效率'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"下单件数\",[供应_下单件数],",
              " \"销售额\",[供应_供应销售额实际],",
              " \"毛利额\",[供应_供应利润额实际],",
              " \"毛利率\",[供应_毛利率] )"
            ]
          },
          {
            "name": "比例结构树状图_供应实际",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('供应_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"供应销售额\", [供应_供应销售额实际],",
              " \"供应利润额\",[供应_供应利润额实际],",
              " \"供应产能\",[供应_供应产能实际]",
              " )"
            ]
          }
        ]
      },
      {
        "name": "组织_指标动态维度",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "subject_name",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \"净利润额\" , ),",
                "    ( \"销售额\" , ),",
                "     ( \"人力成本额\" , ),",
                "      ( \"组织投入产出比\" , ),",
                "       ( \"日销\" , ),",
                "        ( \"人员冗余值\" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "组织实际",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('组织_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"净利润额\", [组织_净利润额实际],",
              " \"销售额\",[组织_销售额实际],",
              " \"人力成本额\",[组织_人力成本额实际],",
              " \"组织投入产出比\",[组织_组织投入产出比实际],",
              " \"日销\",[组织_日销实际],",
              " \"人员冗余值\",[组织_人员冗余值实际]",
              " )"
            ]
          },
          {
            "name": "组织目标",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('组织_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"净利润额\", [组织_净利润额目标],",
              " \"销售额\",[组织_销售额目标],",
              " \"人力成本额\",[组织_人力成本额目标],",
              " \"组织投入产出比\",[组织_组织投入产出比目标],",
              " \"日销\",[组织_日销目标],",
              " \"人员冗余值\",[组织_人员冗余值目标]",
              " )"
            ]
          },
          {
            "name": "组织目标实际差异",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('组织_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"净利润额\", [组织_净利润额目标实际差异],",
              " \"销售额\",[组织_销售额目标实际差异],",
              " \"人力成本额\",[组织_人力成本额目标实际差异],",
              " \"组织投入产出比\",[组织_组织投入产出比目标实际差异],",
              " \"日销\",[组织_日销目标实际差异],",
              " \"人员冗余值\",[组织_人员冗余值目标实际差异]",
              " )"
            ]
          },
          {
            "name": "组织同比",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('组织_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"净利润额\", [组织_净利润额同比增长率 %],",
              " \"销售额\",[组织_销售额同比增长率 %],",
              " \"人力成本额\",[组织_人力成本额同比增长率 %],",
              " \"组织投入产出比\",[组织_组织投入产出比同比增长率 %],",
              " \"日销\",[组织_日销同比增长率 %],",
              " \"人员冗余值\",[组织_人员冗余值同比增长率 %]",
              " )"
            ]
          },
          {
            "name": "组织环比",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('组织_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"净利润额\", [组织_净利润额环比增长率 %],",
              " \"销售额\",[组织_销售额环比增长率 %],",
              " \"人力成本额\",[组织_人力成本额环比增长率 %],",
              " \"组织投入产出比\",[组织_组织投入产出比环比增长率 %],",
              " \"日销\",[组织_日销环比增长率 %],",
              " \"人员冗余值\",[组织_人员冗余值环比增长率 %]",
              " )"
            ]
          },
          {
            "name": "组织目标达成率",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('组织_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"净利润额\", [组织_净利润额目标达成率],",
              " \"销售额\",[组织_销售额目标达成率],",
              " \"人力成本额\",[组织_人力成本额目标达成率],",
              " \"组织投入产出比\",[组织_组织投入产出比目标达成率],",
              " \"日销\",[组织_日销目标达成率],",
              " \"人员冗余值\",[组织_人员冗余值目标达成率]",
              " )"
            ]
          },
          {
            "name": "组织散点图",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('度量值_组织效率'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"价格\", [组织_平均售价],",
              "  \"销售件数\",[销售件数],",
              " \"销售额\",[组织_销售额实际],",
              " \"净利润额\",[组织_净利润额实际],",
              " \"毛利率\",[组织_毛利率] )"
            ]
          },
          {
            "name": "比例结构树结构_组织实际",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('组织_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"净利润额\", [组织_净利润额实际],",
              " \"销售额\",[组织_销售额实际],",
              " \"人力成本额\",[组织_人力成本额实际],",
              " \"日销\",[组织_日销实际],",
              " \"人员冗余值\",[组织_人员冗余值实际]",
              " )"
            ]
          }
        ]
      },
      {
        "name": "资金_指标动态维度",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "subject_name",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \"总成本费用额\" , ),",
                "    ( \"销售额\" , ),",
                "     ( \"回款额\" , ),",
                "      ( \"净利润额\" , ),",
                "       ( \"净利率\" , ),",
                "        ( \"净现金流\" , ),",
                "         ( \"投资回报率\" , ),",
                "          ( \"资金周转率\" , ),",
                "           ( \"资金冗余值\" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "资金实际",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('资金_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"总成本费用额\", [资金_总成本费用额实际],",
              " \"销售额\",[资金_销售额实际],",
              " \"回款额\",[资金_回款额实际],",
              " \"净利润额\",[资金_净利润额实际],",
              " \"净利率\",[资金_净利率实际],",
              " \"净现金流\",[资金_净现金流实际],",
              "  \"投资回报率\",[资金_投资回报率实际],",
              "   \"资金周转率\",[资金_资金周转率实际],",
              "    \"资金冗余值\",[资金_资金冗余值实际]",
              " )"
            ]
          },
          {
            "name": "资金目标",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('资金_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE,",
              " \"总成本费用额\", [资金_总成本费用额目标],",
              " \"销售额\",[资金_销售额目标],",
              " \"回款额\",[资金_回款额目标],",
              " \"净利润额\",[资金_净利润额目标],",
              " \"净利率\",[资金_净利率目标],",
              " \"净现金流\",[资金_净现金流目标],",
              "  \"投资回报率\",[资金_投资回报率目标],",
              "   \"资金周转率\",[资金_资金周转率目标],",
              "    \"资金冗余值\",[资金_资金冗余值目标]",
              " )"
            ]
          },
          {
            "name": "资金目标实际差异",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('资金_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"总成本费用额\", [资金_总成本费用额目标实际差异],",
              " \"销售额\",[资金_销售额目标实际差异],",
              " \"回款额\",[资金_回款额目标实际差异],",
              " \"净利润额\",[资金_净利润额目标实际差异],",
              " \"净利率\",[资金_净利率目标实际差异],",
              " \"净现金流\",[资金_净现金流目标实际差异],",
              "  \"投资回报率\",[资金_投资回报率目标实际差异],",
              "   \"资金周转率\",[资金_资金周转率目标实际差异],",
              "    \"资金冗余值\",[资金_资金冗余值目标实际差异]",
              " )"
            ]
          },
          {
            "name": "资金同比",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('资金_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"总成本费用额\", [资金_总成本费用额同比增长率 %],",
              " \"销售额\",[资金_销售额同比增长率 %],",
              " \"回款额\",[资金_回款额同比增长率 %],",
              " \"净利润额\",[资金_净利润额同比增长率 %],",
              " \"净利率\",[资金_净利率同比增长率 %],",
              " \"净现金流\",[资金_净现金流同比增长率 %],",
              "  \"投资回报率\",[资金_投资回报率同比增长率 %],",
              "   \"资金周转率\",[资金_资金周转率同比增长率 %],",
              "    \"资金冗余值\",[资金_资金冗余值同比增长率 %]",
              " )"
            ]
          },
          {
            "name": "资金环比",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('资金_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"总成本费用额\", [资金_总成本费用额环比增长率 %],",
              " \"销售额\",[资金_销售额环比增长率 %],",
              " \"回款额\",[资金_回款额环比增长率 %],",
              " \"净利润额\",[资金_净利润额环比增长率 %],",
              " \"净利率\",[资金_净利率环比增长率 %],",
              " \"净现金流\",[资金_净现金流环比增长率 %],",
              "  \"投资回报率\",[资金_投资回报率环比增长率 %],",
              "   \"资金周转率\",[资金_资金周转率环比增长率 %],",
              "    \"资金冗余值\",[资金_资金冗余值环比增长率 %]",
              " )"
            ]
          },
          {
            "name": "资金目标达成率",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('资金_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"总成本费用额\",[资金_总成本费用额目标达成率],",
              " \"销售额\",[资金_销售额目标达成率],",
              " \"回款额\",[资金_回款额目标达成率],",
              " \"净利润额\",[资金_净利润额目标达成率],",
              " \"净利率\",[资金_净利润额目标达成率],",
              " \"净现金流\",[资金_净现金流目标达成率],",
              "  \"投资回报率\",[资金_投资回报率目标达成率],",
              "   \"资金周转率\",[资金_资金周转率目标达成率],",
              "    \"资金冗余值\",[资金_资金冗余值目标达成率]",
              " )"
            ]
          },
          {
            "name": "资金散点图",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('度量值_资金效率'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"销售额\",[资金_销售额实际],",
              " \"净利润额\",[资金_净利润额实际],",
              " \"毛利率\",[组织_毛利率] )"
            ]
          },
          {
            "name": "比例结构树状图_资金实际",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('资金_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"总成本费用额\", [资金_总成本费用额实际],",
              " \"销售额\",[资金_销售额实际],",
              " \"回款额\",[资金_回款额实际],",
              " \"净利润额\",[资金_净利润额实际],",
              " \"净现金流\",[资金_净现金流实际],",
              "    \"资金冗余值\",[资金_资金冗余值实际]",
              " )"
            ]
          }
        ]
      },
      {
        "name": "基本竞争力_指标动态维度",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "subject_name",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \"销售额\" , ),",
                "    ( \"销售增长额\" , ),",
                "    ( \"销售增长率\" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "基本竞争力_实际",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('基本竞争力_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"销售额\", [基本竞争力_销售额实际],",
              " \"销售增长额\",[基本竞争力_销售增长额实际],",
              " \"销售增长率\",[基本竞争力_销售增长率实际]",
              " )"
            ]
          },
          {
            "name": "基本竞争力_目标",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('基本竞争力_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"销售额\", [基本竞争力_销售额目标],",
              " \"销售增长额\",[基本竞争力_销售增长额目标],",
              " \"销售增长率\",[基本竞争力_销售增长率目标]",
              " )"
            ]
          },
          {
            "name": "基本竞争力_差异",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('基本竞争力_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"销售额\", [基本竞争力_销售额目标实际差异],",
              " \"销售增长额\",[基本竞争力_销售增长额目标实际差异],",
              " \"销售增长率\",[基本竞争力_销售增长率目标实际差异]",
              " )"
            ]
          }
        ]
      },
      {
        "name": "持续竞争力_指标动态维度",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "subject_name",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \"净利润额\" , ),",
                "    ( \"净利润增长额\" , ),",
                "    ( \"净利率\" , ),",
                "    ( \"净利润增长率\" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "持续竞争力_实际",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('持续竞争力_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"净利润额\", [持续竞争力_净利润额实际],",
              " \"净利润增长额\", [持续竞争力_净利润增长额实际],",
              " \"净利率\", [持续竞争力_净利率实际],",
              " \"净利润增长率\", [持续竞争力_净利润增长率实际]",
              " )"
            ]
          },
          {
            "name": "持续竞争力_目标",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('持续竞争力_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"净利润额\", [持续竞争力_净利润额目标],",
              " \"净利润增长额\", [持续竞争力_净利润增长额目标],",
              " \"净利率\", [持续竞争力_净利率目标],",
              " \"净利润增长率\", [持续竞争力_净利润增长率目标]",
              " )"
            ]
          },
          {
            "name": "持续竞争力_差异",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('持续竞争力_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"净利润额\", [持续竞争力_净利润额目标实际差异],",
              " \"净利润增长额\", [持续竞争力_净利润增长额目标实际差异],",
              " \"净利率\", [持续竞争力_净利率目标实际差异],",
              " \"净利润增长率\", [持续竞争力_净利润增长率目标实际差异]",
              " )"
            ]
          }
        ]
      },
      {
        "name": "核心竞争力_产品效率_指标动态维度",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "subject_name",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \"SKU数量\" , ),",
                "    ( \"单品平均毛利润额\" , ),",
                "    ( \"单品平均销售额\" , ),",
                "    ( \"单品平均成本费用额\" , ),",
                "    ( \"投入产出比\" , ),",
                "    ( \"库存周转率\" , ),",
                "   ( \"单品平均日销\" , ),",
                "    ( \"产品冗余值\" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "核心竞争力_产品效率_实际",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('核心竞争力_产品效率_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"SKU数量\", [核心竞争力_产品效率_SKU数量实际],",
              " \"单品平均毛利润额\", [核心竞争力_产品效率_单品平均毛利润额实际],",
              " \"单品平均销售额\", [核心竞争力_产品效率_单品平均销售额实际],",
              " \"单品平均成本费用额\", [核心竞争力_产品效率_单品平均成本费用额实际],",
              " \"投入产出比\", [核心竞争力_产品效率_投入产出比实际],",
              " \"库存周转率\", [核心竞争力_产品效率_库存周转率实际],",
              " \"单品平均日销\", [核心竞争力_产品效率_日销实际],",
              " \"产品冗余值\", [核心竞争力_产品效率_产品冗余值实际]",
              " )"
            ]
          },
          {
            "name": "核心竞争力_产品效率_目标",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('核心竞争力_产品效率_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"SKU数量\", [核心竞争力_产品效率_SKU数量目标],",
              " \"单品平均毛利润额\", [核心竞争力_产品效率_单品平均毛利润额目标],",
              " \"单品平均销售额\", [核心竞争力_产品效率_单品平均销售额目标],",
              " \"单品平均成本费用额\", [核心竞争力_产品效率_单品平均成本费用额目标],",
              " \"投入产出比\", [核心竞争力_产品效率_投入产出比目标],",
              " \"库存周转率\", [核心竞争力_产品效率_库存周转率目标],",
              " \"单品平均日销\", [核心竞争力_产品效率_日销目标],",
              " \"产品冗余值\", [核心竞争力_产品效率_产品冗余值目标]",
              " )"
            ]
          },
          {
            "name": "核心竞争力_产品效率_差异",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('核心竞争力_产品效率_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"SKU数量\", [核心竞争力_产品效率_SKU数量目标实际差异],",
              " \"单品平均毛利润额\", [核心竞争力_产品效率_单品平均毛利润额目标实际差异],",
              " \"单品平均销售额\", [核心竞争力_产品效率_单品平均销售额目标实际差异],",
              " \"单品平均成本费用额\", [核心竞争力_产品效率_单品平均成本费用额目标实际差异],",
              " \"投入产出比\", [核心竞争力_产品效率_投入产出比目标实际差异],",
              " \"库存周转率\", [核心竞争力_产品效率_库存周转率目标实际差异],",
              " \"单品平均日销\", [核心竞争力_产品效率_日销目标实际差异],",
              " \"产品冗余值\", [核心竞争力_产品效率_产品冗余值目标实际差异]",
              " )"
            ]
          }
        ]
      },
      {
        "name": "核心竞争力_渠道效率_指标动态维度",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "subject_name",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \"店铺数量\" , ),",
                "    ( \"单店平均营业利润额\" , ),",
                "    ( \"单店平均销售额\" , ),",
                "    ( \"单店平均成本费用额\" , ),",
                "    ( \"投入产出比\" , ),",
                "    ( \"渠道冗余值\" , ),",
                "    ( \"单店平均日销\" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "核心竞争力_渠道效率_实际",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('核心竞争力_渠道效率_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"店铺数量\", [核心竞争力_渠道效率_店铺数量实际],",
              " \"单店平均营业利润额\", [核心竞争力_渠道效率_单店平均营业利润额实际],",
              " \"单店平均销售额\", [核心竞争力_渠道效率_单店平均销售额实际],",
              " \"单店平均成本费用额\", [核心竞争力_渠道效率_单店平均成本费用额实际],",
              " \"投入产出比\", [核心竞争力_渠道效率_投入产出比实际],",
              " \"渠道冗余值\", [核心竞争力_渠道效率_渠道冗余值实际],",
              " \"单店平均日销\", [核心竞争力_渠道效率_日销实际]",
              " )"
            ]
          },
          {
            "name": "核心竞争力_渠道效率_目标",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('核心竞争力_渠道效率_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"店铺数量\", [核心竞争力_渠道效率_店铺数量目标],",
              " \"单店平均营业利润额\", [核心竞争力_渠道效率_单店平均营业利润额目标],",
              " \"单店平均销售额\", [核心竞争力_渠道效率_单店平均销售额目标],",
              " \"单店平均成本费用额\", [核心竞争力_渠道效率_单店平均成本费用额目标],",
              " \"投入产出比\", [核心竞争力_渠道效率_投入产出比目标],",
              " \"渠道冗余值\", [核心竞争力_渠道效率_渠道冗余值目标],",
              " \"单店平均日销\", [核心竞争力_渠道效率_日销目标]",
              " )"
            ]
          },
          {
            "name": "核心竞争力_渠道效率_差异",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('核心竞争力_渠道效率_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"店铺数量\", [核心竞争力_渠道效率_店铺数量目标实际差异],",
              " \"单店平均营业利润额\", [核心竞争力_渠道效率_单店平均营业利润额目标实际差异],",
              " \"单店平均销售额\", [核心竞争力_渠道效率_单店平均销售额目标实际差异],",
              " \"单店平均成本费用额\", [核心竞争力_渠道效率_单店平均成本费用额目标实际差异],",
              " \"投入产出比\", [核心竞争力_渠道效率_投入产出比目标实际差异],",
              " \"渠道冗余值\", [核心竞争力_渠道效率_渠道冗余值目标实际差异],",
              " \"单店平均日销\", [核心竞争力_渠道效率_日销目标实际差异]",
              " )"
            ]
          }
        ]
      },
      {
        "name": "核心竞争力_客户效率_指标动态维度",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "subject_name",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \"消费者人数\" , ),",
                "    ( \"消费者人均客户利润额\" , ),",
                "    ( \"消费者人均销售额\" , ),",
                "    ( \"消费者人均成本费用额\" , ),",
                "    ( \"投入产出比\" , ),",
                "    ( \"消费者冗余值\" , ),",
                "    ( \"消费者人均日销\" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "核心竞争力_客户效率_实际",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('核心竞争力_客户效率_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"消费者人数\", [核心竞争力_客户效率_消费者人数实际],",
              " \"消费者人均客户利润额\",[核心竞争力_客户效率_消费者人均客户利润额实际],",
              " \"消费者人均销售额\",[核心竞争力_客户效率_消费者人均销售额实际],",
              " \"消费者人均成本费用额\", [核心竞争力_客户效率_消费者人均成本费用额实际],",
              " \"投入产出比\",[核心竞争力_客户效率_投入产出比实际],",
              " \"消费者冗余值\", [核心竞争力_客户效率_消费者冗余值实际],",
              " \"消费者人均日销\", [核心竞争力_客户效率_日销实际]",
              " )"
            ]
          },
          {
            "name": "核心竞争力_客户效率_目标",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('核心竞争力_客户效率_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"消费者人数\", [核心竞争力_客户效率_消费者人数目标],",
              " \"消费者人均客户利润额\",[核心竞争力_客户效率_消费者人均客户利润额目标],",
              " \"消费者人均销售额\",[核心竞争力_客户效率_消费者人均销售额目标],",
              " \"消费者人均成本费用额\", [核心竞争力_客户效率_消费者人均成本费用额目标],",
              " \"投入产出比\",[核心竞争力_客户效率_投入产出比目标],",
              " \"消费者冗余值\", [核心竞争力_客户效率_消费者冗余值目标],",
              " \"消费者人均日销\", [核心竞争力_客户效率_日销目标]",
              " )"
            ]
          },
          {
            "name": "核心竞争力_客户效率_目标实际差异",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('核心竞争力_客户效率_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"消费者人数\", [核心竞争力_客户效率_消费者人数目标实际差异],",
              " \"消费者人均客户利润额\",[核心竞争力_客户效率_消费者人均客户利润额目标实际差异],",
              " \"消费者人均销售额\",[核心竞争力_客户效率_消费者人均销售额目标实际差异],",
              " \"消费者人均成本费用额\", [核心竞争力_客户效率_消费者人均成本费用额目标实际差异],",
              " \"投入产出比\",[核心竞争力_客户效率_投入产出比目标实际差异],",
              " \"消费者冗余值\", [核心竞争力_客户效率_消费者冗余值目标实际差异],",
              " \"消费者人均日销\", [核心竞争力_客户效率_日销目标实际差异]",
              " )"
            ]
          }
        ]
      },
      {
        "name": "核心竞争力_供应效率_指标动态维度",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "subject_name",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \"工厂数量\" , ),",
                "    ( \"工厂平均销售额\" , ),",
                "    ( \"工厂平均毛利额\" , ),",
                "    ( \"工厂平均产能\" , ),",
                "    ( \"产供比\" , ),",
                "    ( \"工厂平均残品率\" , ),",
                "    ( \"工厂平均交期达成率\" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "核心竞争力_供应效率_实际",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('核心竞争力_供应效率_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"工厂数量\", [核心竞争力_供应效率_工厂数量实际],",
              " \"工厂平均销售额\",[核心竞争力_供应效率_工厂平均销售额实际],",
              " \"工厂平均毛利额\",[核心竞争力_供应效率_工厂平均毛利额实际],",
              " \"工厂平均产能\", [核心竞争力_供应效率_工厂平均产能实际],",
              " \"产供比\",[核心竞争力_供应效率_产供比实际],",
              " \"工厂平均残品率\", [核心竞争力_供应效率_工厂平均残品率实际],",
              " \"工厂平均交期达成率\", [核心竞争力_供应效率_工厂平均交期达成率实际]",
              " )"
            ]
          },
          {
            "name": "核心竞争力_供应效率_目标",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('核心竞争力_供应效率_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"工厂数量\", [核心竞争力_供应效率_工厂数量目标],",
              " \"工厂平均销售额\",[核心竞争力_供应效率_工厂平均销售额目标],",
              " \"工厂平均毛利额\",[核心竞争力_供应效率_工厂平均毛利额目标],",
              " \"工厂平均产能\", [核心竞争力_供应效率_工厂平均产能目标],",
              " \"产供比\",[核心竞争力_供应效率_产供比目标],",
              " \"工厂平均残品率\", [核心竞争力_供应效率_工厂平均残品率目标],",
              " \"工厂平均交期达成率\", [核心竞争力_供应效率_工厂平均交期达成率目标]",
              " )"
            ]
          },
          {
            "name": "核心竞争力_供应效率_目标实际差异",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('核心竞争力_供应效率_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"工厂数量\", [核心竞争力_供应效率_工厂数量目标实际差异],",
              " \"工厂平均销售额\",[核心竞争力_供应效率_工厂平均销售额目标实际差异],",
              " \"工厂平均毛利额\",[核心竞争力_供应效率_工厂平均毛利额目标实际差异],",
              " \"工厂平均产能\", [核心竞争力_供应效率_工厂平均产能目标实际差异],",
              " \"产供比\",[核心竞争力_供应效率_产供比目标实际差异],",
              " \"工厂平均残品率\", [核心竞争力_供应效率_工厂平均残品率目标实际差异],",
              " \"工厂平均交期达成率\", [核心竞争力_供应效率_工厂平均交期达成率目标实际差异]",
              " )"
            ]
          }
        ]
      },
      {
        "name": "核心竞争力_组织效率_指标动态维度",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "subject_name",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \"企业人数\" , ),",
                "    ( \"企业人均净利润额\" , ),",
                "    ( \"企业人均销售额\" , ),",
                "    ( \"企业人均成本额\" , ),",
                "    ( \"投入产出比\" , ),",
                "    ( \"企业人均日销\" , ),",
                "    ( \"企业人均冗余值\" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "核心竞争力_组织效率_实际",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('核心竞争力_组织效率_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"企业人数\", [核心竞争力_组织效率_企业人数实际],",
              " \"企业人均净利润额\",[核心竞争力_组织效率_企业人均净利润额实际],",
              " \"企业人均销售额\",[核心竞争力_组织效率_企业人均销售额实际],",
              " \"企业人均成本额\", [核心竞争力_组织效率_企业人均成本额实际],",
              " \"投入产出比\",[核心竞争力_组织效率_投入产出比实际],",
              " \"企业人均日销\", [核心竞争力_组织效率_日销实际],",
              " \"企业人均冗余值\", [核心竞争力_组织效率_企业人均冗余值实际]",
              " )"
            ]
          },
          {
            "name": "核心竞争力_组织效率_目标",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('核心竞争力_组织效率_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"企业人数\", [核心竞争力_组织效率_企业人数目标],",
              " \"企业人均净利润额\",[核心竞争力_组织效率_企业人均净利润额目标],",
              " \"企业人均销售额\",[核心竞争力_组织效率_企业人均销售额目标],",
              " \"企业人均成本额\", [核心竞争力_组织效率_企业人均成本额目标],",
              " \"投入产出比\",[核心竞争力_组织效率_投入产出比目标],",
              " \"企业人均日销\", [核心竞争力_组织效率_日销目标],",
              " \"企业人均冗余值\", [核心竞争力_组织效率_企业人均冗余值目标]",
              " )"
            ]
          },
          {
            "name": "核心竞争力_组织效率_差异",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('核心竞争力_组织效率_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"企业人数\", [核心竞争力_组织效率_企业人数目标实际差异],",
              " \"企业人均净利润额\",[核心竞争力_组织效率_企业人均净利润额目标实际差异],",
              " \"企业人均销售额\",[核心竞争力_组织效率_企业人均销售额目标实际差异],",
              " \"企业人均成本额\", [核心竞争力_组织效率_企业人均成本额目标实际差异],",
              " \"投入产出比\",[核心竞争力_组织效率_投入产出比目标实际差异],",
              " \"企业人均日销\", [核心竞争力_组织效率_日销目标实际差异],",
              " \"企业人均冗余值\", [核心竞争力_组织效率_企业人均冗余值目标实际差异]",
              " )"
            ]
          }
        ]
      },
      {
        "name": "核心竞争力_资金效率_指标动态维度",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "subject_name",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \"总成本费用额\" , ),",
                "    ( \"销售额\" , ),",
                "    ( \"回款额\" , ),",
                "    ( \"净利润额\" , ),",
                "    ( \"净利率\" , ),",
                "    ( \"净现金流\" , ),",
                "    ( \"投资回报率\" , ),",
                "    ( \"资金周转率\" , ),",
                "    ( \"资金冗余值\" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "核心竞争力_资金效率_实际",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('核心竞争力_资金效率_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"总成本费用额\", [核心竞争力_资金效率_总成本费用额实际],",
              " \"销售额\",[核心竞争力_资金效率_销售额实际],",
              " \"回款额\",[核心竞争力_资金效率_回款额实际],",
              " \"净利润额\", [核心竞争力_资金效率_净利润额实际],",
              " \"净利率\",[核心竞争力_资金效率_净利率实际],",
              " \"净现金流\", [核心竞争力_资金效率_净现金流实际],",
              " \"投资回报率\", [核心竞争力_资金效率_投资回报率实际],",
              " \"资金周转率\", [核心竞争力_资金效率_资金周转率实际],",
              " \"资金冗余值\", [核心竞争力_资金效率_资金冗余值实际]",
              " )"
            ]
          },
          {
            "name": "核心竞争力_资金效率_目标",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('核心竞争力_资金效率_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"总成本费用额\", [核心竞争力_资金效率_总成本费用额目标],",
              " \"销售额\",[核心竞争力_资金效率_销售额目标],",
              " \"回款额\",[核心竞争力_资金效率_回款额目标],",
              " \"净利润额\", [核心竞争力_资金效率_净利润额目标],",
              " \"净利率\",[核心竞争力_资金效率_净利率目标],",
              " \"净现金流\", [核心竞争力_资金效率_净现金流目标],",
              " \"投资回报率\", [核心竞争力_资金效率_投资回报率目标],",
              " \"资金周转率\", [核心竞争力_资金效率_资金周转率目标],",
              " \"资金冗余值\", [核心竞争力_资金效率_资金冗余值目标]",
              " )"
            ]
          },
          {
            "name": "核心竞争力_资金效率_差异",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('核心竞争力_资金效率_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"总成本费用额\", [核心竞争力_资金效率_总成本费用额目标实际差异],",
              " \"销售额\",[核心竞争力_资金效率_销售额目标实际差异],",
              " \"回款额\",[核心竞争力_资金效率_回款额目标实际差异],",
              " \"净利润额\", [核心竞争力_资金效率_净利润额目标实际差异],",
              " \"净利率\",[核心竞争力_资金效率_净利率目标实际差异],",
              " \"净现金流\", [核心竞争力_资金效率_净现金流目标实际差异],",
              " \"投资回报率\", [核心竞争力_资金效率_投资回报率目标实际差异],",
              " \"资金周转率\", [核心竞争力_资金效率_资金周转率目标实际差异],",
              " \"资金冗余值\", [核心竞争力_资金效率_资金冗余值目标实际差异]",
              " )"
            ]
          }
        ]
      },
      {
        "name": "品牌价值_指标动态维度",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "subject_name",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \"品质合格率\" , ),",
                "    ( \"传播网点数\" , ),",
                "    ( \"传播成本\" , ),",
                "    ( \"传播的投入产出比\" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "品牌价值_实际",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('品牌价值_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"品质合格率\", [品牌价值_品质合格率实际],",
              " \"传播网点数\", [品牌价值_传播网点数实际],",
              " \"传播成本\", [品牌价值_传播成本实际],",
              " \"传播的投入产出比\", [品牌价值_传播的投入产出比实际]",
              " )"
            ]
          },
          {
            "name": "品牌价值_目标",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('品牌价值_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"品质合格率\", [品牌价值_品质合格率目标],",
              " \"传播网点数\", [品牌价值_传播网点数目标],",
              " \"传播成本\", [品牌价值_传播成本目标],",
              " \"传播的投入产出比\", [品牌价值_传播的投入产出比目标]",
              " )"
            ]
          },
          {
            "name": "品牌价值_差异",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('品牌价值_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"品质合格率\", [品牌价值_品质合格率目标实际差异],",
              " \"传播网点数\", [品牌价值_传播网点数目标实际差异],",
              " \"传播成本\", [品牌价值_传播成本目标实际差异],",
              " \"传播的投入产出比\", [品牌价值_传播的投入产出比目标实际差异]",
              " )"
            ]
          }
        ]
      },
      {
        "name": "盈利空间_指标动态维度",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "subject_name",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \"毛利率\" , ),",
                "    ( \"回款额\" , ),",
                "    ( \"回款增长额\" , ),",
                "    ( \"回款增长率\" , ),",
                "    ( \"总成本费用额\" , ),",
                "    ( \"总成本费用增长额\" , ),",
                "    ( \"总成本费用增长率\" , ),",
                "    ( \"盈利空间\" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "盈利空间_实际",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('盈利空间_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"毛利率\", [盈利空间_毛利率实际],",
              " \"回款额\", [盈利空间_回款额实际],",
              " \"回款增长额\", [盈利空间_回款增长额实际],",
              " \"回款增长率\", [盈利空间_回款增长率实际],",
              " \"总成本费用额\", [盈利空间_总成本费用额实际],",
              " \"总成本费用增长额\", [盈利空间_总成本费用增长额实际],",
              " \"总成本费用增长率\", [盈利空间_总成本费用增长率实际],",
              " \"盈利空间\", [盈利空间_盈利空间实际]",
              " )"
            ]
          },
          {
            "name": "盈利空间_目标",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('盈利空间_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"毛利率\", [盈利空间_毛利率目标],",
              " \"回款额\", [盈利空间_回款额目标],",
              " \"回款增长额\", [盈利空间_回款增长额目标],",
              " \"回款增长率\", [盈利空间_回款增长率目标],",
              " \"总成本费用额\", [盈利空间_总成本费用额目标],",
              " \"总成本费用增长额\", [盈利空间_总成本费用增长额目标],",
              " \"总成本费用增长率\", [盈利空间_总成本费用增长率目标],",
              " \"盈利空间\", [盈利空间_盈利空间目标]",
              " )"
            ]
          },
          {
            "name": "盈利空间_差异",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('盈利空间_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"毛利率\", [盈利空间_毛利率目标实际差异],",
              " \"回款额\", [盈利空间_回款额目标实际差异],",
              " \"回款增长额\", [盈利空间_回款增长额目标实际差异],",
              " \"回款增长率\", [盈利空间_回款增长率目标实际差异],",
              " \"总成本费用额\", [盈利空间_总成本费用额目标实际差异],",
              " \"总成本费用增长额\", [盈利空间_总成本费用增长额目标实际差异],",
              " \"总成本费用增长率\", [盈利空间_总成本费用增长率目标实际差异],",
              " \"盈利空间\", [盈利空间_盈利空间目标实际差异]",
              " )"
            ]
          }
        ]
      },
      {
        "name": "盈利能力_指标动态维度",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "subject_name",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \"订单额\" , ),",
                "    ( \"订单增长额\" , ),",
                "    ( \"订单增长率\" , ),",
                "    ( \"库存额\" , ),",
                "    ( \"库存增长额\" , ),",
                "    ( \"库存增长率\" , ),",
                "    ( \"库存周转率\" , ),",
                "    ( \"库龄\" , ),",
                "    ( \"盈利能力\" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "盈利能力_实际",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('盈利能力_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"订单额\", [盈利能力_订单额实际],",
              " \"订单增长额\", [盈利能力_订单增长额实际],",
              " \"订单增长率\", [盈利能力_订单增长率实际],",
              " \"库存额\", [盈利能力_库存额实际],",
              " \"库存增长额\", [盈利能力_库存增长额实际],",
              " \"库存增长率\", [盈利能力_库存增长率实际],",
              " \"库存周转率\", [盈利能力_库存周转率实际],",
              " \"库龄\", [盈利能力_库龄实际],",
              " \"盈利能力\", [盈利能力_盈利能力实际]",
              " )"
            ]
          },
          {
            "name": "盈利能力_目标",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('盈利能力_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"订单额\", [盈利能力_订单额目标],",
              " \"订单增长额\", [盈利能力_订单增长额目标],",
              " \"订单增长率\", [盈利能力_订单增长率目标],",
              " \"库存额\", [盈利能力_库存额目标],",
              " \"库存增长额\", [盈利能力_库存增长额目标],",
              " \"库存增长率\", [盈利能力_库存增长率目标],",
              " \"库存周转率\", [盈利能力_库存周转率目标],",
              " \"库龄\", [盈利能力_库龄目标],",
              " \"盈利能力\", [盈利能力_盈利能力目标]",
              " )"
            ]
          },
          {
            "name": "盈利能力_差异",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('盈利能力_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"订单额\", [盈利能力_订单额目标实际差异],",
              " \"订单增长额\", [盈利能力_订单增长额目标实际差异],",
              " \"订单增长率\", [盈利能力_订单增长率目标实际差异],",
              " \"库存额\", [盈利能力_库存额目标实际差异],",
              " \"库存增长额\", [盈利能力_库存增长额目标实际差异],",
              " \"库存增长率\", [盈利能力_库存增长率目标实际差异],",
              " \"库存周转率\", [盈利能力_库存周转率目标实际差异],",
              " \"库龄\", [盈利能力_库龄目标实际差异],",
              " \"盈利能力\", [盈利能力_盈利能力目标实际差异]",
              " )"
            ]
          }
        ]
      },
      {
        "name": "支付能力_指标动态维度",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "subject_name",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \"资金周转率\" , ),",
                "    ( \"固定资产占用率\" , ),",
                "    ( \"现金流入\" , ),",
                "    ( \"现金流出\" , ),",
                "    ( \"净现金流\" , ),",
                "    ( \"应收额\" , ),",
                "    ( \"应收增长额\" , ),",
                "    ( \"应收增长率\" , ),",
                "    ( \"应付额\" , ),",
                "    ( \"应付增长额\" , ),",
                "    ( \"应付增长率\" , ),",
                "    ( \"支付能力1\" , ),",
                "    ( \"支付能力2\" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "支付能力_实际",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('支付能力_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"资金周转率\", [支付能力_资金周转率实际],",
              " \"固定资产占用率\", [支付能力_固定资产占用率实际],",
              " \"现金流入\", [支付能力_现金流入实际],",
              " \"现金流出\", [支付能力_现金流出实际],",
              " \"净现金流\", [支付能力_净现金流实际],",
              " \"应收额\", [支付能力_应收额实际],",
              " \"应收增长额\", [支付能力_应收增长额实际],",
              " \"应收增长率\", [支付能力_应收增长率实际],",
              " \"应付额\", [支付能力_应付额实际],",
              " \"应付增长额\", [支付能力_应付增长额实际],",
              " \"应付增长率\", [支付能力_应付增长率实际],",
              " \"支付能力1\", [支付能力_支付能力1实际],",
              " \"支付能力2\", [支付能力_支付能力2实际]",
              " )"
            ]
          },
          {
            "name": "支付能力_目标",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('支付能力_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"资金周转率\", [支付能力_资金周转率目标],",
              " \"固定资产占用率\", [支付能力_固定资产占用率目标],",
              " \"现金流入\", [支付能力_现金流入目标],",
              " \"现金流出\", [支付能力_现金流出目标],",
              " \"净现金流\", [支付能力_净现金流目标],",
              " \"应收额\", [支付能力_应收额目标],",
              " \"应收增长额\", [支付能力_应收增长额目标],",
              " \"应收增长率\", [支付能力_应收增长率目标],",
              " \"应付额\", [支付能力_应付额目标],",
              " \"应付增长额\", [支付能力_应付增长额目标],",
              " \"应付增长率\", [支付能力_应付增长率目标],",
              " \"支付能力1\", [支付能力_支付能力1目标],",
              " \"支付能力2\", [支付能力_支付能力2目标]",
              " )"
            ]
          },
          {
            "name": "支付能力_差异",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('支付能力_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"资金周转率\", [支付能力_资金周转率目标实际差异],",
              " \"固定资产占用率\", [支付能力_固定资产占用率目标实际差异],",
              " \"现金流入\", [支付能力_现金流入目标实际差异],",
              " \"现金流出\", [支付能力_现金流出目标实际差异],",
              " \"净现金流\", [支付能力_净现金流目标实际差异],",
              " \"应收额\", [支付能力_应收额目标实际差异],",
              " \"应收增长额\", [支付能力_应收增长额目标实际差异],",
              " \"应收增长率\", [支付能力_应收增长率目标实际差异],",
              " \"应付额\", [支付能力_应付额目标实际差异],",
              " \"应付增长额\", [支付能力_应付增长额目标实际差异],",
              " \"应付增长率\", [支付能力_应付增长率目标实际差异],",
              " \"支付能力1\", [支付能力_支付能力1目标实际差异],",
              " \"支付能力2\", [支付能力_支付能力2目标实际差异]",
              " )"
            ]
          }
        ]
      },
      {
        "name": "tree_channel",
        "columns": [
          {
            "name": "ChannelKey",
            "dataType": "int64",
            "sourceColumn": "ChannelKey"
          },
          {
            "name": "cha_id",
            "dataType": "string",
            "sourceColumn": "cha_id"
          },
          {
            "name": "cha_name",
            "dataType": "string",
            "sourceColumn": "cha_name"
          },
          {
            "name": "ParentKey",
            "dataType": "int64",
            "sourceColumn": "ParentKey"
          },
          {
            "name": "level",
            "dataType": "int64",
            "sourceColumn": "level"
          },
          {
            "name": "is_parent",
            "dataType": "int64",
            "sourceColumn": "is_parent"
          },
          {
            "name": "level_cn",
            "dataType": "string",
            "sourceColumn": "level_cn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_tree_channel = Source{[Schema=\"dbo\",Item=\"tree_channel\"]}[Data],",
                "    #\"Added Conditional Column\" = Table.AddColumn(dbo_tree_channel, \"level_cn\", each if [level] = 1 then \"公司\" else if [level] = 2 then \"品牌\" else if [level] = 3 then \"平台\" else if [level] = 4 then \"店铺\" else if [level] = 5 then \"页面\" else null)",
                "in",
                "    #\"Added Conditional Column\""
              ]
            }
          }
        ]
      },
      {
        "name": "tree_customer",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "cus_id",
            "dataType": "string",
            "sourceColumn": "cus_id"
          },
          {
            "name": "cus_name",
            "dataType": "string",
            "sourceColumn": "cus_name"
          },
          {
            "name": "ParentKey",
            "dataType": "int64",
            "sourceColumn": "ParentKey"
          },
          {
            "name": "level",
            "dataType": "int64",
            "sourceColumn": "level"
          },
          {
            "name": "is_parent",
            "dataType": "int64",
            "sourceColumn": "is_parent"
          },
          {
            "name": "level_cn",
            "dataType": "string",
            "sourceColumn": "level_cn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_tree_customer = Source{[Schema=\"dbo\",Item=\"tree_customer\"]}[Data],",
                "    #\"Added Conditional Column\" = Table.AddColumn(dbo_tree_customer, \"level_cn\", each if [level] = 1 then \"公司\" else if [level] = 2 then \"整体人群\" else if [level] = 3 then \"聚类人群\" else if [level] = 4 then \"典型客户\" else if [level] = 5 then \"客户\" else null)",
                "in",
                "    #\"Added Conditional Column\""
              ]
            }
          }
        ]
      },
      {
        "name": "tree_org",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "org_id",
            "dataType": "string",
            "sourceColumn": "org_id"
          },
          {
            "name": "org_name",
            "dataType": "string",
            "sourceColumn": "org_name"
          },
          {
            "name": "ParentKey",
            "dataType": "int64",
            "sourceColumn": "ParentKey"
          },
          {
            "name": "level",
            "dataType": "int64",
            "sourceColumn": "level"
          },
          {
            "name": "is_parent",
            "dataType": "int64",
            "sourceColumn": "is_parent"
          },
          {
            "name": "type",
            "dataType": "int64",
            "sourceColumn": "type"
          },
          {
            "name": "level_cn",
            "dataType": "string",
            "sourceColumn": "level_cn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_tree_org = Source{[Schema=\"dbo\",Item=\"tree_org\"]}[Data],",
                "    #\"Added Conditional Column\" = Table.AddColumn(dbo_tree_org, \"level_cn\", each if [level] = 1 then \"集团\" else if [level] = 2 then \"公司\" else if [level] = 3 then \"事业部\" else if [level] = 4 then \"部门\" else if [level] = 5 then \"小组\" else null)",
                "in",
                "    #\"Added Conditional Column\""
              ]
            }
          }
        ]
      },
      {
        "name": "tree_product",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "pro_id",
            "dataType": "string",
            "sourceColumn": "pro_id"
          },
          {
            "name": "pro_name",
            "dataType": "string",
            "sourceColumn": "pro_name"
          },
          {
            "name": "ParentKey",
            "dataType": "int64",
            "sourceColumn": "ParentKey"
          },
          {
            "name": "level",
            "dataType": "int64",
            "sourceColumn": "level"
          },
          {
            "name": "is_parent",
            "dataType": "int64",
            "sourceColumn": "is_parent"
          },
          {
            "name": "level_cn",
            "dataType": "string",
            "sourceColumn": "level_cn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_tree_product = Source{[Schema=\"dbo\",Item=\"tree_product\"]}[Data],",
                "    #\"Added Conditional Column\" = Table.AddColumn(dbo_tree_product, \"level_cn\", each if [level] = 1 then \"公司\" else if [level] = 2 then \"品牌\" else if [level] = 3 then \"品类\" else if [level] = 4 then \"品种\" else if [level] = 5 then \"单品\" else null)",
                "in",
                "    #\"Added Conditional Column\""
              ]
            }
          }
        ]
      },
      {
        "name": "tree_supply",
        "columns": [
          {
            "name": "SupplyKey",
            "dataType": "int64",
            "sourceColumn": "SupplyKey"
          },
          {
            "name": "supply_id",
            "dataType": "string",
            "sourceColumn": "supply_id"
          },
          {
            "name": "supply_name",
            "dataType": "string",
            "sourceColumn": "supply_name"
          },
          {
            "name": "ParentKey",
            "dataType": "int64",
            "sourceColumn": "ParentKey"
          },
          {
            "name": "level",
            "dataType": "int64",
            "sourceColumn": "level"
          },
          {
            "name": "is_parent",
            "dataType": "int64",
            "sourceColumn": "is_parent"
          },
          {
            "name": "type",
            "dataType": "int64",
            "sourceColumn": "type"
          },
          {
            "name": "level_cn",
            "dataType": "string",
            "sourceColumn": "level_cn"
          },
          {
            "name": "供应商等级",
            "dataType": "string",
            "sourceColumn": "供应商等级"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_tree_supply = Source{[Schema=\"dbo\",Item=\"tree_supply\"]}[Data],",
                "    #\"Added Conditional Column\" = Table.AddColumn(dbo_tree_supply, \"level_cn\", each if [level] = 1 then \"公司\" else if [level] = 2 then \"生产类别\" else if [level] = 3 then \"工厂\" else if [level] = 4 then \"产线\" else if [level] = 5 then \"产组\" else null),",
                "    已添加条件列 = Table.AddColumn(#\"Added Conditional Column\", \"供应商等级\", each if [type] = 1 then \"战略供应商\" else if [type] = 2 then \"合作供应商\" else if [type] = 3 then \"通用供应商 \" else if [type] = 4 then \"瓶颈供应商\" else null)",
                "in",
                "    已添加条件列"
              ]
            }
          }
        ]
      },
      {
        "name": "绩效_外部合作_指标动态维度",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "subject_name",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[subject_name]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \"产能\",\"\" ),",
                "    ( \"品质\"  ,\"\" ),",
                "    ( \"性价\" ,\"\" ),",
                "    ( \"交付\" ,\"\" ),",
                "    ( \"效率\" ,\"\" ),",
                "    ( \"服务\" ,\"\" ),",
                "    ( \"资金\"  ,\"\"),",
                "    ( \"开发\"  ,\"\")",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"subject_name\" , [Value1] )"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "选择指标绩效得分",
            "expression": [
              "",
              "VAR SELECTVLAUE = SELECTEDVALUE('绩效_外部合作_指标动态维度'[subject_name])",
              "RETURN ",
              "SWITCH(",
              " SELECTVLAUE, ",
              " \"产能\", [外部合作_产能得分],",
              " \"品质\", [外部合作_品质得分],",
              " \"性价\", [外部合作_性价得分],",
              " \"交付\", [外部合作_交付得分],",
              " \"效率\", [外部合作_效率得分],",
              " \"服务\", [外部合作_服务得分],",
              " \"资金\", [外部合作_资金得分],",
              " \"开发\", [外部合作_开发得分]",
              " )"
            ]
          },
          {
            "name": "外部合作_产能得分",
            "expression": " AVERAGE('fact_external_performance'[capacity_score])",
            "formatString": "0.00"
          },
          {
            "name": "外部合作_品质得分",
            "expression": " AVERAGE('fact_external_performance'[quality_score])",
            "formatString": "0.00"
          },
          {
            "name": "外部合作_性价得分",
            "expression": " AVERAGE('fact_external_performance'[value_for_money_score])",
            "formatString": "0.00"
          },
          {
            "name": "外部合作_交付得分",
            "expression": " AVERAGE('fact_external_performance'[delivery_score])",
            "formatString": "0.00"
          },
          {
            "name": "外部合作_效率得分",
            "expression": " AVERAGE('fact_external_performance'[efficiency_score])",
            "formatString": "0.00"
          },
          {
            "name": "外部合作_服务得分",
            "expression": " AVERAGE('fact_external_performance'[service_score])",
            "formatString": "0.00"
          },
          {
            "name": "外部合作_资金得分",
            "expression": " AVERAGE('fact_external_performance'[finance_score])",
            "formatString": "0.00"
          },
          {
            "name": "外部合作_开发得分",
            "expression": " AVERAGE('fact_external_performance'[development_score])",
            "formatString": "0.00"
          },
          {
            "name": "外部合作_总得分",
            "expression": " [外部合作_交付得分]*0.125+[外部合作_产能得分]*0.125+[外部合作_品质得分]*0.125+[外部合作_开发得分]*0.125+[外部合作_性价得分]*0.125+[外部合作_效率得分]*0.125+[外部合作_服务得分]*0.125+[外部合作_资金得分]*0.125",
            "formatString": "0.00"
          }
        ]
      },
      {
        "name": "雷达_绩效_外部合作",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "指标",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[指标]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "绩效得分",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[绩效得分]",
            "formatString": "0.00"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{",
                "    ( \"产能\" ,   [外部合作_产能得分]),",
                "    ( \"品质\" ,   [外部合作_品质得分]),",
                "    ( \"性价\" ,   [外部合作_性价得分]),",
                "    ( \"交付\" ,   [外部合作_交付得分]),",
                "    ( \"效率\" ,   [外部合作_效率得分]),",
                "    ( \"服务\" ,   [外部合作_服务得分]),",
                "    ( \"资金\" ,   [外部合作_资金得分]),",
                "    ( \"开发\" ,   [外部合作_开发得分]) ",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \"指标\" , [Value1] , \"绩效得分\" , [Value2] )"
              ]
            }
          }
        ]
      },
      {
        "name": "度量值_预算",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "列1",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[ ]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR X =",
                "{ ",
                "    ( \" \" , )",
                "} ",
                "RETURN",
                "SELECTCOLUMNS( X , \" \" , [Value1])"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "预算_科目目标",
            "expression": [
              " ",
              "    IF (",
              "        HASONEVALUE ( dim_org[c5_name] ),",
              "        CALCULATE (",
              "            SUM (target_budget[target_cost_amt]),",
              "             target_budget[OrgKey] = VALUES (dim_org[c5])",
              "        ),",
              "        IF (",
              "            HASONEVALUE (dim_org[c4_name] ),",
              "            CALCULATE (",
              "                SUM (target_budget[target_cost_amt]),",
              "                target_budget[OrgKey]= VALUES (dim_org[c4] )",
              "            ),",
              "            IF (",
              "                HASONEVALUE ( dim_org[c3_name] ),",
              "                CALCULATE (",
              "                    SUM (target_budget[OrgKey]),",
              "                    target_budget[OrgKey] = VALUES (dim_org[c3] )",
              "                ),",
              "                 IF (",
              "                HASONEVALUE ( dim_org[c2_name] ),",
              "                CALCULATE (",
              "                    SUM (target_budget[OrgKey]),",
              "                    target_budget[OrgKey] = VALUES (dim_org[c2] )",
              "                ),",
              "                 IF (",
              "                HASONEVALUE ( dim_org[c1_name] ),",
              "                CALCULATE (",
              "                    SUM (target_budget[OrgKey]),",
              "                    target_budget[OrgKey] = VALUES (dim_org[c1] )",
              "                )",
              "                )",
              "                )",
              "                )",
              "            )",
              "   )"
            ],
            "formatString": "0.00"
          },
          {
            "name": "预算_科目目标达成率",
            "expression": " DIVIDE([预算_科目实际],[预算_科目目标])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "预算_科目实际",
            "expression": " SUMX('fact_application_fee','fact_application_fee'[cost_amt])",
            "formatString": "0.00"
          }
        ]
      },
      {
        "name": "总得分",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "fact_performance_OrgKey",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "fact_performance[OrgKey]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "total score",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[total score]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "fact_performance_DateKey",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "fact_performance[DateKey]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "GROUPBY('fact_performance','fact_performance'[OrgKey],'fact_performance'[DateKey],\"total score\",SUMX(CURRENTGROUP(),'fact_performance'[score]*'fact_performance'[weights]))"
            }
          }
        ]
      },
      {
        "name": "strategy_library",
        "columns": [
          {
            "name": "id",
            "dataType": "int64",
            "sourceColumn": "id"
          },
          {
            "name": "lxxl_type",
            "dataType": "int64",
            "sourceColumn": "lxxl_type"
          },
          {
            "name": "lxxl_level",
            "dataType": "int64",
            "sourceColumn": "lxxl_level"
          },
          {
            "name": "type",
            "dataType": "int64",
            "sourceColumn": "type"
          },
          {
            "name": "subject",
            "dataType": "string",
            "sourceColumn": "subject"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "rank",
            "dataType": "int64",
            "sourceColumn": "rank"
          },
          {
            "name": "influencing_factor",
            "dataType": "string",
            "sourceColumn": "influencing_factor"
          },
          {
            "name": "strategy",
            "dataType": "string",
            "sourceColumn": "strategy"
          },
          {
            "name": "status",
            "dataType": "int64",
            "sourceColumn": "status"
          },
          {
            "name": "subject_type",
            "dataType": "int64",
            "sourceColumn": "subject_type"
          },
          {
            "name": "rankCn",
            "dataType": "string",
            "sourceColumn": "rankCn"
          },
          {
            "name": "lxxl_level_cn_orgFin",
            "dataType": "string",
            "sourceColumn": "lxxl_level_cn_orgFin"
          },
          {
            "name": "lxxl_level_cn",
            "dataType": "string",
            "sourceColumn": "lxxl_level_cn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_strategy_library = Source{[Schema=\"dbo\",Item=\"strategy_library\"]}[Data],",
                "    #\"Added Conditional Column\" = Table.AddColumn(dbo_strategy_library, \"rankCn\", each if [rank] = 1 then \"优\" else if [rank] = 2 then \"良\" else if [rank] = 3 then \"中\" else if [rank] = 4 then \"差\" else null),",
                "    #\"Added Conditional Column1\" = Table.AddColumn(#\"Added Conditional Column\", \"lxxl_level_cn_orgFin\", each if [lxxl_level] = 1 then \"集团\" else if [lxxl_level] = 2 then \"公司\" else if [lxxl_level] = 3 then \"事业部\" else if [lxxl_level] = 4 then \"部门\" else if [lxxl_level] = 5 then \"小组\" else null),",
                "    #\"Added Conditional Column2\" = Table.AddColumn(#\"Added Conditional Column1\", \"lxxl_level_cn\", ",
                "each if [lxxl_type] = 1 and [lxxl_level] = 1  then \"公司\" else if [lxxl_type] = 1 and  [lxxl_level] = 2 then \"品牌\" else if [lxxl_type] = 1 and [lxxl_level] = 3 then \"品类\" else if [lxxl_type] = 1 and  [lxxl_level] = 4 then \"品种\" else if [lxxl_type] = 1 and  [lxxl_level] = 5 then \"单品\" ",
                "else if [lxxl_type] = 2 and  [lxxl_level] = 1 then \"公司\" else if [lxxl_type] = 2 and  [lxxl_level] = 2 then \"品牌\" else if [lxxl_type] = 2 and  [lxxl_level] = 3 then \"平台\"  else if [lxxl_type] = 2 and  [lxxl_level] = 4 then \"店铺\"  else if [lxxl_type] = 2 and  [lxxl_level] = 5 then \"页面\" ",
                "else if [lxxl_type] = 3 and  [lxxl_level] = 1 then \"公司\" else if [lxxl_type] = 3 and  [lxxl_level] = 2 then \"事业部\" else if [lxxl_type] = 3 and  [lxxl_level] = 3 then \"部门\" else if [lxxl_type] = 3 and  [lxxl_level] = 4 then \"小组\" else if [lxxl_type] = 3 and  [lxxl_level] = 5 then \"个人\" ",
                "else if [lxxl_type] = 4 and  [lxxl_level] = 1 then \"公司\" else if [lxxl_type] = 4 and  [lxxl_level] = 2 then \"事业部\" else if [lxxl_type] = 4 and  [lxxl_level] = 3 then \"部门\" else if [lxxl_type] = 4 and  [lxxl_level] = 4 then \"小组\" else if [lxxl_type] = 4 and  [lxxl_level] = 5 then \"个人\" ",
                "else if [lxxl_type] = 5 and  [lxxl_level] = 1 then \"整体人群\" else if [lxxl_type] = 5 and  [lxxl_level] = 2 then \"聚类人群\" else if [lxxl_type] = 5 and  [lxxl_level] = 3 then \"典型客户\" else if [lxxl_type] = 5 and  [lxxl_level] = 4 then \"普通客户\" else if [lxxl_type] = 5 and  [lxxl_level] = 5 then \"客户\"  ",
                "else if [lxxl_type] = 6 and  [lxxl_level] = 1 then \"公司\" else if [lxxl_type] = 6 and  [lxxl_level] = 2 then \"生产类别\" else if [lxxl_type] = 6 and  [lxxl_level] = 3 then \"工厂\" else if [lxxl_type] = 6 and  [lxxl_level] = 4 then \"产线\" else if [lxxl_type] = 6 and  [lxxl_level] = 5 then \"产组\"   else null)",
                "in",
                "    #\"Added Conditional Column2\""
              ]
            }
          }
        ]
      },
      {
        "name": "tree_budget",
        "columns": [
          {
            "name": "BudgetKey",
            "dataType": "int64",
            "sourceColumn": "BudgetKey"
          },
          {
            "name": "budget_id",
            "dataType": "string",
            "sourceColumn": "budget_id"
          },
          {
            "name": "budget_name",
            "dataType": "string",
            "sourceColumn": "budget_name"
          },
          {
            "name": "ParentKey",
            "dataType": "int64",
            "sourceColumn": "ParentKey"
          },
          {
            "name": "level",
            "dataType": "int64",
            "sourceColumn": "level"
          },
          {
            "name": "is_parent",
            "dataType": "int64",
            "sourceColumn": "is_parent"
          },
          {
            "name": "lxxl_type",
            "dataType": "int64",
            "sourceColumn": "lxxl_type"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_tree_budget = Source{[Schema=\"dbo\",Item=\"tree_budget\"]}[Data]",
                "in",
                "    dbo_tree_budget"
              ]
            }
          }
        ]
      },
      {
        "name": "result_finance",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "profit_amt",
            "dataType": "double",
            "sourceColumn": "profit_amt"
          },
          {
            "name": "sale_amt",
            "dataType": "double",
            "sourceColumn": "sale_amt"
          },
          {
            "name": "total_cost_amt",
            "dataType": "double",
            "sourceColumn": "total_cost_amt"
          },
          {
            "name": "return_amt",
            "dataType": "double",
            "sourceColumn": "return_amt"
          },
          {
            "name": "invest_amt",
            "dataType": "double",
            "sourceColumn": "invest_amt"
          },
          {
            "name": "total_assets_amt",
            "dataType": "double",
            "sourceColumn": "total_assets_amt"
          },
          {
            "name": "cash_flow_amt",
            "dataType": "double",
            "sourceColumn": "cash_flow_amt"
          },
          {
            "name": "net_interest_rate",
            "dataType": "double",
            "sourceColumn": "net_interest_rate"
          },
          {
            "name": "return_on_investment",
            "dataType": "double",
            "sourceColumn": "return_on_investment"
          },
          {
            "name": "capital_turnover_rate",
            "dataType": "double",
            "sourceColumn": "capital_turnover_rate"
          },
          {
            "name": "redundancy",
            "dataType": "double",
            "sourceColumn": "redundancy"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_result_finance = Source{[Schema=\"dbo\",Item=\"result_finance\"]}[Data]",
                "in",
                "    dbo_result_finance"
              ]
            }
          }
        ]
      },
      {
        "name": "result_channel",
        "columns": [
          {
            "name": "ChannelKey",
            "dataType": "int64",
            "sourceColumn": "ChannelKey"
          },
          {
            "name": "profit_amt",
            "dataType": "double",
            "sourceColumn": "profit_amt"
          },
          {
            "name": "sale_amt",
            "dataType": "double",
            "sourceColumn": "sale_amt"
          },
          {
            "name": "cost_amt",
            "dataType": "double",
            "sourceColumn": "cost_amt"
          },
          {
            "name": "input_output_ratio",
            "dataType": "double",
            "sourceColumn": "input_output_ratio"
          },
          {
            "name": "redundancy",
            "dataType": "double",
            "sourceColumn": "redundancy"
          },
          {
            "name": "day_sale_amt",
            "dataType": "double",
            "sourceColumn": "day_sale_amt"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_result_channel = Source{[Schema=\"dbo\",Item=\"result_channel\"]}[Data]",
                "in",
                "    dbo_result_channel"
              ]
            }
          }
        ]
      },
      {
        "name": "result_org",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "profit_amt",
            "dataType": "double",
            "sourceColumn": "profit_amt"
          },
          {
            "name": "sale_amt",
            "dataType": "double",
            "sourceColumn": "sale_amt"
          },
          {
            "name": "cost_amt",
            "dataType": "double",
            "sourceColumn": "cost_amt"
          },
          {
            "name": "input_output_ratio",
            "dataType": "double",
            "sourceColumn": "input_output_ratio"
          },
          {
            "name": "day_sale_amt",
            "dataType": "double",
            "sourceColumn": "day_sale_amt"
          },
          {
            "name": "redundancy",
            "dataType": "double",
            "sourceColumn": "redundancy"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_result_org = Source{[Schema=\"dbo\",Item=\"result_org\"]}[Data],",
                "    筛选的行 = Table.SelectRows(dbo_result_org, each true)",
                "in",
                "    筛选的行"
              ]
            }
          }
        ]
      },
      {
        "name": "result_product",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "profit_amt",
            "dataType": "double",
            "sourceColumn": "profit_amt"
          },
          {
            "name": "sale_amt",
            "dataType": "double",
            "sourceColumn": "sale_amt"
          },
          {
            "name": "cost_amt",
            "dataType": "double",
            "sourceColumn": "cost_amt"
          },
          {
            "name": "stock_amt",
            "dataType": "double",
            "sourceColumn": "stock_amt"
          },
          {
            "name": "stock_rate",
            "dataType": "double",
            "sourceColumn": "stock_rate"
          },
          {
            "name": "day_sale_amt",
            "dataType": "double",
            "sourceColumn": "day_sale_amt"
          },
          {
            "name": "input_output_ratio",
            "dataType": "double",
            "sourceColumn": "input_output_ratio"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_result_product = Source{[Schema=\"dbo\",Item=\"result_product\"]}[Data]",
                "in",
                "    dbo_result_product"
              ]
            }
          }
        ]
      },
      {
        "name": "rank_channel",
        "columns": [
          {
            "name": "ChannelKey",
            "dataType": "int64",
            "sourceColumn": "ChannelKey"
          },
          {
            "name": "subject",
            "dataType": "string",
            "sourceColumn": "subject"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "real_value",
            "dataType": "double",
            "sourceColumn": "real_value"
          },
          {
            "name": "ring_value",
            "dataType": "double",
            "sourceColumn": "ring_value"
          },
          {
            "name": "yoy_value",
            "dataType": "double",
            "sourceColumn": "yoy_value"
          },
          {
            "name": "score",
            "dataType": "double",
            "sourceColumn": "score"
          },
          {
            "name": "rank",
            "dataType": "int64",
            "sourceColumn": "rank"
          },
          {
            "name": "date_type",
            "dataType": "int64",
            "sourceColumn": "date_type"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          },
          {
            "name": "rankCn",
            "dataType": "string",
            "sourceColumn": "rankCn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_rank_channel = Source{[Schema=\"dbo\",Item=\"rank_channel\"]}[Data],",
                "    已添加条件列 = Table.AddColumn(dbo_rank_channel, \"rankCn\", each if [rank] = 1 then \"优\" else if [rank] = 2 then \"良\" else if [rank] = 3 then \"中\" else if [rank] = 4 then \"差\" else null)",
                "in",
                "    已添加条件列"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "rank_channel_颜色填充",
            "expression": " SWITCH(SELECTEDVALUE('rank_channel'[rankCn]),\"差\",\"#A7DCFC\",\"中\",\"#70BCDE\",\"良\",\"#23A9CC\",\"优\",\"#007Eb0\")"
          },
          {
            "name": "rankCn_chananel_转换",
            "expression": "IF(SELECTEDVALUE('rank_channel'[rank])=1,\"优\",IF(SELECTEDVALUE('rank_channel'[rank])=2,\"良\",IF(SELECTEDVALUE('rank_channel'[rank])=3,\"中\",IF(SELECTEDVALUE('rank_channel'[rank])=4,\"差\",\"暂无\"))))"
          }
        ]
      },
      {
        "name": "rank_customer",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "subject",
            "dataType": "string",
            "sourceColumn": "subject"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "real_value",
            "dataType": "double",
            "sourceColumn": "real_value"
          },
          {
            "name": "ring_value",
            "dataType": "double",
            "sourceColumn": "ring_value"
          },
          {
            "name": "yoy_value",
            "dataType": "double",
            "sourceColumn": "yoy_value"
          },
          {
            "name": "score",
            "dataType": "double",
            "sourceColumn": "score"
          },
          {
            "name": "rank",
            "dataType": "int64",
            "sourceColumn": "rank"
          },
          {
            "name": "date_type",
            "dataType": "int64",
            "sourceColumn": "date_type"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          },
          {
            "name": "rankCn",
            "dataType": "string",
            "sourceColumn": "rankCn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_rank_customer = Source{[Schema=\"dbo\",Item=\"rank_customer\"]}[Data],",
                "    已添加条件列 = Table.AddColumn(dbo_rank_customer, \"rankCn\", each if [rank] = 1 then \"优\" else if [rank] = 2 then \"良\" else if [rank] = 3 then \"中\" else if [rank] = 4 then \"差\" else null)",
                "in",
                "    已添加条件列"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "rank_customer_颜色填充",
            "expression": " SWITCH(SELECTEDVALUE('rank_customer'[rankCn]),\"差\",\"#A7DCFC\",\"中\",\"#70BCDE\",\"良\",\"#23A9CC\",\"优\",\"#007Eb0\")"
          },
          {
            "name": "rankCn_customer_转换",
            "expression": "IF(SELECTEDVALUE('rank_customer'[rank])=1,\"优\",IF(SELECTEDVALUE('rank_customer'[rank])=2,\"良\",IF(SELECTEDVALUE('rank_customer'[rank])=3,\"中\",IF(SELECTEDVALUE('rank_customer'[rank])=4,\"差\",\"暂无\"))))"
          }
        ]
      },
      {
        "name": "rank_finance",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "subject",
            "dataType": "string",
            "sourceColumn": "subject"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "real_value",
            "dataType": "double",
            "sourceColumn": "real_value"
          },
          {
            "name": "ring_value",
            "dataType": "double",
            "sourceColumn": "ring_value"
          },
          {
            "name": "yoy_value",
            "dataType": "double",
            "sourceColumn": "yoy_value"
          },
          {
            "name": "score",
            "dataType": "double",
            "sourceColumn": "score"
          },
          {
            "name": "rank",
            "dataType": "int64",
            "sourceColumn": "rank"
          },
          {
            "name": "date_type",
            "dataType": "int64",
            "sourceColumn": "date_type"
          },
          {
            "name": "rankCn",
            "dataType": "string",
            "sourceColumn": "rankCn"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_rank_finance = Source{[Schema=\"dbo\",Item=\"rank_finance\"]}[Data],",
                "    已添加条件列 = Table.AddColumn(dbo_rank_finance, \"rankCn\", each if [rank] = 1 then \"优\" else if [rank] = 2 then \"良\" else if [rank] = 3 then \"中\" else if [rank] = 4 then \"差\" else null)",
                "in",
                "    已添加条件列"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "rank_finance_颜色填充",
            "expression": " SWITCH(SELECTEDVALUE('rank_finance'[rankCn]),\"差\",\"#A7DCFC\",\"中\",\"#70BCDE\",\"良\",\"#23A9CC\",\"优\",\"#007Eb0\")"
          },
          {
            "name": "rankCn_finance_转换",
            "expression": "IF(SELECTEDVALUE('rank_finance'[rank])=1,\"优\",IF(SELECTEDVALUE('rank_finance'[rank])=2,\"良\",IF(SELECTEDVALUE('rank_finance'[rank])=3,\"中\",IF(SELECTEDVALUE('rank_finance'[rank])=4,\"差\",\"暂无\"))))"
          }
        ]
      },
      {
        "name": "rank_org",
        "columns": [
          {
            "name": "OrgKey",
            "dataType": "int64",
            "sourceColumn": "OrgKey"
          },
          {
            "name": "subject",
            "dataType": "string",
            "sourceColumn": "subject"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "real_value",
            "dataType": "double",
            "sourceColumn": "real_value"
          },
          {
            "name": "ring_value",
            "dataType": "double",
            "sourceColumn": "ring_value"
          },
          {
            "name": "yoy_value",
            "dataType": "double",
            "sourceColumn": "yoy_value"
          },
          {
            "name": "score",
            "dataType": "double",
            "sourceColumn": "score"
          },
          {
            "name": "rank",
            "dataType": "int64",
            "sourceColumn": "rank"
          },
          {
            "name": "date_type",
            "dataType": "int64",
            "sourceColumn": "date_type"
          },
          {
            "name": "rankCn",
            "dataType": "string",
            "sourceColumn": "rankCn"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_rank_org = Source{[Schema=\"dbo\",Item=\"rank_org\"]}[Data],",
                "    已添加条件列 = Table.AddColumn(dbo_rank_org, \"rankCn\", each if [rank] = 1 then \"优\" else if [rank] = 2 then \"良\" else if [rank] = 3 then \"中\" else if [rank] = 4 then \"差\" else null)",
                "in",
                "    已添加条件列"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "rank_org_颜色填充",
            "expression": " SWITCH(SELECTEDVALUE('rank_org'[rankCn]),\"差\",\"#A7DCFC\",\"中\",\"#70BCDE\",\"良\",\"#23A9CC\",\"优\",\"#007Eb0\")"
          },
          {
            "name": "rankCn_org_转换",
            "expression": "IF(SELECTEDVALUE('rank_org'[rank])=1,\"优\",IF(SELECTEDVALUE('rank_org'[rank])=2,\"良\",IF(SELECTEDVALUE('rank_org'[rank])=3,\"中\",IF(SELECTEDVALUE('rank_org'[rank])=4,\"差\",\"暂无\"))))"
          }
        ]
      },
      {
        "name": "rank_product",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "subject",
            "dataType": "string",
            "sourceColumn": "subject"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "real_value",
            "dataType": "double",
            "sourceColumn": "real_value"
          },
          {
            "name": "ring_value",
            "dataType": "double",
            "sourceColumn": "ring_value"
          },
          {
            "name": "yoy_value",
            "dataType": "double",
            "sourceColumn": "yoy_value"
          },
          {
            "name": "score",
            "dataType": "double",
            "sourceColumn": "score"
          },
          {
            "name": "rank",
            "dataType": "int64",
            "sourceColumn": "rank"
          },
          {
            "name": "date_type",
            "dataType": "int64",
            "sourceColumn": "date_type"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          },
          {
            "name": "rankCn",
            "dataType": "string",
            "sourceColumn": "rankCn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_rank_product = Source{[Schema=\"dbo\",Item=\"rank_product\"]}[Data],",
                "    已添加条件列 = Table.AddColumn(dbo_rank_product, \"rankCn\", each if [rank] = 1 then \"优\" else if [rank] = 2 then \"良\" else if [rank] = 3 then \"中\" else if [rank] = 4 then \"差\" else null)",
                "in",
                "    已添加条件列"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "rank_product_颜色填充",
            "expression": " SWITCH(MAX('rank_product'[rankCn]),\"差\",\"#A7DCFC\",\"中\",\"#70BCDE\",\"良\",\"#23A9CC\",\"优\",\"#007Eb0\",\"暂无\",\"E6E6E6\")"
          },
          {
            "name": "rankCn_product_转换",
            "expression": "IF(SELECTEDVALUE('rank_product'[rank])=1,\"优\",IF(SELECTEDVALUE('rank_product'[rank])=2,\"良\",IF(SELECTEDVALUE('rank_product'[rank])=3,\"中\",IF(SELECTEDVALUE('rank_product'[rank])=4,\"差\",\"暂无\"))))"
          }
        ]
      },
      {
        "name": "rank_supply",
        "columns": [
          {
            "name": "SupplyKey",
            "dataType": "int64",
            "sourceColumn": "SupplyKey"
          },
          {
            "name": "subject",
            "dataType": "string",
            "sourceColumn": "subject"
          },
          {
            "name": "subject_name",
            "dataType": "string",
            "sourceColumn": "subject_name"
          },
          {
            "name": "real_value",
            "dataType": "double",
            "sourceColumn": "real_value"
          },
          {
            "name": "ring_value",
            "dataType": "double",
            "sourceColumn": "ring_value"
          },
          {
            "name": "yoy_value",
            "dataType": "double",
            "sourceColumn": "yoy_value"
          },
          {
            "name": "score",
            "dataType": "double",
            "sourceColumn": "score"
          },
          {
            "name": "rank",
            "dataType": "int64",
            "sourceColumn": "rank"
          },
          {
            "name": "date_type",
            "dataType": "int64",
            "sourceColumn": "date_type"
          },
          {
            "name": "rankCn",
            "dataType": "string",
            "sourceColumn": "rankCn"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/10 8 1 66;test_yueying\",",
                "    dbo_rank_supply = Source{[Schema=\"dbo\",Item=\"rank_supply\"]}[Data],",
                "    已添加条件列 = Table.AddColumn(dbo_rank_supply, \"rankCn\", each if [rank] = 1 then \"优\" else if [rank] = 2 then \"良\" else if [rank] = 3 then \"中\" else if [rank] = 4 then \"差\" else null)",
                "in",
                "    已添加条件列"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "rank_supply_颜色填充",
            "expression": " SWITCH(SELECTEDVALUE('rank_supply'[rankCn]),\"差\",\"#A7DCFC\",\"中\",\"#70BCDE\",\"良\",\"#23A9CC\",\"优\",\"#007Eb0\")"
          },
          {
            "name": "rankCn_supply_转换",
            "expression": "IF(SELECTEDVALUE('rank_supply'[rank])=1,\"优\",IF(SELECTEDVALUE('rank_supply'[rank])=2,\"良\",IF(SELECTEDVALUE('rank_supply'[rank])=3,\"中\",IF(SELECTEDVALUE('rank_supply'[rank])=4,\"差\",\"暂无\"))))"
          }
        ]
      },
      {
        "name": "策略优化_有效次数",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "fact_strategy_log_strategy_id",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "fact_strategy_log[strategy_id]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "采纳次数",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[采纳次数]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "有效次数",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[有效次数]"
          },
          {
            "type": "calculated",
            "name": "策略准确度",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": "DIVIDE('策略优化_有效次数'[有效次数],'策略优化_有效次数'[采纳次数])"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "GROUPBY('fact_strategy_log','fact_strategy_log'[strategy_id],\"采纳次数\", COUNTAX(CURRENTGROUP(),IF('fact_strategy_log'[useful]<>-1,fact_strategy_log[useful])),\"有效次数\", COUNTAX(CURRENTGROUP(),IF('fact_strategy_log'[useful]=1,fact_strategy_log[useful])))"
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "bdf14d78-b09b-42a6-b952-d1a663db8444",
        "fromTable": "fact_stock",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "0d83e0c9-1c3a-410a-927f-867247d43a17",
        "fromTable": "fact_order",
        "fromColumn": "PayDateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "c4469fa7-7331-4e07-a2e9-fa9324146acd",
        "fromTable": "result_supply",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "2ba45f3f-f2a9-421a-bf7f-6cdfdb997ebd",
        "fromTable": "fact_supply_order",
        "fromColumn": "OrderDateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "86cef6b7-ab7d-4671-8301-48caac50a3bd",
        "fromTable": "fact_channel_costs",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "41461d99-0b21-4377-9c9c-170a29028ddc",
        "fromTable": "result_customer",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "37e10b45-a6a6-46d7-acd0-c0b15dd98656",
        "fromTable": "fact_fin_costs",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "80a7a410-162a-452a-9bf7-2d5f0b21eb13",
        "fromTable": "fact_org_costs",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "9e1a20f2-3a96-4210-ad18-9d051cfde537",
        "fromTable": "fact_internal_plan",
        "fromColumn": "StageStartDateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "1cdd1d01-7cbc-436f-a0d8-2b1507448c53",
        "fromTable": "fact_performance",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "619ba72d-8b54-41c1-a8bb-b8f1074aeed9",
        "fromTable": "fact_external_performance",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "8ad77b3b-30c3-4bad-968a-cc0620eb3b09",
        "fromTable": "fact_amount_repaid",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "6c6e3866-0e3a-44a3-8b3f-003972de8003",
        "fromTable": "fact_person_costs",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "3af3ce22-397d-42f0-9c6f-214b54da543e",
        "fromTable": "fact_application_fee",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "f086cab9-663c-45d6-81a9-de4cffc53654",
        "fromTable": "fact_company",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "64267115-f689-430f-b0b7-03e9b22f1ddf",
        "fromTable": "target_product",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "4bd1ae59-69e9-4124-a56e-9064ac56fb9d",
        "fromTable": "target_channel",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "8e7a6842-1acd-4ede-b0cd-d591d6353643",
        "fromTable": "target_customer",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "33edb35b-cb91-4b27-b2ca-f87cf22b5631",
        "fromTable": "target_supply",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "9931c47c-c566-40a6-9cfc-abc392ced039",
        "fromTable": "target_org",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "6d1cc740-8140-4c2e-802e-6642a7b24333",
        "fromTable": "target_finance",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "fa4b9de4-d8f3-4ff4-8211-98046b0672b0",
        "fromTable": "target_budget",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "71409b7c-29fc-4799-a02b-614544de49bc",
        "fromTable": "target_company",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "a4d67ce5-e5c0-4cfe-9810-b3e65827a2b7",
        "fromTable": "target_supply_order",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "ecaaeb99-a1f2-4d6b-a156-1afbd2d8e4cf",
        "fromTable": "fact_amount_repaid",
        "fromColumn": "ChannelKey",
        "toTable": "dim_channel",
        "toColumn": "ChannelKey"
      },
      {
        "name": "b5d421fc-4d06-473b-b936-4b8336ef350b",
        "fromTable": "fact_application_fee",
        "fromColumn": "ChannelKey",
        "toTable": "dim_channel",
        "toColumn": "ChannelKey"
      },
      {
        "name": "6a58c528-8626-4960-9b14-b0e5d2b56e80",
        "fromTable": "fact_channel_costs",
        "fromColumn": "ChannelKey",
        "toTable": "dim_channel",
        "toColumn": "ChannelKey"
      },
      {
        "name": "478dca34-2836-4369-9a71-3a87e2987dac",
        "fromTable": "fact_order",
        "fromColumn": "ChannelKey",
        "toTable": "dim_channel",
        "toColumn": "ChannelKey"
      },
      {
        "name": "23c2650a-ac17-44c8-a590-9cffea4a1fd4",
        "fromTable": "fact_amount_repaid",
        "fromColumn": "OrgKey",
        "toTable": "dim_org",
        "toColumn": "OrgKey"
      },
      {
        "name": "de90c5af-5588-4509-837b-aa7b39d920ac",
        "fromTable": "fact_application_fee",
        "fromColumn": "OrgKey",
        "toTable": "dim_org",
        "toColumn": "OrgKey"
      },
      {
        "name": "0eec921d-e19a-4b1d-85b5-010817e652aa",
        "fromTable": "fact_fin_costs",
        "fromColumn": "OrgKey",
        "toTable": "dim_org",
        "toColumn": "OrgKey"
      },
      {
        "name": "d038ae6c-21cf-4f53-abe4-5325b7549e32",
        "fromTable": "fact_org_costs",
        "fromColumn": "OrgKey",
        "toTable": "dim_org",
        "toColumn": "OrgKey"
      },
      {
        "name": "1ebf96fe-76fa-4f52-b49e-d06f54d34f95",
        "fromTable": "fact_performance",
        "fromColumn": "OrgKey",
        "toTable": "dim_org",
        "toColumn": "OrgKey"
      },
      {
        "name": "98eff2a3-4a99-455b-ad29-36a941388ca1",
        "fromTable": "fact_person_costs",
        "fromColumn": "OrgKey",
        "toTable": "dim_org",
        "toColumn": "OrgKey"
      },
      {
        "name": "aad7b5a2-9436-4f0f-b4d5-e47e00bd8184",
        "fromTable": "fact_supply_order",
        "fromColumn": "OrgKey",
        "toTable": "dim_org",
        "toColumn": "OrgKey"
      },
      {
        "name": "5ca65ba9-15cf-4c93-a105-79c7badbe8f2",
        "fromTable": "target_company",
        "fromColumn": "OrgKey",
        "toTable": "dim_org",
        "toColumn": "OrgKey"
      },
      {
        "name": "e428491f-5102-41fa-bcd3-b70c180076c9",
        "fromTable": "target_supply_order",
        "fromColumn": "OrgKey",
        "toTable": "dim_org",
        "toColumn": "OrgKey"
      },
      {
        "name": "a8c497c9-32ea-49a9-b298-0a5317f9007f",
        "fromTable": "fact_order",
        "fromColumn": "ProductKey",
        "toTable": "dim_product",
        "toColumn": "ProductKey"
      },
      {
        "name": "b3d2d717-3acc-4164-8637-0c5dce3dfe81",
        "fromTable": "fact_stock",
        "fromColumn": "ProductKey",
        "toTable": "dim_product",
        "toColumn": "ProductKey"
      },
      {
        "name": "f6fa5420-d1ff-4282-93cb-1d0362e649c7",
        "fromTable": "fact_supply_order",
        "fromColumn": "ProductKey",
        "toTable": "dim_product",
        "toColumn": "ProductKey"
      },
      {
        "name": "e2b035a3-1153-41f6-8222-d7b24a420213",
        "fromTable": "target_supply_order",
        "fromColumn": "ProductKey",
        "toTable": "dim_product",
        "toColumn": "ProductKey"
      },
      {
        "name": "f52ccc12-6245-4bb3-a4cc-c5422ccb0623",
        "fromTable": "fact_external_performance",
        "fromColumn": "SupplyKey",
        "toTable": "dim_supply",
        "toColumn": "SupplyKey"
      },
      {
        "name": "5b3bca13-661f-4627-8e76-82e43506f16a",
        "fromTable": "fact_supply_order",
        "fromColumn": "SupplyKey",
        "toTable": "dim_supply",
        "toColumn": "SupplyKey"
      },
      {
        "name": "ff23933d-cfa7-427d-b45b-ef2b8d6d482d",
        "fromTable": "target_supply_order",
        "fromColumn": "SupplyKey",
        "toTable": "dim_supply",
        "toColumn": "SupplyKey"
      },
      {
        "name": "64dc1941-25a9-4b9c-9d03-a44e0f2d04a4",
        "fromTable": "fact_external_performance",
        "fromColumn": "SupplyKey",
        "toTable": "tree_supply",
        "toColumn": "SupplyKey"
      },
      {
        "name": "28bec427-9c6e-4d83-9049-e575cf469199",
        "fromTable": "fact_application_fee",
        "fromColumn": "BudgetKey",
        "toTable": "dim_budget",
        "toColumn": "BudgetKey"
      },
      {
        "name": "d6da0ef1-c7d6-4ff2-ad05-bc22dc2bfa9c",
        "fromTable": "target_budget",
        "fromColumn": "BudgetKey",
        "toTable": "dim_budget",
        "toColumn": "BudgetKey"
      },
      {
        "name": "cf8812c5-9259-425c-8d7d-2ba21697bbd1",
        "fromTable": "fact_strategy_log",
        "fromColumn": "strategy_id",
        "toTable": "strategy_library",
        "toColumn": "id"
      },
      {
        "name": "f1443740-8613-49ce-9283-da99f209d144",
        "fromTable": "strategy_library",
        "fromColumn": "id",
        "toTable": "tree_supply",
        "toColumn": "SupplyKey"
      },
      {
        "name": "742d5225-be13-4778-bddf-613c2c2b2396",
        "fromTable": "fact_application_fee",
        "fromColumn": "BudgetKey",
        "toTable": "tree_budget",
        "toColumn": "BudgetKey"
      },
      {
        "name": "3a42bb72-8e9b-48c4-88fd-ea333c2a10d7",
        "fromTable": "target_budget",
        "fromColumn": "BudgetKey",
        "toTable": "tree_budget",
        "toColumn": "BudgetKey"
      },
      {
        "name": "06b7af98-9911-4a4e-9dcb-2b8d781305cd",
        "fromTable": "fact_application_fee",
        "fromColumn": "OrgKey",
        "toTable": "tree_org",
        "toColumn": "OrgKey"
      },
      {
        "name": "8e368a4d-57d1-4b93-8b16-c4029f5f0acd",
        "fromTable": "result_channel",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "e4c21bc5-97e8-4884-81ec-5daf0ad7ac27",
        "fromTable": "result_org",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "f7a57260-78d7-49ea-8a35-fc6748a95110",
        "fromTable": "result_finance",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "f0867258-965d-4a95-ba93-60df4d21c8c2",
        "fromTable": "result_product",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "874229e0-c21b-43f6-ae5d-7e1ee09bf870",
        "fromTable": "rank_product",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "30481aa6-5244-49a9-bcb8-4c4792479901",
        "fromTable": "rank_product",
        "fromColumn": "ProductKey",
        "toTable": "dim_product",
        "toColumn": "ProductKey"
      },
      {
        "name": "2fd6aa5a-2b64-4ef7-8406-5e72bb451e0e",
        "fromTable": "rank_product",
        "fromColumn": "ProductKey",
        "toTable": "tree_product",
        "toColumn": "ProductKey"
      },
      {
        "name": "f09e7f12-3a01-4673-8cb3-354cf7639416",
        "fromTable": "rank_channel",
        "fromColumn": "ChannelKey",
        "toTable": "dim_channel",
        "toColumn": "ChannelKey"
      },
      {
        "name": "ea6ab531-056c-4c5c-8e09-1bdd44f46187",
        "fromTable": "rank_channel",
        "fromColumn": "ChannelKey",
        "toTable": "tree_channel",
        "toColumn": "ChannelKey"
      },
      {
        "name": "e4667e17-f771-411b-904b-6649489489ff",
        "fromTable": "rank_channel",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "afd66628-662b-47c2-8ed2-2b369f93d70a",
        "fromTable": "rank_customer",
        "fromColumn": "CustomerKey",
        "toTable": "dim_cus",
        "toColumn": "CustomerKey"
      },
      {
        "name": "263fa4ce-2ff5-483a-b662-ce36c89d40bd",
        "fromTable": "rank_customer",
        "fromColumn": "CustomerKey",
        "toTable": "tree_customer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "0a1f4e10-e2e7-4422-99ca-25ae93a93fc3",
        "fromTable": "rank_customer",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "0ce9b9d8-4c29-42ae-ab06-f27048195f58",
        "fromTable": "rank_supply",
        "fromColumn": "SupplyKey",
        "toTable": "dim_supply",
        "toColumn": "SupplyKey"
      },
      {
        "name": "06e7e56e-ed8d-411c-9af2-8fa04f8441a9",
        "fromTable": "rank_supply",
        "fromColumn": "SupplyKey",
        "toTable": "tree_supply",
        "toColumn": "SupplyKey"
      },
      {
        "name": "6c2fe5e1-d248-4aec-bcf6-ec863315756b",
        "fromTable": "rank_org",
        "fromColumn": "OrgKey",
        "toTable": "dim_org",
        "toColumn": "OrgKey"
      },
      {
        "name": "67d8ab8a-8f6e-478c-aa89-131a30a6882c",
        "fromTable": "rank_org",
        "fromColumn": "OrgKey",
        "toTable": "tree_org",
        "toColumn": "OrgKey"
      },
      {
        "name": "fba51133-772a-412e-8596-73ad886a7f32",
        "fromTable": "rank_finance",
        "fromColumn": "OrgKey",
        "toTable": "dim_org",
        "toColumn": "OrgKey"
      },
      {
        "name": "c312c2da-f586-44c7-9a05-e888063d0624",
        "fromTable": "rank_finance",
        "fromColumn": "OrgKey",
        "toTable": "tree_org",
        "toColumn": "OrgKey"
      },
      {
        "name": "f4526f34-8b69-4f43-9814-786b41190039",
        "fromTable": "rank_finance",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "d3f21701-f703-433d-a7f4-d03c12ebf576",
        "fromTable": "rank_org",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "f4a6a0c6-effd-4104-8ddc-53ab5a12cc54",
        "fromTable": "rank_supply",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "4f54f9cf-c586-42a9-ba65-7311b5af10a0",
        "fromTable": "fact_strategy_log",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "a981cd25-6171-4faa-b959-510738e96464",
        "fromTable": "fact_internal_plan",
        "fromColumn": "OrgKey",
        "toTable": "tree_org",
        "toColumn": "OrgKey"
      },
      {
        "name": "46db5032-513e-4982-b4cb-b5cdfcce5ed3",
        "fromTable": "总得分",
        "fromColumn": "fact_performance_DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "7b74af68-9743-4a60-811d-e5c4c61c2225",
        "fromTable": "总得分",
        "fromColumn": "fact_performance_OrgKey",
        "toTable": "tree_org",
        "toColumn": "OrgKey"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "500"
      }
    ]
  },
  "id": "SemanticModel"
}